SELECT
    CODPARC,PARCEIRO,
    SUM(QTDREAL) AS QTD_REAL,
    SUM(QTDPREV) AS QTD_PREV,
    SUM(VLRREAL) AS VLR_REAL,
    SUM(VLRPREV) AS VLR_PREV
FROM (
    SELECT 
    MET.DTREF,
    NVL(VGF.CODPARC, NVL(MET.CODPARC, 0)) CODPARC,
    NVL(VGF.PARCEIRO, 'SEM PARCEIRO') PARCEIRO,
    SUM(NVL(VGF.QTD, 0)) AS QTDREAL,
    MAX(NVL(MET.QTDPREV, 0)) AS QTDPREV,
    SUM(NVL(VGF.VLR, 0)) AS VLRREAL,
    MAX(NVL(MET.QTDPREV, 0) * NVL(PRC.VLRVENDALT, 0)) AS VLRPREV
    FROM TGFMET MET
    LEFT JOIN TGFMAR MAR ON MAR.DESCRICAO = MET.MARCA
    LEFT JOIN TGFVEN VEN ON MET.CODVEND = VEN.CODVEND
    LEFT JOIN VGF_VENDAS_SATIS VGF 
    ON MET.DTREF = TRUNC(VGF.DTMOV, 'MM')
    AND MET.CODVEND = VGF.CODVEND
    AND MET.CODPARC = VGF.CODPARC
    AND MET.MARCA = VGF.MARCA
    AND VGF.BONIFICACAO = 'N'
    ${realIntervalFilter}
    LEFT JOIN AD_PRECOMARCA PRC 
    ON MET.MARCA = PRC.MARCA
    AND PRC.CODMETA = MET.CODMETA
    AND PRC.DTREF = (
        SELECT MAX(DTREF)
        FROM AD_PRECOMARCA
        WHERE CODMETA = MET.CODMETA
            AND DTREF <= MET.DTREF
            AND MARCA = MET.MARCA
    )
    WHERE MET.CODMETA = 4 
    ${prevFullMonthFilter}
    ${parceirosIn}
    ${vendedoresIn}
    ${gerentesIn}
    ${naturezasIn}
    ${marcasIn}
    ${gruposIn}
    ${crsIn}
    AND (
        MET.CODVEND = (SELECT CODVEND FROM TSIUSU WHERE CODUSU = STP_GET_CODUSULOGADO) 
        OR MET.CODVEND IN (SELECT VEN.CODVEND FROM TGFVEN VEN, TSIUSU USU WHERE USU.CODVEND = VEN.CODGER AND USU.CODUSU = STP_GET_CODUSULOGADO)
        OR MET.CODVEND IN (SELECT VEN.CODVEND FROM TGFVEN VEN, TSIUSU USU WHERE USU.CODVEND = VEN.AD_COORDENADOR AND USU.CODUSU = STP_GET_CODUSULOGADO)
        OR (SELECT AD_GESTOR_META FROM TSIUSU WHERE CODUSU = STP_GET_CODUSULOGADO) = 'S' 
    )
    GROUP BY MET.DTREF,
    MET.CODVEND,
    MET.CODPARC,
    MET.MARCA,
    NVL(VGF.CODPARC, NVL(MET.CODPARC, 0)),
    NVL(VGF.PARCEIRO, 'SEM PARCEIRO')
)
GROUP BY CODPARC,PARCEIRO
ORDER BY 2,1