FROM sankhyacloud/plataforma-om-sankhya:sandbox-wildfly-23-standard-eldest

# Defina o comando que roda o Wildfly em primeiro plano (sem nohup ou &)
CMD ["/home/mgeweb/wildfly_producao/bin/standalone.sh", "-b", "0.0.0.0"]
