SELECT
CODIGO1,
DESCRICAO,
GRAU,

MAX(CASE WHEN MES = '01' THEN PREV END) AS "JAN_P",
MAX(CASE WHEN MES = '01' THEN REAL END) AS "JAN_R",
MAX(CASE WHEN MES = '01' THEN PERC END) AS "JAN_PERC",
MAX(CASE WHEN MES = '02' THEN PREV END) AS "FEV_P",
MAX(CASE WHEN MES = '02' THEN REAL END) AS "FEV_R",
MAX(CASE WHEN MES = '02' THEN PERC END) AS "FEV_PERC",
MAX(CASE WHEN MES = '03' THEN PREV END) AS "MAR_P",
MAX(CASE WHEN MES = '03' THEN REAL END) AS "MAR_R",
MAX(CASE WHEN MES = '03' THEN PERC END) AS "MAR_PERC",
MAX(CASE WHEN MES = '04' THEN PREV END) AS "ABR_P",
MAX(CASE WHEN MES = '04' THEN REAL END) AS "ABR_R",
MAX(CASE WHEN MES = '04' THEN PERC END) AS "ABR_PERC",
MAX(CASE WHEN MES = '05' THEN PREV END) AS "MAI_P",
MAX(CASE WHEN MES = '05' THEN REAL END) AS "MAI_R",
MAX(CASE WHEN MES = '05' THEN PERC END) AS "MAI_PERC",
MAX(CASE WHEN MES = '06' THEN PREV END) AS "JUN_P",
MAX(CASE WHEN MES = '06' THEN REAL END) AS "JUN_R",
MAX(CASE WHEN MES = '06' THEN PERC END) AS "JUN_PERC",
MAX(CASE WHEN MES = '07' THEN PREV END) AS "JUL_P",
MAX(CASE WHEN MES = '07' THEN REAL END) AS "JUL_R",
MAX(CASE WHEN MES = '07' THEN PERC END) AS "JUL_PERC",
MAX(CASE WHEN MES = '08' THEN PREV END) AS "AGO_P",
MAX(CASE WHEN MES = '08' THEN REAL END) AS "AGO_R",
MAX(CASE WHEN MES = '08' THEN PERC END) AS "AGO_PERC",
MAX(CASE WHEN MES = '09' THEN PREV END) AS "SET_P",
MAX(CASE WHEN MES = '09' THEN REAL END) AS "SET_R",
MAX(CASE WHEN MES = '09' THEN PERC END) AS "SET_PERC",
MAX(CASE WHEN MES = '10' THEN PREV END) AS "OUT_P",
MAX(CASE WHEN MES = '10' THEN PREV END) AS "OUT_R",
MAX(CASE WHEN MES = '10' THEN PERC END) AS "OUT_PERC",
MAX(CASE WHEN MES = '11' THEN PREV END) AS "NOV_P",
MAX(CASE WHEN MES = '11' THEN REAL END) AS "NOV_R",
MAX(CASE WHEN MES = '11' THEN PERC END) AS "NOV_PERC",
MAX(CASE WHEN MES = '12' THEN PREV END) AS "DEZ_P",
MAX(CASE WHEN MES = '12' THEN REAL END) AS "DEZ_R",
MAX(CASE WHEN MES = '12' THEN PERC END) AS "DEZ_PERC",
CASE 
WHEN GRAU = 1 THEN '#8EA9DB' 
WHEN GRAU = 2 THEN '#c6d4ed'
WHEN GRAU = 3 THEN '#dde5f4'
WHEN GRAU = 4 THEN '#e8f5cc'
WHEN GRAU = 5 THEN '#f0eaf5'
WHEN GRAU IS NULL THEN '#2e34db'
END AS BKCOLOR,

CASE 
WHEN GRAU IS NULL THEN '#fafafc'
END AS FGCOLOR



FROM

(

WITH B AS (SELECT LPAD(CODIGO, 10, '0') AS CODIGO1, DESCRICAO,GRAU FROM AD_ORCFIN)

SELECT
A.ANO,A.MES,A.MES_ANO,

A.CODIGO1,
CASE
WHEN A.CODIGO1 LIKE '0499999999' THEN 'MARGEM DE CONTRIBUIÇÃO'
WHEN A.CODIGO1 LIKE '0599999999' THEN 'LUCRO OPERACIONAL ANTES DOS INVESTIMENTOS'
WHEN A.CODIGO1 LIKE '0699999998' THEN 'DESPESA OPERACIONAL TOTAL'
WHEN A.CODIGO1 LIKE '0699999999' THEN 'LUCRO OPERACIONAL'
WHEN A.CODIGO1 LIKE '0799999999' THEN 'RESULTADO LÍQUIDO'
WHEN A.CODIGO1 LIKE '0899999998' THEN 'DISTRIBUIÇÃO PARA SÓCIOS'
WHEN A.CODIGO1 LIKE '0899999999' THEN 'REINVESTIMENTO GRUPO SATIS'
ELSE B.DESCRICAO 
END AS DESCRICAO, 
B.GRAU,
A.PREV,A.REAL,
(A.REAL / MAX(A.REAL) OVER (PARTITION BY A.MES))*100 AS PERC
FROM

(

SELECT
ANO,MES,MES_ANO,GRAU,CODIGO1,
SUM(PREV) AS PREV,SUM(REAL) AS REAL

FROM
(
WITH BAS AS
(

/*RECUPERAR VALOR PREVISTO BASEADO NA TGFMET*/
SELECT 
ORC.CODIGO,
TO_CHAR(DTREF,'YYYY') AS ANO,
TO_CHAR(DTREF,'MM') AS MES,
TO_CHAR(DTREF,'MM-YYYY') AS MES_ANO,
SUM(PREVREC - PREVDESP) AS PREV,
0 AS REAL
FROM AD_ORCFIN ORC
INNER JOIN AD_ORCFINDET DET ON ORC.CODIGO = DET.CODIGO
INNER JOIN TGFMET MET ON DET.CODNAT = MET.CODNAT
WHERE CODMETA = 7 AND DTREF BETWEEN :P_PERIODO.INI AND :P_PERIODO.FIN
GROUP BY
ORC.CODIGO,
TO_CHAR(DTREF,'YYYY'),
TO_CHAR(DTREF,'MM'),
TO_CHAR(DTREF,'MM-YYYY')

UNION ALL

/*RECUPERAR VALOR REAL SOMENTE PARTE DO FATURAMENTO*/
SELECT
ORC.CODIGO,
TO_CHAR(DTMOV,'YYYY') AS ANO,
TO_CHAR(DTMOV,'MM') AS MES,
TO_CHAR(DTMOV,'MM-YYYY') AS MES_ANO,
0 AS PREV,
SUM(CASE WHEN CAB.TIPMOV='D' THEN (ITE.VLRTOT-ITE.VLRDESC-ITE.VLRREPRED)*-1 ELSE (ITE.VLRTOT-ITE.VLRDESC-ITE.VLRREPRED) END) AS REAL
FROM TSIEMP EMP
INNER JOIN TGFCAB CAB ON (EMP.CODEMP = CAB.CODEMP)
INNER JOIN TGFVEN VEN ON (CAB.CODVEND = VEN.CODVEND)
INNER JOIN TGFPAR PAR ON (CAB.CODPARC = PAR.CODPARC)
INNER JOIN TGFITE ITE ON (CAB.NUNOTA = ITE.NUNOTA)
INNER JOIN TGFPRO PRO ON (ITE.CODPROD = PRO.CODPROD)
INNER JOIN TGFTOP TOP ON (CAB.CODTIPOPER = TOP.CODTIPOPER AND CAB.DHTIPOPER = TOP.DHALTER)
---LEFT JOIN AD_ITENSGRUPOSATIS GRUS ON (GRUS.CODPROD=PRO.CODPROD AND $P{GRUPOSATIS} IS NOT NULL)
INNER JOIN AD_ORCFIN ORC ON (ORC.TIPOMOV = CAB.TIPMOV OR ORC.TIPOMOV = 'A') AND ORC.CALCFAT = 'S'
INNER JOIN AD_ORCFINDET DET ON DET.CODIGO = ORC.CODIGO AND DET.CODNAT = CAB.CODNAT
WHERE
(TOP.ATUALEST <> 'N' OR TOP.CODTIPOPER = 1112)
AND CAB.TIPMOV IN ('V','D')
AND CAB.STATUSNOTA='L'
AND (CAB.STATUSNFE = 'A' OR CAB.STATUSNFE = 'T'  OR CAB.STATUSNFE = 'S' OR CAB.STATUSNFE IS NULL)
AND ((TOP.ATUALFIN<>0 AND TOP.TIPATUALFIN='I') OR (TOP.CODTIPOPER IN (1112,1113)))
AND ORC.CODIGO IS NOT NULL
AND CAB.DTMOV BETWEEN :P_PERIODO.INI AND :P_PERIODO.FIN
AND (ORC.MARCA = PRO.MARCA OR ORC.MARCA IS NULL)
AND ((:P_LINHABIO = 'S' AND PRO.CODGRUPOPROD <> 1020000) OR (:P_LINHABIO = 'N'))
GROUP BY
TO_CHAR(DTMOV,'YYYY'),
TO_CHAR(DTMOV,'MM'),
TO_CHAR(DTMOV,'MM-YYYY'),
ORC.CODIGO

UNION ALL


/*RECUPERAR VALOR REAL DA DESPESA COM BASE NA VGF_RESULTADO_SATIS = DHBAIXA IS NOT NULL*/
SELECT
ORC.CODIGO,
TO_CHAR(FIN.DHBAIXA,'YYYY') AS ANO,
TO_CHAR(FIN.DHBAIXA,'MM') AS MES,
TO_CHAR(FIN.DHBAIXA,'MM-YYYY') AS MES_ANO,
0 AS PREV,
SUM(FIN.VLRBAIXA * FIN.RECDESP) AS REAL
FROM VGF_RESULTADO_SATIS FIN
LEFT JOIN AD_ORCFINDET DET ON FIN.CODNAT = DET.CODNAT
LEFT JOIN AD_ORCFIN ORC ON DET.CODIGO = ORC.CODIGO
WHERE FIN.DHBAIXA IS NOT NULL
AND FIN.DHBAIXA BETWEEN :P_PERIODO.INI AND :P_PERIODO.FIN
AND (NVL(ORC.CALCFAT,'N') = 'N')
GROUP BY
ORC.CODIGO,
TO_CHAR(FIN.DHBAIXA,'YYYY'),
TO_CHAR(FIN.DHBAIXA,'MM'),
TO_CHAR(FIN.DHBAIXA,'MM-YYYY')


),

GRAU1 AS (
SELECT
ANO,
MES,
MES_ANO,
SUBSTR(LPAD(CODIGO, 10, '0'), 1, 2)||'00000000' AS CODIGO1,
'GRAU 1' AS GRAU,
PREV,
REAL
FROM BAS
GROUP BY
ANO,MES,MES_ANO,SUBSTR(LPAD(CODIGO, 10, '0'), 1, 2)||'00000000',PREV,REAL),

GRAU2 AS (
SELECT
ANO,
MES,
MES_ANO,
SUBSTR(LPAD(CODIGO, 10, '0'), 1, 4)||'000000' AS CODIGO1,
'GRAU 2' AS GRAU,
PREV,
REAL
FROM BAS
GROUP BY
ANO, MES,MES_ANO,SUBSTR(LPAD(CODIGO, 10, '0'), 1, 4)||'000000',PREV,REAL),

GRAU3 AS (
SELECT
ANO,
MES,
MES_ANO,
SUBSTR(LPAD(CODIGO, 10, '0'), 1, 6)||'0000' AS CODIGO1,
'GRAU 3' AS GRAU,
PREV,
REAL
FROM BAS
GROUP BY
ANO, MES,MES_ANO,SUBSTR(LPAD(CODIGO, 10, '0'), 1, 6)||'0000',PREV,REAL),

GRAU4 AS (
SELECT
ANO,
MES,
MES_ANO,
SUBSTR(LPAD(CODIGO, 10, '0'), 1, 8)||'00' AS CODIGO1,
'GRAU 4' AS GRAU,
PREV,
REAL
FROM BAS
GROUP BY
ANO,MES,MES_ANO,SUBSTR(LPAD(CODIGO, 10, '0'), 1, 8)||'00',PREV,REAL),

GRAU5 AS (
SELECT
ANO,
MES,
MES_ANO,
SUBSTR(LPAD(CODIGO, 10, '0'), 1, 10) AS CODIGO1,
'GRAU 5' AS GRAU,
PREV,
REAL
FROM BAS
GROUP BY
ANO, MES, MES_ANO, SUBSTR(LPAD(CODIGO, 10, '0'), 1, 10), PREV, REAL)

SELECT * FROM GRAU1

UNION ALL

SELECT * FROM GRAU2

UNION ALL

SELECT * FROM GRAU3

UNION ALL

SELECT * FROM GRAU4

UNION ALL

SELECT * FROM GRAU5

)

GROUP BY ANO,MES,MES_ANO,GRAU,CODIGO1


UNION ALL


SELECT
ANO,MES,MES_ANO,
'TOTAL' AS GRAU, '0499999999' AS CODIGO1,
SUM(CASE WHEN CODIGO1 LIKE '0300000000' AND GRAU LIKE 'GRAU 1' THEN PREV END) - 
SUM(CASE WHEN CODIGO1 LIKE '0400000000' AND GRAU LIKE 'GRAU 1' THEN PREV END) 
AS PREV,
SUM(CASE WHEN CODIGO1 LIKE '0300000000' AND GRAU LIKE 'GRAU 1' THEN REAL END) - 
SUM(CASE WHEN CODIGO1 LIKE '0400000000' AND GRAU LIKE 'GRAU 1' THEN REAL END) 
AS REAL


FROM
(
WITH BAS AS
(


/*PREVISTO BASEADO NA TGFMET*/
SELECT 
ORC.CODIGO,
TO_CHAR(DTREF,'YYYY') AS ANO,
TO_CHAR(DTREF,'MM') AS MES,
TO_CHAR(DTREF,'MM-YYYY') AS MES_ANO,
SUM(PREVREC - PREVDESP) AS PREV,
0 AS REAL
FROM AD_ORCFIN ORC
INNER JOIN AD_ORCFINDET DET ON ORC.CODIGO = DET.CODIGO
INNER JOIN TGFMET MET ON DET.CODNAT = MET.CODNAT
WHERE CODMETA = 7 AND DTREF BETWEEN :P_PERIODO.INI AND :P_PERIODO.FIN
GROUP BY
ORC.CODIGO,
TO_CHAR(DTREF,'YYYY'),
TO_CHAR(DTREF,'MM'),
TO_CHAR(DTREF,'MM-YYYY')

UNION ALL

/*REAL SOMENTE PARTE DO FATURAMENTO*/
SELECT
ORC.CODIGO,
TO_CHAR(DTMOV,'YYYY') AS ANO,
TO_CHAR(DTMOV,'MM') AS MES,
TO_CHAR(DTMOV,'MM-YYYY') AS MES_ANO,
0 AS PREV,
SUM(CASE WHEN CAB.TIPMOV='D' THEN (ITE.VLRTOT-ITE.VLRDESC-ITE.VLRREPRED)*-1 ELSE (ITE.VLRTOT-ITE.VLRDESC-ITE.VLRREPRED) END) AS REAL
FROM TSIEMP EMP
INNER JOIN TGFCAB CAB ON (EMP.CODEMP = CAB.CODEMP)
INNER JOIN TGFVEN VEN ON (CAB.CODVEND = VEN.CODVEND)
INNER JOIN TGFPAR PAR ON (CAB.CODPARC = PAR.CODPARC)
INNER JOIN TGFITE ITE ON (CAB.NUNOTA = ITE.NUNOTA)
INNER JOIN TGFPRO PRO ON (ITE.CODPROD = PRO.CODPROD)
INNER JOIN TGFTOP TOP ON (CAB.CODTIPOPER = TOP.CODTIPOPER AND CAB.DHTIPOPER = TOP.DHALTER)
---LEFT JOIN AD_ITENSGRUPOSATIS GRUS ON (GRUS.CODPROD=PRO.CODPROD AND $P{GRUPOSATIS} IS NOT NULL)
INNER JOIN AD_ORCFIN ORC ON (ORC.TIPOMOV = CAB.TIPMOV OR ORC.TIPOMOV = 'A') AND ORC.CALCFAT = 'S'
INNER JOIN AD_ORCFINDET DET ON DET.CODIGO = ORC.CODIGO AND DET.CODNAT = CAB.CODNAT
WHERE
(TOP.ATUALEST <> 'N' OR TOP.CODTIPOPER = 1112)
AND CAB.TIPMOV IN ('V','D')
AND CAB.STATUSNOTA='L'
AND (CAB.STATUSNFE = 'A' OR CAB.STATUSNFE = 'T'  OR CAB.STATUSNFE = 'S' OR CAB.STATUSNFE IS NULL)
AND ((TOP.ATUALFIN<>0 AND TOP.TIPATUALFIN='I') OR (TOP.CODTIPOPER IN (1112,1113)))
AND ORC.CODIGO IS NOT NULL
AND CAB.DTMOV BETWEEN :P_PERIODO.INI AND :P_PERIODO.FIN
AND (ORC.MARCA = PRO.MARCA OR ORC.MARCA IS NULL)
AND ((:P_LINHABIO = 'S' AND PRO.CODGRUPOPROD <> 1020000) OR (:P_LINHABIO = 'N'))
GROUP BY
TO_CHAR(DTMOV,'YYYY'),
TO_CHAR(DTMOV,'MM'),
TO_CHAR(DTMOV,'MM-YYYY'),
ORC.CODIGO

UNION ALL


/*REAL DA DESPESA VGF_RESULTADO_SATIS DHBAIXA IS NOT NULL*/
SELECT
ORC.CODIGO,
TO_CHAR(FIN.DHBAIXA,'YYYY') AS ANO,
TO_CHAR(FIN.DHBAIXA,'MM') AS MES,
TO_CHAR(FIN.DHBAIXA,'MM-YYYY') AS MES_ANO,
0 AS PREV,
SUM(FIN.VLRBAIXA * FIN.RECDESP) AS REAL
FROM VGF_RESULTADO_SATIS FIN
INNER JOIN AD_ORCFINDET DET ON FIN.CODNAT = DET.CODNAT
INNER JOIN AD_ORCFIN ORC ON DET.CODIGO = ORC.CODIGO
WHERE FIN.DHBAIXA IS NOT NULL
AND FIN.DHBAIXA BETWEEN :P_PERIODO.INI AND :P_PERIODO.FIN
AND (NVL(ORC.CALCFAT,'N') = 'N')
GROUP BY
ORC.CODIGO,
TO_CHAR(FIN.DHBAIXA,'YYYY'),
TO_CHAR(FIN.DHBAIXA,'MM'),
TO_CHAR(FIN.DHBAIXA,'MM-YYYY')


),

GRAU1 AS (
SELECT
ANO,
MES,
MES_ANO,
SUBSTR(LPAD(CODIGO, 10, '0'), 1, 2)||'00000000' AS CODIGO1,
'GRAU 1' AS GRAU,
PREV AS PREV,
REAL AS REAL
FROM BAS
GROUP BY
ANO,MES,MES_ANO,SUBSTR(LPAD(CODIGO, 10, '0'), 1, 2)||'00000000',PREV,REAL),




GRAU2 AS (
SELECT
ANO,
MES,
MES_ANO,
SUBSTR(LPAD(CODIGO, 10, '0'), 1, 4)||'000000' AS CODIGO1,
'GRAU 2' AS GRAU,
PREV,
REAL
FROM BAS
GROUP BY
ANO, MES,MES_ANO,SUBSTR(LPAD(CODIGO, 10, '0'), 1, 4)||'000000',PREV,REAL),

GRAU3 AS (
SELECT
ANO,
MES,
MES_ANO,
SUBSTR(LPAD(CODIGO, 10, '0'), 1, 6)||'0000' AS CODIGO1,
'GRAU 3' AS GRAU,
PREV,
REAL
FROM BAS
GROUP BY
ANO, MES,MES_ANO,SUBSTR(LPAD(CODIGO, 10, '0'), 1, 6)||'0000',PREV,REAL),

GRAU4 AS (
SELECT
ANO,
MES,
MES_ANO,
SUBSTR(LPAD(CODIGO, 10, '0'), 1, 8)||'00' AS CODIGO1,
'GRAU 4' AS GRAU,
PREV,
REAL
FROM BAS
GROUP BY
ANO,MES,MES_ANO,SUBSTR(LPAD(CODIGO, 10, '0'), 1, 8)||'00',PREV,REAL),

GRAU5 AS (
SELECT
ANO,
MES,
MES_ANO,
SUBSTR(LPAD(CODIGO, 10, '0'), 1, 10) AS CODIGO1,
'GRAU 5' AS GRAU,
PREV,
REAL
FROM BAS
GROUP BY
ANO, MES, MES_ANO, SUBSTR(LPAD(CODIGO, 10, '0'), 1, 10), PREV, REAL)

SELECT * FROM GRAU1

UNION ALL

SELECT * FROM GRAU2

UNION ALL

SELECT * FROM GRAU3

UNION ALL

SELECT * FROM GRAU4

UNION ALL

SELECT * FROM GRAU5

)
GROUP BY ANO,MES,MES_ANO



UNION ALL


SELECT
ANO,MES,MES_ANO,
'TOTAL' AS GRAU, '0599999999' AS CODIGO1,
SUM(CASE WHEN CODIGO1 LIKE '0300000000' AND GRAU LIKE 'GRAU 1' THEN PREV END) - 
SUM(CASE WHEN CODIGO1 LIKE '0400000000' AND GRAU LIKE 'GRAU 1' THEN PREV END) -
SUM(CASE WHEN CODIGO1 LIKE '0500000000' AND GRAU LIKE 'GRAU 1' THEN PREV END) 
AS PREV,
SUM(CASE WHEN CODIGO1 LIKE '0300000000' AND GRAU LIKE 'GRAU 1' THEN REAL END) - 
SUM(CASE WHEN CODIGO1 LIKE '0400000000' AND GRAU LIKE 'GRAU 1' THEN REAL END) -
SUM(CASE WHEN CODIGO1 LIKE '0500000000' AND GRAU LIKE 'GRAU 1' THEN REAL END)
AS REAL


FROM
(
WITH BAS AS
(



/*PREVISTO BASEADO NA TGFMET*/
SELECT 
ORC.CODIGO,
TO_CHAR(DTREF,'YYYY') AS ANO,
TO_CHAR(DTREF,'MM') AS MES,
TO_CHAR(DTREF,'MM-YYYY') AS MES_ANO,
SUM(PREVREC - PREVDESP) AS PREV,
0 AS REAL
FROM AD_ORCFIN ORC
INNER JOIN AD_ORCFINDET DET ON ORC.CODIGO = DET.CODIGO
INNER JOIN TGFMET MET ON DET.CODNAT = MET.CODNAT
WHERE CODMETA = 7 AND DTREF BETWEEN :P_PERIODO.INI AND :P_PERIODO.FIN
GROUP BY
ORC.CODIGO,
TO_CHAR(DTREF,'YYYY'),
TO_CHAR(DTREF,'MM'),
TO_CHAR(DTREF,'MM-YYYY')

UNION ALL

/*REAL SOMENTE PARTE DO FATURAMENTO*/
SELECT
ORC.CODIGO,
TO_CHAR(DTMOV,'YYYY') AS ANO,
TO_CHAR(DTMOV,'MM') AS MES,
TO_CHAR(DTMOV,'MM-YYYY') AS MES_ANO,
0 AS PREV,
SUM(CASE WHEN CAB.TIPMOV='D' THEN (ITE.VLRTOT-ITE.VLRDESC-ITE.VLRREPRED)*-1 ELSE (ITE.VLRTOT-ITE.VLRDESC-ITE.VLRREPRED) END) AS REAL
FROM TSIEMP EMP
INNER JOIN TGFCAB CAB ON (EMP.CODEMP = CAB.CODEMP)
INNER JOIN TGFVEN VEN ON (CAB.CODVEND = VEN.CODVEND)
INNER JOIN TGFPAR PAR ON (CAB.CODPARC = PAR.CODPARC)
INNER JOIN TGFITE ITE ON (CAB.NUNOTA = ITE.NUNOTA)
INNER JOIN TGFPRO PRO ON (ITE.CODPROD = PRO.CODPROD)
INNER JOIN TGFTOP TOP ON (CAB.CODTIPOPER = TOP.CODTIPOPER AND CAB.DHTIPOPER = TOP.DHALTER)
---LEFT JOIN AD_ITENSGRUPOSATIS GRUS ON (GRUS.CODPROD=PRO.CODPROD AND $P{GRUPOSATIS} IS NOT NULL)
INNER JOIN AD_ORCFIN ORC ON (ORC.TIPOMOV = CAB.TIPMOV OR ORC.TIPOMOV = 'A') AND ORC.CALCFAT = 'S'
INNER JOIN AD_ORCFINDET DET ON DET.CODIGO = ORC.CODIGO AND DET.CODNAT = CAB.CODNAT
WHERE
(TOP.ATUALEST <> 'N' OR TOP.CODTIPOPER = 1112)
AND CAB.TIPMOV IN ('V','D')
AND CAB.STATUSNOTA='L'
AND (CAB.STATUSNFE = 'A' OR CAB.STATUSNFE = 'T'  OR CAB.STATUSNFE = 'S' OR CAB.STATUSNFE IS NULL)
AND ((TOP.ATUALFIN<>0 AND TOP.TIPATUALFIN='I') OR (TOP.CODTIPOPER IN (1112,1113)))
AND ORC.CODIGO IS NOT NULL
AND CAB.DTMOV BETWEEN :P_PERIODO.INI AND :P_PERIODO.FIN
AND (ORC.MARCA = PRO.MARCA OR ORC.MARCA IS NULL)
AND ((:P_LINHABIO = 'S' AND PRO.CODGRUPOPROD <> 1020000) OR (:P_LINHABIO = 'N'))
GROUP BY
TO_CHAR(DTMOV,'YYYY'),
TO_CHAR(DTMOV,'MM'),
TO_CHAR(DTMOV,'MM-YYYY'),
ORC.CODIGO

UNION ALL


/*REAL DA DESPESA VGF_RESULTADO_SATIS DHBAIXA IS NOT NULL*/
SELECT
ORC.CODIGO,
TO_CHAR(FIN.DHBAIXA,'YYYY') AS ANO,
TO_CHAR(FIN.DHBAIXA,'MM') AS MES,
TO_CHAR(FIN.DHBAIXA,'MM-YYYY') AS MES_ANO,
0 AS PREV,
SUM(FIN.VLRBAIXA * FIN.RECDESP) AS REAL
FROM VGF_RESULTADO_SATIS FIN
LEFT JOIN AD_ORCFINDET DET ON FIN.CODNAT = DET.CODNAT
LEFT JOIN AD_ORCFIN ORC ON DET.CODIGO = ORC.CODIGO
WHERE FIN.DHBAIXA IS NOT NULL
AND FIN.DHBAIXA BETWEEN :P_PERIODO.INI AND :P_PERIODO.FIN
AND (NVL(ORC.CALCFAT,'N') = 'N')
GROUP BY
ORC.CODIGO,
TO_CHAR(FIN.DHBAIXA,'YYYY'),
TO_CHAR(FIN.DHBAIXA,'MM'),
TO_CHAR(FIN.DHBAIXA,'MM-YYYY')

),

GRAU1 AS (
SELECT
ANO,
MES,
MES_ANO,
SUBSTR(LPAD(CODIGO, 10, '0'), 1, 2)||'00000000' AS CODIGO1,
'GRAU 1' AS GRAU,
PREV AS PREV,
REAL AS REAL
FROM BAS
GROUP BY
ANO,MES,MES_ANO,SUBSTR(LPAD(CODIGO, 10, '0'), 1, 2)||'00000000',PREV,REAL),




GRAU2 AS (
SELECT
ANO,
MES,
MES_ANO,
SUBSTR(LPAD(CODIGO, 10, '0'), 1, 4)||'000000' AS CODIGO1,
'GRAU 2' AS GRAU,
PREV,
REAL
FROM BAS
GROUP BY
ANO, MES,MES_ANO,SUBSTR(LPAD(CODIGO, 10, '0'), 1, 4)||'000000',PREV,REAL),

GRAU3 AS (
SELECT
ANO,
MES,
MES_ANO,
SUBSTR(LPAD(CODIGO, 10, '0'), 1, 6)||'0000' AS CODIGO1,
'GRAU 3' AS GRAU,
PREV,
REAL
FROM BAS
GROUP BY
ANO, MES,MES_ANO,SUBSTR(LPAD(CODIGO, 10, '0'), 1, 6)||'0000',PREV,REAL),

GRAU4 AS (
SELECT
ANO,
MES,
MES_ANO,
SUBSTR(LPAD(CODIGO, 10, '0'), 1, 8)||'00' AS CODIGO1,
'GRAU 4' AS GRAU,
PREV,
REAL
FROM BAS
GROUP BY
ANO,MES,MES_ANO,SUBSTR(LPAD(CODIGO, 10, '0'), 1, 8)||'00',PREV,REAL),

GRAU5 AS (
SELECT
ANO,
MES,
MES_ANO,
SUBSTR(LPAD(CODIGO, 10, '0'), 1, 10) AS CODIGO1,
'GRAU 5' AS GRAU,
PREV,
REAL
FROM BAS
GROUP BY
ANO, MES, MES_ANO, SUBSTR(LPAD(CODIGO, 10, '0'), 1, 10), PREV, REAL)

SELECT * FROM GRAU1

UNION ALL

SELECT * FROM GRAU2

UNION ALL

SELECT * FROM GRAU3

UNION ALL

SELECT * FROM GRAU4

UNION ALL

SELECT * FROM GRAU5

)
GROUP BY ANO,MES,MES_ANO



UNION ALL


SELECT
ANO,MES,MES_ANO,
'TOTAL' AS GRAU, '0699999998' AS CODIGO1,
SUM(CASE WHEN CODIGO1 LIKE '0400000000' AND GRAU LIKE 'GRAU 1' THEN PREV END) + 
SUM(CASE WHEN CODIGO1 LIKE '0500000000' AND GRAU LIKE 'GRAU 1' THEN PREV END) +
SUM(CASE WHEN CODIGO1 LIKE '0600000000' AND GRAU LIKE 'GRAU 1' THEN PREV END) 
AS PREV,
SUM(CASE WHEN CODIGO1 LIKE '0400000000' AND GRAU LIKE 'GRAU 1' THEN REAL END) + 
SUM(CASE WHEN CODIGO1 LIKE '0500000000' AND GRAU LIKE 'GRAU 1' THEN REAL END) +
SUM(CASE WHEN CODIGO1 LIKE '0600000000' AND GRAU LIKE 'GRAU 1' THEN REAL END)
AS REAL


FROM
(
WITH BAS AS
(



/*PREVISTO BASEADO NA TGFMET*/
SELECT 
ORC.CODIGO,
TO_CHAR(DTREF,'YYYY') AS ANO,
TO_CHAR(DTREF,'MM') AS MES,
TO_CHAR(DTREF,'MM-YYYY') AS MES_ANO,
SUM(PREVREC - PREVDESP) AS PREV,
0 AS REAL
FROM AD_ORCFIN ORC
INNER JOIN AD_ORCFINDET DET ON ORC.CODIGO = DET.CODIGO
INNER JOIN TGFMET MET ON DET.CODNAT = MET.CODNAT
WHERE CODMETA = 7 AND DTREF BETWEEN :P_PERIODO.INI AND :P_PERIODO.FIN
GROUP BY
ORC.CODIGO,
TO_CHAR(DTREF,'YYYY'),
TO_CHAR(DTREF,'MM'),
TO_CHAR(DTREF,'MM-YYYY')

UNION ALL

/*REAL SOMENTE PARTE DO FATURAMENTO*/
SELECT
ORC.CODIGO,
TO_CHAR(DTMOV,'YYYY') AS ANO,
TO_CHAR(DTMOV,'MM') AS MES,
TO_CHAR(DTMOV,'MM-YYYY') AS MES_ANO,
0 AS PREV,
SUM(CASE WHEN CAB.TIPMOV='D' THEN (ITE.VLRTOT-ITE.VLRDESC-ITE.VLRREPRED)*-1 ELSE (ITE.VLRTOT-ITE.VLRDESC-ITE.VLRREPRED) END) AS REAL
FROM TSIEMP EMP
INNER JOIN TGFCAB CAB ON (EMP.CODEMP = CAB.CODEMP)
INNER JOIN TGFVEN VEN ON (CAB.CODVEND = VEN.CODVEND)
INNER JOIN TGFPAR PAR ON (CAB.CODPARC = PAR.CODPARC)
INNER JOIN TGFITE ITE ON (CAB.NUNOTA = ITE.NUNOTA)
INNER JOIN TGFPRO PRO ON (ITE.CODPROD = PRO.CODPROD)
INNER JOIN TGFTOP TOP ON (CAB.CODTIPOPER = TOP.CODTIPOPER AND CAB.DHTIPOPER = TOP.DHALTER)
---LEFT JOIN AD_ITENSGRUPOSATIS GRUS ON (GRUS.CODPROD=PRO.CODPROD AND $P{GRUPOSATIS} IS NOT NULL)
INNER JOIN AD_ORCFIN ORC ON (ORC.TIPOMOV = CAB.TIPMOV OR ORC.TIPOMOV = 'A') AND ORC.CALCFAT = 'S'
INNER JOIN AD_ORCFINDET DET ON DET.CODIGO = ORC.CODIGO AND DET.CODNAT = CAB.CODNAT
WHERE
(TOP.ATUALEST <> 'N' OR TOP.CODTIPOPER = 1112)
AND CAB.TIPMOV IN ('V','D')
AND CAB.STATUSNOTA='L'
AND (CAB.STATUSNFE = 'A' OR CAB.STATUSNFE = 'T'  OR CAB.STATUSNFE = 'S' OR CAB.STATUSNFE IS NULL)
AND ((TOP.ATUALFIN<>0 AND TOP.TIPATUALFIN='I') OR (TOP.CODTIPOPER IN (1112,1113)))
AND ORC.CODIGO IS NOT NULL
AND CAB.DTMOV BETWEEN :P_PERIODO.INI AND :P_PERIODO.FIN
AND (ORC.MARCA = PRO.MARCA OR ORC.MARCA IS NULL)
AND ((:P_LINHABIO = 'S' AND PRO.CODGRUPOPROD <> 1020000) OR (:P_LINHABIO = 'N'))
GROUP BY
TO_CHAR(DTMOV,'YYYY'),
TO_CHAR(DTMOV,'MM'),
TO_CHAR(DTMOV,'MM-YYYY'),
ORC.CODIGO

UNION ALL


/*REAL DA DESPESA VGF_RESULTADO_SATIS DHBAIXA IS NOT NULL*/
SELECT
ORC.CODIGO,
TO_CHAR(FIN.DHBAIXA,'YYYY') AS ANO,
TO_CHAR(FIN.DHBAIXA,'MM') AS MES,
TO_CHAR(FIN.DHBAIXA,'MM-YYYY') AS MES_ANO,
0 AS PREV,
SUM(FIN.VLRBAIXA * FIN.RECDESP) AS REAL
FROM VGF_RESULTADO_SATIS FIN
LEFT JOIN AD_ORCFINDET DET ON FIN.CODNAT = DET.CODNAT
LEFT JOIN AD_ORCFIN ORC ON DET.CODIGO = ORC.CODIGO
WHERE FIN.DHBAIXA IS NOT NULL
AND FIN.DHBAIXA BETWEEN :P_PERIODO.INI AND :P_PERIODO.FIN
AND (NVL(ORC.CALCFAT,'N') = 'N')
GROUP BY
ORC.CODIGO,
TO_CHAR(FIN.DHBAIXA,'YYYY'),
TO_CHAR(FIN.DHBAIXA,'MM'),
TO_CHAR(FIN.DHBAIXA,'MM-YYYY')

),

GRAU1 AS (
SELECT
ANO,
MES,
MES_ANO,
SUBSTR(LPAD(CODIGO, 10, '0'), 1, 2)||'00000000' AS CODIGO1,
'GRAU 1' AS GRAU,
PREV AS PREV,
REAL AS REAL
FROM BAS
GROUP BY
ANO,MES,MES_ANO,SUBSTR(LPAD(CODIGO, 10, '0'), 1, 2)||'00000000',PREV,REAL),

GRAU2 AS (
SELECT
ANO,
MES,
MES_ANO,
SUBSTR(LPAD(CODIGO, 10, '0'), 1, 4)||'000000' AS CODIGO1,
'GRAU 2' AS GRAU,
PREV,
REAL
FROM BAS
GROUP BY
ANO, MES,MES_ANO,SUBSTR(LPAD(CODIGO, 10, '0'), 1, 4)||'000000',PREV,REAL),

GRAU3 AS (
SELECT
ANO,
MES,
MES_ANO,
SUBSTR(LPAD(CODIGO, 10, '0'), 1, 6)||'0000' AS CODIGO1,
'GRAU 3' AS GRAU,
PREV,
REAL
FROM BAS
GROUP BY
ANO, MES,MES_ANO,SUBSTR(LPAD(CODIGO, 10, '0'), 1, 6)||'0000',PREV,REAL),

GRAU4 AS (
SELECT
ANO,
MES,
MES_ANO,
SUBSTR(LPAD(CODIGO, 10, '0'), 1, 8)||'00' AS CODIGO1,
'GRAU 4' AS GRAU,
PREV,
REAL
FROM BAS
GROUP BY
ANO,MES,MES_ANO,SUBSTR(LPAD(CODIGO, 10, '0'), 1, 8)||'00',PREV,REAL),

GRAU5 AS (
SELECT
ANO,
MES,
MES_ANO,
SUBSTR(LPAD(CODIGO, 10, '0'), 1, 10) AS CODIGO1,
'GRAU 5' AS GRAU,
PREV,
REAL
FROM BAS
GROUP BY
ANO, MES, MES_ANO, SUBSTR(LPAD(CODIGO, 10, '0'), 1, 10), PREV, REAL)

SELECT * FROM GRAU1

UNION ALL

SELECT * FROM GRAU2

UNION ALL

SELECT * FROM GRAU3

UNION ALL

SELECT * FROM GRAU4

UNION ALL

SELECT * FROM GRAU5

)
GROUP BY ANO,MES,MES_ANO



UNION ALL


SELECT
ANO,MES,MES_ANO,
'TOTAL' AS GRAU, '0699999999' AS CODIGO1,
SUM(CASE WHEN CODIGO1 LIKE '0300000000' AND GRAU LIKE 'GRAU 1' THEN PREV END) -
SUM(CASE WHEN CODIGO1 LIKE '0400000000' AND GRAU LIKE 'GRAU 1' THEN PREV END) - 
SUM(CASE WHEN CODIGO1 LIKE '0500000000' AND GRAU LIKE 'GRAU 1' THEN PREV END) -
SUM(CASE WHEN CODIGO1 LIKE '0600000000' AND GRAU LIKE 'GRAU 1' THEN PREV END) 
AS PREV,
SUM(CASE WHEN CODIGO1 LIKE '0300000000' AND GRAU LIKE 'GRAU 1' THEN REAL END) -
SUM(CASE WHEN CODIGO1 LIKE '0400000000' AND GRAU LIKE 'GRAU 1' THEN REAL END) - 
SUM(CASE WHEN CODIGO1 LIKE '0500000000' AND GRAU LIKE 'GRAU 1' THEN REAL END) -
SUM(CASE WHEN CODIGO1 LIKE '0600000000' AND GRAU LIKE 'GRAU 1' THEN REAL END)
AS REAL


FROM
(
WITH BAS AS
(



/*PREVISTO BASEADO NA TGFMET*/
SELECT 
ORC.CODIGO,
TO_CHAR(DTREF,'YYYY') AS ANO,
TO_CHAR(DTREF,'MM') AS MES,
TO_CHAR(DTREF,'MM-YYYY') AS MES_ANO,
SUM(PREVREC - PREVDESP) AS PREV,
0 AS REAL
FROM AD_ORCFIN ORC
INNER JOIN AD_ORCFINDET DET ON ORC.CODIGO = DET.CODIGO
INNER JOIN TGFMET MET ON DET.CODNAT = MET.CODNAT
WHERE CODMETA = 7 AND DTREF BETWEEN :P_PERIODO.INI AND :P_PERIODO.FIN
GROUP BY
ORC.CODIGO,
TO_CHAR(DTREF,'YYYY'),
TO_CHAR(DTREF,'MM'),
TO_CHAR(DTREF,'MM-YYYY')

UNION ALL

/*REAL SOMENTE PARTE DO FATURAMENTO*/
SELECT
ORC.CODIGO,
TO_CHAR(DTMOV,'YYYY') AS ANO,
TO_CHAR(DTMOV,'MM') AS MES,
TO_CHAR(DTMOV,'MM-YYYY') AS MES_ANO,
0 AS PREV,
SUM(CASE WHEN CAB.TIPMOV='D' THEN (ITE.VLRTOT-ITE.VLRDESC-ITE.VLRREPRED)*-1 ELSE (ITE.VLRTOT-ITE.VLRDESC-ITE.VLRREPRED) END) AS REAL
FROM TSIEMP EMP
INNER JOIN TGFCAB CAB ON (EMP.CODEMP = CAB.CODEMP)
INNER JOIN TGFVEN VEN ON (CAB.CODVEND = VEN.CODVEND)
INNER JOIN TGFPAR PAR ON (CAB.CODPARC = PAR.CODPARC)
INNER JOIN TGFITE ITE ON (CAB.NUNOTA = ITE.NUNOTA)
INNER JOIN TGFPRO PRO ON (ITE.CODPROD = PRO.CODPROD)
INNER JOIN TGFTOP TOP ON (CAB.CODTIPOPER = TOP.CODTIPOPER AND CAB.DHTIPOPER = TOP.DHALTER)
---LEFT JOIN AD_ITENSGRUPOSATIS GRUS ON (GRUS.CODPROD=PRO.CODPROD AND $P{GRUPOSATIS} IS NOT NULL)
INNER JOIN AD_ORCFIN ORC ON (ORC.TIPOMOV = CAB.TIPMOV OR ORC.TIPOMOV = 'A') AND ORC.CALCFAT = 'S'
INNER JOIN AD_ORCFINDET DET ON DET.CODIGO = ORC.CODIGO AND DET.CODNAT = CAB.CODNAT
WHERE
(TOP.ATUALEST <> 'N' OR TOP.CODTIPOPER = 1112)
AND CAB.TIPMOV IN ('V','D')
AND CAB.STATUSNOTA='L'
AND (CAB.STATUSNFE = 'A' OR CAB.STATUSNFE = 'T'  OR CAB.STATUSNFE = 'S' OR CAB.STATUSNFE IS NULL)
AND ((TOP.ATUALFIN<>0 AND TOP.TIPATUALFIN='I') OR (TOP.CODTIPOPER IN (1112,1113)))
AND ORC.CODIGO IS NOT NULL
AND CAB.DTMOV BETWEEN :P_PERIODO.INI AND :P_PERIODO.FIN
AND (ORC.MARCA = PRO.MARCA OR ORC.MARCA IS NULL)
AND ((:P_LINHABIO = 'S' AND PRO.CODGRUPOPROD <> 1020000) OR (:P_LINHABIO = 'N'))
GROUP BY
TO_CHAR(DTMOV,'YYYY'),
TO_CHAR(DTMOV,'MM'),
TO_CHAR(DTMOV,'MM-YYYY'),
ORC.CODIGO

UNION ALL


/*REAL DA DESPESA VGF_RESULTADO_SATIS DHBAIXA IS NOT NULL*/
SELECT
ORC.CODIGO,
TO_CHAR(FIN.DHBAIXA,'YYYY') AS ANO,
TO_CHAR(FIN.DHBAIXA,'MM') AS MES,
TO_CHAR(FIN.DHBAIXA,'MM-YYYY') AS MES_ANO,
0 AS PREV,
SUM(FIN.VLRBAIXA * FIN.RECDESP) AS REAL
FROM VGF_RESULTADO_SATIS FIN
LEFT JOIN AD_ORCFINDET DET ON FIN.CODNAT = DET.CODNAT
LEFT JOIN AD_ORCFIN ORC ON DET.CODIGO = ORC.CODIGO
WHERE FIN.DHBAIXA IS NOT NULL
AND FIN.DHBAIXA BETWEEN :P_PERIODO.INI AND :P_PERIODO.FIN
AND (NVL(ORC.CALCFAT,'N') = 'N')
GROUP BY
ORC.CODIGO,
TO_CHAR(FIN.DHBAIXA,'YYYY'),
TO_CHAR(FIN.DHBAIXA,'MM'),
TO_CHAR(FIN.DHBAIXA,'MM-YYYY')


),

GRAU1 AS (
SELECT
ANO,
MES,
MES_ANO,
SUBSTR(LPAD(CODIGO, 10, '0'), 1, 2)||'00000000' AS CODIGO1,
'GRAU 1' AS GRAU,
PREV AS PREV,
REAL AS REAL
FROM BAS
GROUP BY
ANO,MES,MES_ANO,SUBSTR(LPAD(CODIGO, 10, '0'), 1, 2)||'00000000',PREV,REAL),

GRAU2 AS (
SELECT
ANO,
MES,
MES_ANO,
SUBSTR(LPAD(CODIGO, 10, '0'), 1, 4)||'000000' AS CODIGO1,
'GRAU 2' AS GRAU,
PREV,
REAL
FROM BAS
GROUP BY
ANO, MES,MES_ANO,SUBSTR(LPAD(CODIGO, 10, '0'), 1, 4)||'000000',PREV,REAL),

GRAU3 AS (
SELECT
ANO,
MES,
MES_ANO,
SUBSTR(LPAD(CODIGO, 10, '0'), 1, 6)||'0000' AS CODIGO1,
'GRAU 3' AS GRAU,
PREV,
REAL
FROM BAS
GROUP BY
ANO, MES,MES_ANO,SUBSTR(LPAD(CODIGO, 10, '0'), 1, 6)||'0000',PREV,REAL),

GRAU4 AS (
SELECT
ANO,
MES,
MES_ANO,
SUBSTR(LPAD(CODIGO, 10, '0'), 1, 8)||'00' AS CODIGO1,
'GRAU 4' AS GRAU,
PREV,
REAL
FROM BAS
GROUP BY
ANO,MES,MES_ANO,SUBSTR(LPAD(CODIGO, 10, '0'), 1, 8)||'00',PREV,REAL),

GRAU5 AS (
SELECT
ANO,
MES,
MES_ANO,
SUBSTR(LPAD(CODIGO, 10, '0'), 1, 10) AS CODIGO1,
'GRAU 5' AS GRAU,
PREV,
REAL
FROM BAS
GROUP BY
ANO, MES, MES_ANO, SUBSTR(LPAD(CODIGO, 10, '0'), 1, 10), PREV, REAL)

SELECT * FROM GRAU1

UNION ALL

SELECT * FROM GRAU2

UNION ALL

SELECT * FROM GRAU3

UNION ALL

SELECT * FROM GRAU4

UNION ALL

SELECT * FROM GRAU5

)
GROUP BY ANO,MES,MES_ANO



UNION ALL


SELECT
ANO,MES,MES_ANO,
'TOTAL' AS GRAU, '0799999999' AS CODIGO1,
SUM(CASE WHEN CODIGO1 LIKE '0300000000' AND GRAU LIKE 'GRAU 1' THEN PREV END) -
SUM(CASE WHEN CODIGO1 LIKE '0400000000' AND GRAU LIKE 'GRAU 1' THEN PREV END) - 
SUM(CASE WHEN CODIGO1 LIKE '0500000000' AND GRAU LIKE 'GRAU 1' THEN PREV END) -
SUM(CASE WHEN CODIGO1 LIKE '0600000000' AND GRAU LIKE 'GRAU 1' THEN PREV END) -
SUM(CASE WHEN CODIGO1 LIKE '0700000000' AND GRAU LIKE 'GRAU 1' THEN PREV END) 
AS PREV,
SUM(CASE WHEN CODIGO1 LIKE '0300000000' AND GRAU LIKE 'GRAU 1' THEN REAL END) -
SUM(CASE WHEN CODIGO1 LIKE '0400000000' AND GRAU LIKE 'GRAU 1' THEN REAL END) - 
SUM(CASE WHEN CODIGO1 LIKE '0500000000' AND GRAU LIKE 'GRAU 1' THEN REAL END) -
SUM(CASE WHEN CODIGO1 LIKE '0600000000' AND GRAU LIKE 'GRAU 1' THEN REAL END) - 
SUM(CASE WHEN CODIGO1 LIKE '0700000000' AND GRAU LIKE 'GRAU 1' THEN REAL END)
AS REAL


FROM
(
WITH BAS AS
(



/*PREVISTO BASEADO NA TGFMET*/
SELECT 
ORC.CODIGO,
TO_CHAR(DTREF,'YYYY') AS ANO,
TO_CHAR(DTREF,'MM') AS MES,
TO_CHAR(DTREF,'MM-YYYY') AS MES_ANO,
SUM(PREVREC - PREVDESP) AS PREV,
0 AS REAL
FROM AD_ORCFIN ORC
INNER JOIN AD_ORCFINDET DET ON ORC.CODIGO = DET.CODIGO
INNER JOIN TGFMET MET ON DET.CODNAT = MET.CODNAT
WHERE CODMETA = 7 AND DTREF BETWEEN :P_PERIODO.INI AND :P_PERIODO.FIN
GROUP BY
ORC.CODIGO,
TO_CHAR(DTREF,'YYYY'),
TO_CHAR(DTREF,'MM'),
TO_CHAR(DTREF,'MM-YYYY')

UNION ALL

/*REAL SOMENTE PARTE DO FATURAMENTO*/
SELECT
ORC.CODIGO,
TO_CHAR(DTMOV,'YYYY') AS ANO,
TO_CHAR(DTMOV,'MM') AS MES,
TO_CHAR(DTMOV,'MM-YYYY') AS MES_ANO,
0 AS PREV,
SUM(CASE WHEN CAB.TIPMOV='D' THEN (ITE.VLRTOT-ITE.VLRDESC-ITE.VLRREPRED)*-1 ELSE (ITE.VLRTOT-ITE.VLRDESC-ITE.VLRREPRED) END) AS REAL
FROM TSIEMP EMP
INNER JOIN TGFCAB CAB ON (EMP.CODEMP = CAB.CODEMP)
INNER JOIN TGFVEN VEN ON (CAB.CODVEND = VEN.CODVEND)
INNER JOIN TGFPAR PAR ON (CAB.CODPARC = PAR.CODPARC)
INNER JOIN TGFITE ITE ON (CAB.NUNOTA = ITE.NUNOTA)
INNER JOIN TGFPRO PRO ON (ITE.CODPROD = PRO.CODPROD)
INNER JOIN TGFTOP TOP ON (CAB.CODTIPOPER = TOP.CODTIPOPER AND CAB.DHTIPOPER = TOP.DHALTER)
---LEFT JOIN AD_ITENSGRUPOSATIS GRUS ON (GRUS.CODPROD=PRO.CODPROD AND $P{GRUPOSATIS} IS NOT NULL)
INNER JOIN AD_ORCFIN ORC ON (ORC.TIPOMOV = CAB.TIPMOV OR ORC.TIPOMOV = 'A') AND ORC.CALCFAT = 'S'
INNER JOIN AD_ORCFINDET DET ON DET.CODIGO = ORC.CODIGO AND DET.CODNAT = CAB.CODNAT
WHERE
(TOP.ATUALEST <> 'N' OR TOP.CODTIPOPER = 1112)
AND CAB.TIPMOV IN ('V','D')
AND CAB.STATUSNOTA='L'
AND (CAB.STATUSNFE = 'A' OR CAB.STATUSNFE = 'T'  OR CAB.STATUSNFE = 'S' OR CAB.STATUSNFE IS NULL)
AND ((TOP.ATUALFIN<>0 AND TOP.TIPATUALFIN='I') OR (TOP.CODTIPOPER IN (1112,1113)))
AND ORC.CODIGO IS NOT NULL
AND CAB.DTMOV BETWEEN :P_PERIODO.INI AND :P_PERIODO.FIN
AND (ORC.MARCA = PRO.MARCA OR ORC.MARCA IS NULL)
AND ((:P_LINHABIO = 'S' AND PRO.CODGRUPOPROD <> 1020000) OR (:P_LINHABIO = 'N'))
GROUP BY
TO_CHAR(DTMOV,'YYYY'),
TO_CHAR(DTMOV,'MM'),
TO_CHAR(DTMOV,'MM-YYYY'),
ORC.CODIGO

UNION ALL


/*REAL DA DESPESA VGF_RESULTADO_SATIS DHBAIXA IS NOT NULL*/
SELECT
ORC.CODIGO,
TO_CHAR(FIN.DHBAIXA,'YYYY') AS ANO,
TO_CHAR(FIN.DHBAIXA,'MM') AS MES,
TO_CHAR(FIN.DHBAIXA,'MM-YYYY') AS MES_ANO,
0 AS PREV,
SUM(FIN.VLRBAIXA * FIN.RECDESP) AS REAL
FROM VGF_RESULTADO_SATIS FIN
LEFT JOIN AD_ORCFINDET DET ON FIN.CODNAT = DET.CODNAT
LEFT JOIN AD_ORCFIN ORC ON DET.CODIGO = ORC.CODIGO
WHERE FIN.DHBAIXA IS NOT NULL
AND FIN.DHBAIXA BETWEEN :P_PERIODO.INI AND :P_PERIODO.FIN
AND (NVL(ORC.CALCFAT,'N') = 'N')
GROUP BY
ORC.CODIGO,
TO_CHAR(FIN.DHBAIXA,'YYYY'),
TO_CHAR(FIN.DHBAIXA,'MM'),
TO_CHAR(FIN.DHBAIXA,'MM-YYYY')


),

GRAU1 AS (
SELECT
ANO,
MES,
MES_ANO,
SUBSTR(LPAD(CODIGO, 10, '0'), 1, 2)||'00000000' AS CODIGO1,
'GRAU 1' AS GRAU,
PREV AS PREV,
REAL AS REAL
FROM BAS
GROUP BY
ANO,MES,MES_ANO,SUBSTR(LPAD(CODIGO, 10, '0'), 1, 2)||'00000000',PREV,REAL),

GRAU2 AS (
SELECT
ANO,
MES,
MES_ANO,
SUBSTR(LPAD(CODIGO, 10, '0'), 1, 4)||'000000' AS CODIGO1,
'GRAU 2' AS GRAU,
PREV,
REAL
FROM BAS
GROUP BY
ANO, MES,MES_ANO,SUBSTR(LPAD(CODIGO, 10, '0'), 1, 4)||'000000',PREV,REAL),

GRAU3 AS (
SELECT
ANO,
MES,
MES_ANO,
SUBSTR(LPAD(CODIGO, 10, '0'), 1, 6)||'0000' AS CODIGO1,
'GRAU 3' AS GRAU,
PREV,
REAL
FROM BAS
GROUP BY
ANO, MES,MES_ANO,SUBSTR(LPAD(CODIGO, 10, '0'), 1, 6)||'0000',PREV,REAL),

GRAU4 AS (
SELECT
ANO,
MES,
MES_ANO,
SUBSTR(LPAD(CODIGO, 10, '0'), 1, 8)||'00' AS CODIGO1,
'GRAU 4' AS GRAU,
PREV,
REAL
FROM BAS
GROUP BY
ANO,MES,MES_ANO,SUBSTR(LPAD(CODIGO, 10, '0'), 1, 8)||'00',PREV,REAL),

GRAU5 AS (
SELECT
ANO,
MES,
MES_ANO,
SUBSTR(LPAD(CODIGO, 10, '0'), 1, 10) AS CODIGO1,
'GRAU 5' AS GRAU,
PREV,
REAL
FROM BAS
GROUP BY
ANO, MES, MES_ANO, SUBSTR(LPAD(CODIGO, 10, '0'), 1, 10), PREV, REAL)

SELECT * FROM GRAU1

UNION ALL

SELECT * FROM GRAU2

UNION ALL

SELECT * FROM GRAU3

UNION ALL

SELECT * FROM GRAU4

UNION ALL

SELECT * FROM GRAU5

)
GROUP BY ANO,MES,MES_ANO



UNION ALL




SELECT
ANO,MES,MES_ANO,
'TOTAL' AS GRAU, '0899999998' AS CODIGO1,
SUM(CASE WHEN CODIGO1 LIKE '0800000000' AND GRAU LIKE 'GRAU 1' THEN PREV END) AS PREV,
SUM(CASE WHEN CODIGO1 LIKE '0800000000' AND GRAU LIKE 'GRAU 1' THEN REAL END) AS REAL
FROM
(
WITH BAS AS
(
/*PREVISTO BASEADO NA TGFMET*/
SELECT 
ORC.CODIGO,
TO_CHAR(DTREF,'YYYY') AS ANO,
TO_CHAR(DTREF,'MM') AS MES,
TO_CHAR(DTREF,'MM-YYYY') AS MES_ANO,
SUM(PREVREC - PREVDESP) AS PREV,
0 AS REAL
FROM AD_ORCFIN ORC
INNER JOIN AD_ORCFINDET DET ON ORC.CODIGO = DET.CODIGO
INNER JOIN TGFMET MET ON DET.CODNAT = MET.CODNAT
WHERE CODMETA = 7 AND DTREF BETWEEN :P_PERIODO.INI AND :P_PERIODO.FIN
GROUP BY
ORC.CODIGO,
TO_CHAR(DTREF,'YYYY'),
TO_CHAR(DTREF,'MM'),
TO_CHAR(DTREF,'MM-YYYY')

UNION ALL

/*REAL SOMENTE PARTE DO FATURAMENTO*/
SELECT
ORC.CODIGO,
TO_CHAR(DTMOV,'YYYY') AS ANO,
TO_CHAR(DTMOV,'MM') AS MES,
TO_CHAR(DTMOV,'MM-YYYY') AS MES_ANO,
0 AS PREV,
SUM(CASE WHEN CAB.TIPMOV='D' THEN (ITE.VLRTOT-ITE.VLRDESC-ITE.VLRREPRED)*-1 ELSE (ITE.VLRTOT-ITE.VLRDESC-ITE.VLRREPRED) END) AS REAL
FROM TSIEMP EMP
INNER JOIN TGFCAB CAB ON (EMP.CODEMP = CAB.CODEMP)
INNER JOIN TGFVEN VEN ON (CAB.CODVEND = VEN.CODVEND)
INNER JOIN TGFPAR PAR ON (CAB.CODPARC = PAR.CODPARC)
INNER JOIN TGFITE ITE ON (CAB.NUNOTA = ITE.NUNOTA)
INNER JOIN TGFPRO PRO ON (ITE.CODPROD = PRO.CODPROD)
INNER JOIN TGFTOP TOP ON (CAB.CODTIPOPER = TOP.CODTIPOPER AND CAB.DHTIPOPER = TOP.DHALTER)
---LEFT JOIN AD_ITENSGRUPOSATIS GRUS ON (GRUS.CODPROD=PRO.CODPROD AND $P{GRUPOSATIS} IS NOT NULL)
INNER JOIN AD_ORCFIN ORC ON (ORC.TIPOMOV = CAB.TIPMOV OR ORC.TIPOMOV = 'A') AND ORC.CALCFAT = 'S'
INNER JOIN AD_ORCFINDET DET ON DET.CODIGO = ORC.CODIGO AND DET.CODNAT = CAB.CODNAT
WHERE
(TOP.ATUALEST <> 'N' OR TOP.CODTIPOPER = 1112)
AND CAB.TIPMOV IN ('V','D')
AND CAB.STATUSNOTA='L'
AND (CAB.STATUSNFE = 'A' OR CAB.STATUSNFE = 'T'  OR CAB.STATUSNFE = 'S' OR CAB.STATUSNFE IS NULL)
AND ((TOP.ATUALFIN<>0 AND TOP.TIPATUALFIN='I') OR (TOP.CODTIPOPER IN (1112,1113)))
AND ORC.CODIGO IS NOT NULL
AND CAB.DTMOV BETWEEN :P_PERIODO.INI AND :P_PERIODO.FIN
AND (ORC.MARCA = PRO.MARCA OR ORC.MARCA IS NULL)
AND ((:P_LINHABIO = 'S' AND PRO.CODGRUPOPROD <> 1020000) OR (:P_LINHABIO = 'N'))
GROUP BY
TO_CHAR(DTMOV,'YYYY'),
TO_CHAR(DTMOV,'MM'),
TO_CHAR(DTMOV,'MM-YYYY'),
ORC.CODIGO

UNION ALL


/*REAL DA DESPESA VGF_RESULTADO_SATIS DHBAIXA IS NOT NULL*/
SELECT
ORC.CODIGO,
TO_CHAR(FIN.DHBAIXA,'YYYY') AS ANO,
TO_CHAR(FIN.DHBAIXA,'MM') AS MES,
TO_CHAR(FIN.DHBAIXA,'MM-YYYY') AS MES_ANO,
0 AS PREV,
SUM(FIN.VLRBAIXA * FIN.RECDESP) AS REAL
FROM VGF_RESULTADO_SATIS FIN
LEFT JOIN AD_ORCFINDET DET ON FIN.CODNAT = DET.CODNAT
LEFT JOIN AD_ORCFIN ORC ON DET.CODIGO = ORC.CODIGO
WHERE FIN.DHBAIXA IS NOT NULL
AND FIN.DHBAIXA BETWEEN :P_PERIODO.INI AND :P_PERIODO.FIN
AND (NVL(ORC.CALCFAT,'N') = 'N')
GROUP BY
ORC.CODIGO,
TO_CHAR(FIN.DHBAIXA,'YYYY'),
TO_CHAR(FIN.DHBAIXA,'MM'),
TO_CHAR(FIN.DHBAIXA,'MM-YYYY')


),

GRAU1 AS (
SELECT
ANO,
MES,
MES_ANO,
SUBSTR(LPAD(CODIGO, 10, '0'), 1, 2)||'00000000' AS CODIGO1,
'GRAU 1' AS GRAU,
PREV AS PREV,
REAL AS REAL
FROM BAS
GROUP BY
ANO,MES,MES_ANO,SUBSTR(LPAD(CODIGO, 10, '0'), 1, 2)||'00000000',PREV,REAL),

GRAU2 AS (
SELECT
ANO,
MES,
MES_ANO,
SUBSTR(LPAD(CODIGO, 10, '0'), 1, 4)||'000000' AS CODIGO1,
'GRAU 2' AS GRAU,
PREV,
REAL
FROM BAS
GROUP BY
ANO, MES,MES_ANO,SUBSTR(LPAD(CODIGO, 10, '0'), 1, 4)||'000000',PREV,REAL),

GRAU3 AS (
SELECT
ANO,
MES,
MES_ANO,
SUBSTR(LPAD(CODIGO, 10, '0'), 1, 6)||'0000' AS CODIGO1,
'GRAU 3' AS GRAU,
PREV,
REAL
FROM BAS
GROUP BY
ANO, MES,MES_ANO,SUBSTR(LPAD(CODIGO, 10, '0'), 1, 6)||'0000',PREV,REAL),

GRAU4 AS (
SELECT
ANO,
MES,
MES_ANO,
SUBSTR(LPAD(CODIGO, 10, '0'), 1, 8)||'00' AS CODIGO1,
'GRAU 4' AS GRAU,
PREV,
REAL
FROM BAS
GROUP BY
ANO,MES,MES_ANO,SUBSTR(LPAD(CODIGO, 10, '0'), 1, 8)||'00',PREV,REAL),

GRAU5 AS (
SELECT
ANO,
MES,
MES_ANO,
SUBSTR(LPAD(CODIGO, 10, '0'), 1, 10) AS CODIGO1,
'GRAU 5' AS GRAU,
PREV,
REAL
FROM BAS
GROUP BY
ANO, MES, MES_ANO, SUBSTR(LPAD(CODIGO, 10, '0'), 1, 10), PREV, REAL)

SELECT * FROM GRAU1

UNION ALL

SELECT * FROM GRAU2

UNION ALL

SELECT * FROM GRAU3

UNION ALL

SELECT * FROM GRAU4

UNION ALL

SELECT * FROM GRAU5

)
GROUP BY ANO,MES,MES_ANO



UNION ALL


SELECT
ANO,MES,MES_ANO,
'TOTAL' AS GRAU, '0899999999' AS CODIGO1,
SUM(CASE WHEN CODIGO1 LIKE '0300000000' AND GRAU LIKE 'GRAU 1' THEN PREV END) -
SUM(CASE WHEN CODIGO1 LIKE '0400000000' AND GRAU LIKE 'GRAU 1' THEN PREV END) - 
SUM(CASE WHEN CODIGO1 LIKE '0500000000' AND GRAU LIKE 'GRAU 1' THEN PREV END) -
SUM(CASE WHEN CODIGO1 LIKE '0600000000' AND GRAU LIKE 'GRAU 1' THEN PREV END) -
SUM(CASE WHEN CODIGO1 LIKE '0700000000' AND GRAU LIKE 'GRAU 1' THEN PREV END) -
SUM(CASE WHEN CODIGO1 LIKE '0800000000' AND GRAU LIKE 'GRAU 1' THEN PREV END)
AS PREV,
SUM(CASE WHEN CODIGO1 LIKE '0300000000' AND GRAU LIKE 'GRAU 1' THEN REAL END) -
SUM(CASE WHEN CODIGO1 LIKE '0400000000' AND GRAU LIKE 'GRAU 1' THEN REAL END) - 
SUM(CASE WHEN CODIGO1 LIKE '0500000000' AND GRAU LIKE 'GRAU 1' THEN REAL END) -
SUM(CASE WHEN CODIGO1 LIKE '0600000000' AND GRAU LIKE 'GRAU 1' THEN REAL END) -
SUM(CASE WHEN CODIGO1 LIKE '0700000000' AND GRAU LIKE 'GRAU 1' THEN REAL END) -
SUM(CASE WHEN CODIGO1 LIKE '0800000000' AND GRAU LIKE 'GRAU 1' THEN REAL END)
AS REAL
FROM
(
WITH BAS AS
(
/*PREVISTO BASEADO NA TGFMET*/
SELECT 
ORC.CODIGO,
TO_CHAR(DTREF,'YYYY') AS ANO,
TO_CHAR(DTREF,'MM') AS MES,
TO_CHAR(DTREF,'MM-YYYY') AS MES_ANO,
SUM(PREVREC - PREVDESP) AS PREV,
0 AS REAL
FROM AD_ORCFIN ORC
INNER JOIN AD_ORCFINDET DET ON ORC.CODIGO = DET.CODIGO
INNER JOIN TGFMET MET ON DET.CODNAT = MET.CODNAT
WHERE CODMETA = 7 AND DTREF BETWEEN :P_PERIODO.INI AND :P_PERIODO.FIN
GROUP BY
ORC.CODIGO,
TO_CHAR(DTREF,'YYYY'),
TO_CHAR(DTREF,'MM'),
TO_CHAR(DTREF,'MM-YYYY')

UNION ALL

/*REAL SOMENTE PARTE DO FATURAMENTO*/
SELECT
ORC.CODIGO,
TO_CHAR(DTMOV,'YYYY') AS ANO,
TO_CHAR(DTMOV,'MM') AS MES,
TO_CHAR(DTMOV,'MM-YYYY') AS MES_ANO,
0 AS PREV,
SUM(CASE WHEN CAB.TIPMOV='D' THEN (ITE.VLRTOT-ITE.VLRDESC-ITE.VLRREPRED)*-1 ELSE (ITE.VLRTOT-ITE.VLRDESC-ITE.VLRREPRED) END) AS REAL
FROM TSIEMP EMP
INNER JOIN TGFCAB CAB ON (EMP.CODEMP = CAB.CODEMP)
INNER JOIN TGFVEN VEN ON (CAB.CODVEND = VEN.CODVEND)
INNER JOIN TGFPAR PAR ON (CAB.CODPARC = PAR.CODPARC)
INNER JOIN TGFITE ITE ON (CAB.NUNOTA = ITE.NUNOTA)
INNER JOIN TGFPRO PRO ON (ITE.CODPROD = PRO.CODPROD)
INNER JOIN TGFTOP TOP ON (CAB.CODTIPOPER = TOP.CODTIPOPER AND CAB.DHTIPOPER = TOP.DHALTER)
---LEFT JOIN AD_ITENSGRUPOSATIS GRUS ON (GRUS.CODPROD=PRO.CODPROD AND $P{GRUPOSATIS} IS NOT NULL)
INNER JOIN AD_ORCFIN ORC ON (ORC.TIPOMOV = CAB.TIPMOV OR ORC.TIPOMOV = 'A') AND ORC.CALCFAT = 'S'
INNER JOIN AD_ORCFINDET DET ON DET.CODIGO = ORC.CODIGO AND DET.CODNAT = CAB.CODNAT
WHERE
(TOP.ATUALEST <> 'N' OR TOP.CODTIPOPER = 1112)
AND CAB.TIPMOV IN ('V','D')
AND CAB.STATUSNOTA='L'
AND (CAB.STATUSNFE = 'A' OR CAB.STATUSNFE = 'T'  OR CAB.STATUSNFE = 'S' OR CAB.STATUSNFE IS NULL)
AND ((TOP.ATUALFIN<>0 AND TOP.TIPATUALFIN='I') OR (TOP.CODTIPOPER IN (1112,1113)))
AND ORC.CODIGO IS NOT NULL
AND CAB.DTMOV BETWEEN :P_PERIODO.INI AND :P_PERIODO.FIN
AND (ORC.MARCA = PRO.MARCA OR ORC.MARCA IS NULL)
AND ((:P_LINHABIO = 'S' AND PRO.CODGRUPOPROD <> 1020000) OR (:P_LINHABIO = 'N'))
GROUP BY
TO_CHAR(DTMOV,'YYYY'),
TO_CHAR(DTMOV,'MM'),
TO_CHAR(DTMOV,'MM-YYYY'),
ORC.CODIGO

UNION ALL


/*REAL DA DESPESA VGF_RESULTADO_SATIS DHBAIXA IS NOT NULL*/
SELECT
ORC.CODIGO,
TO_CHAR(FIN.DHBAIXA,'YYYY') AS ANO,
TO_CHAR(FIN.DHBAIXA,'MM') AS MES,
TO_CHAR(FIN.DHBAIXA,'MM-YYYY') AS MES_ANO,
0 AS PREV,
SUM(FIN.VLRBAIXA * FIN.RECDESP) AS REAL
FROM VGF_RESULTADO_SATIS FIN
LEFT JOIN AD_ORCFINDET DET ON FIN.CODNAT = DET.CODNAT
LEFT JOIN AD_ORCFIN ORC ON DET.CODIGO = ORC.CODIGO
WHERE FIN.DHBAIXA IS NOT NULL
AND FIN.DHBAIXA BETWEEN :P_PERIODO.INI AND :P_PERIODO.FIN
AND (NVL(ORC.CALCFAT,'N') = 'N')
GROUP BY
ORC.CODIGO,
TO_CHAR(FIN.DHBAIXA,'YYYY'),
TO_CHAR(FIN.DHBAIXA,'MM'),
TO_CHAR(FIN.DHBAIXA,'MM-YYYY')


),

GRAU1 AS (
SELECT
ANO,
MES,
MES_ANO,
SUBSTR(LPAD(CODIGO, 10, '0'), 1, 2)||'00000000' AS CODIGO1,
'GRAU 1' AS GRAU,
PREV AS PREV,
REAL AS REAL
FROM BAS
GROUP BY
ANO,MES,MES_ANO,SUBSTR(LPAD(CODIGO, 10, '0'), 1, 2)||'00000000',PREV,REAL),

GRAU2 AS (
SELECT
ANO,
MES,
MES_ANO,
SUBSTR(LPAD(CODIGO, 10, '0'), 1, 4)||'000000' AS CODIGO1,
'GRAU 2' AS GRAU,
PREV,
REAL
FROM BAS
GROUP BY
ANO, MES,MES_ANO,SUBSTR(LPAD(CODIGO, 10, '0'), 1, 4)||'000000',PREV,REAL),

GRAU3 AS (
SELECT
ANO,
MES,
MES_ANO,
SUBSTR(LPAD(CODIGO, 10, '0'), 1, 6)||'0000' AS CODIGO1,
'GRAU 3' AS GRAU,
PREV,
REAL
FROM BAS
GROUP BY
ANO, MES,MES_ANO,SUBSTR(LPAD(CODIGO, 10, '0'), 1, 6)||'0000',PREV,REAL),

GRAU4 AS (
SELECT
ANO,
MES,
MES_ANO,
SUBSTR(LPAD(CODIGO, 10, '0'), 1, 8)||'00' AS CODIGO1,
'GRAU 4' AS GRAU,
PREV,
REAL
FROM BAS
GROUP BY
ANO,MES,MES_ANO,SUBSTR(LPAD(CODIGO, 10, '0'), 1, 8)||'00',PREV,REAL),

GRAU5 AS (
SELECT
ANO,
MES,
MES_ANO,
SUBSTR(LPAD(CODIGO, 10, '0'), 1, 10) AS CODIGO1,
'GRAU 5' AS GRAU,
PREV,
REAL
FROM BAS
GROUP BY
ANO, MES, MES_ANO, SUBSTR(LPAD(CODIGO, 10, '0'), 1, 10), PREV, REAL)

SELECT * FROM GRAU1

UNION ALL

SELECT * FROM GRAU2

UNION ALL

SELECT * FROM GRAU3

UNION ALL

SELECT * FROM GRAU4

UNION ALL

SELECT * FROM GRAU5

)
GROUP BY ANO,MES,MES_ANO



) A
LEFT JOIN B ON A.CODIGO1 = B.CODIGO1

WHERE A.CODIGO1 NOT IN ('00','0000','000000','00000000')
GROUP BY
A.ANO,A.MES,A.MES_ANO,
A.CODIGO1,B.DESCRICAO,B.GRAU, A.PREV,A.REAL

)

GROUP BY 
CODIGO1,
DESCRICAO,
GRAU
ORDER BY CODIGO1