/*LEFT JOIN TGFPAR PAR ON (MET.CODPARC = PAR.CODPARC)
AND CAB.CODPARC = MET.CODPARC
LEFT JOIN TGFVEN VEN ON (MET.CODVEND = VEN.CODVEND)
CAB.CODVEND = VEN.CODVEND
*/




LEFT JOIN AD_PRECOMARCA PRC ON (
    MET.MARCA = PRC.MARCA
    AND PRC.CODMETA = MET.CODMETA
    AND PRC.DTREF = '01/07/2023'
)

LEFT JOIN TGFCAB CAB ON TRUNC(DTMOV, 'MM') = MET.DTREF
AND CAB.TIPMOV IN ('V', 'D')
AND CAB.STATUSNOTA = 'L'
AND (
    CAB.STATUSNFE IN ('A', 'T', 'S')
    OR CAB.STATUSNFE IS NULL
)

AND (
    SELECT
        COUNT(TOP.CODTIPOPER)
    FROM
        TGFTOP TOP
    WHERE
        TOP.CODTIPOPER = CAB.CODTIPOPER
        AND TOP.DHALTER = (
            SELECT
                MAX(DHALTER)
            FROM
                TGFTOP
            WHERE
                CODTIPOPER = CAB.CODTIPOPER
        )
        AND TOP.ATUALEST <> 'N'
        AND TOP.GOLSINAL = -1
) > 0
LEFT JOIN TGFPRO PRO ON PRO.MARCA = MET.MARCA
LEFT JOIN TGFITE ITE ON CAB.NUNOTA = ITE.NUNOTA
AND PRO.CODPROD = ITE.CODPROD