/* Razão Auxilar das Contas que quebra por AD_CODPARC */
SELECT	P.CODEMP,
		P.AD_CODPARC,
		P.NOMEPARC,
		P.CODCTACTB,
		P.CTACTB,
		P.DESCRCTA,
		CASE WHEN SUM(P.SALDOANT) < 0 THEN SUM(P.SALDOANT)*-1 ELSE SUM(P.SALDOANT) END AS SALDOANT,
		CASE WHEN SUM(P.DEBITO) < 0 THEN SUM(P.DEBITO)*-1 ELSE SUM(P.DEBITO) END AS DEBITO,
		CASE WHEN SUM(P.CREDITO) < 0 THEN SUM(P.CREDITO)*-1 ELSE SUM(P.CREDITO) END AS CREDITO,
		CASE WHEN SUM(P.SALDOANT) + SUM(P.DEBITO) + SUM(P.CREDITO) < 0 
		THEN (SUM(P.SALDOANT) + SUM(P.DEBITO) + SUM(P.CREDITO))*-1
		ELSE (SUM(P.SALDOANT) + SUM(P.DEBITO) + SUM(P.CREDITO)) END AS SALDOATUAL,
		CASE WHEN P.CTACTB < '2' 
			 THEN CASE WHEN (SUM(P.SALDOANT) + SUM(P.DEBITO) + SUM(P.CREDITO)) >= 0 
			      THEN 'D' 
				  ELSE 'C' 
				  END
			 ELSE CASE WHEN P.CTACTB >= '2' AND P.CTACTB < '3'
				  THEN CASE WHEN (SUM(P.SALDOANT) + SUM(P.DEBITO) + SUM(P.CREDITO)) <= 0 
							THEN 'C' 
							ELSE 'D' 
							END
				  END			
			 END AS DC

FROM		

(/* Pega as Contas de Ativo */
SELECT	LAN.CODEMP,
		LAN.AD_CODPARC,
		LAN.CODCTACTB,
		PLA.CTACTB,
		PLA.DESCRCTA,
		CASE WHEN LAN.AD_CODPARC = 0 THEN 'SEM PARCEIRO' ELSE PAR.NOMEPARC END AS NOMEPARC,
		NVL(SUM(CASE WHEN TIPLANC = 'D' THEN LAN.VLRLANC END), 0) + NVL(SUM(CASE WHEN TIPLANC = 'R' THEN LAN.VLRLANC*-1 END), 0) AS SALDOANT,
		0 AS DEBITO,
		0 AS CREDITO


FROM	TCBLAN LAN
LEFT JOIN TGFPAR PAR ON PAR.CODPARC = LAN.AD_CODPARC
INNER JOIN TCBPLA PLA ON PLA.CODCTACTB = LAN.CODCTACTB
WHERE	LAN.REFERENCIA < :DTREFERENCIA
AND		LAN.CODEMP = :CODEMP
AND		LAN.CODCTACTB = :CODCTACTB
AND		(LAN.AD_CODPARC = :CODPARC OR :CODPARC IS NULL)
AND		PLA.CTACTB >= '1'
AND		PLA.CTACTB < '2'

GROUP BY 	LAN.CODEMP,
			LAN.AD_CODPARC,
			PAR.NOMEPARC,
			LAN.CODCTACTB,
			PLA.CTACTB,
			PLA.DESCRCTA
			
UNION ALL

SELECT	LAN.CODEMP,
		LAN.AD_CODPARC,
		LAN.CODCTACTB,
		PLA.CTACTB,
		PLA.DESCRCTA,
		CASE WHEN LAN.AD_CODPARC = 0 THEN 'SEM PARCEIRO' ELSE PAR.NOMEPARC END AS NOMEPARC,
		0 AS SALDOANT,
		NVL(SUM(CASE WHEN LAN.TIPLANC = 'D' THEN LAN.VLRLANC END), 0) AS DEBITO,
		NVL(SUM(CASE WHEN LAN.TIPLANC = 'R' THEN LAN.VLRLANC*-1 END), 0) AS CREDITO


FROM	TCBLAN LAN
LEFT JOIN TGFPAR PAR ON PAR.CODPARC = LAN.AD_CODPARC
INNER JOIN TCBPLA PLA ON PLA.CODCTACTB = LAN.CODCTACTB
WHERE	LAN.REFERENCIA = :DTREFERENCIA
AND		LAN.CODEMP = :CODEMP
AND		LAN.CODCTACTB = :CODCTACTB
AND		(LAN.AD_CODPARC = :CODPARC OR :CODPARC IS NULL)
AND		PLA.CTACTB >= '1'
AND		PLA.CTACTB < '2'

GROUP BY 	LAN.CODEMP,
			LAN.AD_CODPARC,
			PAR.NOMEPARC,
			LAN.CODCTACTB,
			PLA.CTACTB,
			PLA.DESCRCTA

UNION ALL

/* Pega as Contas de Passivo */		
SELECT	LAN.CODEMP,
		LAN.AD_CODPARC,
		LAN.CODCTACTB,
		PLA.CTACTB,
		PLA.DESCRCTA,
		CASE WHEN LAN.AD_CODPARC = 0 THEN 'SEM PARCEIRO' ELSE PAR.NOMEPARC END AS NOMEPARC,
		NVL(SUM(CASE WHEN TIPLANC = 'D' THEN LAN.VLRLANC END), 0) + NVL(SUM(CASE WHEN TIPLANC = 'R' THEN LAN.VLRLANC*-1 END), 0) AS SALDOANT,
		0 AS DEBITO,
		0 AS CREDITO


FROM	TCBLAN LAN
LEFT JOIN TGFPAR PAR ON PAR.CODPARC = LAN.AD_CODPARC
INNER JOIN TCBPLA PLA ON PLA.CODCTACTB = LAN.CODCTACTB
WHERE	LAN.REFERENCIA < :DTREFERENCIA
AND		LAN.CODEMP = :CODEMP
AND		LAN.CODCTACTB = :CODCTACTB
AND		(LAN.AD_CODPARC = :CODPARC OR :CODPARC IS NULL)
AND		PLA.CTACTB >= '2'
AND		PLA.CTACTB < '3'

GROUP BY 	LAN.CODEMP,
			LAN.AD_CODPARC,
			PAR.NOMEPARC,
			LAN.CODCTACTB,
			PLA.CTACTB,
			PLA.DESCRCTA
			
UNION ALL

SELECT	LAN.CODEMP,
		LAN.AD_CODPARC,
		LAN.CODCTACTB,
		PLA.CTACTB,
		PLA.DESCRCTA,
		CASE WHEN LAN.AD_CODPARC = 0 THEN 'SEM PARCEIRO' ELSE PAR.NOMEPARC END AS NOMEPARC,
		0 AS SALDOANT,
		NVL(SUM(CASE WHEN LAN.TIPLANC = 'D' THEN LAN.VLRLANC END), 0) AS DEBITO,
		NVL(SUM(CASE WHEN LAN.TIPLANC = 'R' THEN LAN.VLRLANC*-1 END), 0) AS CREDITO


FROM	TCBLAN LAN
LEFT JOIN TGFPAR PAR ON PAR.CODPARC = LAN.AD_CODPARC
INNER JOIN TCBPLA PLA ON PLA.CODCTACTB = LAN.CODCTACTB
WHERE	LAN.REFERENCIA = :DTREFERENCIA
AND		LAN.CODEMP = :CODEMP
AND		LAN.CODCTACTB = :CODCTACTB
AND		(LAN.AD_CODPARC = :CODPARC OR :CODPARC IS NULL)
AND		PLA.CTACTB >= '2'
AND		PLA.CTACTB < '3'

GROUP BY 	LAN.CODEMP,
			LAN.AD_CODPARC,
			PAR.NOMEPARC,
			LAN.CODCTACTB,
			PLA.CTACTB,
			PLA.DESCRCTA) P
			
GROUP BY 	P.CODEMP,
			P.AD_CODPARC,
			P.NOMEPARC,
			P.CODCTACTB,
			P.CTACTB,
			P.DESCRCTA

ORDER BY 2
