SELECT	LAN.CODEMP,
		PLA.CTACTB,
		PLA.DESCRCTA,
		LAN.REFERENCIA,
		LAN.NUMLOTE,
		LAN.NUMLANC,
		LAN.TIPLANC,
		LAN.CODCTACTB,
		LAN.CODCONPAR,
		LAN.AD_CODPARC,
		CASE WHEN LAN.AD_CODPARC = 0 THEN 'SEM PARCEIRO' ELSE PAR.NOMEPARC END AS NOMEPARC,
		LAN.CODCENCUS,
		LAN.DTMOV,
		NVL((CASE WHEN LAN.TIPLANC = 'D' THEN LAN.VLRLANC END), 0) AS DEBITO,
		NVL((CASE WHEN LAN.TIPLANC = 'R' THEN LAN.VLRLANC END), 0) AS CREDITO,
		LAN.CODHISTCTB,
		LAN.COMPLHIST,
		LAN.NUMDOC,
		LAN.VENCIMENTO,
		LAN.LIBERADO,
		LAN.CODUSU,
		LAN.CODPROJ,
		PRJ.IDENTIFICACAO,
		LAN.SEQUENCIA,
		CASE WHEN LAN.TIPLANC = 'D' THEN 'RED' ELSE 'BLUE' END AS FGCOLOR
		
FROM TCBLAN LAN LEFT JOIN TGFPAR PAR ON (PAR.CODPARC = LAN.AD_CODPARC)
JOIN TCBPLA PLA ON (PLA.CODCTACTB = LAN.CODCTACTB)
LEFT JOIN TCSPRJ PRJ ON(LAN.CODPROJ = PRJ.CODPROJ)

WHERE	LAN.REFERENCIA = :DTREFERENCIA
AND		LAN.CODEMP = :CODEMP
AND		LAN.CODCTACTB = :CODCTACTB
AND		(LAN.AD_CODPARC = :CODPARC OR :CODPARC IS NULL)
AND		((PLA.CTACTB >= '2' AND PLA.CTACTB < '3') OR (PLA.CTACTB >= '1' AND PLA.CTACTB < '2'))

ORDER BY 5, 6