WITH 
MET AS (
    SELECT 
        MET.DTREF,
        MET.CODVEND,
        MET.CODPARC,
        MET.MARCA,
        MET.QTDPREV,
        NVL(PRC.VLRVENDALT, 0) * MET.QTDPREV AS VLRPREV
    FROM TGFMET MET
    LEFT JOIN AD_PRECOMARCA PRC ON MET.MARCA = PRC.MARCA AND PRC.CODMETA = MET.CODMETA AND PRC.DTREF = (SELECT MAX(DTREF) FROM AD_PRECOMARCA WHERE CODMETA = MET.CODMETA AND DTREF <= MET.DTREF AND MARCA = MET.MARCA)
    WHERE MET.CODMETA = 4)
SELECT 
    SUM(QTDPREV) AS QTDPREV,
    SUM(QTD) AS QTDREAL,
    SUM(VLRPREV) AS VLR_PREV,
    SUM(VLR) AS VLR_REAL,
    CASE WHEN SUM(QTDPREV) = 0 THEN 0 ELSE SUM(QTD) * 100 / NULLIF(SUM(QTDPREV), 0) END AS PERC,
    CASE WHEN SUM(VLRPREV) = 0 THEN 0 ELSE NVL(SUM(VLR) * 100 / NULLIF(SUM(VLRPREV), 0), 0) END AS PERC_VLR
FROM (
    SELECT 
        *
    FROM VGF_VENDAS_SATIS VGF
    LEFT JOIN MET ON VGF.CODVEND = MET.CODVEND AND VGF.CODPARC = MET.CODPARC AND VGF.MARCA = MET.MARCA AND VGF.DTMOV BETWEEN MET.DTREF AND LAST_DAY(MET.DTREF)
    WHERE VGF.DTMOV BETWEEN '01-07-2024' AND '03-07-2024' --AND ((VGF.ATUALFIN <> 0 AND VGF.TIPATUALFIN = 'I') OR (VGF.CODTIPOPER IN (1112, 1113)))
/*
    AND (VGF.CODGRUPOPROD = :P_GRUPOPROD OR :P_GRUPOPROD IS NULL)
    AND (VGF.CODPARC = :P_CODPARC OR :P_CODPARC IS NULL)
    AND (VGF.CODVEND IN :P_CODVEND) AND (CODGER IN :P_COORD)
    AND (VGF.MARCA IN :P_MARCA)
    AND
(
CODVEND = (SELECT CODVEND FROM TSIUSU WHERE CODUSU = STP_GET_CODUSULOGADO) 
OR CODVEND IN (SELECT VEN.CODVEND FROM TGFVEN VEN, TSIUSU USU WHERE USU.CODVEND = VEN.CODGER AND USU.CODUSU = STP_GET_CODUSULOGADO) 
OR (SELECT AD_GESTOR_META FROM TSIUSU WHERE CODUSU = STP_GET_CODUSULOGADO) = 'S' 
*/
)

