SELECT
    CODPROD,
    DESCRICAO,
    AVG(PRECO_COMPRA_LIQ) AS PRECO_COMPRA_LIQ
FROM
(
    SELECT 
        ITE.CODPROD,
        PRO.DESCRPROD AS DESCRICAO,
        ITE.CODVOL AS UN,
        ITE.NUNOTA AS NUNOTA,
        F_DESCROPC('TGFCAB','TIPMOV',CAB.TIPMOV) AS TIPMOV,
        VEN.CODVEND||'-'||VEN.APELIDO AS COMPRADOR,
        ITE.QTDNEG,
        ITE.VLRTOT,
        ITE.VLRDESC,
        (ITE.VLRTOT) / NULLIF(ITE.QTDNEG,0) AS PRECO_COMPRA,
        (ITE.VLRTOT - ITE.VLRDESC) / NULLIF(ITE.QTDNEG,0) AS PRECO_COMPRA_LIQ,
        ITE.VLRDESC AS SAVING,
        ((ITE.VLRTOT) / NULLIF(ITE.QTDNEG,0)) - ((ITE.VLRTOT - ITE.VLRDESC) / NULLIF(ITE.QTDNEG,0)) AS SAVING_UN,
        (ITE.VLRDESC / NULLIF(ITE.VLRTOT,0)) * 100 AS PERCENTUAL_SAVING
      FROM TGFITE ITE
      INNER JOIN TGFPRO PRO ON (ITE.CODPROD = PRO.CODPROD)
      INNER JOIN TGFCAB CAB ON (ITE.NUNOTA = CAB.NUNOTA)
      INNER JOIN TGFTOP TOP ON ( CAB.CODTIPOPER = TOP.CODTIPOPER AND CAB.DHTIPOPER = ( SELECT MAX (TOP.DHALTER) FROM TGFTOP WHERE CODTIPOPER = TOP.CODTIPOPER ) )
      INNER JOIN TGFVEN VEN ON (CAB.CODVEND = VEN.CODVEND)
     WHERE CAB.TIPMOV = 'O'
       AND CAB.STATUSNOTA = 'L'
       AND CAB.DTNEG < '01-06-2024')
GROUP BY CODPROD, DESCRICAO
ORDER BY 2,3 DESC