SELECT B.*
--CASE WHEN IATV.CODEXEC ISnull AND IATV.DHACEITE ISnull THEN 'G' END  AS SITUACAO
FROM (
SELECT 
TPRIPA.IDIPROC AS IDIPROC,TPRIPA.CODPRODPA AS CODPRODPA,TPRIPA.CONCLUIDO AS CONCLUIDO,TPRIPA.CONTROLEPA AS CONTROLEPA,TPRIPA.DTFAB AS DTFAB,TPRIPA.DTVAL AS DTVAL,
TPRIPA.NROLOTE AS NROLOTE,TPRIPA.QTDPRODUZIR AS QTDPRODUZIR,TPRIPA.QTDPRODUZIR_ORIGINAL AS QTDPRODUZIR_ORIGINAL, 
( SELECT REFERENCIA FROM TGFPRO PRO WHERE CODPROD = TPRIPA.CODPRODPA) AS REFERENCIA, 
( SELECT
TPRIPA.QTDPRODUZIR - NVL(SUM(NOTA.QTDNEG), 0) - (CASE
WHEN NVL(SUM(NOTA.QTDNEG), 0) > 0 THEN NVL(MAX(APO_PERDA.QTDPERDA), 0)
ELSE 0 
END) AS SALDO
FROM
TPRIPA IPA
INNER JOIN TPRIPROC IPROC ON (IPA.IDIPROC = IPROC.IDIPROC)
LEFT JOIN (
SELECT IDIPROC, ITE.QTDNEG, ITE.CODPROD, ITE.CONTROLE 
FROM TGFCAB CAB INNER JOIN TGFITE ITE ON (ITE.NUNOTA = CAB.NUNOTA)
INNER JOIN TPRROPE ROPE ON (ROPE.NUNOTA = CAB.NUNOTA)
INNER JOIN TPROEST OEST ON (OEST.IDEFX = ROPE.IDEFX AND OEST.SEQOPER = ROPE.SEQOPER)
WHERE CAB.IDIPROC IS NOT NULL 
AND OEST.TIPOITENS = 'PA'
AND OEST.QUANDO = 'PA'
AND CAB.TIPMOV = 'F'
) NOTA ON (NOTA.IDIPROC = IPROC.IDIPROC AND NOTA.CODPROD = IPA.CODPRODPA AND (NVL(NOTA.CONTROLE, ' ') = ' ' OR NVL(NOTA.CONTROLE, ' ') = NVL(IPA.CONTROLEPA, ' ')))
LEFT JOIN (
SELECT  NVL(SUM(APA.QTDPERDA), 0) AS QTDPERDA , IATV.IDIPROC, APA.CODPRODPA, APA.CONTROLEPA
FROM TPRAPA APA
INNER JOIN TPRAPO APO ON(APO.NUAPO = APA.NUAPO)
INNER JOIN TPRIATV IATV ON(IATV.IDIATV = APO.IDIATV)
WHERE APO.SITUACAO = 'C'
AND APA.QTDPERDA > 0
GROUP BY IATV.IDIPROC, APA.CODPRODPA, APA.CONTROLEPA
) APO_PERDA ON (APO_PERDA.IDIPROC = IPROC.IDIPROC AND APO_PERDA.CODPRODPA = IPA.CODPRODPA AND (NVL(APO_PERDA.CONTROLEPA, ' ') = ' ' OR NVL(APO_PERDA.CONTROLEPA, ' ') = NVL(IPA.CONTROLEPA, ' ')))
WHERE IPA.CODPRODPA = TPRIPA.CODPRODPA
AND NVL(IPA.CONTROLEPA, ' ') = TPRIPA.CONTROLEPA
AND IPROC.STATUSPROC IN ('A', 'R', 'P2', 'S', 'S2')
AND IPROC.IDIPROC = TPRIPA.IDIPROC) AS SALDOOP FROM TPRIPA /*SQL_92_JOINED_TABLES*/   --WHERE (TPRIPA.IDIPROC = ?) 


)B
--LEFT JOIN 