CREATE OR REPLACE TRIGGER "SATISTST"."STP_BLOQUEIO_EXCLUSAO_SATIS" BEFORE DELETE ON TGFCAB FOR EACH ROW
DECLARE
   P_CONTAR INT;
BEGIN
    IF :OLD.CODTIPOPER IN (1001, 1009) AND :OLD.STATUSNOTA = 'L' THEN
        SELECT COUNT(*) INTO P_CONTAR FROM TSIUSU WHERE CODUSU = STP_GET_CODUSULOGADO AND AD_GESTORVENDAS = 'S';
        IF P_CONTAR > 0 THEN
            --PROSSEGUIR COM A EXCLUSAO
            NULL;
        ELSE
            -- NAO PROSSEGUIR COM EXCLUSAO
            RAISE_APPLICATION_ERROR (-20101, 'Exclusao PROIBIDA! Apenas gestores de venda podem excluir pedidos de venda confirmados.');
        END IF;
    END IF;
END;
/