SELECT 
    TPRIPA.IDIPROC,
    TPRIPA.DTFAB,
    TPRIPA.CODPRODPA,
    PRO.DESCRPROD,
    TPRIPA.QTDPRODUZIR,
    PRO.CODVOL,
    TPRIPA.NROLOTE,
    (SELECT MIN(TPRIATV.DHINICIO) FROM TPRIATV WHERE TPRIATV.IDIPROC = TPRIPA.IDIPROC) AS DHINICIO,
    --PRO.REFERENCIA,
    --TPRIPA.QTDPRODUZIR_ORIGINAL,
    --TPRIPA.CONCLUIDO,
    --TPRIPA.CONTROLEPA,
    --TPRIPA.DTVAL,
    (
        SELECT 
            TPRIPA.QTDPRODUZIR - NVL(SUM(NOTA.QTDNEG), 0) - 
            CASE 
                WHEN NVL(SUM(NOTA.QTDNEG), 0) > 0 THEN NVL(MAX(APO_PERDA.QTDPERDA), 0)
                ELSE 0 
            END AS SALDO
        FROM TPRIPA IPA
        INNER JOIN TPRIPROC IPROC ON IPA.IDIPROC = IPROC.IDIPROC
        LEFT JOIN (
            SELECT 
                CAB.IDIPROC, 
                ITE.QTDNEG, 
                ITE.CODPROD, 
                ITE.CONTROLE 
            FROM TGFCAB CAB 
            INNER JOIN TGFITE ITE ON ITE.NUNOTA = CAB.NUNOTA
            INNER JOIN TPRROPE ROPE ON ROPE.NUNOTA = CAB.NUNOTA
            INNER JOIN TPROEST OEST ON OEST.IDEFX = ROPE.IDEFX 
                AND OEST.SEQOPER = ROPE.SEQOPER
            WHERE CAB.IDIPROC IS NOT NULL 
                AND OEST.TIPOITENS = 'PA'
                AND OEST.QUANDO = 'PA'
                AND CAB.TIPMOV = 'F'
        ) NOTA ON NOTA.IDIPROC = IPROC.IDIPROC 
            AND NOTA.CODPROD = IPA.CODPRODPA 
            AND (NVL(NOTA.CONTROLE, ' ') = ' ' OR NVL(NOTA.CONTROLE, ' ') = NVL(IPA.CONTROLEPA, ' '))
        LEFT JOIN (
            SELECT  
                IATV.IDIPROC, 
                APA.CODPRODPA, 
                APA.CONTROLEPA,
                NVL(SUM(APA.QTDPERDA), 0) AS QTDPERDA
            FROM TPRAPA APA
            INNER JOIN TPRAPO APO ON APO.NUAPO = APA.NUAPO
            INNER JOIN TPRIATV IATV ON IATV.IDIATV = APO.IDIATV
            WHERE APO.SITUACAO = 'C'
                AND APA.QTDPERDA > 0
            GROUP BY IATV.IDIPROC, APA.CODPRODPA, APA.CONTROLEPA
        ) APO_PERDA ON APO_PERDA.IDIPROC = IPROC.IDIPROC 
            AND APO_PERDA.CODPRODPA = IPA.CODPRODPA 
            AND (NVL(APO_PERDA.CONTROLEPA, ' ') = ' ' OR NVL(APO_PERDA.CONTROLEPA, ' ') = NVL(IPA.CONTROLEPA, ' '))
        WHERE IPA.CODPRODPA = TPRIPA.CODPRODPA
            AND NVL(IPA.CONTROLEPA, ' ') = TPRIPA.CONTROLEPA
            AND IPROC.STATUSPROC IN ('A', 'R', 'P2', 'S', 'S2')
            AND IPROC.IDIPROC = TPRIPA.IDIPROC
    ) AS SALDOOP 
FROM TPRIPA
INNER JOIN TGFPRO PRO ON TPRIPA.CODPRODPA = PRO.CODPROD
WHERE TPRIPA.IDIPROC = 12356;







SELECT  
    IATV.IDIATV,
    IATV.IDEFX,
    IATV.IDIPROC, 
    IATV.CODWCP,
    APA.CODPRODPA, 
    APA.CONTROLEPA,
    NVL(SUM(APA.QTDPERDA), 0) AS QTDPERDA
FROM TPRAPA APA
INNER JOIN TPRAPO APO ON APO.NUAPO = APA.NUAPO
INNER JOIN TPRIATV IATV ON IATV.IDIATV = APO.IDIATV
WHERE 
IATV.IDIPROC = 2648
--IATV.IDIATV = 
-- APO.SITUACAO = 'C'
--AND APA.QTDPERDA > 0
GROUP BY IATV.IDIATV,IATV.IDEFX,IATV.IDIPROC,IATV.CODWCP, APA.CODPRODPA, APA.CONTROLEPA
