
CREATE OR REPLACE VIEW AD_VGFFINDUPL AS

SELECT
ROWNUM AS CODIGO
,NUFIN
,SITUACAO
,NUFINREC
,NUFINDESP
,VALOR
,VLRCOMPENSADO
,SALDO
,CODPARC
,CODDUPL
,QUERY FROM
(
--FINANCEIRO PRÓPRIO
SELECT
'PROPRIO' AS SITUACAO
,
        CAB.CODDUPL
,
        CAB.NUFIN
,
        CAB.VALOR
,
        CAB.NUFIN AS NUFINREC
,
        0 AS NUFINDESP
,
        CASE 
            WHEN FIN.DHBAIXA IS NULL THEN FIN.VLRDESDOB 
            ELSE 0 
        END AS SALDO
,
        CAB.VALOR - NVL(CASE 
            WHEN FIN.DHBAIXA IS NULL THEN FIN.VLRDESDOB 
            ELSE 0 
        END,
        0) AS VLRCOMPENSADO
,
        CAB.CODPARC
,
        'FINAN PROPRIO' AS QUERY
FROM AD_CTRLDUPL CAB
LEFT 
    JOIN
        TGFFIN FIN 
            ON FIN.NUFIN = CAB.NUFIN

UNION ALL
--FINANCEIRO PRÓPRIO - TITULOS DE TERCEIRO
SELECT
'TERCEIRO' AS SITUACAO
,
        CAB.CODDUPL
,
        CAB.NUFIN
,
        ITE.VALOR
,
        ITE.NUFINREC
,
        ITE.NUFINDESP
,
        ITE.VALOR - FIN.VLRBAIXA AS SALDO
,
        FIN.VLRBAIXA AS VLRCOMPENSADO
,
        ITE.CODPARC
,
        'FINAN PROPRIO - TITULOS TERCEIRO' AS QUERY
FROM AD_CTRLDUPL CAB
INNER 
    JOIN
        AD_CTRLDUPLTERC ITE 
            ON CAB.CODDUPL = ITE.CODDUPL
LEFT 
    JOIN
        TGFFIN FIN 
            ON FIN.NUFIN = ITE.NUFINDESP


UNION ALL

--RECEITA DE TERCEIROS - TITULO PROPRIO
SELECT
'PROPRIO' AS SITUACAO
,
        CAB.CODDUPL
,
        ITE.NUFINREC AS NUFIN
,
        CAB.VALOR
,
        CAB.NUFIN AS NUFINREC
,
        0 AS NUFINDESP
,
        CASE 
            WHEN FIN.DHBAIXA IS NULL THEN FIN.VLRDESDOB 
            ELSE 0 
        END AS SALDO
,
        CAB.VALOR - NVL(CASE 
            WHEN FIN.DHBAIXA IS NULL THEN FIN.VLRDESDOB 
            ELSE 0 
        END,
        0) AS VLRCOMPENSADO
,
        CAB.CODPARC
,
        'RECEITA DE TERCEIROS - TITULO PROPRIO' AS QUERY
FROM AD_CTRLDUPL CAB
INNER 
    JOIN
        AD_CTRLDUPLTERC ITE 
            ON CAB.CODDUPL = ITE.CODDUPL
LEFT 
    JOIN
        TGFFIN FIN 
            ON FIN.NUFIN = CAB.NUFIN

UNION ALL

--RECEITA DE TERCEIROS - TITULOS TERCEIROS
SELECT
'TERCEIRO' AS SITUACAO
,
        CAB.CODDUPL
,
        ITE.NUFINREC AS NUFIN
,
        ITE.VALOR
,
        ITE.NUFINREC
,
        ITE.NUFINDESP
,
        ITE.VALOR - FIN.VLRBAIXA AS SALDO
,
        FIN.VLRBAIXA AS VLRCOMPENSADO
,
        ITE.CODPARC
,
        'RECEITA DE TERCEIROS - TITULOS TERCEIROS' AS QUERY
FROM AD_CTRLDUPL CAB
INNER 
    JOIN
        AD_CTRLDUPLTERC ITE 
            ON CAB.CODDUPL = ITE.CODDUPL
LEFT 
    JOIN
        TGFFIN FIN 
            ON FIN.NUFIN = ITE.NUFINDESP

UNION ALL

--DESPESA DE TERCEIROS - TITULO PROPRIO
SELECT
'PROPRIO' AS SITUACAO
,
        CAB.CODDUPL
,
        ITE.NUFINDESP AS NUFIN
,
        CAB.VALOR
,
        CAB.NUFIN AS NUFINREC
,
        0 AS NUFINDESP
,
        CASE 
            WHEN FIN.DHBAIXA IS NULL THEN FIN.VLRDESDOB 
            ELSE 0 
        END AS SALDO
,
        CAB.VALOR - NVL(CASE 
            WHEN FIN.DHBAIXA IS NULL THEN FIN.VLRDESDOB 
            ELSE 0 
        END,
        0) AS VLRCOMPENSADO
,
        CAB.CODPARC
,
        'DESPESA DE TERCEIROS - TITULO PROPRIO' AS QUERY
FROM AD_CTRLDUPL CAB
INNER 
    JOIN
        AD_CTRLDUPLTERC ITE 
            ON CAB.CODDUPL = ITE.CODDUPL
LEFT 
    JOIN
        TGFFIN FIN 
            ON FIN.NUFIN = CAB.NUFIN

UNION ALL

--DESPESA DE TERCEIROS - TITULOS TERCEIROS
SELECT
'TERCEIRO' AS SITUACAO
,
        CAB.CODDUPL
,
        ITE.NUFINDESP AS NUFIN
,
        ITE.VALOR
,
        ITE.NUFINREC
,
        ITE.NUFINDESP
,
        ITE.VALOR - FIN.VLRBAIXA AS SALDO
,
        FIN.VLRBAIXA AS VLRCOMPENSADO
,
        ITE.CODPARC
,
        'DESPESA DE TERCEIROS - TITULOS TERCEIROS' AS QUERY
FROM AD_CTRLDUPL CAB
INNER 
    JOIN
        AD_CTRLDUPLTERC ITE 
            ON CAB.CODDUPL = ITE.CODDUPL
LEFT 
    JOIN
        TGFFIN FIN 
            ON FIN.NUFIN = ITE.NUFINDESP

UNION ALL

--FINANCEIRO PRÓPRIO RENEGOCIADO
SELECT
'PROPRIO' AS SITUACAO
,
        CAB.CODDUPL
,
        FINR.NUFIN
,
        CAB.VALOR
,
        CAB.NUFIN AS NUFINREC
,
        0 AS NUFINDESP
,
        CASE 
            WHEN FIN.DHBAIXA IS NULL THEN FIN.VLRDESDOB 
            ELSE 0 
        END AS SALDO
,
        CAB.VALOR - NVL(CASE 
            WHEN FIN.DHBAIXA IS NULL THEN FIN.VLRDESDOB 
            ELSE 0 
        END,
        0) AS VLRCOMPENSADO
,
        CAB.CODPARC
,
        'FINAN PROPRIO RENEGOCIADO' AS QUERY
FROM AD_CTRLDUPL CAB
INNER 
    JOIN
        TGFFIN FIN 
            ON FIN.NUFIN = CAB.NUFIN 
            AND NVL(FIN.NURENEG,
        0) <> 0
INNER 
    JOIN
        TGFFIN FINR 
            ON FINR.NURENEG = NVL(FIN.NURENEG,
        0) 
        AND FINR.RECDESP <> 0
        AND FINR.NUFIN <> CAB.NUFIN

UNION ALL
--FINANCEIRO PRÓPRIO RENEGOCIADO - TITULOS DE TERCEIRO
SELECT
'TERCEIRO' AS SITUACAO
,
        CAB.CODDUPL
,
        FINR.NUFIN
,
        ITE.VALOR
,
        ITE.NUFINREC
,
        ITE.NUFINDESP
,
        ITE.VALOR - FIN.VLRBAIXA AS SALDO
,
        FIN.VLRBAIXA AS VLRCOMPENSADO
,
        ITE.CODPARC
,
        'FINAN PROPRIO RENEGOCIADO - TITULOS TERCEIRO' AS QUERY
FROM AD_CTRLDUPL CAB
INNER 
    JOIN
        AD_CTRLDUPLTERC ITE 
            ON CAB.CODDUPL = ITE.CODDUPL
INNER 
    JOIN
        TGFFIN FIN 
            ON FIN.NUFIN = ITE.NUFINDESP
INNER 
    JOIN
        TGFFIN FINC 
            ON FINC.NUFIN = CAB.NUFIN 
            AND NVL(FINC.NURENEG,
        0) <> 0
INNER 
    JOIN
        TGFFIN FINR 
            ON FINR.NURENEG = NVL(FINC.NURENEG,
        0) 
        AND FINR.RECDESP <> 0
        AND FINR.NUFIN <> CAB.NUFIN
)