SELECT
NUNOTA,
NVL(AD_LINHAPROD1,0) AS FORM,
VLR_REAL_COMPR,
AD_LINHAPROD1,
MARCA,
CASE WHEN AD_LINHAPROD1 IS NOT NULL THEN VLR_REAL_COMPR / NULLIF(COUNT(AD_LINHAPROD1) OVER (PARTITION BY NUNOTA) +
                                                      COUNT(AD_LINHAPROD2) OVER (PARTITION BY NUNOTA) +
                                                      COUNT(AD_LINHAPROD3) OVER (PARTITION BY NUNOTA), 0)
     ELSE 0 END AS valor_campo1,
AD_LINHAPROD2,
MARCA1,
CASE WHEN AD_LINHAPROD2 IS NOT NULL THEN VLR_REAL_COMPR / NULLIF(COUNT(AD_LINHAPROD1) OVER (PARTITION BY NUNOTA) +
                                                      COUNT(AD_LINHAPROD2) OVER (PARTITION BY NUNOTA) +
                                                      COUNT(AD_LINHAPROD3) OVER (PARTITION BY NUNOTA), 0)
     ELSE 0 END AS valor_campo2,
AD_LINHAPROD3,
MARCA2,
CASE WHEN AD_LINHAPROD3 IS NOT NULL THEN VLR_REAL_COMPR / NULLIF(COUNT(AD_LINHAPROD1) OVER (PARTITION BY NUNOTA) +
                                                      COUNT(AD_LINHAPROD2) OVER (PARTITION BY NUNOTA) +
                                                      COUNT(AD_LINHAPROD3) OVER (PARTITION BY NUNOTA), 0)
     ELSE 0 END AS valor_campo3

FROM
(


WITH 
FIN AS (SELECT NUFIN, NUNOTA, DESDOBRAMENTO, VLRDESDOB FROM TGFFIN),
CAB AS (SELECT NUNOTA, CODTIPOPER,AD_TIPVERBA,AD_REGIAO,AD_CODVENDRTV,AD_LINHAPROD1,MAR.MARCA,AD_LINHAPROD2,MAR1.MARCA AS MARCA1,AD_LINHAPROD3,MAR2.MARCA AS MARCA2 
FROM TGFCAB
LEFT JOIN AD_VGFMARCA MAR ON TGFCAB.AD_LINHAPROD1 = MAR.SEQ
LEFT JOIN AD_VGFMARCA MAR1 ON TGFCAB.AD_LINHAPROD2 = MAR1.SEQ
LEFT JOIN AD_VGFMARCA MAR2 ON TGFCAB.AD_LINHAPROD3 = MAR2.SEQ)

SELECT
VGF.NUFIN,
FIN.DESDOBRAMENTO,
FIN.NUNOTA,
VGF.NUMNOTA,
CAB.AD_TIPVERBA,
COALESCE(F_DESCROPC('TGFCAB','AD_TIPVERBA',CAB.AD_TIPVERBA),'Vazio') AS TIPVERBA,
CAB.AD_REGIAO,
CAB.AD_CODVENDRTV,
CAB.AD_LINHAPROD1,
CAB.MARCA,
CAB.AD_LINHAPROD2,
CAB.MARCA1,
CAB.AD_LINHAPROD3,
CAB.MARCA2,
ABS((CASE WHEN VGF.PROVISAO = 'S' THEN VGF.VLRDESDOB ELSE 0 END) + (CASE WHEN VGF.PROVISAO = 'N' THEN VGF.VLRBAIXA ELSE 0 END)) AS VLR_REAL_COMPR
FROM VGF_RESULTADO_PROV_SATIS VGF
LEFT JOIN FIN ON VGF.NUFIN = FIN.NUFIN
LEFT JOIN CAB ON FIN.NUNOTA = CAB.NUNOTA
INNER JOIN TCSPRJ PRJ ON VGF.CODPROJ = PRJ.CODPROJ
WHERE
VGF.RECDESP = -1
AND SUBSTR(VGF.CODPROJ, 1, 1) = '8'
AND COALESCE(F_ANO_SAFRA(VGF.DHBAIXA), F_ANO_SAFRA(VGF.DTVENC)) = '2023-2024' --:P_ANO_SAFRA

)