CREATE OR REPLACE PROCEDURE SANKHYA.STP_RETORN_PEND AS

  P_NUNOTA   TGFCAB.NUNOTA%TYPE;
  P_PENDENTE TGFCAB.PENDENTE%TYPE; 
  P_DIAS     NUMBER;


  CURSOR RET_PEND IS
    SELECT
      NUNOTA,
      PENDENTE,
      AD_DT_MARC_ENTREG, 
      SYSDATE - AD_DT_MARC_ENTREG AS DIAS
    FROM
      TGFCAB
    WHERE
      DTNEG > SYSDATE - 60
      AND PENDENTE = 'N'
      AND (AD_VALIDACAO_COMPROV_ENTREGA = 'N' OR AD_VALIDACAO_COMPROV_ENTREGA IS NULL);


BEGIN
  FOR r_pending IN RET_PEND LOOP
    P_NUNOTA   := r_pending.NUNOTA;
    P_PENDENTE := r_pending.PENDENTE;
    P_DIAS     := r_pending.DIAS;

    IF P_DIAS >= 7 THEN
      -- Update the PENDENTE field to 'S'
      UPDATE TGFCAB
      SET PENDENTE = 'S'
      WHERE NUNOTA = P_NUNOTA;
    END IF;
  END LOOP;

  COMMIT; 
 
 
 
 
 

END;