WITH 
MET AS (
    SELECT 
        MET.DTREF,
        MET.CODVEND,
        MET.CODPARC,
        MET.MARCA,
        MET.QTDPREV,
        NVL(PRC.VLRVENDALT, 0) * MET.QTDPREV AS VLRPREV
    FROM TGFMET MET
    LEFT JOIN AD_PRECOMARCA PRC ON MET.MARCA = PRC.MARCA AND PRC.CODMETA = MET.CODMETA AND PRC.DTREF = (SELECT MAX(DTREF) FROM AD_PRECOMARCA WHERE CODMETA = MET.CODMETA AND DTREF <= MET.DTREF AND MARCA = MET.MARCA)
    WHERE MET.CODMETA = 4)
SELECT 
    SUM(VLR) AS VLR
FROM (
    SELECT 
        *
    FROM VGF_VENDAS_SATIS VGF
    LEFT JOIN MET ON VGF.CODVEND = MET.CODVEND AND VGF.CODPARC = MET.CODPARC AND VGF.MARCA = MET.MARCA AND VGF.DTMOV BETWEEN MET.DTREF AND LAST_DAY(MET.DTREF)
    WHERE VGF.DTMOV BETWEEN '01-07-2024' AND '03-07-2024' AND ((VGF.ATUALFIN <> 0 AND VGF.TIPATUALFIN = 'I') OR (VGF.CODTIPOPER IN (1112, 1113)))
)