/*BASE MES ANTERIOR - RESUMO*/


SELECT
COMPRADOR,
SUM(QTDNEG) AS QTDNEG,
SUM(VLRTOT) AS VLRTOT,
SUM(SAVING) AS SAVING,
SUM(GANHO_EVOLUCAO) AS GANHO_EVOLUCAO,
SUM(SAVING)+SUM(GANHO_EVOLUCAO) AS ECONOMIA_COMPRAS
FROM
(

SELECT
*
FROM(
WITH
USU AS (SELECT CODUSU,NOMEUSU,AD_USUCOMPRADOR FROM TSIUSU)

SELECT CAB.CODEMP,
       SUBSTR(CAB.CODPARC||'-'||UPPER(PAR.RAZAOSOCIAL), 1, 20) AS PARCEIRO,
       SUBSTR(ITE.CODPROD||'-'||PRO.DESCRPROD,1,15) AS PRODUTO,
       SUBSTR(PRO.CODGRUPOPROD||'-'|| GRU.DESCRGRUPOPROD,1,15) AS GRUPO,
       ITE.CODVOL AS UN,
       ITE.NUNOTA AS NUNOTA,
       CAB.TIPMOV AS TIPMOV,
       CAB.DTNEG,
       SUBSTR(VEN.CODVEND||'-'||VEN.APELIDO,1,10) AS COMPRADOR,
       SUBSTR(CAB.CODUSUINC||'-'||USU.NOMEUSU,1,10) AS USUARIO_INC,
       ITE.QTDNEG,
       ITE.VLRTOT,
       ITE.VLRDESC AS SAVING,
       (ITE.VLRDESC / NULLIF(ITE.VLRTOT,0)) * 100 AS PERC_SAVING,
       (ITE.VLRTOT) / NULLIF(ITE.QTDNEG,0) AS PRECO_COMPRA_UN,
       (ITE.VLRTOT - ITE.VLRDESC) / NULLIF(ITE.QTDNEG,0) AS PRECO_COMPRA_UN_LIQ,
       GET_PRECMED_ANT_PROD_COMP_SAT(CAB.DTNEG,ITE.CODPROD,NULL) AS PRECO_COMPRA_UN_LIQ_ANT_MED,
       CASE
       WHEN (GET_PRECMED_ANT_PROD_COMP_SAT(CAB.DTNEG,ITE.CODPROD,NULL)-((ITE.VLRTOT - ITE.VLRDESC) / NULLIF(ITE.QTDNEG,0)))>0
       AND PRO.CODGRUPOPROD IN(3020000,3010000)
       THEN
       ABS(GET_PRECMED_ANT_PROD_COMP_SAT(CAB.DTNEG,ITE.CODPROD,NULL)-((ITE.VLRTOT - ITE.VLRDESC) / NULLIF(ITE.QTDNEG,0))) ELSE 0 END GANHO_EVOLUCAO_UN,

       CASE WHEN (GET_PRECMED_ANT_PROD_COMP_SAT(CAB.DTNEG,ITE.CODPROD,NULL)-((ITE.VLRTOT - ITE.VLRDESC) / NULLIF(ITE.QTDNEG,0)))>0
       AND PRO.CODGRUPOPROD IN(3020000,3010000)
       THEN
       ABS(GET_PRECMED_ANT_PROD_COMP_SAT(CAB.DTNEG,ITE.CODPROD,NULL)-((ITE.VLRTOT - ITE.VLRDESC) / NULLIF(ITE.QTDNEG,0))) * ITE.QTDNEG ELSE 0 END GANHO_EVOLUCAO,
        CASE
        WHEN GET_PRECMED_ANT_PROD_COMP_SAT(CAB.DTNEG,ITE.CODPROD,NULL) - ((ITE.VLRTOT - ITE.VLRDESC) / NULLIF(ITE.QTDNEG, 0)) > 0 THEN 'REDUCAO'
        WHEN GET_PRECMED_ANT_PROD_COMP_SAT(CAB.DTNEG,ITE.CODPROD,NULL) - ((ITE.VLRTOT - ITE.VLRDESC) / NULLIF(ITE.QTDNEG, 0)) < 0 AND GET_PRECMED_ANT_PROD_COMP_SAT(CAB.DTNEG,ITE.CODPROD,NULL) <> 0 THEN 'AUMENTO'
        WHEN GET_PRECMED_ANT_PROD_COMP_SAT(CAB.DTNEG,ITE.CODPROD,NULL) - ((ITE.VLRTOT - ITE.VLRDESC) / NULLIF(ITE.QTDNEG, 0)) < 0  AND GET_PRECMED_ANT_PROD_COMP_SAT(CAB.DTNEG,ITE.CODPROD,NULL) = 0 THEN 'SEM ALTERACAO'
        ELSE 'MANTEVE'
        END AS SITUACAO_PRECO,
            (CASE WHEN GET_PRECMED_ANT_PROD_COMP_SAT(CAB.DTNEG,ITE.CODPROD,NULL) - ((ITE.VLRTOT - ITE.VLRDESC) / NULLIF(ITE.QTDNEG, 0)) < 0  AND GET_PRECMED_ANT_PROD_COMP_SAT(CAB.DTNEG,ITE.CODPROD,NULL) = 0 THEN 0 ELSE
           ABS(ABS(GET_PRECMED_ANT_PROD_COMP_SAT(CAB.DTNEG,ITE.CODPROD,NULL)-((ITE.VLRTOT - ITE.VLRDESC) / NULLIF(ITE.QTDNEG,0)))/NULLIF(((ITE.VLRTOT - ITE.VLRDESC) / NULLIF(ITE.QTDNEG,0)),0))*100 END) AS PERC_DIF_PRECO_ULT_COMPRA_UN_LIQ_MED_POR_COMPRA_UN_ATUAL_LIQ
  FROM TGFITE ITE
  INNER JOIN TGFPRO PRO ON (ITE.CODPROD = PRO.CODPROD)
  INNER JOIN TGFCAB CAB ON (ITE.NUNOTA = CAB.NUNOTA)
  INNER JOIN TGFTOP TOP ON ( CAB.CODTIPOPER = TOP.CODTIPOPER AND CAB.DHTIPOPER = ( SELECT MAX (TOP.DHALTER) FROM TGFTOP WHERE CODTIPOPER = TOP.CODTIPOPER ) )
  INNER JOIN TGFVEN VEN ON (CAB.CODVEND = VEN.CODVEND)
  INNER JOIN TGFPAR PAR ON CAB.CODPARC = PAR.CODPARC
  INNER JOIN TGFGRU GRU ON PRO.CODGRUPOPROD = GRU.CODGRUPOPROD

  INNER JOIN USU ON CAB.CODUSUINC = USU.CODUSU
 WHERE CAB.TIPMOV = 'O'
   AND CAB.STATUSNOTA = 'L'
   AND USU.AD_USUCOMPRADOR = 'S'
   AND CAB.DTNEG BETWEEN '01-01-2024' AND '30-06-2024' --$P{DTINI} AND $P{DTFIM}
   --AND (CAB.CODPARC = $P{P_CODPARC} OR $P{P_CODPARC} IS NULL)
   --AND (ITE.CODPROD = $P{P_CODPARC} OR $P{P_CODPARC} IS NULL)
)
WHERE (SAVING <> 0 OR GANHO_EVOLUCAO_UN <> 0)
ORDER BY 4,17 DESC



)GROUP BY COMPRADOR