WITH
ANT AS (
SELECT
    CODPROD,
    DESCRICAO,
    AVG(PRECO_COMPRA_UN_LIQ) AS PRECO_COMPRA_UN_LIQ_ANT_MED
FROM
(
    SELECT 
        ITE.CODPROD,
        PRO.DESCRPROD AS DESCRICAO,
        ITE.CODVOL AS UN,
        ITE.NUNOTA AS NUNOTA,
        F_DESCROPC('TGFCAB','TIPMOV',CAB.TIPMOV) AS TIPMOV,
        VEN.CODVEND||'-'||VEN.APELIDO AS COMPRADOR,
        ITE.QTDNEG,
        ITE.VLRTOT,
        ITE.VLRDESC,
        (ITE.VLRTOT) / NULLIF(ITE.QTDNEG,0) AS PRECO_COMPRA,
        (ITE.VLRTOT - ITE.VLRDESC) / NULLIF(ITE.QTDNEG,0) AS PRECO_COMPRA_UN_LIQ,
        
        ITE.VLRDESC AS SAVING,
        ((ITE.VLRTOT) / NULLIF(ITE.QTDNEG,0)) - ((ITE.VLRTOT - ITE.VLRDESC) / NULLIF(ITE.QTDNEG,0)) AS SAVING_UN,
        (ITE.VLRDESC / NULLIF(ITE.VLRTOT,0)) * 100 AS PERCENTUAL_SAVING
      FROM TGFITE ITE
      INNER JOIN TGFPRO PRO ON (ITE.CODPROD = PRO.CODPROD)
      INNER JOIN TGFCAB CAB ON (ITE.NUNOTA = CAB.NUNOTA)
      INNER JOIN TGFTOP TOP ON ( CAB.CODTIPOPER = TOP.CODTIPOPER AND CAB.DHTIPOPER = ( SELECT MAX (TOP.DHALTER) FROM TGFTOP WHERE CODTIPOPER = TOP.CODTIPOPER ) )
      INNER JOIN TGFVEN VEN ON (CAB.CODVEND = VEN.CODVEND)
     WHERE CAB.TIPMOV = 'O'
       AND CAB.STATUSNOTA = 'L'
       AND CAB.DTNEG < '01-06-2024') --$P{DTINI})
GROUP BY CODPROD, DESCRICAO
ORDER BY 2,3 DESC
),
USU AS (SELECT CODUSU,NOMEUSU FROM TSIUSU)

SELECT CAB.CODEMP,
       SUBSTR(CAB.CODPARC||'-'||UPPER(PAR.RAZAOSOCIAL), 1, 20) AS PARCEIRO,
       SUBSTR(ITE.CODPROD||'-'||PRO.DESCRPROD,1,15) AS PRODUTO,
       SUBSTR(PRO.CODGRUPOPROD||'-'|| GRU.DESCRGRUPOPROD,1,15) AS GRUPO,
       ITE.CODVOL AS UN,
       ITE.NUNOTA AS NUNOTA,
       CAB.TIPMOV AS TIPMOV,
       CAB.DTNEG,
       SUBSTR(VEN.CODVEND||'-'||VEN.APELIDO,1,10) AS COMPRADOR,
       SUBSTR(CAB.CODUSUINC||'-'||USU.NOMEUSU,1,10) AS USUARIO_INC,
       ITE.QTDNEG,
       ITE.VLRTOT,
       ITE.VLRDESC,
       (ITE.VLRTOT) / NULLIF(ITE.QTDNEG,0) AS PRECO_COMPRA_UN,
       (ITE.VLRTOT - ITE.VLRDESC) / NULLIF(ITE.QTDNEG,0) AS PRECO_COMPRA_UN_LIQ,
       NVL(PRECO_COMPRA_UN_LIQ_ANT_MED,0) AS PRECO_COMPRA_UN_LIQ_ANT_MED,
       NVL(PRECO_COMPRA_UN_LIQ_ANT_MED,0)-((ITE.VLRTOT - ITE.VLRDESC) / NULLIF(ITE.QTDNEG,0)) AS DIF_PRECO_ULT_COMPRA_UN_LIQ_MED_POR_COMPRA_UN_ATUAL_LIQ,
        CASE
        WHEN NVL(PRECO_COMPRA_UN_LIQ_ANT_MED, 0) - ((ITE.VLRTOT - ITE.VLRDESC) / NULLIF(ITE.QTDNEG, 0)) > 0 THEN 'REDUCAO'
        WHEN NVL(PRECO_COMPRA_UN_LIQ_ANT_MED, 0) - ((ITE.VLRTOT - ITE.VLRDESC) / NULLIF(ITE.QTDNEG, 0)) < 0 AND NVL(PRECO_COMPRA_UN_LIQ_ANT_MED,0) <> 0 THEN 'AUMENTO'
        WHEN NVL(PRECO_COMPRA_UN_LIQ_ANT_MED, 0) - ((ITE.VLRTOT - ITE.VLRDESC) / NULLIF(ITE.QTDNEG, 0)) < 0  AND NVL(PRECO_COMPRA_UN_LIQ_ANT_MED,0) = 0 THEN 'SEM DADOS'
        ELSE 'MANTEVE'
        END AS SITUACAO_PRECO,
       ABS(NVL(PRECO_COMPRA_UN_LIQ_ANT_MED,0)-((ITE.VLRTOT - ITE.VLRDESC) / NULLIF(ITE.QTDNEG,0)))/NULLIF(((ITE.VLRTOT - ITE.VLRDESC) / NULLIF(ITE.QTDNEG,0)),0)*100 AS PERC_DIF_PRECO_ULT_COMPRA_UN_LIQ_MED_POR_COMPRA_UN_ATUAL_LIQ,
       ITE.VLRDESC AS SAVING,
       ((ITE.VLRTOT) / NULLIF(ITE.QTDNEG,0)) - ((ITE.VLRTOT - ITE.VLRDESC) / NULLIF(ITE.QTDNEG,0)) AS SAVING_UN,
       (ITE.VLRDESC / NULLIF(ITE.VLRTOT,0)) * 100 AS PERC_SAVING
  FROM TGFITE ITE
  INNER JOIN TGFPRO PRO ON (ITE.CODPROD = PRO.CODPROD)
  INNER JOIN TGFCAB CAB ON (ITE.NUNOTA = CAB.NUNOTA)
  INNER JOIN TGFTOP TOP ON ( CAB.CODTIPOPER = TOP.CODTIPOPER AND CAB.DHTIPOPER = ( SELECT MAX (TOP.DHALTER) FROM TGFTOP WHERE CODTIPOPER = TOP.CODTIPOPER ) )
  INNER JOIN TGFVEN VEN ON (CAB.CODVEND = VEN.CODVEND)
  INNER JOIN TGFPAR PAR ON CAB.CODPARC = PAR.CODPARC
  INNER JOIN TGFGRU GRU ON PRO.CODGRUPOPROD = GRU.CODGRUPOPROD
  LEFT JOIN ANT ON ITE.CODPROD = ANT.CODPROD
  INNER JOIN USU ON CAB.CODUSUINC = USU.CODUSU
 WHERE CAB.TIPMOV = 'O'
   AND CAB.STATUSNOTA = 'L'
   AND CAB.DTNEG BETWEEN '01-06-2024' AND '30-06-2024'
   /*AND CAB.DTNEG BETWEEN $P{DTINI} AND $P{DTFIM}
   AND (CAB.CODPARC = $P{P_CODPARC} OR $P{P_CODPARC} IS NULL)*/
ORDER BY 4,17 DESC