SELECT
    CUS.CODCENCUS AS ID_CR,
    CUS.DESCRCENCUS AS CR,
    CRP.CODCENCUS AS ID_PAI_CR,
    CRP.DESCRCENCUS AS PAI_CR
FROM TSICUS CUS
LEFT JOIN TSICUS CRP ON CRP.CODCENCUS = CUS.CODCENCUSPAI
WHERE CUS.ATIVO LIKE 'S'
AND CUS.ANALITICO LIKE 'S'
ORDER BY 1 ASC