SELECT
    S.MES,
    S.ID_CONTA_CONTABIL,
    S.NUMLOTE,
    S.ID_CR,
    S.ID_EMPRESA,
    S.ID_HISTORICO,
    S.ID_NUMERO_DE_LANCAMENTO,
    SUM(S.SALDO_ATUAL / 1000) AS VALOR
FROM SALDO_ATUAL S
INNER JOIN IMP_CONTA_CONTABIL CC
    ON CC.ID_CONTA_CONTABIL = S.ID_CONTA_CONTABIL
GROUP BY
    S.MES,
    S.ID_CONTA_CONTABIL,
    S.NUMLOTE,
    S.ID_CR,
    S.ID_EMPRESA,
    S.ID_HISTORICO,
    S.ID_NUMERO_DE_LANCAMENTO
  
UNION ALL

SELECT
    S.MES,
    '2.3.04.01.000011' AS ID_CONTA_CONTABIL,
     S.NUMLOTE,
    S.ID_CR,
    S.ID_EMPRESA,
    S.ID_HISTORICO,
    S.ID_NUMERO_DE_LANCAMENTO,
    SUM(S.SALDO_ATUAL / 1000) AS VALOR

FROM SALDO_ATUAL S
INNER JOIN IMP_CONTA_CONTABIL CC
    ON CC.ID_CONTA_CONTABIL = S.ID_CONTA_CONTABIL
INNER JOIN DEMONSTRATIVOS D
    ON D.ID_CONTA_CONTABIL = CC.ID_CONTA_CONTABIL
WHERE D.ID_DRE IN (1,2,3,4,5,6,7,8,9,10,11)
GROUP BY
    S.MES,
    S.ID_CR,
    S.ID_EMPRESA,
    S.ID_HISTORICO,
    S.ID_NUMERO_DE_LANCAMENTO,
    S.NUMLOTE