SELECT PLA0.CTACTB AS ID_CONTA_CONTABIL ,
       PLA0.DESCRCTA AS CONTA_CONTABIL ,
       PLA1.CTACTB AS ID_PAI_CONTA_CONTABIL,
       PLA1.DESCRCTA AS PAI_CONTA_CONTABIL ,
       PLA2.CTACTB AS ID_AVO_CONTA_CONTABIL ,
       PLA2.DESCRCTA AS AVO_CONTA_CONTABIL ,
       PLA3.CTACTB AS ID_BISAVO_CONTA_CONTABIL ,
       PLA3.DESCRCTA AS BISAVO_CONTA_CONTABIL ,
       PLA4.CTACTB AS ID_TATARAVO_CONTA_CONTABIL ,
       PLA4.DESCRCTA AS TATARAVO_CONTA_CONTABIL 
FROM TCBPLA PLA0
LEFT JOIN TCBPLA PLA1 ON PLA0.CODCTACTBPAI = PLA1.CODCTACTB
LEFT JOIN TCBPLA PLA2 ON PLA1.CODCTACTBPAI = PLA2.CODCTACTB
LEFT JOIN TCBPLA PLA3 ON PLA2.CODCTACTBPAI = PLA3.CODCTACTB
LEFT JOIN TCBPLA PLA4 ON PLA3.CODCTACTBPAI = PLA4.CODCTACTB
LEFT JOIN TCBPLA PLA5 ON PLA4.CODCTACTBPAI = PLA5.CODCTACTB
WHERE PLA0.GRAU = 5
