SELECT  
    EMP.CODEMP AS ID_EMPRESA,
    EMP.NOMEFANTASIA AS EMPRESA,
    EMP.CGC AS CNPJ,
    EMP.REGJUNTACOM AS NIRE,
    INITCAP(
        ENDI.TIPO || ' ' || ENDI.NOMEEND || ', n° ' || EMP.NUMEND ||
        CASE 
            WHEN EMP.COMPLEMENTO IS NOT NULL AND TRIM(EMP.COMPLEMENTO) <> '' 
            THEN ' - ' || EMP.COMPLEMENTO 
            ELSE ''
        END ||
        ', Bairro: ' || BAI.NOMEBAI ||
        ', CEP: ' || EMP.CEP || ' ' || CID.NOMECID || ' - ' || UFS.DESCRICAO
    ) AS ENDERECO

FROM TSIEMP EMP
INNER JOIN TSIEND ENDI ON EMP.CODEND = ENDI.CODEND
INNER JOIN TSIBAI BAI ON EMP.CODBAI = BAI.CODBAI
INNER JOIN TSICID CID ON EMP.CODCID = CID.CODCID
INNER JOIN TSIUFS UFS ON CID.UF = UFS.CODUF
ORDER BY 1 ASC
