-- Mantem a query original (TPRAMP -> TGFPRO) e acrescenta TPREFX.TIPO/DESCRICAO
-- Sem multiplicar registros: escolhe 1 IDEFX por AMP (via agregacao em TPRLMP).
SELECT
  AMP.NUAPO,
  AMP.SEQAPA,
  AMP.SEQMP,
  AMP.CODPRODMP,
  PRO.DESCRPROD,
  AMP.CONTROLEMP,
  AMP.QTD,
  AMP.CODVOL,
  F_DESCROPC('TPRAMP', 'TIPOUSO', AMP.TIPOUSO) DESC_TIPOUSO,
  TPREFX_TIPO.TIPO AS TIPO,
  TPREFX_TIPO.DESCRICAO AS DESCRICAO
FROM TPRAMP AMP
INNER JOIN TGFPRO PRO
  ON AMP.CODPRODMP = PRO.CODPROD
LEFT JOIN (
  SELECT
    LMP.SEQMP,
    LMP.CODPRODMP,
    NVL(LMP.CONTROLEMP, ' ') AS CONTROLEMP,
    MAX(LMP.IDEFX) AS IDEFX
  FROM TPRLMP LMP
  GROUP BY
    LMP.SEQMP,
    LMP.CODPRODMP,
    NVL(LMP.CONTROLEMP, ' ')
) LMP_UM ON LMP_UM.SEQMP = AMP.SEQMP
        AND LMP_UM.CODPRODMP = AMP.CODPRODMP
        AND LMP_UM.CONTROLEMP = NVL(AMP.CONTROLEMP, ' ')
LEFT JOIN TPREFX TPREFX_TIPO
  ON TPREFX_TIPO.IDEFX = LMP_UM.IDEFX
WHERE AMP.NUAPO = ${nVal}
  AND AMP.SEQAPA = ${sVal}
ORDER BY 1, 2, 3

