CREATE OR REPLACE TRIGGER TRG_DEL_TGFNCC_GM
AFTER UPDATE ON TGFNAT
FOR EACH ROW
DECLARE
    FIELD_CODNAT TGFNAT.CODNAT%TYPE;
    v_count NUMBER;
BEGIN
    -- Obtém o CODNAT atual
    FIELD_CODNAT := :OLD.CODNAT;

    -- Verifica se existem registros em TGFNCC antes de deletar
    FOR rec IN (
        SELECT '23' AS grp FROM DUAL WHERE :NEW.AD_CR23_COMERCIAL IS NULL AND :OLD.AD_CR23_COMERCIAL IS NOT NULL UNION ALL
        SELECT '24' FROM DUAL WHERE :NEW.AD_CR24_LOGISTICA IS NULL AND :OLD.AD_CR24_LOGISTICA IS NOT NULL UNION ALL
        SELECT '25' FROM DUAL WHERE :NEW.AD_CR25_INDUSTRIA IS NULL AND :OLD.AD_CR25_INDUSTRIA IS NOT NULL UNION ALL
        SELECT '26' FROM DUAL WHERE :NEW.AD_CR26_ADMINISTRATIVO IS NULL AND :OLD.AD_CR26_ADMINISTRATIVO IS NOT NULL UNION ALL
        SELECT '27' FROM DUAL WHERE :NEW.AD_CR27_PATRIMONIAL IS NULL AND :OLD.AD_CR27_PATRIMONIAL IS NOT NULL UNION ALL
        SELECT '28' FROM DUAL WHERE :NEW.AD_CR28_TI IS NULL AND :OLD.AD_CR28_TI IS NOT NULL UNION ALL
        SELECT '29' FROM DUAL WHERE :NEW.AD_CR29_JURIDICO IS NULL AND :OLD.AD_CR29_JURIDICO IS NOT NULL
    ) LOOP
        
        -- Conta quantos registros existem para os critérios
        SELECT COUNT(*) INTO v_count 
        FROM TGFNCC 
        WHERE CODNAT = FIELD_CODNAT 
        AND (SUBSTR(codcencus, 1, 2) = rec.grp OR codcencus IN (SELECT codcencus FROM tsicus WHERE AD_GRUPO_CR_CONTACONTAB = rec.grp));

        -- Se existir, realiza o DELETE
        IF v_count > 0 THEN
            DELETE FROM TGFNCC 
            WHERE CODNAT = FIELD_CODNAT 
            AND (SUBSTR(codcencus, 1, 2) = rec.grp OR codcencus IN (SELECT codcencus FROM tsicus WHERE AD_GRUPO_CR_CONTACONTAB = rec.grp));
        END IF;
    END LOOP;
END;
