SELECT 
SUM(A_RECEBER_PROV_S) A_RECEBER_PROV_S,
SUM(A_RECEBER_PROV_N) A_RECEBER_PROV_N,
SUM(A_PAGAR_PROV_S) A_PAGAR_PROV_S,
SUM(A_PAGAR_PROV_N) A_PAGAR_PROV_N,
SUM(DIFERENCA) DIFERENCA

FROM (

WITH BASE_DADOS AS (
  SELECT 
    DTVENC,
    RECDESP,
    PROVISAO,
    VLRDESDOB
  FROM TGFFIN
  WHERE
    DTVENC < TO_DATE('22/04/2025','DD/MM/YYYY')
    AND DHBAIXA IS NULL

  UNION ALL

  SELECT 
    AD_SIMULACAO_DTVENC AS DTVENC,
    AD_SIMULACAO_RECDESP AS RECDESP,
    AD_SIMULACAO_PROVISAO AS PROVISAO,
    AD_SIMULACAO_VLRDESDOB AS VLRDESDOB
  FROM TGAPEA
  WHERE
    AD_SIMULACAO_DTVENC < TO_DATE('22/04/2025','DD/MM/YYYY')
    AND AD_SIMULACAO_STATUS = 1
)

SELECT 
  DTVENC,
  NVL(SUM(CASE WHEN RECDESP = 1 AND PROVISAO = 'S' THEN VLRDESDOB END), 0) AS A_RECEBER_PROV_S,
  NVL(SUM(CASE WHEN RECDESP = 1 AND NVL(PROVISAO, 'N') = 'N' THEN VLRDESDOB END), 0) AS A_RECEBER_PROV_N,
  NVL(SUM(CASE WHEN RECDESP = -1 AND PROVISAO = 'S' THEN -1 * VLRDESDOB END), 0) AS A_PAGAR_PROV_S,
  NVL(SUM(CASE WHEN RECDESP = -1 AND NVL(PROVISAO, 'N') = 'N' THEN -1 * VLRDESDOB END), 0) AS A_PAGAR_PROV_N,
  
  -- DIFERENÇA DO DIA
  NVL(SUM(CASE WHEN RECDESP = 1 THEN VLRDESDOB END), 0) -
  NVL(SUM(CASE WHEN RECDESP = -1 THEN VLRDESDOB END), 0) AS DIFERENCA

FROM BASE_DADOS
GROUP BY DTVENC
ORDER BY DTVENC
)
