SELECT
CODCENCUS
, 1 GRAU
,RECDESP
,DTNEG
,DTVENC
,NUNOTA
,NUMNOTA
,CODEMP
,CODPARC
,NOMEPARC
,HISTORICO
,SUM(VLRLIQ) VLRLIQ
,SUM(VLRREC)VLRREC
,SUM(VLRDESP)VLRDESP
FROM (
SELECT 
RPAD(SUBSTR(
    CASE WHEN LENGTH(TO_CHAR(CUS.CODCENCUS)) = 9 THEN LPAD(TO_CHAR(CUS.CODCENCUS), 10, '0') ELSE TO_CHAR(CUS.CODCENCUS)     END 
, 1, 2), 10, '0') AS CODCENCUS
,X.RECDESP
,X.DTNEG
,X.DTVENC
,X.NUNOTA
,X.NUMNOTA
,X.CODEMP
,X.CODPARC
,X.NOMEPARC
,X.HISTORICO
,SUM(CASE WHEN NVL(X.VLRBAIXA,0) = 0 THEN X.VLRDESDOB ELSE X.VLRBAIXA END) AS VLRLIQ
,SUM(CASE WHEN X.RECDESP = 1 AND NVL(X.VLRBAIXA,0) = 0 THEN X.VLRDESDOB 
          WHEN X.RECDESP = 1 AND NVL(X.VLRBAIXA,0) <> 0 THEN X.VLRBAIXA END) AS VLRREC
,SUM(CASE WHEN X.RECDESP = -1 AND NVL(X.VLRBAIXA,0) = 0 THEN X.VLRDESDOB 
          WHEN X.RECDESP = -1 AND NVL(X.VLRBAIXA,0) <> 0 THEN X.VLRBAIXA END) AS VLRDESP


FROM TSICUS CUS
LEFT JOIN VGF_RESULTADO_SATIS X ON CUS.CODCENCUS = X.CODCENCUS
WHERE CUS.ATIVO = 'S' AND NVL(CUS.CODCENCUS,0) <> 0 
AND X.DHBAIXA BETWEEN '01/12/2024' AND '31/12/2024'
AND X.RECDESP = -1
GROUP BY CUS.CODCENCUS,X.RECDESP
,X.RECDESP
,X.DTNEG
,X.DTVENC
,X.NUNOTA
,X.NUMNOTA
,X.CODEMP
,X.CODPARC
,X.NOMEPARC
,X.HISTORICO
)GROUP BY CODCENCUS
,RECDESP
,DTNEG
,DTVENC
,NUNOTA
,NUMNOTA
,CODEMP
,CODPARC
,NOMEPARC
,HISTORICO





UNION ALL

SELECT
CODCENCUS
, 2 GRAU
,SUM(VLRLIQ) VLRLIQ
,SUM(VLRREC)VLRREC
,SUM(VLRDESP)VLRDESP
FROM (
SELECT 
RPAD(SUBSTR(
    CASE WHEN LENGTH(TO_CHAR(CUS.CODCENCUS)) = 9 THEN LPAD(TO_CHAR(CUS.CODCENCUS), 10, '0') ELSE TO_CHAR(CUS.CODCENCUS)     END 
, 1, 4), 10, '0') AS CODCENCUS
,SUM(CASE WHEN NVL(X.VLRBAIXA,0) = 0 THEN X.VLRDESDOB ELSE X.VLRBAIXA END) AS VLRLIQ
,SUM(CASE WHEN X.RECDESP = 1 AND NVL(X.VLRBAIXA,0) = 0 THEN X.VLRDESDOB 
          WHEN X.RECDESP = 1 AND NVL(X.VLRBAIXA,0) <> 0 THEN X.VLRBAIXA END) AS VLRREC
,SUM(CASE WHEN X.RECDESP = -1 AND NVL(X.VLRBAIXA,0) = 0 THEN X.VLRDESDOB 
          WHEN X.RECDESP = -1 AND NVL(X.VLRBAIXA,0) <> 0 THEN X.VLRBAIXA END) AS VLRDESP
FROM TSICUS CUS
LEFT JOIN VGF_RESULTADO_SATIS X ON CUS.CODCENCUS = X.CODCENCUS
WHERE CUS.ATIVO = 'S' AND NVL(CUS.CODCENCUS,0) <> 0 
AND X.DHBAIXA BETWEEN '01/12/2024' AND '31/12/2024'
AND X.RECDESP = -1 AND CUS.GRAU = 2
GROUP BY CUS.CODCENCUS
)GROUP BY CODCENCUS


UNION ALL

SELECT
CODCENCUS
, 3 GRAU
,SUM(VLRLIQ) VLRLIQ
,SUM(VLRREC)VLRREC
,SUM(VLRDESP)VLRDESP
FROM (
SELECT 
RPAD(SUBSTR(
    CASE WHEN LENGTH(TO_CHAR(CUS.CODCENCUS)) = 9 THEN LPAD(TO_CHAR(CUS.CODCENCUS), 10, '0') ELSE TO_CHAR(CUS.CODCENCUS)     END 
, 1, 6), 10, '0') AS CODCENCUS
,SUM(CASE WHEN NVL(X.VLRBAIXA,0) = 0 THEN X.VLRDESDOB ELSE X.VLRBAIXA END) AS VLRLIQ
,SUM(CASE WHEN X.RECDESP = 1 AND NVL(X.VLRBAIXA,0) = 0 THEN X.VLRDESDOB 
          WHEN X.RECDESP = 1 AND NVL(X.VLRBAIXA,0) <> 0 THEN X.VLRBAIXA END) AS VLRREC
,SUM(CASE WHEN X.RECDESP = -1 AND NVL(X.VLRBAIXA,0) = 0 THEN X.VLRDESDOB 
          WHEN X.RECDESP = -1 AND NVL(X.VLRBAIXA,0) <> 0 THEN X.VLRBAIXA END) AS VLRDESP
FROM TSICUS CUS
LEFT JOIN VGF_RESULTADO_SATIS X ON CUS.CODCENCUS = X.CODCENCUS
WHERE CUS.ATIVO = 'S' AND NVL(CUS.CODCENCUS,0) <> 0 
AND X.DHBAIXA BETWEEN '01/12/2024' AND '31/12/2024'
AND X.RECDESP = -1 AND CUS.GRAU = 3
GROUP BY CUS.CODCENCUS
)GROUP BY CODCENCUS


UNION ALL

SELECT
CODCENCUS
, 4 GRAU
,SUM(VLRLIQ) VLRLIQ
,SUM(VLRREC)VLRREC
,SUM(VLRDESP)VLRDESP
FROM (
SELECT 
RPAD(SUBSTR(
    CASE WHEN LENGTH(TO_CHAR(CUS.CODCENCUS)) = 9 THEN LPAD(TO_CHAR(CUS.CODCENCUS), 10, '0') ELSE TO_CHAR(CUS.CODCENCUS)     END 
, 1, 8), 10, '0') AS CODCENCUS
,SUM(CASE WHEN NVL(X.VLRBAIXA,0) = 0 THEN X.VLRDESDOB ELSE X.VLRBAIXA END) AS VLRLIQ
,SUM(CASE WHEN X.RECDESP = 1 AND NVL(X.VLRBAIXA,0) = 0 THEN X.VLRDESDOB 
          WHEN X.RECDESP = 1 AND NVL(X.VLRBAIXA,0) <> 0 THEN X.VLRBAIXA END) AS VLRREC
,SUM(CASE WHEN X.RECDESP = -1 AND NVL(X.VLRBAIXA,0) = 0 THEN X.VLRDESDOB 
          WHEN X.RECDESP = -1 AND NVL(X.VLRBAIXA,0) <> 0 THEN X.VLRBAIXA END) AS VLRDESP
FROM TSICUS CUS
LEFT JOIN VGF_RESULTADO_SATIS X ON CUS.CODCENCUS = X.CODCENCUS
WHERE CUS.ATIVO = 'S' AND NVL(CUS.CODCENCUS,0) <> 0 
AND X.DHBAIXA BETWEEN '01/12/2024' AND '31/12/2024'
AND X.RECDESP = -1 AND CUS.GRAU = 4
GROUP BY CUS.CODCENCUS
)GROUP BY CODCENCUS


UNION ALL

SELECT
CODCENCUS
, 5 GRAU
,SUM(VLRLIQ) VLRLIQ
,SUM(VLRREC)VLRREC
,SUM(VLRDESP)VLRDESP
FROM (
SELECT 
RPAD(SUBSTR(
    CASE WHEN LENGTH(TO_CHAR(CUS.CODCENCUS)) = 9 THEN LPAD(TO_CHAR(CUS.CODCENCUS), 10, '0') ELSE TO_CHAR(CUS.CODCENCUS)     END 
, 1, 10), 10, '0') AS CODCENCUS
,SUM(CASE WHEN NVL(X.VLRBAIXA,0) = 0 THEN X.VLRDESDOB ELSE X.VLRBAIXA END) AS VLRLIQ
,SUM(CASE WHEN X.RECDESP = 1 AND NVL(X.VLRBAIXA,0) = 0 THEN X.VLRDESDOB 
          WHEN X.RECDESP = 1 AND NVL(X.VLRBAIXA,0) <> 0 THEN X.VLRBAIXA END) AS VLRREC
,SUM(CASE WHEN X.RECDESP = -1 AND NVL(X.VLRBAIXA,0) = 0 THEN X.VLRDESDOB 
          WHEN X.RECDESP = -1 AND NVL(X.VLRBAIXA,0) <> 0 THEN X.VLRBAIXA END) AS VLRDESP
FROM TSICUS CUS
LEFT JOIN VGF_RESULTADO_SATIS X ON CUS.CODCENCUS = X.CODCENCUS
WHERE CUS.ATIVO = 'S' AND NVL(CUS.CODCENCUS,0) <> 0 
AND X.DHBAIXA BETWEEN '01/12/2024' AND '31/12/2024'
AND X.RECDESP = -1 AND CUS.GRAU = 5
GROUP BY CUS.CODCENCUS
)GROUP BY CODCENCUS


ORDER BY 1




