# Dockerfile
FROM python:3.8
COPY bmi_calculator.py /app/bmi_calculator.py
WORKDIR /app
CMD ["python", "bmi_calculator.py"]

# execute estes comandos
# docker build -t bmi-calculator .
# docker run -it --rm bmi-calculator