version: '3.8'

services:
  oracle-db:
    image: gvenzl/oracle-xe
    container_name: oracle-xe
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: minha_senha_segura
    volumes:
      - oracle_data:/opt/oracle/oradata

  sankhya-app:
    image: diogomou/sankhya-app:latest
    container_name: sankhya-app
    depends_on:
      - oracle-db
    ports:
      - "8080:8080"
    environment:
      DB_HOST: oracle-db
      DB_PORT: 1521
      DB_USER: sankhya
      DB_PASSWORD: minha_senha_segura
      DB_NAME: XE

volumes:
  oracle_data:
