-- Versão otimizada do SQL para melhor performance
-- Mantém toda funcionalidade original mas com melhor performance

-- Usar CTEs para melhorar legibilidade e performance das subconsultas
WITH 
-- CTE para observações das notas
NotasObs AS (
    SELECT 
        FIN.NUFIN,
        CAB.OBSERVACAO AS AD_OBSNOTA
    FROM TGFCAB CAB WITH (NOLOCK)
    INNER JOIN TGFFIN FIN WITH (NOLOCK) ON FIN.NUNOTA = CAB.NUNOTA
),

-- CTE para dados de antecipação bancária
AntecBancaria AS (
    SELECT DISTINCT
        NUFINTITORI AS NUFIN,
        'S' AS FLG_ANTECIPADO
    FROM TGFANB WITH (NOLOCK)
    WHERE NUFINTITORI IS NOT NULL
),

-- CTE para conciliação bancária
ConciliacaoBancaria AS (
    SELECT 
        NUBCO,
        CONCILIADO,
        DHCONCILIACAO AS DHCONCIL
    FROM TGFMBC WITH (NOLOCK)
),

-- CTE para contabilização
Contabilizacao AS (
    SELECT 
        NUNICO,
        COUNT(*) AS QTD_CONTAB
    FROM TCBINT WITH (NOLOCK)
    WHERE ORIGEM IN ('F','B')
    GROUP BY NUNICO
),

-- CTE para dados de antecipação
Antecipacao AS (
    SELECT 
        NUANTBANC,
        NUFINTITORI,
        DTANTBANC
    FROM TGFANB WITH (NOLOCK)
),

-- CTE para PIX
PixData AS (
    SELECT 
        NUFIN,
        IDTRANSACAO
    FROM TGFPIX WITH (NOLOCK)
    WHERE SEQPIX = (
        SELECT MAX(P2.SEQPIX) 
        FROM TGFPIX P2 WITH (NOLOCK)
        WHERE P2.NUFIN = TGFPIX.NUFIN
    )
),

-- CTE para complementos fixos
ComplFix AS (
    SELECT 
        NUNOTA,
        NUMNOTA,
        SERIENOTA
    FROM TGFCAB WITH (NOLOCK)
    WHERE NUNOTA IN (
        SELECT DISTINCT NFCOMPLFIX 
        FROM TGFFIN WITH (NOLOCK)
        WHERE NFCOMPLFIX IS NOT NULL
    )
),

-- CTE para operações Vendamais
OperacaoVM AS (
    SELECT 
        FIN.NUFIN,
        CAB.CODOPERACAOVENDAMAIS AS CODOPERACAOVM,
        CAB.DHAPROVACAO AS DHAPROVACAOVENDAMAIS
    FROM TGFCABVM CAB WITH (NOLOCK)
    INNER JOIN TGFFINVM FIN WITH (NOLOCK) ON FIN.NUNOTA = CAB.NUNOTA
),

-- CTE para dados TIM
TimData AS (
    SELECT 
        DTLPARCELA,
        SUM(ISNULL(DTLVALOR, 0)) AS TIMVLRALUGUEL
    FROM TIMDTL WITH (NOLOCK)
    WHERE DTLHISTORICO = ISNULL((
        SELECT INTEIRO 
        FROM TSIPAR WITH (NOLOCK)
        WHERE UPPER(CHAVE) = 'TIMHISTDETLALUG' 
        AND CODUSU = 0
    ), 2)
    GROUP BY DTLPARCELA
),

-- CTE para impostos
Impostos AS (
    SELECT 
        NUFIN,
        ROUND(SUM(VALOR * TIPIMP), 2) AS VLR_IMPOSTOS
    FROM TGFIMF WITH (NOLOCK)
    GROUP BY NUFIN
)

-- Query principal otimizada
SELECT 
    -- Campos originais da TGFFIN
    TGFFIN.ABATIMENTO,
    TGFFIN.ABATIMENTOCAN,
    TGFFIN.AD_CODREC,
    TGFFIN.AGENCIA_CMC7,
    TGFFIN.ALIQICMS,
    TGFFIN.AUTORIZADO,
    TGFFIN.BAIXAAPI,
    TGFFIN.BASEICMS,
    TGFFIN.BASEINSS,
    TGFFIN.BASEIRF,
    TGFFIN.BLOQVAR,
    TGFFIN.CARTA,
    TGFFIN.CARTAODESC,
    TGFFIN.CGC_CPF_CMC7,
    TGFFIN.CHAVECTE,
    TGFFIN.CHAVECTEREF,
    TGFFIN.CHAVENFEGNRE,
    TGFFIN.CHEQUERASTREADO_CMC7,
    TGFFIN.CLASSIFCESSAOOBRA,
    TGFFIN.CODBARRA,
    TGFFIN.CODBCO,
    TGFFIN.CODBCO_CMC7,
    TGFFIN.CODCBE,
    TGFFIN.CODCC,
    TGFFIN.CODCENCUS,
    TGFFIN.CODCFO,
    TGFFIN.CODCIDFIMCTE,
    TGFFIN.CODCIDINICTE,
    TGFFIN.CODCONTATO,
    TGFFIN.CODCTABCOINT,
    TGFFIN.CODEMP,
    TGFFIN.CODEMPBAIXA,
    TGFFIN.CODFUNC,
    TGFFIN.CODIGOBARRA,
    TGFFIN.CODIMOVELRURAL,
    TGFFIN.CODIPTU,
    TGFFIN.CODLST,
    TGFFIN.CODMOEDA,
    TGFFIN.CODNAT,
    TGFFIN.CODOBRA,
    TGFFIN.CODOBSPADRAO,
    TGFFIN.CODPARC,
    TGFFIN.CODPROJ,
    TGFFIN.CODRECEITA,
    TGFFIN.CODREGUA,
    TGFFIN.CODTIPOPER,
    TGFFIN.CODTIPOPERBAIXA,
    TGFFIN.CODTIPTIT,
    TGFFIN.CODTRIB,
    TGFFIN.CODUSU,
    TGFFIN.CODUSUBAIXA,
    TGFFIN.CODUSUCOBR,
    TGFFIN.CODVEICULO,
    TGFFIN.CODVEND,
    TGFFIN.CONTA_CMC7,
    TGFFIN.CUSTASPROCESSUAIS,
    TGFFIN.DEPOSITOJUDICIAL,
    TGFFIN.DESCRTPAGNFCE,
    TGFFIN.DESDOBDUPL,
    TGFFIN.DESDOBRAMENTO,
    TGFFIN.DESPADVOGADO,
    TGFFIN.DESPCART,
    TGFFIN.DHBAIXA,
    TGFFIN.DHMOV,
    TGFFIN.DHTIPOPER,
    TGFFIN.DHTIPOPERBAIXA,
    TGFFIN.DH_IMPRESSAO,
    TGFFIN.DIGSAFRA,
    TGFFIN.DTALTER,
    TGFFIN.DTBAIXAPREV,
    TGFFIN.DTCONTAB,
    TGFFIN.DTCONTABBAIXA,
    TGFFIN.DTENTSAI,
    TGFFIN.DTENTSAIINFO,
    TGFFIN.DTINITREFAPURACAO,
    TGFFIN.DTINTEGRACAOIPI,
    TGFFIN.DTNEG,
    TGFFIN.DTPRAZO,
    TGFFIN.DTREFERENCIA,
    TGFFIN.DTVENC,
    TGFFIN.DTVENCINIC,
    TGFFIN.EMVPIX,
    TGFFIN.EXIGEISSQN,
    TGFFIN.HISTORICO,
    TGFFIN.IDLOTEFDIC,
    TGFFIN.IDUNICO,
    TGFFIN.INDRECEFDCONT,
    TGFFIN.INFCOMPLEFDCONT,
    TGFFIN.INSSRETIDO,
    TGFFIN.IRFRETIDO,
    TGFFIN.ISSRETIDO,
    TGFFIN.JUROSAVP,
    TGFFIN.LINHADIGITAVEL,
    TGFFIN.M2,
    TGFFIN.METODOCALCIRRF,
    TGFFIN.MODELONFDES,
    TGFFIN.MONIOCOREM,
    TGFFIN.MOTNAORETERISSQN,
    TGFFIN.NATUREZAOPERDES,
    TGFFIN.NFCOMPLFIX,
    TGFFIN.NFENTSEQFIX,
    TGFFIN.NOMEEMITENTE_CMC7,
    TGFFIN.NOSSONUM,
    TGFFIN.NROIMPORT,
    TGFFIN.NROLOTEGNRE,
    TGFFIN.NUANTBANC,
    TGFFIN.NUAPONTA,
    TGFFIN.NUBCO,
    TGFFIN.NUCAIXA,
    TGFFIN.NUCCR,
    TGFFIN.NUCHQ,
    TGFFIN.NUCKC,
    TGFFIN.NUCOMPENS,
    TGFFIN.NUDEV,
    TGFFIN.NUFIN,
    TGFFIN.NUFTC,
    TGFFIN.NUMBOR,
    TGFFIN.NUMCONTRATO,
    TGFFIN.NUMDOCARRECAD,
    TGFFIN.NUMDUPL,
    TGFFIN.NUMNFSE,
    TGFFIN.NUMNOTA,
    TGFFIN.NUMOCORRENCIAS,
    TGFFIN.NUMOS,
    TGFFIN.NUMPROCADMJUDIC,
    TGFFIN.NUMREMESSA,
    TGFFIN.NUNOTA,
    TGFFIN.NUPED,
    TGFFIN.NURENEG,
    TGFFIN.NUVERBA,
    TGFFIN.OBRACONSTCIVIL,
    TGFFIN.ORDEMCARGA,
    TGFFIN.ORIGEM,
    TGFFIN.PARCRENEG,
    TGFFIN.PDD,
    TGFFIN.PIXTEF,
    TGFFIN.PROVISAO,
    TGFFIN.RATEADO,
    TGFFIN.RECADIANTAMENTORURAL,
    TGFFIN.RECDESP,
    TGFFIN.RECEBCARTAO,
    TGFFIN.RECEBIDO,
    TGFFIN.REFATCON,
    TGFFIN.REGESPTRIBUT,
    TGFFIN.REJEICAOGNRE,
    TGFFIN.SANGDESPDV,
    TGFFIN.SEQCAIXA,
    TGFFIN.SEQUENCIA,
    TGFFIN.SERIENFDES,
    TGFFIN.SERIENOTA,
    TGFFIN.SITESPECIALRESP,
    TGFFIN.STATUSGNRE,
    TGFFIN.TIMBLOQUEADA,
    TGFFIN.TIMCONTALANC,
    TGFFIN.TIMCONTAREP,
    TGFFIN.TIMCONTRATOADM,
    TGFFIN.TIMCONTRATOLOC,
    TGFFIN.TIMCONTRATOLTV,
    TGFFIN.TIMDATADEJUR,
    TGFFIN.TIMDHBAIXA,
    TGFFIN.TIMDHGERREPASSE,
    TGFFIN.TIMDHGERREPPARCIAL,
    TGFFIN.TIMDTIMPBOL,
    TGFFIN.TIMDTIMPBOLLOCAL,
    TGFFIN.TIMDTREPASSE,
    TGFFIN.TIMDTREPPARCIAL,
    TGFFIN.TIMFECHAMENTO,
    TGFFIN.TIMFECHAMENTOALU,
    TGFFIN.TIMFINGARANTORIG,
    TGFFIN.TIMIMOVEL,
    TGFFIN.TIMNEGOCIACAO,
    TGFFIN.TIMNOMEADVOGADO,
    TGFFIN.TIMNUFINORIG,
    TGFFIN.TIMNUMREG,
    TGFFIN.TIMORIGEM,
    TGFFIN.TIMORIGRENEG,
    TGFFIN.TIMPARCELA,
    TGFFIN.TIMRENEGCANCLOTE,
    TGFFIN.TIMRENEGIMV,
    TGFFIN.TIMRENEGLOTE,
    TGFFIN.TIMREPINTELIGENTE,
    TGFFIN.TIMREPPARCIAL,
    TGFFIN.TIMRESCISAOLOC,
    TGFFIN.TIMRESCISAOLTV,
    TGFFIN.TIMSAC,
    TGFFIN.TIMTIPOINTERMED,
    TGFFIN.TIMTXADMGERALU,
    TGFFIN.TIMVENDAIMV,
    TGFFIN.TIMVENDALOTE,
    TGFFIN.TIMVLRAMORTCONTRATO,
    TGFFIN.TIMVLRCORRMONET,
    TGFFIN.TIMVLRJUROCONTRATO,
    TGFFIN.TIPAPURACAO,
    TGFFIN.TIPJURO,
    TGFFIN.TIPMARCCHEQ,
    TGFFIN.TIPMULTA,
    TGFFIN.TPAGNFCE,
    TGFFIN.TROCOPDV,
    TGFFIN.VALORPRESENTE,
    TGFFIN.VENDAMAIS,
    TGFFIN.VLRALIBERAR,
    TGFFIN.VLRBAIXA,
    TGFFIN.VLRCESSAO,
    TGFFIN.VLRCHEQUE,
    TGFFIN.VLRDESC,
    TGFFIN.VLRDESCCALC,
    TGFFIN.VLRDESCEMBUT,
    TGFFIN.VLRDESDOB,
    TGFFIN.VLRDESDOBCALC,
    TGFFIN.VLRFATCARTAO,
    TGFFIN.VLRGNREDOIS,
    TGFFIN.VLRICMSXMLCTE,
    TGFFIN.VLRINSS,
    TGFFIN.VLRIRF,
    TGFFIN.VLRISS,
    TGFFIN.VLRJURO,
    TGFFIN.VLRJUROEMBUT,
    TGFFIN.VLRJUROLIB,
    TGFFIN.VLRJURONEGOC,
    TGFFIN.VLRMOEDA,
    TGFFIN.VLRMOEDABAIXA,
    TGFFIN.VLRMULTA,
    TGFFIN.VLRMULTAEMBUT,
    TGFFIN.VLRMULTALIB,
    TGFFIN.VLRMULTANEGOC,
    TGFFIN.VLRPROV,
    TGFFIN.VLRVARCAMBIAL,
    TGFFIN.VLRVENDOR,

    -- Campos calculados otimizados usando CTEs
    NOBS.AD_OBSNOTA,
    ISNULL(ANTB.FLG_ANTECIPADO, 'N') AS ANTECIPADO,
    
    -- Cálculos de atraso otimizados
    CASE 
        WHEN TGFFIN.DTVENC IS NULL THEN 0 
        WHEN TGFFIN.DHBAIXA IS NOT NULL AND (TGFFIN.VLRBAIXA <> 0 OR TGFFIN.VLRDESC >= TGFFIN.VLRDESDOB) 
            THEN DATEDIFF(DAY, TGFFIN.DTVENC, TGFFIN.DHBAIXA)
        ELSE DATEDIFF(DAY, CONVERT(date, TGFFIN.DTVENC), CONVERT(date, GETDATE()))
    END AS ATRASO,
    
    CASE 
        WHEN TGFFIN.DTVENCINIC IS NULL THEN 0 
        WHEN TGFFIN.DHBAIXA IS NOT NULL AND TGFFIN.VLRBAIXA <> 0 
            THEN DATEDIFF(DAY, TGFFIN.DTVENCINIC, TGFFIN.DHBAIXA)
        ELSE DATEDIFF(DAY, CONVERT(date, TGFFIN.DTVENCINIC), CONVERT(date, GETDATE()))
    END AS ATRASOINICIAL,

    -- Dados do parceiro
    PAR.CGC_CPF AS CGC_CPF_PARC,
    PAR.CHAVEPIX,

    -- Operação Vendamais
    OPVM.CODOPERACAOVM,
    ISNULL(CONCB.CONCILIADO, 'N') AS CONCILIADO,
    CASE WHEN CONTAB.QTD_CONTAB > 0 THEN 'S' ELSE 'N' END AS CONTABILIZADO,
    OPVM.DHAPROVACAOVENDAMAIS,
    CONCB.DHCONCIL,
    
    -- Data de antecipação
    CASE 
        WHEN TGFFIN.NUANTBANC IS NOT NULL 
            THEN ANT.DTANTBANC
        ELSE NULL
    END AS DTANTECIPACAO,

    -- PIX
    PIX.IDTRANSACAO AS IDTRANSACAOPIX,

    -- Complementos fixos
    CASE 
        WHEN ISNULL(TGFFIN.NFCOMPLFIX, 0) <> 0 
            THEN CF.NUMNOTA 
        ELSE NULL 
    END AS NUMCOMPLFIX,

    -- Percentual de desconto
    CASE 
        WHEN TGFFIN.VLRDESDOB IS NOT NULL AND TGFFIN.VLRDESDOB > 0 
            THEN ROUND(TGFFIN.VLRDESC / TGFFIN.VLRDESDOB * 100, 2)
        ELSE 0 
    END AS PERCDESC,

    -- Prazos
    CASE 
        WHEN TGFFIN.DTVENC IS NOT NULL AND TGFFIN.DTNEG IS NOT NULL 
            THEN DATEDIFF(DAY, TGFFIN.DTNEG, TGFFIN.DTVENC)
        ELSE NULL 
    END AS PRAZO,

    CASE 
        WHEN TGFFIN.DTVENCINIC IS NOT NULL AND TGFFIN.DTNEG IS NOT NULL 
            THEN DATEDIFF(DAY, TGFFIN.DTNEG, TGFFIN.DTVENCINIC)
        ELSE NULL 
    END AS PRAZOINICIAL,

    -- Rateado do cabeçalho
    CASE 
        WHEN TGFFIN.NUNOTA IS NOT NULL AND TGFFIN.NUNOTA > 0 
            THEN ISNULL(CABRATEADO.RATEADO, 'N')
        ELSE 'N' 
    END AS RATEADOCAB,

    -- Série da nota complementar
    CASE 
        WHEN ISNULL(TGFFIN.NFCOMPLFIX, 0) <> 0 
            THEN CF.SERIENOTA 
        ELSE NULL 
    END AS SERIENOTACOMPL,

    -- Subtipo de venda
    TIT.SUBTIPOVENDA,

    -- Taxa Vendamais
    ISNULL(TGFFIN.CARTAODESC, 0) AS TAXAVENDAMAIS,

    -- Estágio TIM
    CASE WHEN TGFFIN.TIMORIGEM IN ('AL','AV','FC') THEN 
        CASE WHEN TGFFIN.DHBAIXA IS NULL THEN 
            CASE WHEN DATEADD(DAY, DATEDIFF(DAY, 0, TGFFIN.DTVENC), 0) < DATEADD(DAY, DATEDIFF(DAY, 0, GETDATE()), 0) THEN 
                CASE WHEN TGFFIN.TIMDATADEJUR IS NOT NULL THEN 'Jurídico' 
                ELSE 'Atrasado' END 
            ELSE 'Aberto' END	 
        ELSE 'Baixado' END 
    ELSE NULL END AS TIMESTAGIO,

    -- Valor aluguel TIM
    CASE WHEN TGFFIN.TIMORIGEM IN ('AL','AV','FC') THEN 
        ISNULL(TIM.TIMVLRALUGUEL, 0)
    ELSE NULL END AS TIMVLRALUGUEL,

    -- Valor ICMS
    CASE 
        WHEN ISNULL(TGFFIN.VLRICMSXMLCTE, 0) = 0 
            THEN ROUND((ISNULL(TGFFIN.BASEICMS, 0) * ISNULL(TGFFIN.ALIQICMS, 0)) / 100, 2)
        ELSE TGFFIN.VLRICMSXMLCTE 
    END AS VLRICMS,

    -- Juros + Multa
    (TGFFIN.VLRJURO + TGFFIN.VLRMULTA) AS VLRJUROSMAISMULTA,

    -- Valor líquido otimizado
    (ISNULL(TGFFIN.VLRDESDOB, 0) + 
     (CASE WHEN TGFFIN.TIPMULTA = '1' THEN ISNULL(TGFFIN.VLRMULTA, 0) ELSE 0 END) + 
     (CASE WHEN TGFFIN.TIPJURO = '1' THEN ISNULL(TGFFIN.VLRJURO, 0) ELSE 0 END) + 
     ISNULL(TGFFIN.DESPCART, 0) + 
     ISNULL(TGFFIN.VLRVENDOR, 0) - 
     ISNULL(TGFFIN.VLRDESC, 0) - 
     (CASE WHEN TGFFIN.IRFRETIDO = 'S' THEN ISNULL(TGFFIN.VLRIRF, 0) ELSE 0 END) - 
     (CASE WHEN TGFFIN.ISSRETIDO = 'S' THEN ISNULL(TGFFIN.VLRISS, 0) ELSE 0 END) - 
     (CASE WHEN TGFFIN.INSSRETIDO = 'S' THEN ISNULL(TGFFIN.VLRINSS, 0) ELSE 0 END) - 
     ISNULL(TGFFIN.CARTAODESC, 0) + 
     ISNULL(IMP.VLR_IMPOSTOS, 0) + 
     ISNULL(TGFFIN.VLRMULTANEGOC, 0) + 
     ISNULL(TGFFIN.VLRJURONEGOC, 0) - 
     ISNULL(TGFFIN.VLRMULTALIB, 0) - 
     ISNULL(TGFFIN.VLRJUROLIB, 0) + 
     ISNULL(TGFFIN.VLRVARCAMBIAL, 0)) * ISNULL(TGFFIN.RECDESP, 0) AS VLRLIQUIDO,

    -- Valor total calculado
    (ISNULL(TGFFIN.VLRDESDOB, 0) + ISNULL(TGFFIN.VLRJURO, 0) + ISNULL(TGFFIN.VLRMULTA, 0) - ISNULL(TGFFIN.VLRDESC, 0)) AS VLRTOTALCALC,

    -- Valor troco otimizado
    CASE 
        WHEN TGFFIN.VLRCHEQUE IS NOT NULL AND TGFFIN.VLRCHEQUE <> 0 AND TGFFIN.VLRBAIXA IS NOT NULL THEN
            TGFFIN.VLRCHEQUE - CASE 
                WHEN TGFFIN.NUBCO IS NULL THEN TGFFIN.VLRBAIXA 
                ELSE ISNULL(BAIXAS.VLRBAIXA_TOTAL, TGFFIN.VLRBAIXA)
            END
        ELSE 0 
    END AS VLRTROCO,

    -- Dados das tabelas relacionadas (mantidos como no original)
    Banco.NOMEBCO AS l0_NOMEBCO,
    CentroResultado.DESCRCENCUS AS l1_DESCRCENCUS,
    ClassificacaoFiscalOperacao.DESCRCFO AS l2_DESCRCFO,
    CompFinancReinf.CODNATREND AS l3_CODNATREND,
    CompFinancReinf.SEMIREXT AS l3_SEMIREXT,
    CompFinancReinf.DTESCRCONT AS l3_DTESCRCONT,
    CompFinancReinf.TRIBIRRFEXT AS l3_TRIBIRRFEXT,
    CompFinancReinf.TEMDEDIRPF AS l3_TEMDEDIRPF,
    CompFinancReinf.CODDEDIRPF AS l3_CODDEDIRPF,
    CompFinancReinf.VLRDEDBASEIRPF AS l3_VLRDEDBASEIRPF,
    CompFinancReinf.IRRFISENTO AS l3_IRRFISENTO,
    CompFinancReinf.TPISENCAO AS l3_TPISENCAO,
    CompFinancReinf.VLRISENCAOIDADE AS l3_VLRISENCAOIDADE,
    CompFinancReinf.DTLAUDO AS l3_DTLAUDO,
    CompFinancReinf.DESCISENCAO AS l3_DESCISENCAO,
    CadastroNaturezaRendimentos4_1.DESCNATREND AS l4_DESCNATREND,
    CadastroNaturezaRendimentos4_1.CODNATREND AS l4_CODNATREND,
    CadastroNaturezaRendimentos4_1.FCI AS l4_FCI,
    CadastroNaturezaRendimentos4_1.DECIMOTERCEIRO AS l4_DECIMOTERCEIRO,
    CadastroNaturezaRendimentos4_1.RRA AS l4_RRA,
    CadastroNaturezaRendimentos4_1.DEDUCAO AS l4_DEDUCAO,
    CadastroNaturezaRendimentos4_1.RENDISENTO AS l4_RENDISENTO,
    CadastroNaturezaRendimentos4_1.TRIBUTO AS l4_TRIBUTO,
    CadastroNaturezaRendimentos4_1.BLOCOAPLIC AS l4_BLOCOAPLIC,
    CadastroNaturezaRendimentos4_1.APLICACAO AS l4_APLICACAO,
    CadastroNaturezaRendimentos4_1.DTINICIOVAL AS l4_DTINICIOVAL,
    CadastroNaturezaRendimentos4_1.DTFIMVAL AS l4_DTFIMVAL,
    CadastroNaturezaRendimentos4_1.ATIVO AS l4_ATIVO,
    CadastroNaturezaRendimentos4_1.GERSEMTRIB AS l4_GERSEMTRIB,
    ContaBancaria.DESCRICAO AS l5_DESCRICAO,
    Contato.NOMECONTATO AS l6_NOMECONTATO,
    Empresa.NOMEFANTASIA AS l7_NOMEFANTASIA,
    EmpresaBaixa.NOMEFANTASIA AS l8_NOMEFANTASIA,
    Funcionario.NOMEFUNC AS l9_NOMEFUNC,
    ImovelRural.NOMEFANTASIA AS l10_NOMEFANTASIA,
    ListaServicoSintegra.DESCRLST AS l11_DESCRLST,
    Moeda.NOMEMOEDA AS l12_NOMEMOEDA,
    Natureza.DESCRNAT AS l13_DESCRNAT,
    ObservacaoNotasFiscais.OBSERVACAO AS l14_OBSERVACAO,
    Parceiro.NOMEPARC AS l15_NOMEPARC,
    UnidadeFederativa16_2.UF AS l16_UF,
    PixTEF.SEQPIXTEF AS l17_SEQPIXTEF,
    Projeto.IDENTIFICACAO AS l18_IDENTIFICACAO,
    ReceitaDarf.DESCRRECEITA AS l19_DESCRRECEITA,
    TEF.REDE AS l20_REDE,
    TEF.TIPODOC AS l20_TIPODOC,
    TEF.NUMCV AS l20_NUMCV,
    TEF.NUMDOC AS l20_NUMDOC,
    TEF.NUMPV AS l20_NUMPV,
    TEF.DESDOBRAMENTO AS l20_DESDOBRAMENTO,
    TEF.DTTRANSACAO AS l20_DTTRANSACAO,
    TEF.VLRTRANSACAO AS l20_VLRTRANSACAO,
    TEF.VLRTAXA AS l20_VLRTAXA,
    TEF.BANDEIRA AS l20_BANDEIRA,
    TEF.CONFIRMADO AS l20_CONFIRMADO,
    TEF.CODUSU AS l20_CODUSU,
    TEF.PROCESSO AS l20_PROCESSO,
    TEF.COMPROVANTE AS l20_COMPROVANTE,
    TEF.IDENTIFICACAOTEF AS l20_IDENTIFICACAOTEF,
    TEF.OPERACAOTEF AS l20_OPERACAOTEF,
    TEF.AUTORIZACAO AS l20_AUTORIZACAO,
    TEF.NUMNSU AS l20_NUMNSU,
    TEF.NOMEREDE AS l20_NOMEREDE,
    TimContaBancaria.DESCRICAO AS l21_DESCRICAO,
    TimImovel.IMVDESCRICAO AS l22_IMVDESCRICAO,
    TimTipoIntermed.TINDESCRICAO AS l23_TINDESCRICAO,
    TipoOperacao.DESCROPER AS l24_DESCROPER,
    TipoOperacao.TIPMOV AS l24_TIPMOV,
    TipoOperacaoBaixa.DESCROPER AS l25_DESCROPER,
    TipoTitulo.DESCRTIPTIT AS l26_DESCRTIPTIT,
    TipoTitulo.INFCMC7 AS l26_INFCMC7,
    Usuario.NOMEUSU AS l27_NOMEUSU,
    Usuario2.NOMEUSU AS l28_NOMEUSU,
    UsuarioBaixa.NOMEUSU AS l29_NOMEUSU,
    Vendedor.APELIDO AS l30_APELIDO

FROM TGFFIN WITH (NOLOCK)
    -- JOINs com CTEs para melhor performance
    LEFT JOIN NotasObs NOBS ON TGFFIN.NUFIN = NOBS.NUFIN
    LEFT JOIN AntecBancaria ANTB ON TGFFIN.NUFIN = ANTB.NUFIN
    LEFT JOIN ConciliacaoBancaria CONCB ON TGFFIN.NUBCO = CONCB.NUBCO
    LEFT JOIN Contabilizacao CONTAB ON TGFFIN.NUFIN = CONTAB.NUNICO
    LEFT JOIN Antecipacao ANT ON TGFFIN.NUANTBANC = ANT.NUANTBANC AND ANT.NUFINTITORI = TGFFIN.NUFIN
    LEFT JOIN PixData PIX ON TGFFIN.NUFIN = PIX.NUFIN
    LEFT JOIN ComplFix CF ON TGFFIN.NFCOMPLFIX = CF.NUNOTA
    LEFT JOIN OperacaoVM OPVM ON TGFFIN.NUFIN = OPVM.NUFIN
    LEFT JOIN TimData TIM ON TGFFIN.NUFIN = TIM.DTLPARCELA
    LEFT JOIN Impostos IMP ON TGFFIN.NUFIN = IMP.NUFIN
    
    -- JOIN para dados do parceiro
    LEFT JOIN TGFPAR PAR WITH (NOLOCK) ON TGFFIN.CODPARC = PAR.CODPARC
    
    -- JOIN para subtipo de venda
    LEFT JOIN TGFTIT TIT WITH (NOLOCK) ON TGFFIN.CODTIPTIT = TIT.CODTIPTIT
    
    -- JOIN para rateado do cabeçalho
    LEFT JOIN TGFCAB CABRATEADO WITH (NOLOCK) ON TGFFIN.NUNOTA = CABRATEADO.NUNOTA
    
    -- JOIN para baixas (para cálculo do troco)
    LEFT JOIN (
        SELECT NUBCO, SUM(VLRBAIXA) AS VLRBAIXA_TOTAL
        FROM TGFFIN WITH (NOLOCK)
        WHERE NUBCO IS NOT NULL
        GROUP BY NUBCO
    ) BAIXAS ON TGFFIN.NUBCO = BAIXAS.NUBCO

    -- Todos os JOINs originais mantidos
    LEFT JOIN TSIBCO Banco WITH (NOLOCK) ON TGFFIN.CODBCO = Banco.CODBCO
    LEFT JOIN TSICUS CentroResultado WITH (NOLOCK) ON TGFFIN.CODCENCUS = CentroResultado.CODCENCUS
    LEFT JOIN TGFCFO ClassificacaoFiscalOperacao WITH (NOLOCK) ON TGFFIN.CODCFO = ClassificacaoFiscalOperacao.CODCFO
    LEFT JOIN TGFRNF CompFinancReinf WITH (NOLOCK) ON TGFFIN.NUFIN = CompFinancReinf.NUFIN
    LEFT JOIN TGFNRR CadastroNaturezaRendimentos4_1 WITH (NOLOCK) ON CompFinancReinf.CODNATREND = CadastroNaturezaRendimentos4_1.CODNATREND
    LEFT JOIN TSICTA ContaBancaria WITH (NOLOCK) ON TGFFIN.CODCTABCOINT = ContaBancaria.CODCTABCOINT
    LEFT JOIN TGFCTT Contato WITH (NOLOCK) ON TGFFIN.CODPARC = Contato.CODPARC AND TGFFIN.CODCONTATO = Contato.CODCONTATO
    LEFT JOIN TSIEMP Empresa WITH (NOLOCK) ON TGFFIN.CODEMP = Empresa.CODEMP
    LEFT JOIN TSIEMP EmpresaBaixa WITH (NOLOCK) ON TGFFIN.CODEMPBAIXA = EmpresaBaixa.CODEMP
    LEFT JOIN TFPFUN Funcionario WITH (NOLOCK) ON TGFFIN.CODEMP = Funcionario.CODEMP AND TGFFIN.CODFUNC = Funcionario.CODFUNC
    LEFT JOIN TSIEMP ImovelRural WITH (NOLOCK) ON TGFFIN.CODIMOVELRURAL = ImovelRural.CODEMP
    LEFT JOIN TGFLST ListaServicoSintegra WITH (NOLOCK) ON TGFFIN.CODLST = ListaServicoSintegra.CODLST
    LEFT JOIN TSIMOE Moeda WITH (NOLOCK) ON TGFFIN.CODMOEDA = Moeda.CODMOEDA
    LEFT JOIN TGFNAT Natureza WITH (NOLOCK) ON TGFFIN.CODNAT = Natureza.CODNAT
    LEFT JOIN TGFOBS ObservacaoNotasFiscais WITH (NOLOCK) ON TGFFIN.CODOBSPADRAO = ObservacaoNotasFiscais.CODOBSPADRAO
    LEFT JOIN TGFPAR Parceiro WITH (NOLOCK) ON TGFFIN.CODPARC = Parceiro.CODPARC
    LEFT JOIN TSICID Cidade16_1 WITH (NOLOCK) ON Parceiro.CODCID = Cidade16_1.CODCID
    LEFT JOIN TSIUFS UnidadeFederativa16_2 WITH (NOLOCK) ON Cidade16_1.UF = UnidadeFederativa16_2.CODUF
    LEFT JOIN TGFPIXTEF PixTEF WITH (NOLOCK) ON TGFFIN.PIXTEF = PixTEF.SEQPIXTEF
    LEFT JOIN TCSPRJ Projeto WITH (NOLOCK) ON TGFFIN.CODPROJ = Projeto.CODPROJ
    LEFT JOIN TGFRDARF ReceitaDarf WITH (NOLOCK) ON TGFFIN.CODRECEITA = ReceitaDarf.CODRECEITA
    LEFT JOIN TGFTEF TEF WITH (NOLOCK) ON TGFFIN.NUFIN = TEF.NUFIN
    LEFT JOIN TSICTA TimContaBancaria WITH (NOLOCK) ON TGFFIN.TIMCONTALANC = TimContaBancaria.CODCTABCOINT
    LEFT JOIN TIMIMV TimImovel WITH (NOLOCK) ON TGFFIN.TIMIMOVEL = TimImovel.IMVCODIGO
    LEFT JOIN TIMTIN TimTipoIntermed WITH (NOLOCK) ON TGFFIN.TIMTIPOINTERMED = TimTipoIntermed.TINCODIGO
    LEFT JOIN TGFTOP TipoOperacao WITH (NOLOCK) ON TGFFIN.CODTIPOPER = TipoOperacao.CODTIPOPER AND TGFFIN.DHTIPOPER = TipoOperacao.DHALTER
    LEFT JOIN TGFTOP TipoOperacaoBaixa WITH (NOLOCK) ON TGFFIN.CODTIPOPERBAIXA = TipoOperacaoBaixa.CODTIPOPER AND TGFFIN.DHTIPOPERBAIXA = TipoOperacaoBaixa.DHALTER
    LEFT JOIN TGFTIT TipoTitulo WITH (NOLOCK) ON TGFFIN.CODTIPTIT = TipoTitulo.CODTIPTIT
    LEFT JOIN TSIUSU Usuario WITH (NOLOCK) ON TGFFIN.CODUSU = Usuario.CODUSU
    LEFT JOIN TSIUSU Usuario2 WITH (NOLOCK) ON TGFFIN.TIMREPINTELIGENTE = Usuario2.CODUSU
    LEFT JOIN TSIUSU UsuarioBaixa WITH (NOLOCK) ON TGFFIN.CODUSUBAIXA = UsuarioBaixa.CODUSU
    LEFT JOIN TGFVEN Vendedor WITH (NOLOCK) ON TGFFIN.CODVEND = Vendedor.CODVEND

WHERE TGFFIN.RECDESP = 1 
    AND TGFFIN.PROVISAO = 'N' 
    AND TGFFIN.DHBAIXA IS NULL 
    AND NOT (TGFFIN.PROVISAO = 'S' AND TGFFIN.DHBAIXA IS NOT NULL AND TGFFIN.ORIGEM = 'E');
