

SELECT MET.CODMETA,MET.DTREF, NVL(MET.CODVEND,0) AS CODVEND, NVL(VEN.APELIDO,0) AS APELIDO,NVL(VEN.CODGER,0) AS CODGER, NVL(MET.CODPARC,0) AS CODPARC, 

NVL(PAR.RAZAOSOCIAL,0) AS PARCEIRO, 

NVL(MET.MARCA,0) AS MARCA,

NVL(VGF.CODGRUPOPROD,MAR.AD_GRUPOPROD) AS CODGRUPOPROD,

NVL(VGF.CODCENCUS,0) AS CODCENCUS, 

NVL(MET.QTDPREV,0) AS QTDPREV, 

SUM(NVL(VGF.QTD,0)) AS QTDREAL,

NVL(PRC.VLRVENDALT,0)AS PRECOLT, 

SUM(NVL(VGF.VLR,0)) AS VLRREAL

FROM TGFMET MET

LEFT JOIN (
    SELECT DESCRICAO, AD_GRUPOPROD
    FROM (
        SELECT DESCRICAO, AD_GRUPOPROD, ROW_NUMBER() OVER (PARTITION BY DESCRICAO ORDER BY ROWID) AS RN
        FROM TGFMAR
    )
    WHERE RN = 1
) MAR ON MAR.DESCRICAO = MET.MARCA

LEFT JOIN VGF_VENDAS_SATIS VGF ON MET.DTREF = TRUNC(VGF.DTMOV,'MM') 
    AND MET.CODVEND = VGF.CODVEND 
    AND MET.CODPARC = VGF.CODPARC 
    AND MET.MARCA = VGF.MARCA 
    AND VGF.BONIFICACAO = 'N'
    -- Filtro de datas para valores REAIS: respeita o intervalo exato
    AND TRUNC(VGF.DTMOV) BETWEEN CAST(:P_PERIODO.INI AS DATE) AND CAST(:P_PERIODO.FIN AS DATE)

LEFT JOIN AD_PRECOMARCA PRC ON (MET.MARCA = PRC.MARCA AND PRC.CODMETA = MET.CODMETA AND PRC.DTREF = (SELECT MAX(DTREF) FROM AD_PRECOMARCA WHERE CODMETA = MET.CODMETA AND DTREF <= MET.DTREF AND MARCA = MET.MARCA))

LEFT JOIN TGFPAR PAR ON MET.CODPARC = PAR.CODPARC

LEFT JOIN TGFVEN VEN ON MET.CODVEND = VEN.CODVEND

WHERE (VGF.CODCENCUS = :P_CR OR :P_CR IS NULL)

GROUP BY NVL(VGF.CODGRUPOPROD,MAR.AD_GRUPOPROD), MET.CODMETA,MET.DTREF,NVL(MET.CODVEND,0),NVL(VEN.APELIDO,0),NVL(VEN.CODGER,0),NVL(MET.CODPARC,0),NVL(PAR.RAZAOSOCIAL,0),NVL(MET.MARCA,0),NVL(VGF.CODCENCUS,0), NVL(MET.QTDPREV,0), NVL(PRC.VLRVENDALT,0)
