SELECT 
'OP ' || C.IDIPROC AS IDIPROC , 
PRO.CODPROD , 
PRO.AD_DESCRETIQ AS DESCRPROD, 
PRO.AD_TXTETIQBAG AS TXTETIQUETA,
PRO.AD_INSTRUCOESGERAIS,
'Lote: ' || I.NROLOTE as NROLOTE,
'Fabricação: ' || TO_CHAR(C.DHINST,'DD/MM/YYYY')  AS DTFAB,
'Validade: ' || TO_CHAR(ADD_MONTHS(C.DHINST,12),'DD/MM/YYYY')  AS DTVAL,
'Reg.Produto: ' || PRO.CODREGMAPA AS CODREGMAPA,
EMP.RAZAOSOCIAL,
EN.TIPO || ' ' || EN.NOMEEND || ', ' || EMP.NUMEND || ' ' || EMP.COMPLEMENTO || ' - '|| CID.NOMECID AS ENDERECO
 FROM TPRIPROC C, TPRIPA I, TGFPRO PRO, TPRPLP PL, TSIEMP EMP, TSIEND EN, TSICID CID
WHERE C.IDIPROC = I.IDIPROC
   AND I.CODPRODPA = PRO.CODPROD
   AND C.CODPLP = PL.CODPLP
   AND PL.CODEMP = EMP.CODEMP
   AND EMP .CODEND = EN.CODEND
   AND EMP.CODCID = CID.CODCID
   AND C.IDIPROC = 489