select 
LAN.CODEMP,
PLA.CTACTB,
LAN.REFERENCIA,
SUM(CASE WHEN LAN.TIPLANC = 'R' THEN LAN.VLRLANC*-1 ELSE  LAN.VLRLANC END) AS VLRLANC
from TCBLAN LAN
INNER JOIN TCBPLA PLA ON LAN.CODCTACTB = PLA.CODCTACTB
WHERE LAN.CODEMP IN (999,7,6)
GROUP BY
LAN.CODEMP,
PLA.CTACTB,
LAN.REFERENCIA