select 
PLA.CTACTB,
SUM(CASE WHEN LAN.TIPLANC = 'R' THEN LAN.VLRLANC*-1 ELSE  LAN.VLRLANC END) AS VLRLANC
from TCBLAN LAN
INNER JOIN TCBPLA PLA ON LAN.CODCTACTB = PLA.CODCTACTB
WHERE
LAN.REFERENCIA <= '01/12/2025'
AND LAN.CODEMP = 999
GROUP BY
PLA.CTACTB