WITH base_bal AS (

    SELECT
        CODEMP,
        CTACTB,
        REFERENCIA,
        
  SUM(ABS(VLRLANC))VLRLANC

    FROM IMP_BASE_BALANCETE

    WHERE CODEMP = :VAR_EMPRESA_DRE
      AND REFERENCIA = DATE(:VAR_DATA_REF_DRE)
          

    GROUP BY 
          CODEMP,
        CTACTB,
        REFERENCIA
)


SELECT
  DET.ID_ESTR_DEMONSTRATIVO,
  DETREF.ID_DET_DEMONSTRATIVO,
  DETCTACTB_EXC.ID_DET_DEMONSTRATIVO_REFERENCIA,
  SUM(BB.VLRLANC*DETCTACTB_EXC.SINAL)/1000 VLRLANC
  
    FROM ESTR_DEMONSTRATIVOS EST

    INNER JOIN DET_DEMONSTRATIVO DET
        ON EST.ID = DET.ID_ESTR_DEMONSTRATIVO

    INNER JOIN DET_DEMONSTRATIVO_REFERENCIA DETREF
        ON DET.ID = DETREF.ID_DET_DEMONSTRATIVO

    LEFT JOIN DET_DEMONSTRATIVO_CTACTB_EXC DETCTACTB_EXC
        ON DETREF.ID = DETCTACTB_EXC.ID_DET_DEMONSTRATIVO_REFERENCIA

    LEFT JOIN base_bal BB
        ON BB.CTACTB = DETCTACTB_EXC.PADRAO_CTACTB

    LEFT JOIN IMP_BASE_BALANCETE B
        ON B.CTACTB = DETCTACTB_EXC.PADRAO_CTACTB
       AND B.REFERENCIA = DETREF.REFERENCIA
       AND B.CODEMP = :VAR_EMPRESA_DRE

    WHERE DETREF.REFERENCIA = DATE(:VAR_DATA_REF_DRE)
      AND EST.ID IN (10)
AND DETCTACTB_EXC.ID IS NOT NULL


GROUP BY
DET.ID_ESTR_DEMONSTRATIVO,
DETREF.ID_DET_DEMONSTRATIVO,
DETCTACTB_EXC.ID_DET_DEMONSTRATIVO_REFERENCIA