-- Pré-agrega IMP_BASE_BALANCETE uma vez por conta (evita subqueries correlacionadas por linha).
-- Requer MySQL 8+ (CTE). Em 5.7, substituir o WITH por subquery derivada equivalente.
WITH base_bal AS (
  SELECT
    CTACTB,
    SUM(CASE WHEN REFERENCIA <= '2025-12-31T00:00:00' THEN VLRLANC ELSE 0 END) AS soma_ate_2025,
    SUM(CASE WHEN REFERENCIA <= '2024-12-31T00:00:00' THEN VLRLANC ELSE 0 END) AS soma_ate_2024
  FROM IMP_BASE_BALANCETE
  WHERE CODEMP = 999
    AND REFERENCIA <= '2025-12-31T00:00:00'
  GROUP BY CTACTB
)
SELECT
  DET.ORDEM,
  DET.NOME_GRUPO,
  SUM(
    CASE
      WHEN DETREF.REFERENCIA = '2025-12-01' THEN
        IFNULL(IFNULL(B.soma_ate_2025, 0) * DETCTACTB.SINAL, 0)
      ELSE 0
    END
  ) AS VLRLANC_ATU,
  SUM(
    CASE
      WHEN DETREF.REFERENCIA = '2024-12-01' THEN
        IFNULL(IFNULL(B.soma_ate_2024, 0) * DETCTACTB.SINAL, 0)
      ELSE 0
    END
  ) AS VLRLANC_ANT
FROM ESTR_DEMONSTRATIVOS EST
INNER JOIN DET_DEMONSTRATIVO DET
  ON EST.ID = DET.ID_ESTR_DEMONSTRATIVO
INNER JOIN DET_DEMONSTRATIVO_REFERENCIA DETREF
  ON DET.ID = DETREF.ID_DET_DEMONSTRATIVO
LEFT JOIN DET_DEMONSTRATIVO_CTACTB DETCTACTB
  ON DETREF.ID = DETCTACTB.ID_DET_DEMONSTRATIVO_REFERENCIA
LEFT JOIN base_bal B
  ON B.CTACTB = DETCTACTB.PADRAO_CTACTB
WHERE DETREF.REFERENCIA IN ('2025-12-01', '2024-12-01')
GROUP BY
  DET.ORDEM,
  DET.NOME_GRUPO
ORDER BY DET.ORDEM;
