SELECT 
  DET.ORDEM,
  DET.NOME_GRUPO,
  SUM(
    CASE 
      WHEN DETREF.REFERENCIA = '2025-12-01' THEN
        IFNULL((
          SELECT SUM(VLRLANC)
          FROM IMP_BASE_BALANCETE B
          WHERE B.CODEMP = 999
            AND B.CTACTB = DETCTACTB.PADRAO_CTACTB
            AND B.REFERENCIA <= '2025-12-31T00:00:00'
        )*DETCTACTB.SINAL, 0)
      ELSE 0
    END
  ) AS VLRLANC_ATU,

  SUM(
    CASE 
      WHEN DETREF.REFERENCIA = '2024-12-01' THEN
        IFNULL((
          SELECT SUM(VLRLANC)
          FROM IMP_BASE_BALANCETE B
          WHERE B.CODEMP = 999
            AND B.CTACTB = DETCTACTB.PADRAO_CTACTB
            AND B.REFERENCIA <= '2024-12-31T00:00:00'
        )*DETCTACTB.SINAL, 0)
      ELSE 0
    END
  ) AS VLRLANC_ANT

FROM ESTR_DEMONSTRATIVOS EST
INNER JOIN DET_DEMONSTRATIVO DET 
  ON EST.ID = DET.ID_ESTR_DEMONSTRATIVO
INNER JOIN DET_DEMONSTRATIVO_REFERENCIA DETREF 
  ON DET.ID = DETREF.ID_DET_DEMONSTRATIVO
LEFT JOIN DET_DEMONSTRATIVO_CTACTB DETCTACTB 
  ON DETREF.ID = DETCTACTB.ID_DET_DEMONSTRATIVO_REFERENCIA

WHERE 

  DETREF.REFERENCIA IN ('2025-12-01', '2024-12-01')

GROUP BY 
  DET.ORDEM,
DET.NOME_GRUPO

ORDER BY DET.ORDEM