<?php

namespace App\Services\Cadastros;

/**
 * Catálogo canônico de grupos de produto — alinhado ao estudo dominio trigger/32.
 *
 * Fontes:
 * - CADASTRO_PRODUTOS_COMPRA.txt (§2–3)
 * - CADASTRO_PRODUTOS_VENDA.txt (§4–5)
 * - CONTROLE_ESTOQUE_PROFISSIONAL.txt (grupo GG máscara bobina)
 * - CODIFICACAO_INFORMACOES_SISTEMA.txt (camadas família → SKU)
 *
 * O código do grupo é o prefixo do SKU de negócio (MP-PAP-nnn, PA-ETQ-nnn…).
 * Não confundir com marca/fornecedor (FAS, COL…) nem com opções de orçamento.
 */
final class ProdutoGrupoCatalogData
{
    /**
     * @return list<array{
     *   codigo: string,
     *   nome: string,
     *   familia: string,
     *   natureza: string,
     *   tipo_item_sped: string,
     *   grupo_estoque_padrao: ?string,
     *   grupos_estoque: ?list<array{codigo: string, nome: string}>,
     *   ncm_padrao: ?string,
     *   unidade_comercial_padrao: ?string,
     *   unidade_interna_padrao: ?string,
     *   cfop_entrada_padrao: ?string,
     *   cfop_saida_padrao: ?string,
     *   exige_dimensao_sku: bool,
     *   ncm_confirmado: bool,
     *   ordenacao: int,
     *   observacao: ?string
     * }>
     */
    public static function grupos(): array
    {
        return [
            // ——— Matéria-prima (compra / estoque / OP) ———
            [
                'codigo' => 'MP-PAP',
                'nome' => 'Papéis autoadesivos e tag',
                'familia' => 'MP',
                'natureza' => 'COMPRA',
                'tipo_item_sped' => '01',
                'grupo_estoque_padrao' => '10',
                'grupos_estoque' => [
                    ['codigo' => '10', 'nome' => 'Couché'],
                    ['codigo' => '11', 'nome' => 'Fosco'],
                    ['codigo' => '12', 'nome' => 'Térmico'],
                    ['codigo' => '13', 'nome' => 'Tag / cartão sem adesivo'],
                ],
                'ncm_padrao' => '48114190',
                'unidade_comercial_padrao' => 'KG',
                'unidade_interna_padrao' => 'M2',
                'cfop_entrada_padrao' => '2101',
                'cfop_saida_padrao' => null,
                'exige_dimensao_sku' => true,
                'ncm_confirmado' => true,
                'ordenacao' => 10,
                'observacao' => 'Couché/fosco/térmico → NCM 4811.41.90. Tag sem adesivo → candidato 4810.13.89 (linha estoque 13). Origem conforme XML. Exact/variável: 1 SKU por material+programa; L×C real = volume (ADR_CADASTRO_INSUMO_VOLUME).',
            ],
            [
                'codigo' => 'MP-FLM',
                'nome' => 'Filmes BOPP autoadesivos',
                'familia' => 'MP',
                'natureza' => 'COMPRA',
                'tipo_item_sped' => '01',
                'grupo_estoque_padrao' => '20',
                'grupos_estoque' => [
                    ['codigo' => '20', 'nome' => 'BOPP'],
                ],
                'ncm_padrao' => '39199010',
                'unidade_comercial_padrao' => 'M2',
                'unidade_interna_padrao' => 'M2',
                'cfop_entrada_padrao' => '2101',
                'cfop_saida_padrao' => null,
                'exige_dimensao_sku' => true,
                'ncm_confirmado' => true,
                'ordenacao' => 20,
                'observacao' => 'Bobinas > 20 cm → 3919.90.10. Marca na descrição, não no grupo. Exact: de-para cProd; não explodir SKU por mm×m (ADR_CADASTRO_INSUMO_VOLUME).',
            ],
            [
                'codigo' => 'MP-TEC',
                'nome' => 'Tecidos para etiquetas têxteis',
                'familia' => 'MP',
                'natureza' => 'COMPRA',
                'tipo_item_sped' => '01',
                'grupo_estoque_padrao' => '30',
                'grupos_estoque' => [
                    ['codigo' => '30', 'nome' => 'Tecidos'],
                ],
                'ncm_padrao' => null,
                'unidade_comercial_padrao' => 'M',
                'unidade_interna_padrao' => 'M',
                'cfop_entrada_padrao' => '2101',
                'cfop_saida_padrao' => null,
                'exige_dimensao_sku' => true,
                'ncm_confirmado' => false,
                'ordenacao' => 30,
                'observacao' => 'NCM a confirmar na NF do fornecedor (candidatos 5806.32.00 / 5903.90.00 / 5906.99.00). Não inventar classificação.',
            ],
            [
                'codigo' => 'MP-LAM',
                'nome' => 'Laminação',
                'familia' => 'MP',
                'natureza' => 'COMPRA',
                'tipo_item_sped' => '01',
                'grupo_estoque_padrao' => '40',
                'grupos_estoque' => [
                    ['codigo' => '40', 'nome' => 'Laminação'],
                ],
                'ncm_padrao' => '39199090',
                'unidade_comercial_padrao' => 'M2',
                'unidade_interna_padrao' => 'M2',
                'cfop_entrada_padrao' => '2101',
                'cfop_saida_padrao' => null,
                'exige_dimensao_sku' => true,
                'ncm_confirmado' => false,
                'ordenacao' => 40,
                'observacao' => 'Confirmar se filme é autoadesivo (3919.90.90) ou PP sem adesivo (3920.20.19).',
            ],
            [
                'codigo' => 'MP-CLD',
                'nome' => 'Cold / hot stamping',
                'familia' => 'MP',
                'natureza' => 'COMPRA',
                'tipo_item_sped' => '01',
                'grupo_estoque_padrao' => '41',
                'grupos_estoque' => [
                    ['codigo' => '41', 'nome' => 'Cold / hot'],
                ],
                'ncm_padrao' => '32121000',
                'unidade_comercial_padrao' => 'RL',
                'unidade_interna_padrao' => 'M',
                'cfop_entrada_padrao' => '2101',
                'cfop_saida_padrao' => null,
                'exige_dimensao_sku' => true,
                'ncm_confirmado' => true,
                'ordenacao' => 50,
                'observacao' => 'Folhas para marcar a ferro (stamping foils). Origem frequentemente importada — conferir XML.',
            ],
            [
                'codigo' => 'MP-TIN',
                'nome' => 'Tintas, vernizes e auxiliares',
                'familia' => 'MP',
                'natureza' => 'COMPRA',
                'tipo_item_sped' => '01',
                'grupo_estoque_padrao' => '50',
                'grupos_estoque' => [
                    ['codigo' => '50', 'nome' => 'Tintas'],
                ],
                'ncm_padrao' => '32151900',
                'unidade_comercial_padrao' => 'KG',
                'unidade_interna_padrao' => 'KG',
                'cfop_entrada_padrao' => '1101',
                'cfop_saida_padrao' => null,
                'exige_dimensao_sku' => false,
                'ncm_confirmado' => true,
                'ordenacao' => 60,
                'observacao' => 'Pretas 3215.11.00 · demais 3215.19.00. Verniz/diluente/antiespumante NÃO são 3215 — classificar pela NF/FISPQ.',
            ],
            [
                'codigo' => 'MP-ADF',
                'nome' => 'Fitas dupla face',
                'familia' => 'MP',
                'natureza' => 'COMPRA',
                'tipo_item_sped' => '01',
                'grupo_estoque_padrao' => '72',
                'grupos_estoque' => [
                    ['codigo' => '72', 'nome' => 'Dupla face'],
                ],
                'ncm_padrao' => '39191090',
                'unidade_comercial_padrao' => 'RL',
                'unidade_interna_padrao' => 'RL',
                'cfop_entrada_padrao' => '2101',
                'cfop_saida_padrao' => null,
                'exige_dimensao_sku' => true,
                'ncm_confirmado' => true,
                'ordenacao' => 70,
                'observacao' => 'Uso produtivo (emenda) = tipo 01. Uso geral pode ser 07 (uso e consumo) — orientar contador. NCM conforme largura da fita.',
            ],
            [
                'codigo' => 'MP-RET',
                'nome' => 'Retalho / sobra de bobina',
                'familia' => 'MP',
                'natureza' => 'COMPRA',
                'tipo_item_sped' => '01',
                'grupo_estoque_padrao' => '90',
                'grupos_estoque' => [
                    ['codigo' => '90', 'nome' => 'Retalho / sobra'],
                ],
                'ncm_padrao' => null,
                'unidade_comercial_padrao' => 'M2',
                'unidade_interna_padrao' => 'M2',
                'cfop_entrada_padrao' => null,
                'cfop_saida_padrao' => null,
                'exige_dimensao_sku' => true,
                'ncm_confirmado' => false,
                'ordenacao' => 80,
                'observacao' => 'Cada retalho útil vira SKU próprio (grupo estoque 90). Herda NCM do material de origem.',
            ],

            // ——— Embalagem ———
            [
                'codigo' => 'EMB-TUB',
                'nome' => 'Tubetes',
                'familia' => 'EMB',
                'natureza' => 'COMPRA',
                'tipo_item_sped' => '02',
                'grupo_estoque_padrao' => '70',
                'grupos_estoque' => [
                    ['codigo' => '70', 'nome' => 'Tubetes'],
                ],
                'ncm_padrao' => '48229000',
                'unidade_comercial_padrao' => 'UN',
                'unidade_interna_padrao' => 'UN',
                'cfop_entrada_padrao' => '2101',
                'cfop_saida_padrao' => null,
                'exige_dimensao_sku' => false,
                'ncm_confirmado' => true,
                'ordenacao' => 100,
                'observacao' => 'Núcleo da bobina — integra o produto vendido; tipo SPED 02.',
            ],
            [
                'codigo' => 'EMB-CX',
                'nome' => 'Caixas de papelão',
                'familia' => 'EMB',
                'natureza' => 'COMPRA',
                'tipo_item_sped' => '02',
                'grupo_estoque_padrao' => '71',
                'grupos_estoque' => [
                    ['codigo' => '71', 'nome' => 'Caixas'],
                ],
                'ncm_padrao' => '48191000',
                'unidade_comercial_padrao' => 'UN',
                'unidade_interna_padrao' => 'UN',
                'cfop_entrada_padrao' => '2101',
                'cfop_saida_padrao' => null,
                'exige_dimensao_sku' => false,
                'ncm_confirmado' => true,
                'ordenacao' => 110,
                'observacao' => 'Acondicionamento do produto acabado — tipo SPED 02.',
            ],

            // ——— Revenda (compra + venda, mesmo SKU) ———
            [
                'codigo' => 'REV-RIB',
                'nome' => 'Ribbons',
                'familia' => 'REV',
                'natureza' => 'AMBOS',
                'tipo_item_sped' => '00',
                'grupo_estoque_padrao' => '60',
                'grupos_estoque' => [
                    ['codigo' => '60', 'nome' => 'Ribbon'],
                ],
                'ncm_padrao' => '96121000',
                'unidade_comercial_padrao' => 'UN',
                'unidade_interna_padrao' => 'UN',
                'cfop_entrada_padrao' => '2102',
                'cfop_saida_padrao' => '5102',
                'exige_dimensao_sku' => false,
                'ncm_confirmado' => true,
                'ordenacao' => 200,
                'observacao' => 'Mesmo SKU na compra e na venda. CFOP entrada comercialização; saída 5102/6102. Consumo interno por requisição sem duplicar cadastro.',
            ],

            // ——— Produto acabado (venda fiscal — poucos registros) ———
            [
                'codigo' => 'PA-ETQ',
                'nome' => 'Etiquetas (família fiscal de saída)',
                'familia' => 'PA',
                'natureza' => 'VENDA',
                'tipo_item_sped' => '04',
                'grupo_estoque_padrao' => '80',
                'grupos_estoque' => [
                    ['codigo' => '80', 'nome' => 'Produto acabado'],
                ],
                'ncm_padrao' => '39191090',
                'unidade_comercial_padrao' => 'MIL',
                'unidade_interna_padrao' => 'UN',
                'cfop_entrada_padrao' => null,
                'cfop_saida_padrao' => '5101',
                'exige_dimensao_sku' => false,
                'ncm_confirmado' => true,
                'ordenacao' => 300,
                'observacao' => 'Regra de ouro: não cadastrar etiqueta sob medida como SKU eterno. Poucas famílias fiscais (BOPP 3919.10.90 / papel 4811.41.90); personalização vive no ORC/PED/OP. Go-live mínimo: PA-ETQ BOPP + PA-ETQ papel.',
            ],
            [
                'codigo' => 'PA-BOB',
                'nome' => 'Bobina / material faturado',
                'familia' => 'PA',
                'natureza' => 'VENDA',
                'tipo_item_sped' => '04',
                'grupo_estoque_padrao' => '80',
                'grupos_estoque' => [
                    ['codigo' => '80', 'nome' => 'Produto acabado'],
                ],
                'ncm_padrao' => '39199010',
                'unidade_comercial_padrao' => 'M2',
                'unidade_interna_padrao' => 'M2',
                'cfop_entrada_padrao' => null,
                'cfop_saida_padrao' => '5101',
                'exige_dimensao_sku' => true,
                'ncm_confirmado' => true,
                'ordenacao' => 310,
                'observacao' => 'Bobinas largas (> 20 cm) faturadas como mercadoria — tipicamente 3919.90.xx. Diferente de PA-ETQ (etiqueta acabada ≤ 20 cm).',
            ],

            // ——— Serviço ———
            [
                'codigo' => 'SVC',
                'nome' => 'Serviços avulsos',
                'familia' => 'SVC',
                'natureza' => 'VENDA',
                'tipo_item_sped' => '09',
                'grupo_estoque_padrao' => null,
                'grupos_estoque' => null,
                'ncm_padrao' => null,
                'unidade_comercial_padrao' => 'UN',
                'unidade_interna_padrao' => 'UN',
                'cfop_entrada_padrao' => null,
                'cfop_saida_padrao' => null,
                'exige_dimensao_sku' => false,
                'ncm_confirmado' => false,
                'ordenacao' => 400,
                'observacao' => 'Rebobinação, acerto, serviço sob encomenda. Confirmar com contador NF-e vs NFS-e antes de emissão automática.',
            ],

            // ——— Ferramental ———
            [
                'codigo' => 'FAC',
                'nome' => 'Ferramental (facas / matrizes)',
                'familia' => 'FAC',
                'natureza' => 'VENDA',
                'tipo_item_sped' => '04',
                'grupo_estoque_padrao' => null,
                'grupos_estoque' => null,
                'ncm_padrao' => null,
                'unidade_comercial_padrao' => 'UN',
                'unidade_interna_padrao' => 'UN',
                'cfop_entrada_padrao' => null,
                'cfop_saida_padrao' => '5101',
                'exige_dimensao_sku' => false,
                'ncm_confirmado' => false,
                'ordenacao' => 500,
                'observacao' => 'Cobrado no 1º pedido e reutilizado. Não é SKU de venda recorrente de etiqueta. Código FAC-NNNN (pad 4).',
            ],
        ];
    }
}
