/* Razão Auxilar das Contas*/
SELECT	P.CODEMP,
		P.CODCTACTB,
		P.CTACTB,
		CAST(P.DESCRCTA AS VARCHAR(MAX)) AS DESCRCTA,
        P.CODPARC,
        CASE
            WHEN PAR.NOMEPARC IS NULL OR LTRIM(RTRIM(CAST(PAR.NOMEPARC AS VARCHAR(MAX)))) = '<SEM PARCEIRO>'
            THEN 'SEM REGISTRO'
            ELSE CAST(PAR.NOMEPARC AS VARCHAR(MAX))
        END AS NOMEPARC,
        P.REFERENCIA,
        P.NUMLOTE,
        P.NUMLANC,
        P.TIPLANC,
        SUM(P.SALDOANT) AS SALDOANT,
		CASE WHEN SUM(P.DEBITO) < 0 THEN SUM(P.DEBITO)*-1 ELSE SUM(P.DEBITO) END AS DEBITO,
		CASE WHEN SUM(P.CREDITO) < 0 THEN SUM(P.CREDITO)*-1 ELSE SUM(P.CREDITO) END AS CREDITO,
		CASE WHEN SUM(P.SALDOANT) + SUM(P.DEBITO) + SUM(P.CREDITO) < 0
		THEN (SUM(P.SALDOANT) + SUM(P.DEBITO) + SUM(P.CREDITO))*-1
		ELSE (SUM(P.SALDOANT) + SUM(P.DEBITO) + SUM(P.CREDITO)) END AS SALDOATUAL,
		CASE WHEN CAST(P.CTACTB AS VARCHAR(50)) < '2'
			 THEN CASE WHEN (SUM(P.SALDOANT) + SUM(P.DEBITO) + SUM(P.CREDITO)) >= 0
			      THEN 'D'
				  ELSE 'C'
				  END
			 ELSE CASE WHEN CAST(P.CTACTB AS VARCHAR(50)) >= '2' AND CAST(P.CTACTB AS VARCHAR(50)) < '3'
				  THEN CASE WHEN (SUM(P.SALDOANT) + SUM(P.DEBITO) + SUM(P.CREDITO)) <= 0
							THEN 'C'
							ELSE 'D'
							END
				  END
			 END AS DC,
        P.DTMOV,
        P.CODHISTCTB,
        CAST(P.COMPLHIST AS VARCHAR(MAX)) AS COMPLHIST,
        P.NUMDOC,
        P.VENCIMENTO,
        P.LIBERADO,
        P.CODUSU,
        P.CODPROJ,
        P.SEQUENCIA,
        P.NUNICO
FROM
(
/* Pega as Contas de Ativo */
SELECT	LAN.CODEMP,
		LAN.CODCTACTB,
		CAST(PLA.CTACTB AS VARCHAR(50)) AS CTACTB,
		CAST(PLA.DESCRCTA AS VARCHAR(MAX)) AS DESCRCTA,
        LAN.AD_CODPARC AS CODPARC,
        LAN.REFERENCIA,
        LAN.NUMLOTE,
        LAN.NUMLANC,
        LAN.TIPLANC,
		ISNULL(SUM(CASE WHEN CAST(LAN.TIPLANC AS VARCHAR(MAX)) = 'D' THEN LAN.VLRLANC END), 0) + ISNULL(SUM(CASE WHEN CAST(LAN.TIPLANC AS VARCHAR(MAX)) = 'R' THEN LAN.VLRLANC*-1 END), 0) AS SALDOANT,
		0 AS DEBITO,
		0 AS CREDITO,
        LAN.DTMOV,
        LAN.CODHISTCTB,
        CAST(LAN.COMPLHIST AS VARCHAR(MAX)) AS COMPLHIST,
        LAN.NUMDOC,
        LAN.VENCIMENTO,
        LAN.LIBERADO,
        LAN.CODUSU,
        LAN.CODPROJ,
        LAN.SEQUENCIA,
        IT.NUNICO
FROM	TCBLAN LAN
INNER JOIN TCBPLA PLA ON CAST(PLA.CODCTACTB AS VARCHAR(MAX)) = CAST(LAN.CODCTACTB AS VARCHAR(MAX))
LEFT JOIN TCBINT IT ON (
    CAST(IT.CODEMP AS VARCHAR(MAX)) = CAST(LAN.CODEMP AS VARCHAR(MAX)) AND
    CAST(IT.REFERENCIA AS VARCHAR(MAX)) = CAST(LAN.REFERENCIA AS VARCHAR(MAX)) AND
    CAST(IT.NUMLANC AS VARCHAR(MAX)) = CAST(LAN.NUMLANC AS VARCHAR(MAX))
    AND CAST(IT.TIPLANC AS VARCHAR(MAX)) = CAST(LAN.TIPLANC AS VARCHAR(MAX))
    AND CAST(IT.NUMLOTE AS VARCHAR(MAX)) = CAST(LAN.NUMLOTE AS VARCHAR(MAX))
    AND CAST(IT.SEQUENCIA AS VARCHAR(MAX)) = CAST(LAN.SEQUENCIA AS VARCHAR(MAX))
)
WHERE	CAST(LAN.REFERENCIA AS VARCHAR(MAX)) = '01/07/2025' --$P{DTREFERENCIA}
AND		CAST(LAN.CODEMP AS VARCHAR(MAX)) = '1'--$P{CODEMP}
AND		CAST(LAN.CODCTACTB AS VARCHAR(MAX)) = '500823' --$P{CODCTACTB}
AND		CAST(PLA.CTACTB AS VARCHAR(50)) >= '1'
AND		CAST(PLA.CTACTB AS VARCHAR(50)) < '2'
GROUP BY 	LAN.CODEMP,
			LAN.CODCTACTB,
			CAST(PLA.CTACTB AS VARCHAR(50)),
			CAST(PLA.DESCRCTA AS VARCHAR(MAX)),
            LAN.AD_CODPARC,
            LAN.REFERENCIA,
            LAN.NUMLOTE,
            LAN.NUMLANC,
            LAN.TIPLANC,
            LAN.DTMOV,
            LAN.CODHISTCTB,
            CAST(LAN.COMPLHIST AS VARCHAR(MAX)),
            LAN.NUMDOC,
            LAN.VENCIMENTO,
            LAN.LIBERADO,
            LAN.CODUSU,
            LAN.CODPROJ,
            LAN.SEQUENCIA,
            IT.NUNICO

UNION ALL

SELECT	LAN.CODEMP,
		LAN.CODCTACTB,
		CAST(PLA.CTACTB AS VARCHAR(50)) AS CTACTB,
		CAST(PLA.DESCRCTA AS VARCHAR(MAX)) AS DESCRCTA,
        LAN.AD_CODPARC AS CODPARC,
        LAN.REFERENCIA,
        LAN.NUMLOTE,
        LAN.NUMLANC,
        LAN.TIPLANC,
		0 AS SALDOANT,
		ISNULL(SUM(CASE WHEN CAST(LAN.TIPLANC AS VARCHAR(MAX)) = 'D' THEN LAN.VLRLANC END), 0) AS DEBITO,
		ISNULL(SUM(CASE WHEN CAST(LAN.TIPLANC AS VARCHAR(MAX)) = 'R' THEN LAN.VLRLANC*-1 END), 0) AS CREDITO,
        LAN.DTMOV,
        LAN.CODHISTCTB,
        CAST(LAN.COMPLHIST AS VARCHAR(MAX)) AS COMPLHIST,
        LAN.NUMDOC,
        LAN.VENCIMENTO,
        LAN.LIBERADO,
        LAN.CODUSU,
        LAN.CODPROJ,
        LAN.SEQUENCIA,
        IT.NUNICO
FROM	TCBLAN LAN
INNER JOIN TCBPLA PLA ON CAST(PLA.CODCTACTB AS VARCHAR(MAX)) = CAST(LAN.CODCTACTB AS VARCHAR(MAX))
LEFT JOIN TCBINT IT ON (
    CAST(IT.CODEMP AS VARCHAR(MAX)) = CAST(LAN.CODEMP AS VARCHAR(MAX)) AND
    CAST(IT.REFERENCIA AS VARCHAR(MAX)) = CAST(LAN.REFERENCIA AS VARCHAR(MAX)) AND
    CAST(IT.NUMLANC AS VARCHAR(MAX)) = CAST(LAN.NUMLANC AS VARCHAR(MAX))
    AND CAST(IT.TIPLANC AS VARCHAR(MAX)) = CAST(LAN.TIPLANC AS VARCHAR(MAX))
    AND CAST(IT.NUMLOTE AS VARCHAR(MAX)) = CAST(LAN.NUMLOTE AS VARCHAR(MAX))
    AND CAST(IT.SEQUENCIA AS VARCHAR(MAX)) = CAST(LAN.SEQUENCIA AS VARCHAR(MAX))
)
WHERE	CAST(LAN.REFERENCIA AS VARCHAR(MAX)) = '01/07/2025' --$P{DTREFERENCIA}
AND		CAST(LAN.CODEMP AS VARCHAR(MAX)) = '1'--$P{CODEMP}
AND		CAST(LAN.CODCTACTB AS VARCHAR(MAX)) = '500823' --$P{CODCTACTB}
AND		CAST(PLA.CTACTB AS VARCHAR(50)) >= '1'
AND		CAST(PLA.CTACTB AS VARCHAR(50)) < '2'
GROUP BY 	LAN.CODEMP,
			LAN.CODCTACTB,
			CAST(PLA.CTACTB AS VARCHAR(50)),
			CAST(PLA.DESCRCTA AS VARCHAR(MAX)),
            LAN.AD_CODPARC,
            LAN.REFERENCIA,
            LAN.NUMLOTE,
            LAN.NUMLANC,
            LAN.TIPLANC,
            LAN.DTMOV,
            LAN.CODHISTCTB,
            CAST(LAN.COMPLHIST AS VARCHAR(MAX)),
            LAN.NUMDOC,
            LAN.VENCIMENTO,
            LAN.LIBERADO,
            LAN.CODUSU,
            LAN.CODPROJ,
            LAN.SEQUENCIA,
            IT.NUNICO

UNION ALL

/* Pega as Contas de Passivo */
SELECT	LAN.CODEMP,
		LAN.CODCTACTB,
		CAST(PLA.CTACTB AS VARCHAR(50)) AS CTACTB,
		CAST(PLA.DESCRCTA AS VARCHAR(MAX)) AS DESCRCTA,
        LAN.AD_CODPARC AS CODPARC,
        LAN.REFERENCIA,
        LAN.NUMLOTE,
        LAN.NUMLANC,
        LAN.TIPLANC,
		ISNULL(SUM(CASE WHEN CAST(LAN.TIPLANC AS VARCHAR(MAX)) = 'D' THEN LAN.VLRLANC END), 0) + ISNULL(SUM(CASE WHEN CAST(LAN.TIPLANC AS VARCHAR(MAX)) = 'R' THEN LAN.VLRLANC*-1 END), 0) AS SALDOANT,
		0 AS DEBITO,
		0 AS CREDITO,
        LAN.DTMOV,
        LAN.CODHISTCTB,
        CAST(LAN.COMPLHIST AS VARCHAR(MAX)) AS COMPLHIST,
        LAN.NUMDOC,
        LAN.VENCIMENTO,
        LAN.LIBERADO,
        LAN.CODUSU,
        LAN.CODPROJ,
        LAN.SEQUENCIA,
        IT.NUNICO
FROM	TCBLAN LAN
INNER JOIN TCBPLA PLA ON CAST(PLA.CODCTACTB AS VARCHAR(MAX)) = CAST(LAN.CODCTACTB AS VARCHAR(MAX))
LEFT JOIN TCBINT IT ON (
    CAST(IT.CODEMP AS VARCHAR(MAX)) = CAST(LAN.CODEMP AS VARCHAR(MAX)) AND
    CAST(IT.REFERENCIA AS VARCHAR(MAX)) = CAST(LAN.REFERENCIA AS VARCHAR(MAX)) AND
    CAST(IT.NUMLANC AS VARCHAR(MAX)) = CAST(LAN.NUMLANC AS VARCHAR(MAX))
    AND CAST(IT.TIPLANC AS VARCHAR(MAX)) = CAST(LAN.TIPLANC AS VARCHAR(MAX))
    AND CAST(IT.NUMLOTE AS VARCHAR(MAX)) = CAST(LAN.NUMLOTE AS VARCHAR(MAX))
    AND CAST(IT.SEQUENCIA AS VARCHAR(MAX)) = CAST(LAN.SEQUENCIA AS VARCHAR(MAX))
)
WHERE	CAST(LAN.REFERENCIA AS VARCHAR(MAX)) = '01/07/2025' --$P{DTREFERENCIA}
AND		CAST(LAN.CODEMP AS VARCHAR(MAX)) = '1'--$P{CODEMP}
AND		CAST(LAN.CODCTACTB AS VARCHAR(MAX)) = '500823' --$P{CODCTACTB}
AND		CAST(PLA.CTACTB AS VARCHAR(50)) >= '2'
AND		CAST(PLA.CTACTB AS VARCHAR(50)) < '3'
GROUP BY 	LAN.CODEMP,
			LAN.CODCTACTB,
			CAST(PLA.CTACTB AS VARCHAR(50)),
			CAST(PLA.DESCRCTA AS VARCHAR(MAX)),
            LAN.AD_CODPARC,
            LAN.REFERENCIA,
            LAN.NUMLOTE,
            LAN.NUMLANC,
            LAN.TIPLANC,
            LAN.DTMOV,
            LAN.CODHISTCTB,
            CAST(LAN.COMPLHIST AS VARCHAR(MAX)),
            LAN.NUMDOC,
            LAN.VENCIMENTO,
            LAN.LIBERADO,
            LAN.CODUSU,
            LAN.CODPROJ,
            LAN.SEQUENCIA,
            IT.NUNICO

UNION ALL

SELECT	LAN.CODEMP,
		LAN.CODCTACTB,
		CAST(PLA.CTACTB AS VARCHAR(50)) AS CTACTB,
		CAST(PLA.DESCRCTA AS VARCHAR(MAX)) AS DESCRCTA,
        LAN.AD_CODPARC AS CODPARC,
        LAN.REFERENCIA,
        LAN.NUMLOTE,
        LAN.NUMLANC,
        LAN.TIPLANC,
		0 AS SALDOANT,
		ISNULL(SUM(CASE WHEN CAST(LAN.TIPLANC AS VARCHAR(MAX)) = 'D' THEN LAN.VLRLANC END), 0) AS DEBITO,
		ISNULL(SUM(CASE WHEN CAST(LAN.TIPLANC AS VARCHAR(MAX)) = 'R' THEN LAN.VLRLANC*-1 END), 0) AS CREDITO,
        LAN.DTMOV,
        LAN.CODHISTCTB,
        CAST(LAN.COMPLHIST AS VARCHAR(MAX)) AS COMPLHIST,
        LAN.NUMDOC,
        LAN.VENCIMENTO,
        LAN.LIBERADO,
        LAN.CODUSU,
        LAN.CODPROJ,
        LAN.SEQUENCIA,
        IT.NUNICO
FROM	TCBLAN LAN
INNER JOIN TCBPLA PLA ON CAST(PLA.CODCTACTB AS VARCHAR(MAX)) = CAST(LAN.CODCTACTB AS VARCHAR(MAX))
LEFT JOIN TCBINT IT ON (
    CAST(IT.CODEMP AS VARCHAR(MAX)) = CAST(LAN.CODEMP AS VARCHAR(MAX)) AND
    CAST(IT.REFERENCIA AS VARCHAR(MAX)) = CAST(LAN.REFERENCIA AS VARCHAR(MAX)) AND
    CAST(IT.NUMLANC AS VARCHAR(MAX)) = CAST(LAN.NUMLANC AS VARCHAR(MAX))
    AND CAST(IT.TIPLANC AS VARCHAR(MAX)) = CAST(LAN.TIPLANC AS VARCHAR(MAX))
    AND CAST(IT.NUMLOTE AS VARCHAR(MAX)) = CAST(LAN.NUMLOTE AS VARCHAR(MAX))
    AND CAST(IT.SEQUENCIA AS VARCHAR(MAX)) = CAST(LAN.SEQUENCIA AS VARCHAR(MAX))
)
LEFT JOIN TGFCAB CAB ON CAST(IT.NUNICO AS VARCHAR(MAX)) = CAST(CAB.NUNOTA AS VARCHAR(MAX))
LEFT JOIN TGFFIN FIN ON CAST(IT.NUNICO AS VARCHAR(MAX)) = CAST(FIN.NUFIN AS VARCHAR(MAX))
WHERE	CAST(LAN.REFERENCIA AS VARCHAR(MAX)) = '01/07/2025' --$P{DTREFERENCIA}
AND		CAST(LAN.CODEMP AS VARCHAR(MAX)) = '1'--$P{CODEMP}
AND		CAST(LAN.CODCTACTB AS VARCHAR(MAX)) = '500823' --$P{CODCTACTB}
AND		CAST(PLA.CTACTB AS VARCHAR(50)) >= '2'
AND		CAST(PLA.CTACTB AS VARCHAR(50)) < '3'
GROUP BY 	LAN.CODEMP,
			LAN.CODCTACTB,
			CAST(PLA.CTACTB AS VARCHAR(50)),
			CAST(PLA.DESCRCTA AS VARCHAR(MAX)),
            LAN.AD_CODPARC,
            LAN.REFERENCIA,
            LAN.NUMLOTE,
            LAN.NUMLANC,
            LAN.TIPLANC,
            LAN.DTMOV,
            LAN.CODHISTCTB,
            CAST(LAN.COMPLHIST AS VARCHAR(MAX)),
            LAN.NUMDOC,
            LAN.VENCIMENTO,
            LAN.LIBERADO,
            LAN.CODUSU,
            LAN.CODPROJ,
            LAN.SEQUENCIA,
            IT.NUNICO
) P
LEFT JOIN TGFPAR PAR ON CAST(P.CODPARC AS VARCHAR(MAX)) = CAST(PAR.CODPARC AS VARCHAR(MAX))
--WHERE (P.CODPARC = $P{P_CODPARC} OR $P{P_CODPARC} IS NULL)
GROUP BY 	P.CODEMP,
			P.CODCTACTB,
			P.CTACTB,
			CAST(P.DESCRCTA AS VARCHAR(MAX)),
            P.CODPARC,
            CAST(PAR.NOMEPARC AS VARCHAR(MAX)),
            P.REFERENCIA,
            P.NUMLOTE,
            P.NUMLANC,
            P.TIPLANC,
            P.DTMOV,
            P.CODHISTCTB,
            CAST(P.COMPLHIST AS VARCHAR(MAX)),
            P.NUMDOC,
            P.VENCIMENTO,
            P.LIBERADO,
            P.CODUSU,
            P.CODPROJ,
            P.SEQUENCIA,
            P.NUNICO
ORDER BY 2
