-- Consulta de Títulos Financeiros - Convertido para SQL Server
-- Consulta para obter informações detalhadas de títulos financeiros com múltiplos JOINs
SELECT 
    TGFFIN.*
    -- TGFFIN.CODPARC,
    -- TGFFIN.RECDESP,
    -- TGFFIN.VLRDESDOB,
    -- TGFFIN.PROVISAO,
    -- TGFFIN.DHBAIXA
FROM TGFFIN WITH (NOLOCK)
     LEFT JOIN TSIBCO Banco WITH (NOLOCK) ON (TGFFIN.CODBCO = Banco.CODBCO)
     LEFT JOIN TSICUS CentroResultado WITH (NOLOCK) ON (TGFFIN.CODCENCUS = CentroResultado.CODCENCUS)
     LEFT JOIN TGFCFO ClassificacaoFiscalOperacao WITH (NOLOCK) ON (TGFFIN.CODCFO = ClassificacaoFiscalOperacao.CODCFO)
     LEFT JOIN TGFRNF CompFinancReinf WITH (NOLOCK) ON (TGFFIN.NUFIN = CompFinancReinf.NUFIN)
     LEFT JOIN TGFNRR CadastroNaturezaRendimentos4_1 WITH (NOLOCK) ON (CompFinancReinf.CODNATREND = CadastroNaturezaRendimentos4_1.CODNATREND)
     LEFT JOIN TSICTA ContaBancaria WITH (NOLOCK) ON (TGFFIN.CODCTABCOINT = ContaBancaria.CODCTABCOINT)
     LEFT JOIN TGFCTT Contato WITH (NOLOCK) ON (TGFFIN.CODPARC = Contato.CODPARC AND TGFFIN.CODCONTATO = Contato.CODCONTATO)
     LEFT JOIN TSIEMP Empresa WITH (NOLOCK) ON (TGFFIN.CODEMP = Empresa.CODEMP)
     LEFT JOIN TSIEMP EmpresaBaixa WITH (NOLOCK) ON (TGFFIN.CODEMPBAIXA = EmpresaBaixa.CODEMP)
     LEFT JOIN TFPFUN Funcionario WITH (NOLOCK) ON (TGFFIN.CODEMP = Funcionario.CODEMP AND TGFFIN.CODFUNC = Funcionario.CODFUNC)
     LEFT JOIN TSIEMP ImovelRural WITH (NOLOCK) ON (TGFFIN.CODIMOVELRURAL = ImovelRural.CODEMP)
     LEFT JOIN TGFLST ListaServicoSintegra WITH (NOLOCK) ON (TGFFIN.CODLST = ListaServicoSintegra.CODLST)
     LEFT JOIN TSIMOE Moeda WITH (NOLOCK) ON (TGFFIN.CODMOEDA = Moeda.CODMOEDA)
     LEFT JOIN TGFNAT Natureza WITH (NOLOCK) ON (TGFFIN.CODNAT = Natureza.CODNAT)
     LEFT JOIN TGFOBS ObservacaoNotasFiscais WITH (NOLOCK) ON (TGFFIN.CODOBSPADRAO = ObservacaoNotasFiscais.CODOBSPADRAO)
     LEFT JOIN TGFPAR Parceiro WITH (NOLOCK) ON (TGFFIN.CODPARC = Parceiro.CODPARC)
     LEFT JOIN TSICID Cidade16_1 WITH (NOLOCK) ON (Parceiro.CODCID = Cidade16_1.CODCID)
     LEFT JOIN TSIUFS UnidadeFederativa16_2 WITH (NOLOCK) ON (Cidade16_1.UF = UnidadeFederativa16_2.CODUF)
     LEFT JOIN TGFPIXTEF PixTEF WITH (NOLOCK) ON (TGFFIN.PIXTEF = PixTEF.SEQPIXTEF)
     LEFT JOIN TCSPRJ Projeto WITH (NOLOCK) ON (TGFFIN.CODPROJ = Projeto.CODPROJ)
     LEFT JOIN TGFRDARF ReceitaDarf WITH (NOLOCK) ON (TGFFIN.CODRECEITA = ReceitaDarf.CODRECEITA)
     LEFT JOIN TGFTEF TEF WITH (NOLOCK) ON (TGFFIN.NUFIN = TEF.NUFIN)
     LEFT JOIN TSICTA TimContaBancaria WITH (NOLOCK) ON (TGFFIN.TIMCONTALANC = TimContaBancaria.CODCTABCOINT)
     LEFT JOIN TIMIMV TimImovel WITH (NOLOCK) ON (TGFFIN.TIMIMOVEL = TimImovel.IMVCODIGO)
     LEFT JOIN TIMTIN TimTipoIntermed WITH (NOLOCK) ON (TGFFIN.TIMTIPOINTERMED = TimTipoIntermed.TINCODIGO)
     LEFT JOIN TGFTOP TipoOperacao WITH (NOLOCK) ON (TGFFIN.CODTIPOPER = TipoOperacao.CODTIPOPER AND TGFFIN.DHTIPOPER = TipoOperacao.DHALTER)
     LEFT JOIN TGFTOP TipoOperacaoBaixa WITH (NOLOCK) ON (TGFFIN.CODTIPOPERBAIXA = TipoOperacaoBaixa.CODTIPOPER AND TGFFIN.DHTIPOPERBAIXA = TipoOperacaoBaixa.DHALTER)
     LEFT JOIN TGFTIT TipoTitulo WITH (NOLOCK) ON (TGFFIN.CODTIPTIT = TipoTitulo.CODTIPTIT)
     LEFT JOIN TSIUSU Usuario WITH (NOLOCK) ON (TGFFIN.CODUSU = Usuario.CODUSU)
     LEFT JOIN TSIUSU Usuario2 WITH (NOLOCK) ON (TGFFIN.TIMREPINTELIGENTE = Usuario2.CODUSU)
     LEFT JOIN TSIUSU UsuarioBaixa WITH (NOLOCK) ON (TGFFIN.CODUSUBAIXA = UsuarioBaixa.CODUSU)
     LEFT JOIN TGFVEN Vendedor WITH (NOLOCK) ON (TGFFIN.CODVEND = Vendedor.CODVEND)
WHERE 
    TGFFIN.RECDESP = 1
    AND TGFFIN.PROVISAO = 'N'
    AND TGFFIN.DHBAIXA IS NULL
    AND DATEADD(DAY, DATEDIFF(DAY, 0, TGFFIN.DTNEG), 0) <= DATEADD(DAY, DATEDIFF(DAY, 0, '31/08/2025'), 0)
    AND TGFFIN.CODEMP IN (1)
    AND NOT (TGFFIN.PROVISAO = 'S' AND TGFFIN.DHBAIXA IS NOT NULL AND TGFFIN.ORIGEM = 'E');
