SELECT 
  TO_CHAR(VGF.DTNEG, 'YYYY') AS ANO,
  TO_CHAR(VGF.DTNEG, 'MM') AS MES,
  TO_CHAR(VGF.DTNEG, 'MM/YYYY') AS MES_ANO,
  SUM(VGF.VLRBAIXA*-1) AS CUSTO_MENSAL 
FROM 
  VGF_RESULTADO_SATIS VGF
  INNER JOIN TSICUS CUS ON CUS.CODCENCUS = VGF.CODCENCUS
WHERE 
	 ((VGF.dtneg >= :P_PERIODO.INI AND VGF.dtneg <= :P_PERIODO.FIN)
    OR (:P_PERIODO.INI IS NULL AND :P_PERIODO.FIN IS NULL))
  AND VGF.CODCENCUS LIKE '7%' 
  AND VGF.DESCRCENCUS NOT LIKE '%QUALIDADE%'
GROUP BY
  TO_CHAR(VGF.DTNEG, 'YYYY'),
  TO_CHAR(VGF.DTNEG, 'MM'),
  TO_CHAR(VGF.DTNEG, 'MM/YYYY')
ORDER BY ANO, MES