WITH 
SUB_GASTO_FIXO AS (
SELECT SUM(VLRBAIXA) * -1 AS VALOR
FROM VGF_RESULTADO_GM
WHERE AD_TIPOCUSTO = 'F'
AND CODCENCUS NOT BETWEEN 2500000 AND 2599999
AND DHBAIXA IS NOT NULL
AND (DHBAIXA BETWEEN :P_PERIODO.INI AND  :P_PERIODO.FIN)
AND RECDESP = -1
)

SELECT
SUB.CODTIPO
, SUB.TIPOPROD
, SUB.HL
, SUB.VLRFAT
, SUB.CUSSEMICM
, SUB.GASTO_VARIAVEL
, SUM( SUB.VLRFAT - SUB.CUSSEMICM - SUB.GASTO_VARIAVEL) AS MARGEM_CONTRIB
, (RATIO_TO_REPORT(SUB.VLRFAT) OVER ()) * GF.VALOR AS GASTO_FIXO
, SUM( SUB.VLRFAT - SUB.CUSSEMICM - SUB.GASTO_VARIAVEL) - ((RATIO_TO_REPORT(SUB.VLRFAT) OVER ()) * GF.VALOR) AS RESULTADO
FROM (

SELECT 
PRO.AD_TPPROD AS CODTIPO
, UPPER (F_DESCROPC('TGFPRO', 'AD_TPPROD', PRO.AD_TPPROD) ) AS TIPOPROD
, SUM(FC_QTDALT_HL(ITE.CODPROD, ITE.QTDNEG, 'HL') * CASE WHEN CAB.TIPMOV = 'D' THEN -1 ELSE 1 END) AS HL 
, SUM(CASE WHEN CAB.TIPMOV = 'D' THEN (ITE.VLRTOT + ITE.VLRIPI + ITE.VLRSUBST - ITE.VLRDESC) * -1 ELSE (ITE.VLRTOT + ITE.VLRIPI + ITE.VLRSUBST - ITE.VLRDESC) END) AS VLRFAT
, SUM(CUS.CUSSEMICM * ITE.QTDNEG) AS CUSSEMICM
, SUM(ITE.VLRSUBST + ITE.VLRIPI + ITE.VLRICMS /*VALOR ST + IPI + ICMS*/ 
    + (SELECT (VALOR) FROM TGFDIN WHERE NUNOTA = ITE.NUNOTA AND SEQUENCIA = ITE.SEQUENCIA AND CODIMP = 6)/*VLRPIS*/
    + (SELECT (VALOR) FROM TGFDIN WHERE NUNOTA = ITE.NUNOTA AND SEQUENCIA = ITE.SEQUENCIA AND CODIMP = 7) )/* VLRCOFINS*/ AS GASTO_VARIAVEL
FROM TGFCAB CAB
INNER JOIN TGFITE ITE ON CAB.NUNOTA = ITE.NUNOTA
INNER JOIN TGFCUS CUS ON CUS.CODPROD = ITE.CODPROD AND CUS.CODEMP = CAB.CODEMP AND CUS.DTATUAL = (SELECT MAX(DTATUAL)FROM TGFCUS WHERE DTATUAL <= CAB.DTNEG AND CODPROD = ITE.CODPROD AND CODEMP = CAB.CODEMP)
INNER JOIN TGFTOP TOP ON CAB.CODTIPOPER = TOP.CODTIPOPER AND TOP.DHALTER = (SELECT MAX(DHALTER) FROM TGFTOP WHERE CODTIPOPER = CAB.CODTIPOPER)
INNER JOIN TGFPRO PRO ON ITE.CODPROD = PRO.CODPROD
WHERE TOP.GOLSINAL = -1
AND (CAB.DTNEG BETWEEN :P_PERIODO.INI AND  :P_PERIODO.FIN)
AND TOP.TIPMOV IN ('V', 'D')
AND TOP.ATIVO = 'S'
AND PRO.AD_TPPROD IS NOT NULL
GROUP BY PRO.AD_TPPROD

) SUB, SUB_GASTO_FIXO GF
GROUP BY
SUB.CODTIPO
, SUB.TIPOPROD
, SUB.HL
, SUB.VLRFAT
, SUB.CUSSEMICM
, SUB.GASTO_VARIAVEL
, GF.VALOR
ORDER BY
SUB.VLRFAT DESC