/*
Essa consulta retorna as matérias primas e quantidade de mistura delas para produzir o PA
relação de materiais primas valida para cada mês
*/

SELECT MAX(ATV.IDEFX)IDEFX
, LAST_DAY(TRUNC(NVL(ATV.DHINICIO, ATV.DHINCLUSAO))) AS DHINICIO
, PA.CODPRODPA 
, MP.CODPRODMP 
, MP.QTDMISTURA
, CUS.CUSSEMICM
, MP.QTDMISTURA * CUS.CUSSEMICM AS CUSTO
FROM TPRIATV ATV
INNER JOIN TPRIPA PA ON PA.IDIPROC = ATV.IDIPROC
INNER JOIN TPRLMP MP ON MP.CODPRODPA = PA.CODPRODPA AND MP.IDEFX = ATV.IDEFX
INNER JOIN TGFCUS CUS ON MP.CODPRODMP = CUS.CODPROD AND 1 = CUS.CODEMP
AND CUS.DTATUAL = (SELECT MAX(DTATUAL)FROM TGFCUS WHERE DTATUAL <= LAST_DAY(TRUNC(NVL(ATV.DHINICIO, ATV.DHINCLUSAO))) AND CODPROD = MP.CODPRODMP AND CODEMP = 1)
WHERE PA.CODPRODPA = 675
AND LAST_DAY(TRUNC(NVL(ATV.DHINICIO, ATV.DHINCLUSAO))) >= ADD_MONTHS(TO_DATE('09/11/2023','DD-MM-YYYY'), -12) 
AND LAST_DAY(TRUNC(NVL(ATV.DHINICIO, ATV.DHINCLUSAO))) < TO_DATE('09/11/2023','DD-MM-YYYY')
GROUP BY LAST_DAY(TRUNC(NVL(ATV.DHINICIO, ATV.DHINCLUSAO)))
, PA.CODPRODPA 
, MP.CODPRODMP
, MP.QTDMISTURA
, CUS.CUSSEMICM

/*
adicione a TGFCUS ai
Multiplique o CUSSEMICM pela quantidade de mistura para obter o custo total de MP
CUS.DTATUAL = (SELECT MAX(DTATUAL) FROM TGFCUS WHERE DTATUAL <= LAST_DAY(X.DATA) AND CODEMP = 1 AND CODPROD = :A_CODPROD)
INNER JOIN TGFCUS CUS ON CUS.CODPROD = ITE.CODPROD AND CUS.CODEMP = CAB.CODEMP AND CUS.DTATUAL = (SELECT MAX(DTATUAL)FROM TGFCUS WHERE DTATUAL <= CAB.DTNEG AND CODPROD = ITE.CODPROD AND CODEMP = CAB.CODEMP)

 AND (SELECT MAX(DTATUAL)FROM TGFCUS WHERE LAST_DAY(TRUNC(NVL(ATV.DHINICIO, ATV.DHINCLUSAO))) <= DTATUAL AND CODPROD = ATV.IDEFX AND CODEMP = 1) = CUS.DTATUAL




fazer um SUM nesse custo total
Agrupando pela Data

*/




WITH CUS_TOT AS(
SELECT MAX(ATV.IDEFX)IDEFX
, LAST_DAY(TRUNC(NVL(ATV.DHINICIO, ATV.DHINCLUSAO))) AS DHINICIO
, PA.CODPRODPA 
, MP.CODPRODMP 
, MP.QTDMISTURA
, CUS.CUSSEMICM
, MP.QTDMISTURA * CUS.CUSSEMICM AS CUSTO
FROM TPRIATV ATV
INNER JOIN TPRIPA PA ON PA.IDIPROC = ATV.IDIPROC
INNER JOIN TPRLMP MP ON MP.CODPRODPA = PA.CODPRODPA AND MP.IDEFX = ATV.IDEFX
INNER JOIN TGFCUS CUS ON MP.CODPRODMP = CUS.CODPROD AND 1 = CUS.CODEMP
AND CUS.DTATUAL = (SELECT MAX(DTATUAL)FROM TGFCUS WHERE DTATUAL <= LAST_DAY(TRUNC(NVL(ATV.DHINICIO, ATV.DHINCLUSAO))) AND CODPROD = MP.CODPRODMP AND CODEMP = 1)
WHERE PA.CODPRODPA = 675
AND LAST_DAY(TRUNC(NVL(ATV.DHINICIO, ATV.DHINCLUSAO))) >= ADD_MONTHS(TO_DATE('09/11/2023','DD-MM-YYYY'), -12) 
AND LAST_DAY(TRUNC(NVL(ATV.DHINICIO, ATV.DHINCLUSAO))) < TO_DATE('09/11/2023','DD-MM-YYYY')
GROUP BY LAST_DAY(TRUNC(NVL(ATV.DHINICIO, ATV.DHINCLUSAO)))
, PA.CODPRODPA 
, MP.CODPRODMP
, MP.QTDMISTURA
, CUS.CUSSEMICM)

SELECT 
DHINICIO as DATA,
SUM(CUSTO) AS CUSTO
FROM CUS_TOT
GROUP BY
DHINICIO
ORDER BY DHINICIO
