SELECT DISTINCT
    LAST_DAY(X.DATA) AS DATA,
    CUS.CODPROD,
    CUS.CUSSEMICM AS CUSTO,
    /*CUS.ENTRADASEMICMS AS CUSREP,*/
    CUSTT.CUSTOT  -- Include the CUSTOT column from the CUSTT table

FROM 
    (
        SELECT
            (
                TO_DATE(SEQ.MM || SEQ.YYYY, 'MM/YYYY') - 1
            ) + SEQ.RESULT AS "DATA"
        FROM
            (
                SELECT
                    ROWNUM RESULT,
                    TO_CHAR(TO_DATE('01/01/2020', 'DD/MM/YYYY'), 'MM') AS "MM",
                    TO_CHAR(TO_DATE('01/01/2020', 'DD/MM/YYYY'), 'YYYY') AS "YYYY"
                FROM
                    (
                        SELECT ROWNUM RESULT
                        FROM DUAL
                        CONNECT BY LEVEL <= (
                            (
                                LAST_DAY(TO_DATE('31/12/2099', 'DD/MM/YYYY'))
                                - TRUNC(TO_DATE('01/01/2020', 'DD/MM/YYYY'))
                            ) + 1
                        )
                    )
            ) SEQ
    ) X
JOIN TGFCUS CUS ON
    CUS.DTATUAL = (
        SELECT MAX(DTATUAL)
        FROM TGFCUS
        WHERE DTATUAL <= LAST_DAY(X.DATA)
        AND CODEMP = 1
        AND CODPROD = :A_CODPROD
    )
    AND CUS.CODEMP = 1
    AND CUS.CODPROD = :A_CODPROD
    AND X.DATA >= ADD_MONTHS(TO_DATE(:P_PERIODO.FIN, 'DD-MM-YYYY'), -12)
    AND X.DATA < TO_DATE(:P_PERIODO.FIN, 'DD-MM-YYYY')
JOIN (
    WITH CUS_TOT AS (
        SELECT MAX(ATV.IDEFX)IDEFX
, LAST_DAY(TRUNC(NVL(ATV.DHINICIO, ATV.DHINCLUSAO))) AS DHINICIO
, PA.CODPRODPA 
, MP.CODPRODMP 
, MP.QTDMISTURA
, CUS.CUSSEMICM
, MP.QTDMISTURA * CUS.CUSSEMICM AS CUSTO
FROM TPRIATV ATV
INNER JOIN TPRIPA PA ON PA.IDIPROC = ATV.IDIPROC
INNER JOIN TPRLMP MP ON MP.CODPRODPA = PA.CODPRODPA AND MP.IDEFX = ATV.IDEFX
INNER JOIN TGFCUS CUS ON MP.CODPRODMP = CUS.CODPROD AND 1 = CUS.CODEMP
AND CUS.DTATUAL = (SELECT MAX(DTATUAL)FROM TGFCUS WHERE DTATUAL <= LAST_DAY(TRUNC(NVL(ATV.DHINICIO, ATV.DHINCLUSAO))) AND CODPROD = MP.CODPRODMP AND CODEMP = 1)
WHERE PA.CODPRODPA = :A_CODPROD
AND LAST_DAY(TRUNC(NVL(ATV.DHINICIO, ATV.DHINCLUSAO))) >= ADD_MONTHS(TO_DATE(:P_PERIODO.FIN,'DD-MM-YYYY'), -12) 
AND LAST_DAY(TRUNC(NVL(ATV.DHINICIO, ATV.DHINCLUSAO))) < TO_DATE(:P_PERIODO.FIN,'DD-MM-YYYY')
GROUP BY LAST_DAY(TRUNC(NVL(ATV.DHINICIO, ATV.DHINCLUSAO)))
, PA.CODPRODPA 
, MP.CODPRODMP
, MP.QTDMISTURA
, CUS.CUSSEMICM
    )
    SELECT 
        DHINICIO as DATA,
        SUM(CUSTO) AS CUSTOT
    FROM CUS_TOT
    GROUP BY DHINICIO
    ORDER BY DHINICIO
) CUSTT ON LAST_DAY(X.DATA) = CUSTT.DATA
ORDER BY LAST_DAY(X.DATA)
