WITH rank_dados AS (
  SELECT 
    CODCENCUS,
    DESCRCENCUS,
    CODNAT,
    DESCRNAT,
    SUM(VLRBAIXA) * -1 AS VALOR,
    'RED' AS BKCOLOR,
    (RATIO_TO_REPORT(SUM(VLRBAIXA) * -1) OVER ()) AS PERC,
    NTILE(6) OVER (ORDER BY SUM(VLRBAIXA) * -1 DESC) AS group_num
  FROM VGF_RESULTADO_GM
  WHERE 
    AD_TIPOCUSTO = 'F'
    AND CODCENCUS NOT BETWEEN 2500000 AND 2599999
    AND DHBAIXA IS NOT NULL
    AND (DHBAIXA BETWEEN TO_DATE('01-01-2023', 'DD-MM-YYYY') and TO_DATE('03-11-2023', 'DD-MM-YYYY'))
    AND RECDESP = -1
  GROUP BY CODCENCUS, DESCRCENCUS, CODNAT, DESCRNAT)
SELECT * FROM rank_dados WHERE group_num <= 6
