
SELECT 
    CODPROD, 
    DESCRPROD,   
    CODTIPO,
    TIPOPROD,
    TESTE AS TIPO_GV,
    TESTES AS VALOR,
    (RATIO_TO_REPORT(TESTES) OVER ())*100 AS PERC_GV
FROM (
    SELECT
		 ITE.CODPROD,
        PRO.DESCRPROD, 
        PRO.AD_TPPROD AS CODTIPO,
        UPPER(F_DESCROPC('TGFPRO', 'AD_TPPROD', PRO.AD_TPPROD)) AS TIPOPROD,
        SUM(ITE.VLRSUBST) AS VLRSUBST,
        SUM(ITE.VLRIPI) AS VLRIPI,
        SUM(ITE.VLRICMS) AS VLRICMS,
        SUM((SELECT (VALOR) FROM TGFDIN WHERE NUNOTA = ITE.NUNOTA AND SEQUENCIA = ITE.SEQUENCIA AND CODIMP = 6)) AS VLRPIS,
        SUM((SELECT (VALOR) FROM TGFDIN WHERE NUNOTA = ITE.NUNOTA AND SEQUENCIA = ITE.SEQUENCIA AND CODIMP = 7)) AS VLRCOFINS
    FROM TGFCAB CAB
    INNER JOIN TGFITE ITE ON CAB.NUNOTA = ITE.NUNOTA
    INNER JOIN TGFCUS CUS ON CUS.CODPROD = ITE.CODPROD AND CUS.CODEMP = CAB.CODEMP AND CUS.DTATUAL = (
        SELECT MAX(DTATUAL) FROM TGFCUS WHERE DTATUAL <= CAB.DTNEG AND CODPROD = ITE.CODPROD AND CODEMP = CAB.CODEMP
    )
    INNER JOIN TGFTOP TOP ON CAB.CODTIPOPER = TOP.CODTIPOPER AND TOP.DHALTER = (
        SELECT MAX(DHALTER) FROM TGFTOP WHERE CODTIPOPER = CAB.CODTIPOPER
    )
    INNER JOIN TGFPRO PRO ON ITE.CODPROD = PRO.CODPROD
    WHERE TOP.GOLSINAL = -1
        AND (CAB.DTNEG BETWEEN :P_PERIODO.INI AND  :P_PERIODO.FIN)
        AND ITE.CODPROD = :A_CODPROD
        AND TOP.TIPMOV IN ('V', 'D')
        AND TOP.ATIVO = 'S'
        AND PRO.AD_TPPROD IS NOT NULL
    GROUP BY ITE.CODPROD, PRO.DESCRPROD,PRO.AD_TPPROD
) SUB
UNPIVOT (
   TESTES  FOR TESTE IN (
        VLRSUBST AS 'ST',
        VLRIPI AS 'IPI',
        VLRICMS AS 'ICMS',
        VLRPIS AS 'PIS',
        VLRCOFINS AS 'COFINS'
    )
)

UNION ALL

SELECT 
    0 AS CODPROD, 
    TIPOPROD AS DESCRPROD,   
    CODTIPO,
    TIPOPROD,
    TESTE AS TIPO_GV,
    TESTES AS VALOR,
    (RATIO_TO_REPORT(TESTES) OVER ())*100 AS PERC_GV
FROM (
    SELECT
        PRO.AD_TPPROD AS CODTIPO,
        UPPER(F_DESCROPC('TGFPRO', 'AD_TPPROD', PRO.AD_TPPROD)) AS TIPOPROD,
        SUM(ITE.VLRSUBST) AS VLRSUBST,
        SUM(ITE.VLRIPI) AS VLRIPI,
        SUM(ITE.VLRICMS) AS VLRICMS,
        SUM((SELECT (VALOR) FROM TGFDIN WHERE NUNOTA = ITE.NUNOTA AND SEQUENCIA = ITE.SEQUENCIA AND CODIMP = 6)) AS VLRPIS,
        SUM((SELECT (VALOR) FROM TGFDIN WHERE NUNOTA = ITE.NUNOTA AND SEQUENCIA = ITE.SEQUENCIA AND CODIMP = 7)) AS VLRCOFINS
    FROM TGFCAB CAB
    INNER JOIN TGFITE ITE ON CAB.NUNOTA = ITE.NUNOTA
    INNER JOIN TGFCUS CUS ON CUS.CODPROD = ITE.CODPROD AND CUS.CODEMP = CAB.CODEMP AND CUS.DTATUAL = (
        SELECT MAX(DTATUAL) FROM TGFCUS WHERE DTATUAL <= CAB.DTNEG AND CODPROD = ITE.CODPROD AND CODEMP = CAB.CODEMP
    )
    INNER JOIN TGFTOP TOP ON CAB.CODTIPOPER = TOP.CODTIPOPER AND TOP.DHALTER = (
        SELECT MAX(DHALTER) FROM TGFTOP WHERE CODTIPOPER = CAB.CODTIPOPER
    )
    INNER JOIN TGFPRO PRO ON ITE.CODPROD = PRO.CODPROD
    WHERE TOP.GOLSINAL = -1
        AND (CAB.DTNEG BETWEEN :P_PERIODO.INI AND  :P_PERIODO.FIN)
        AND PRO.AD_TPPROD = :A_TPPROD
        AND TOP.TIPMOV IN ('V', 'D')
        AND TOP.ATIVO = 'S'
        AND PRO.AD_TPPROD IS NOT NULL
    GROUP BY PRO.AD_TPPROD
) SUB
UNPIVOT (
   TESTES  FOR TESTE IN (
        VLRSUBST AS 'ST',
        VLRIPI AS 'IPI',
        VLRICMS AS 'ICMS',
        VLRPIS AS 'PIS',
        VLRCOFINS AS 'COFINS'
    )
)
ORDER BY "VALOR" DESC
