CREATE OR REPLACE PROCEDURE             STP_SOLICT_DESC (P_NUNOTA INT, P_SUCESSO OUT VARCHAR, P_MENSAGEM OUT VARCHAR2, P_CODUSULIB OUT NUMBER)
AS
BEGIN
DECLARE
    
    P_COUNT INT;
    FIELD_N INT;
    FIELD_DESCONTO FLOAT;
    FIELD_VLRNOTA FLOAT;
    P_COUNT_2 INT;
    P_COUNT_3 INT;
BEGIN

        P_SUCESSO := 'S';

        SELECT COUNT(*) INTO P_COUNT_3 
        FROM TSILIB 
        WHERE NUCHAVE = P_NUNOTA
        AND EVENTO = 1009
        AND DHLIB IS NOT NULL
        AND REPROVADO = 'N';

      IF P_COUNT_3 < 1 THEN
        -- VERIFICA SE TEM DESCONTO
        SELECT COUNT(*) INTO P_COUNT 
        FROM TGFITE ITE
        WHERE ITE.NUNOTA = P_NUNOTA
        AND AD_DESC_LIB> 0;
        
        SELECT COUNT(*) INTO P_COUNT_2
        FROM TGFCAB CAB
        WHERE CAB.NUNOTA = P_NUNOTA
        AND CAB.CODTIPOPER = 1000;

        IF P_COUNT > 0 AND P_COUNT_2 >0 THEN 
               P_SUCESSO := 'N';

        SELECT NVL(SUM(NVL(ITE.AD_DESC_LIB, 0)), 0)
        INTO FIELD_DESCONTO
        FROM TGFITE ITE
        WHERE ITE.NUNOTA = P_NUNOTA;

          UPDATE TSILIB
          SET VLRLIMITE = FIELD_DESCONTO
          WHERE NUCHAVE = (SELECT NVL(NUNOTA,0) FROM TGFCAB WHERE CODTIPOPER = 1000 AND NUNOTA = P_NUNOTA);
          
    END IF;
    END IF;
    END;  
END;
/