SELECT * FROM (
SELECT DISTINCT
VGF.NUNOTA,
CAB.AD_STATUSA2WV2 STATUS_A2W
FROM AD_VGFSTATUSA2W VGF
INNER JOIN TGFCAB CAB ON VGF.NUNOTA = CAB.NUNOTA
LEFT JOIN TGFVAR VAR ON CAB.NUNOTA = VAR.NUNOTAORIG
LEFT JOIN TGFCAB CAB1 ON VAR.NUNOTA = CAB1.NUNOTA
LEFT JOIN TGFVAR VAR1 ON CAB1.NUNOTA = VAR1.NUNOTAORIG
LEFT JOIN TGFCAB CAB2 ON VAR1.NUNOTA = CAB2.NUNOTA
WHERE CAB.AD_STATUSA2WV2 IS NOT NULL 
AND CAB.DTMOV >= TO_DATE('01/07/2024','DD/MM/YYYY')

UNION ALL

SELECT DISTINCT
VAR.NUNOTA,
CAB.AD_STATUSA2WV2
FROM AD_VGFSTATUSA2W VGF
INNER JOIN TGFCAB CAB ON VGF.NUNOTA = CAB.NUNOTA
LEFT JOIN TGFVAR VAR ON CAB.NUNOTA = VAR.NUNOTAORIG
LEFT JOIN TGFCAB CAB1 ON VAR.NUNOTA = CAB1.NUNOTA
LEFT JOIN TGFVAR VAR1 ON CAB1.NUNOTA = VAR1.NUNOTAORIG
LEFT JOIN TGFCAB CAB2 ON VAR1.NUNOTA = CAB2.NUNOTA
WHERE CAB.AD_STATUSA2WV2 IS NOT NULL 
AND VAR.NUNOTA IS NOT NULL 
AND CAB.AD_STATUSA2WV2 <> CAB1.AD_STATUSA2WV2
AND CAB.DTMOV >= TO_DATE('01/07/2024','DD/MM/YYYY')

UNION ALL

SELECT DISTINCT
VAR1.NUNOTA,
CAB.AD_STATUSA2WV2
FROM AD_VGFSTATUSA2W VGF
INNER JOIN TGFCAB CAB ON VGF.NUNOTA = CAB.NUNOTA
LEFT JOIN TGFVAR VAR ON CAB.NUNOTA = VAR.NUNOTAORIG
LEFT JOIN TGFCAB CAB1 ON VAR.NUNOTA = CAB1.NUNOTA
LEFT JOIN TGFVAR VAR1 ON CAB1.NUNOTA = VAR1.NUNOTAORIG
LEFT JOIN TGFCAB CAB2 ON VAR1.NUNOTA = CAB2.NUNOTA
WHERE CAB.AD_STATUSA2WV2 IS NOT NULL 
AND CAB.AD_STATUSA2WV2 <> CAB1.AD_STATUSA2WV2
AND VAR.NUNOTA IS NOT NULL 
AND CAB.DTMOV >= TO_DATE('01/07/2024','DD/MM/YYYY')
)
WHERE NUNOTA IS NOT NULL        
