        WITH base AS (
            SELECT
                VGF.NUNOTA AS NUNOTA_ORIG,
                VAR.NUNOTA AS NUNOTA_VAR,
                VAR1.NUNOTA AS NUNOTA_VAR1,
                CAB.AD_STATUSA2WV2 AS STATUS_A2W
            FROM AD_VGFSTATUSA2W VGF
            INNER JOIN TGFCAB CAB ON VGF.NUNOTA = CAB.NUNOTA
            LEFT JOIN TGFVAR VAR ON CAB.NUNOTA = VAR.NUNOTAORIG
            LEFT JOIN TGFCAB CAB1 ON VAR.NUNOTA = CAB1.NUNOTA
            LEFT JOIN TGFVAR VAR1 ON CAB1.NUNOTA = VAR1.NUNOTAORIG
            LEFT JOIN TGFCAB CAB2 ON VAR1.NUNOTA = CAB2.NUNOTA
            WHERE VAR.NUNOTA IS NOT NULL
        )
        SELECT 
               CASE
                 WHEN STATUS_A2W = 'ENC' THEN 'PEDIDO ENCERRADO'
                 WHEN STATUS_A2W = 'ME' THEN 'MERCADORIA ENTREGUE'
                 WHEN STATUS_A2W = 'MA' THEN 'MERCDORIA A CAMINHO'
                 WHEN STATUS_A2W = 'PE' THEN 'PREVISAO ENTREGA'
                 WHEN STATUS_A2W = 'ANF' THEN 'AGUARDANDO NF'
                 WHEN STATUS_A2W = 'NFE' THEN 'NOTA FISCAL EMITIDA'
                 WHEN STATUS_A2W = 'PS' THEN 'PEDIDO EM SEPARACAO'
                 WHEN STATUS_A2W = 'R' THEN 'REJEITADO'
                 WHEN STATUS_A2W = 'A' THEN 'APROVADO'
                 WHEN STATUS_A2W = 'EE' THEN 'EM ANALISE'
                 WHEN STATUS_A2W = 'C' THEN 'CANCELADO'
                 WHEN STATUS_A2W = 'PFP' THEN 'PEDIDO FATURADO PARCIAL'
               END AS STATUS_DESCRICAO
        FROM (
            SELECT DISTINCT NUNOTA_ORIG AS NUNOTA, STATUS_A2W FROM base
            UNION ALL
            SELECT DISTINCT NUNOTA_VAR AS NUNOTA, STATUS_A2W FROM base WHERE STATUS_A2W IS NOT NULL
            UNION ALL
            SELECT DISTINCT NUNOTA_VAR1 AS NUNOTA, STATUS_A2W FROM base WHERE STATUS_A2W IS NOT NULL AND NUNOTA_VAR1 IS NOT NULL
        )
        WHERE NUNOTA = TGFCAB.NUNOTA
        FETCH FIRST 1 ROW ONLY
