CREATE OR REPLACE PROCEDURE STP_ATU_STATUS_A2W_SATIS AS
BEGIN
    EXECUTE IMMEDIATE 'ALTER TRIGGER TRG_AD_TGFCABVENCI_SATIS DISABLE';
    EXECUTE IMMEDIATE 'ALTER TRIGGER TRG_UPD_TGFCAB DISABLE';
    EXECUTE IMMEDIATE 'ALTER TRIGGER TRG_AD_TGFCABVENCI_SATIS DISABLE';
    EXECUTE IMMEDIATE 'ALTER TRIGGER TRG_INC_UPD_TGFCAB_ORD DISABLE';
    EXECUTE IMMEDIATE 'ALTER TRIGGER TRG_LIBCARGA_SATIS  DISABLE';
    EXECUTE IMMEDIATE 'ALTER TRIGGER TRG_CARGAINTERNA_SATIS  DISABLE';
    EXECUTE IMMEDIATE 'ALTER TRIGGER TRG_INSLIB_TGFFINLIB_SATIS  DISABLE';
    EXECUTE IMMEDIATE 'ALTER TRIGGER TRG_INC_UPD_TGFCAB_SATIS  DISABLE';
    EXECUTE IMMEDIATE 'ALTER TRIGGER TRG_DTCOLCARGANOTA_SATIS  DISABLE';
    EXECUTE IMMEDIATE 'ALTER TRIGGER TGF_TRVDATAEFET_SATIS  DISABLE';

  MERGE INTO TGFCAB cab
  USING (
    SELECT NUNOTA, MAX(STATUS_A2W) AS STATUS_A2W
    FROM (
      SELECT DISTINCT
        VGF.NUNOTA,
        CAB.AD_STATUSA2WV2 AS STATUS_A2W
      FROM AD_VGFSTATUSA2W VGF
      INNER JOIN TGFCAB CAB ON VGF.NUNOTA = CAB.NUNOTA
      LEFT JOIN TGFVAR VAR ON CAB.NUNOTA = VAR.NUNOTAORIG
      LEFT JOIN TGFCAB CAB1 ON VAR.NUNOTA = CAB1.NUNOTA
      LEFT JOIN TGFVAR VAR1 ON CAB1.NUNOTA = VAR1.NUNOTAORIG
      LEFT JOIN TGFCAB CAB2 ON VAR1.NUNOTA = CAB2.NUNOTA
      WHERE CAB.AD_STATUSA2WV2 IS NOT NULL
        AND CAB.DTMOV >= TO_DATE('01/07/2024','DD/MM/YYYY')

      UNION ALL

      SELECT DISTINCT
        VAR.NUNOTA,
        CAB.AD_STATUSA2WV2
      FROM AD_VGFSTATUSA2W VGF
      INNER JOIN TGFCAB CAB ON VGF.NUNOTA = CAB.NUNOTA
      LEFT JOIN TGFVAR VAR ON CAB.NUNOTA = VAR.NUNOTAORIG
      LEFT JOIN TGFCAB CAB1 ON VAR.NUNOTA = CAB1.NUNOTA
      LEFT JOIN TGFVAR VAR1 ON CAB1.NUNOTA = VAR1.NUNOTAORIG
      LEFT JOIN TGFCAB CAB2 ON VAR1.NUNOTA = CAB2.NUNOTA
      WHERE CAB.AD_STATUSA2WV2 IS NOT NULL
        AND CAB.DTMOV >= TO_DATE('01/07/2024','DD/MM/YYYY')

      UNION ALL

      SELECT DISTINCT
        VAR1.NUNOTA,
        CAB.AD_STATUSA2WV2
      FROM AD_VGFSTATUSA2W VGF
      INNER JOIN TGFCAB CAB ON VGF.NUNOTA = CAB.NUNOTA
      LEFT JOIN TGFVAR VAR ON CAB.NUNOTA = VAR.NUNOTAORIG
      LEFT JOIN TGFCAB CAB1 ON VAR.NUNOTA = CAB1.NUNOTA
      LEFT JOIN TGFVAR VAR1 ON CAB1.NUNOTA = VAR1.NUNOTAORIG
      LEFT JOIN TGFCAB CAB2 ON VAR1.NUNOTA = CAB2.NUNOTA
      WHERE CAB.AD_STATUSA2WV2 IS NOT NULL
        AND CAB.DTMOV >= TO_DATE('01/07/2024','DD/MM/YYYY')
    )
    WHERE NUNOTA IS NOT NULL
    GROUP BY NUNOTA
  ) q
  ON (cab.NUNOTA = q.NUNOTA)
  WHEN MATCHED THEN
    UPDATE SET cab.AD_STATUSA2WV3 = q.STATUS_A2W;

  COMMIT;

    EXECUTE IMMEDIATE 'ALTER TRIGGER TRG_AD_TGFCABVENCI_SATIS ENABLE';
    EXECUTE IMMEDIATE 'ALTER TRIGGER TRG_UPD_TGFCAB ENABLE';
    EXECUTE IMMEDIATE 'ALTER TRIGGER TRG_AD_TGFCABVENCI_SATIS ENABLE';
    EXECUTE IMMEDIATE 'ALTER TRIGGER TRG_INC_UPD_TGFCAB_ORD ENABLE';
    EXECUTE IMMEDIATE 'ALTER TRIGGER TRG_LIBCARGA_SATIS  ENABLE';
    EXECUTE IMMEDIATE 'ALTER TRIGGER TRG_CARGAINTERNA_SATIS  ENABLE';
    EXECUTE IMMEDIATE 'ALTER TRIGGER TRG_INSLIB_TGFFINLIB_SATIS  ENABLE';
    EXECUTE IMMEDIATE 'ALTER TRIGGER TRG_INC_UPD_TGFCAB_SATIS  ENABLE';
    EXECUTE IMMEDIATE 'ALTER TRIGGER TRG_DTCOLCARGANOTA_SATIS  ENABLE';
    EXECUTE IMMEDIATE 'ALTER TRIGGER TGF_TRVDATAEFET_SATIS  ENABLE';
END STP_ATU_STATUS_A2W_SATIS;
/
