SELECT
MARCA,

CASE WHEN TO_DATE('01-07-'||TO_CHAR(:P_PERIODO.INI, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN JUL_QTDPREV
     WHEN TO_DATE('01-07-'||TO_CHAR(:P_PERIODO.FIN, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN JUL_QTDPREV ELSE NULL END AS JUL_QTDPREV,
CASE WHEN TO_DATE('01-07-'||TO_CHAR(:P_PERIODO.INI, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN JUL_QTDREAL
     WHEN TO_DATE('01-07-'||TO_CHAR(:P_PERIODO.FIN, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN JUL_QTDREAL ELSE NULL END AS JUL_QTDREAL,
CASE WHEN TO_DATE('01-07-'||TO_CHAR(:P_PERIODO.INI, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN JUL_VLR_PREV
     WHEN TO_DATE('01-07-'||TO_CHAR(:P_PERIODO.FIN, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN JUL_VLR_PREV ELSE NULL END AS JUL_VLR_PREV,	 
CASE WHEN TO_DATE('01-07-'||TO_CHAR(:P_PERIODO.INI, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN JUL_VLR_REAL
     WHEN TO_DATE('01-07-'||TO_CHAR(:P_PERIODO.FIN, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN JUL_VLR_REAL ELSE NULL END AS JUL_VLR_REAL,	 
	 
CASE WHEN TO_DATE('01-08-'||TO_CHAR(:P_PERIODO.INI, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN AGO_QTDPREV
     WHEN TO_DATE('01-08-'||TO_CHAR(:P_PERIODO.FIN, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN AGO_QTDPREV ELSE NULL END AS AGO_QTDPREV,
CASE WHEN TO_DATE('01-08-'||TO_CHAR(:P_PERIODO.INI, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN AGO_QTDREAL
     WHEN TO_DATE('01-08-'||TO_CHAR(:P_PERIODO.FIN, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN AGO_QTDREAL ELSE NULL END AS AGO_QTDREAL,
CASE WHEN TO_DATE('01-08-'||TO_CHAR(:P_PERIODO.INI, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN AGO_VLR_PREV
     WHEN TO_DATE('01-08-'||TO_CHAR(:P_PERIODO.FIN, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN AGO_VLR_PREV ELSE NULL END AS AGO_VLR_PREV,	 
CASE WHEN TO_DATE('01-08-'||TO_CHAR(:P_PERIODO.INI, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN AGO_VLR_REAL
     WHEN TO_DATE('01-08-'||TO_CHAR(:P_PERIODO.FIN, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN AGO_VLR_REAL ELSE NULL END AS AGO_VLR_REAL,	 

CASE WHEN TO_DATE('01-09-'||TO_CHAR(:P_PERIODO.INI, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN SET_QTDPREV
     WHEN TO_DATE('01-09-'||TO_CHAR(:P_PERIODO.FIN, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN SET_QTDPREV ELSE NULL END AS SET_QTDPREV,
CASE WHEN TO_DATE('01-09-'||TO_CHAR(:P_PERIODO.INI, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN SET_QTDREAL
     WHEN TO_DATE('01-09-'||TO_CHAR(:P_PERIODO.FIN, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN SET_QTDREAL ELSE NULL END AS SET_QTDREAL,
CASE WHEN TO_DATE('01-09-'||TO_CHAR(:P_PERIODO.INI, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN SET_VLR_PREV
     WHEN TO_DATE('01-09-'||TO_CHAR(:P_PERIODO.FIN, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN SET_VLR_PREV ELSE NULL END AS SET_VLR_PREV,	 
CASE WHEN TO_DATE('01-09-'||TO_CHAR(:P_PERIODO.INI, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN SET_VLR_REAL
     WHEN TO_DATE('01-09-'||TO_CHAR(:P_PERIODO.FIN, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN SET_VLR_REAL ELSE NULL END AS SET_VLR_REAL,	 

CASE WHEN TO_DATE('01-10-'||TO_CHAR(:P_PERIODO.INI, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN OUT_QTDPREV
     WHEN TO_DATE('01-10-'||TO_CHAR(:P_PERIODO.FIN, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN OUT_QTDPREV ELSE NULL END AS OUT_QTDPREV,
CASE WHEN TO_DATE('01-10-'||TO_CHAR(:P_PERIODO.INI, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN OUT_QTDREAL
     WHEN TO_DATE('01-10-'||TO_CHAR(:P_PERIODO.FIN, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN OUT_QTDREAL ELSE NULL END AS OUT_QTDREAL,
CASE WHEN TO_DATE('01-10-'||TO_CHAR(:P_PERIODO.INI, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN OUT_VLR_PREV
     WHEN TO_DATE('01-10-'||TO_CHAR(:P_PERIODO.FIN, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN OUT_VLR_PREV ELSE NULL END AS OUT_VLR_PREV,	 
CASE WHEN TO_DATE('01-10-'||TO_CHAR(:P_PERIODO.INI, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN OUT_VLR_REAL
     WHEN TO_DATE('01-10-'||TO_CHAR(:P_PERIODO.FIN, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN OUT_VLR_REAL ELSE NULL END AS OUT_VLR_REAL,	 

CASE WHEN TO_DATE('01-11-'||TO_CHAR(:P_PERIODO.INI, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN NOV_QTDPREV
     WHEN TO_DATE('01-11-'||TO_CHAR(:P_PERIODO.FIN, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN NOV_QTDPREV ELSE NULL END AS NOV_QTDPREV,
CASE WHEN TO_DATE('01-11-'||TO_CHAR(:P_PERIODO.INI, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN NOV_QTDREAL
     WHEN TO_DATE('01-11-'||TO_CHAR(:P_PERIODO.FIN, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN NOV_QTDREAL ELSE NULL END AS NOV_QTDREAL,
CASE WHEN TO_DATE('01-11-'||TO_CHAR(:P_PERIODO.INI, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN NOV_VLR_PREV
     WHEN TO_DATE('01-11-'||TO_CHAR(:P_PERIODO.FIN, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN NOV_VLR_PREV ELSE NULL END AS NOV_VLR_PREV,	 
CASE WHEN TO_DATE('01-11-'||TO_CHAR(:P_PERIODO.INI, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN NOV_VLR_REAL
     WHEN TO_DATE('01-11-'||TO_CHAR(:P_PERIODO.FIN, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN NOV_VLR_REAL ELSE NULL END AS NOV_VLR_REAL,	 

CASE WHEN TO_DATE('01-12-'||TO_CHAR(:P_PERIODO.INI, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN DEZ_QTDPREV
     WHEN TO_DATE('01-12-'||TO_CHAR(:P_PERIODO.FIN, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN DEZ_QTDPREV ELSE NULL END AS DEZ_QTDPREV,
CASE WHEN TO_DATE('01-12-'||TO_CHAR(:P_PERIODO.INI, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN DEZ_QTDREAL
     WHEN TO_DATE('01-12-'||TO_CHAR(:P_PERIODO.FIN, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN DEZ_QTDREAL ELSE NULL END AS DEZ_QTDREAL,
CASE WHEN TO_DATE('01-12-'||TO_CHAR(:P_PERIODO.INI, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN DEZ_VLR_PREV
     WHEN TO_DATE('01-12-'||TO_CHAR(:P_PERIODO.FIN, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN DEZ_VLR_PREV ELSE NULL END AS DEZ_VLR_PREV,	 
CASE WHEN TO_DATE('01-12-'||TO_CHAR(:P_PERIODO.INI, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN DEZ_VLR_REAL
     WHEN TO_DATE('01-12-'||TO_CHAR(:P_PERIODO.FIN, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN DEZ_VLR_REAL ELSE NULL END AS DEZ_VLR_REAL,	 

CASE WHEN TO_DATE('01-01-'||TO_CHAR(:P_PERIODO.INI, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN JAN_QTDPREV
     WHEN TO_DATE('01-01-'||TO_CHAR(:P_PERIODO.FIN, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN JAN_QTDPREV ELSE NULL END AS JAN_QTDPREV,
CASE WHEN TO_DATE('01-01-'||TO_CHAR(:P_PERIODO.INI, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN JAN_QTDREAL
     WHEN TO_DATE('01-01-'||TO_CHAR(:P_PERIODO.FIN, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN JAN_QTDREAL ELSE NULL END AS JAN_QTDREAL,
CASE WHEN TO_DATE('01-01-'||TO_CHAR(:P_PERIODO.INI, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN JAN_VLR_PREV
     WHEN TO_DATE('01-01-'||TO_CHAR(:P_PERIODO.FIN, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN JAN_VLR_PREV ELSE NULL END AS JAN_VLR_PREV,	 
CASE WHEN TO_DATE('01-01-'||TO_CHAR(:P_PERIODO.INI, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN JAN_VLR_REAL
     WHEN TO_DATE('01-01-'||TO_CHAR(:P_PERIODO.FIN, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN JAN_VLR_REAL ELSE NULL END AS JAN_VLR_REAL,	 
	 
CASE WHEN TO_DATE('01-02-'||TO_CHAR(:P_PERIODO.INI, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN FEV_QTDPREV
     WHEN TO_DATE('01-02-'||TO_CHAR(:P_PERIODO.FIN, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN FEV_QTDPREV ELSE NULL END AS FEV_QTDPREV,
CASE WHEN TO_DATE('01-02-'||TO_CHAR(:P_PERIODO.INI, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN FEV_QTDREAL
     WHEN TO_DATE('01-02-'||TO_CHAR(:P_PERIODO.FIN, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN FEV_QTDREAL ELSE NULL END AS FEV_QTDREAL,
CASE WHEN TO_DATE('01-02-'||TO_CHAR(:P_PERIODO.INI, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN FEV_VLR_PREV
     WHEN TO_DATE('01-02-'||TO_CHAR(:P_PERIODO.FIN, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN FEV_VLR_PREV ELSE NULL END AS FEV_VLR_PREV,	 
CASE WHEN TO_DATE('01-02-'||TO_CHAR(:P_PERIODO.INI, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN FEV_VLR_REAL
     WHEN TO_DATE('01-02-'||TO_CHAR(:P_PERIODO.FIN, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN FEV_VLR_REAL ELSE NULL END AS FEV_VLR_REAL,	 

CASE WHEN TO_DATE('01-03-'||TO_CHAR(:P_PERIODO.INI, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN MAR_QTDPREV
     WHEN TO_DATE('01-03-'||TO_CHAR(:P_PERIODO.FIN, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN MAR_QTDPREV ELSE NULL END AS MAR_QTDPREV,
CASE WHEN TO_DATE('01-03-'||TO_CHAR(:P_PERIODO.INI, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN MAR_QTDREAL
     WHEN TO_DATE('01-03-'||TO_CHAR(:P_PERIODO.FIN, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN MAR_QTDREAL ELSE NULL END AS MAR_QTDREAL,
CASE WHEN TO_DATE('01-03-'||TO_CHAR(:P_PERIODO.INI, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN MAR_VLR_PREV
     WHEN TO_DATE('01-03-'||TO_CHAR(:P_PERIODO.FIN, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN MAR_VLR_PREV ELSE NULL END AS MAR_VLR_PREV,	 
CASE WHEN TO_DATE('01-03-'||TO_CHAR(:P_PERIODO.INI, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN MAR_VLR_REAL
     WHEN TO_DATE('01-03-'||TO_CHAR(:P_PERIODO.FIN, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN MAR_VLR_REAL ELSE NULL END AS MAR_VLR_REAL,	 

CASE WHEN TO_DATE('01-04-'||TO_CHAR(:P_PERIODO.INI, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN ABR_QTDPREV
     WHEN TO_DATE('01-04-'||TO_CHAR(:P_PERIODO.FIN, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN ABR_QTDPREV ELSE NULL END AS ABR_QTDPREV,
CASE WHEN TO_DATE('01-04-'||TO_CHAR(:P_PERIODO.INI, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN ABR_QTDREAL
     WHEN TO_DATE('01-04-'||TO_CHAR(:P_PERIODO.FIN, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN ABR_QTDREAL ELSE NULL END AS ABR_QTDREAL,
CASE WHEN TO_DATE('01-04-'||TO_CHAR(:P_PERIODO.INI, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN ABR_VLR_PREV
     WHEN TO_DATE('01-04-'||TO_CHAR(:P_PERIODO.FIN, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN ABR_VLR_PREV ELSE NULL END AS ABR_VLR_PREV,	 
CASE WHEN TO_DATE('01-04-'||TO_CHAR(:P_PERIODO.INI, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN ABR_VLR_REAL
     WHEN TO_DATE('01-04-'||TO_CHAR(:P_PERIODO.FIN, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN ABR_VLR_REAL ELSE NULL END AS ABR_VLR_REAL,	 

CASE WHEN TO_DATE('01-05-'||TO_CHAR(:P_PERIODO.INI, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN MAI_QTDPREV
     WHEN TO_DATE('01-05-'||TO_CHAR(:P_PERIODO.FIN, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN MAI_QTDPREV ELSE NULL END AS MAI_QTDPREV,
CASE WHEN TO_DATE('01-05-'||TO_CHAR(:P_PERIODO.INI, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN MAI_QTDREAL
     WHEN TO_DATE('01-05-'||TO_CHAR(:P_PERIODO.FIN, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN MAI_QTDREAL ELSE NULL END AS MAI_QTDREAL,
CASE WHEN TO_DATE('01-05-'||TO_CHAR(:P_PERIODO.INI, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN MAI_VLR_PREV
     WHEN TO_DATE('01-05-'||TO_CHAR(:P_PERIODO.FIN, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN MAI_VLR_PREV ELSE NULL END AS MAI_VLR_PREV,	 
CASE WHEN TO_DATE('01-05-'||TO_CHAR(:P_PERIODO.INI, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN MAI_VLR_REAL
     WHEN TO_DATE('01-05-'||TO_CHAR(:P_PERIODO.FIN, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN MAI_VLR_REAL ELSE NULL END AS MAI_VLR_REAL,
	 
CASE WHEN TO_DATE('01-06-'||TO_CHAR(:P_PERIODO.INI, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN JUN_QTDPREV
     WHEN TO_DATE('01-06-'||TO_CHAR(:P_PERIODO.FIN, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN JUN_QTDPREV ELSE NULL END AS JUN_QTDPREV,
CASE WHEN TO_DATE('01-06-'||TO_CHAR(:P_PERIODO.INI, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN JUN_QTDREAL
     WHEN TO_DATE('01-06-'||TO_CHAR(:P_PERIODO.FIN, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN JUN_QTDREAL ELSE NULL END AS JUN_QTDREAL,
CASE WHEN TO_DATE('01-06-'||TO_CHAR(:P_PERIODO.INI, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN JUN_VLR_PREV
     WHEN TO_DATE('01-06-'||TO_CHAR(:P_PERIODO.FIN, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN JUN_VLR_PREV ELSE NULL END AS JUN_VLR_PREV,	 
CASE WHEN TO_DATE('01-06-'||TO_CHAR(:P_PERIODO.INI, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN JUN_VLR_REAL
     WHEN TO_DATE('01-06-'||TO_CHAR(:P_PERIODO.FIN, 'YYYY'), 'DD-MM-YYYY') BETWEEN TO_DATE(:P_PERIODO.INI) AND TO_DATE(:P_PERIODO.FIN) THEN JUN_VLR_REAL ELSE NULL END AS JUN_VLR_REAL,
TTL_QTDPREV,TTL_QTDREAL,TTL_VLR_PREV,TTL_VLR_REAL

FROM
(

SELECT
T.*,
(JUL_QTDPREV + AGO_QTDPREV + SET_QTDPREV + OUT_QTDPREV+NOV_QTDPREV+DEZ_QTDPREV+JAN_QTDPREV+FEV_QTDPREV+MAR_QTDPREV+ABR_QTDPREV+MAI_QTDPREV+JUN_QTDPREV) AS TTL_QTDPREV,
(JUL_QTDREAL + AGO_QTDREAL + SET_QTDREAL + OUT_QTDREAL+NOV_QTDREAL+DEZ_QTDREAL+JAN_QTDREAL+FEV_QTDREAL+MAR_QTDREAL+ABR_QTDREAL+MAI_QTDREAL+JUN_QTDREAL) AS TTL_QTDREAL,
(JUL_VLR_PREV + AGO_VLR_PREV + SET_VLR_PREV + OUT_VLR_PREV+NOV_VLR_PREV+DEZ_VLR_PREV+JAN_VLR_PREV+FEV_VLR_PREV+MAR_VLR_PREV+ABR_VLR_PREV+MAI_VLR_PREV+JUN_VLR_PREV) AS TTL_VLR_PREV,
(JUL_VLR_REAL + AGO_VLR_REAL + SET_VLR_REAL + OUT_VLR_REAL+NOV_VLR_REAL+DEZ_VLR_REAL+JAN_VLR_REAL+FEV_VLR_REAL+MAR_VLR_REAL+ABR_VLR_REAL+MAI_VLR_REAL+JUN_VLR_REAL) AS TTL_VLR_REAL

FROM (
SELECT 
    MARCA,
    SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 7 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN QTDPREV ELSE 0 END) AS JUL_QTDPREV,
    SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 7 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN QTDREAL ELSE 0 END) AS JUL_QTDREAL,
    SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 7 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN (QTDPREV * PRECOLT) ELSE 0 END) AS JUL_VLR_PREV,
    SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 7 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN (VLRREAL) ELSE 0 END) AS JUL_VLR_REAL,

    SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 8 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN QTDPREV ELSE 0 END) AS AGO_QTDPREV,
    SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 8 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN QTDREAL ELSE 0 END) AS AGO_QTDREAL,
    SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 8 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN (QTDPREV * PRECOLT) ELSE 0 END) AS AGO_VLR_PREV,
    SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 8 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN (VLRREAL) ELSE 0 END) AS AGO_VLR_REAL,

    SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 9 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN QTDPREV ELSE 0 END) AS SET_QTDPREV,
    SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 9 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN QTDREAL ELSE 0 END) AS SET_QTDREAL,
    SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 9 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN (QTDPREV * PRECOLT) ELSE 0 END) AS SET_VLR_PREV,
    SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 9 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN (VLRREAL) ELSE 0 END) AS SET_VLR_REAL,

    SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 10 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN QTDPREV ELSE 0 END) AS OUT_QTDPREV,
    SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 10 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN QTDREAL ELSE 0 END) AS OUT_QTDREAL,
    SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 10 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN (QTDPREV * PRECOLT) ELSE 0 END) AS OUT_VLR_PREV,
    SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 10 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN (VLRREAL) ELSE 0 END) AS OUT_VLR_REAL,

    SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 11 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN QTDPREV ELSE 0 END) AS NOV_QTDPREV,
    SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 11 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN QTDREAL ELSE 0 END) AS NOV_QTDREAL,
    SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 11 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN (QTDPREV * PRECOLT) ELSE 0 END) AS NOV_VLR_PREV,
    SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 11 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN (VLRREAL) ELSE 0 END) AS NOV_VLR_REAL,

    SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 12 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN QTDPREV ELSE 0 END) AS DEZ_QTDPREV,
    SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 12 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN QTDREAL ELSE 0 END) AS DEZ_QTDREAL,
    SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 12 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN (QTDPREV * PRECOLT) ELSE 0 END) AS DEZ_VLR_PREV,
    SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 12 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN (VLRREAL) ELSE 0 END) AS DEZ_VLR_REAL,

    SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 1 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN QTDPREV ELSE 0 END) AS JAN_QTDPREV,
    SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 1 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN QTDREAL ELSE 0 END) AS JAN_QTDREAL,
    SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 1 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN (QTDPREV * PRECOLT) ELSE 0 END) AS JAN_VLR_PREV,
    SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 1 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN (VLRREAL) ELSE 0 END) AS JAN_VLR_REAL,

    SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 2 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN QTDPREV ELSE 0 END) AS FEV_QTDPREV,
    SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 2 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN QTDREAL ELSE 0 END) AS FEV_QTDREAL,
    SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 2 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN (QTDPREV * PRECOLT) ELSE 0 END) AS FEV_VLR_PREV,
    SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 2 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN (VLRREAL) ELSE 0 END) AS FEV_VLR_REAL,

    SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 3 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN QTDPREV ELSE 0 END) AS MAR_QTDPREV,
    SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 3 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN QTDREAL ELSE 0 END) AS MAR_QTDREAL,
    SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 3 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN (QTDPREV * PRECOLT) ELSE 0 END) AS MAR_VLR_PREV,
    SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 3 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN (VLRREAL) ELSE 0 END) AS MAR_VLR_REAL,
    
    SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 4 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN QTDPREV ELSE 0 END) AS ABR_QTDPREV,
    SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 4 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN QTDREAL ELSE 0 END) AS ABR_QTDREAL,
    SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 4 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN (QTDPREV * PRECOLT) ELSE 0 END) AS ABR_VLR_PREV,
    SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 4 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN (VLRREAL) ELSE 0 END) AS ABR_VLR_REAL,

    SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 5 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN QTDPREV ELSE 0 END) AS MAI_QTDPREV,
    SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 5 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN QTDREAL ELSE 0 END) AS MAI_QTDREAL,
    SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 5 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN (QTDPREV * PRECOLT) ELSE 0 END) AS MAI_VLR_PREV,
    SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 5 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN (VLRREAL) ELSE 0 END) AS MAI_VLR_REAL,

    SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 6 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN QTDPREV ELSE 0 END) AS JUN_QTDPREV,
    SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 6 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN QTDREAL ELSE 0 END) AS JUN_QTDREAL,
    SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 6 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN (QTDPREV * PRECOLT) ELSE 0 END) AS JUN_VLR_PREV,
    SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 6 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN (VLRREAL) ELSE 0 END) AS JUN_VLR_REAL








FROM
(
SELECT MET.DTREF, NVL(MET.CODVEND,0) AS CODVEND, NVL(MET.CODPARC,0) AS CODPARC, NVL(MET.MARCA,0) AS MARCA,NVL(VGF.CODCENCUS,0) AS CODCENCUS, NVL(MET.QTDPREV,0) AS QTDPREV, SUM(NVL(VGF.QTD,0)) AS QTDREAL,NVL(PRC.VLRVENDALT,0)AS PRECOLT, SUM(NVL(VGF.VLR,0)) AS VLRREAL
FROM TGFMET MET
LEFT JOIN VGF_VENDAS_SATIS VGF ON MET.DTREF = TRUNC(VGF.DTMOV,'MM') AND MET.CODVEND = VGF.CODVEND AND MET.CODPARC = VGF.CODPARC AND MET.MARCA = VGF.MARCA AND VGF.BONIFICACAO = 'N'
LEFT JOIN AD_PRECOMARCA PRC ON (MET.MARCA = PRC.MARCA AND PRC.CODMETA = MET.CODMETA AND PRC.DTREF = (SELECT MAX(DTREF) FROM AD_PRECOMARCA WHERE CODMETA = MET.CODMETA AND DTREF <= MET.DTREF AND MARCA = MET.MARCA))
WHERE 
MET.CODMETA = :P_CODMETA
AND MET.DTREF BETWEEN :P_PERIODO.INI   AND  :P_PERIODO.FIN

AND (VGF.CODGRUPOPROD = :P_GRUPOPROD OR :P_GRUPOPROD IS NULL)

GROUP BY MET.DTREF,NVL(MET.CODVEND,0),NVL(MET.CODPARC,0),NVL(MET.MARCA,0),NVL(VGF.CODCENCUS,0), NVL(MET.QTDPREV,0), NVL(PRC.VLRVENDALT,0)


)A
INNER JOIN TGFPAR PAR ON A.CODPARC = PAR.CODPARC
INNER JOIN TGFVEN VEN ON A.CODVEND = VEN.CODVEND
WHERE
(VEN.CODVEND IN :P_CODVEND)
AND (VEN.CODGER IN :P_CODGER)
AND (PAR.CODPARC = :P_CODPARC OR :P_CODPARC IS NULL)
AND (A.MARCA IN (SELECT MARCA FROM TGFPRO WHERE CODPROD IN :P_MARCA))
AND (A.CODCENCUS = :P_CR OR :P_CR IS NULL)
AND
(
VEN.CODVEND = (SELECT CODVEND FROM TSIUSU WHERE CODUSU = STP_GET_CODUSULOGADO) ---CONSULTA VENDEDOR
OR VEN.CODVEND IN (SELECT VEN.CODVEND FROM TGFVEN VEN, TSIUSU USU WHERE USU.CODVEND = VEN.CODGER AND USU.CODUSU = STP_GET_CODUSULOGADO) ---CONSULTA GERENTE
OR (SELECT AD_GESTOR_META FROM TSIUSU WHERE CODUSU = STP_GET_CODUSULOGADO) = 'S' ---CONSULTA MASTER
)

GROUP BY MARCA)T
)
WHERE ((:P_NTEMMETA = 'S' AND (TTL_QTDPREV <> 0 OR TTL_QTDREAL <> 0 OR TTL_VLR_PREV <> 0 OR TTL_VLR_REAL<> 0)) OR :P_NTEMMETA = 'N')

ORDER BY 1