SELECT
  CODVEND,
  VENDEDOR AS APELIDO,
  SUM(JUL_QTDPREV) AS JUL_QTDPREV,
  SUM(JUL_QTDREAL) AS JUL_QTDREAL,
  -- Calcula % de atingimento da meta considerando realizado / previsto
  NVL(ROUND((SUM(JUL_QTDREAL) / NULLIF(SUM(JUL_QTDPREV), 0)) * 100, 2), 0) AS JUL_PCT_QTD,
  SUM(JUL_VLR_PREV) AS JUL_VLR_PREV,
  SUM(JUL_VLR_REAL) AS JUL_VLR_REAL,
  NVL(ROUND((SUM(JUL_VLR_REAL) / NULLIF(SUM(JUL_VLR_PREV), 0)) * 100, 2), 0) AS JUL_PCT_VLR,
  SUM(AGO_QTDPREV) AS AGO_QTDPREV,
  SUM(AGO_QTDREAL) AS AGO_QTDREAL,
  NVL(ROUND((SUM(AGO_QTDREAL) / NULLIF(SUM(AGO_QTDPREV), 0)) * 100, 2), 0) AS AGO_PCT_QTD,
  SUM(AGO_VLR_PREV) AS AGO_VLR_PREV,
  SUM(AGO_VLR_REAL) AS AGO_VLR_REAL,
  NVL(ROUND((SUM(AGO_VLR_REAL) / NULLIF(SUM(AGO_VLR_PREV), 0)) * 100, 2), 0) AS AGO_PCT_VLR,
  SUM(SET_QTDPREV) AS SET_QTDPREV,
  SUM(SET_QTDREAL) AS SET_QTDREAL,
  NVL(ROUND((SUM(SET_QTDREAL) / NULLIF(SUM(SET_QTDPREV), 0)) * 100, 2), 0) AS SET_PCT_QTD,
  SUM(SET_VLR_PREV) AS SET_VLR_PREV,
  SUM(SET_VLR_REAL) AS SET_VLR_REAL,
  NVL(ROUND((SUM(SET_VLR_REAL) / NULLIF(SUM(SET_VLR_PREV), 0)) * 100, 2), 0) AS SET_PCT_VLR,
  SUM(OUT_QTDPREV) AS OUT_QTDPREV,
  SUM(OUT_QTDREAL) AS OUT_QTDREAL,
  NVL(ROUND((SUM(OUT_QTDREAL) / NULLIF(SUM(OUT_QTDPREV), 0)) * 100, 2), 0) AS OUT_PCT_QTD,
  SUM(OUT_VLR_PREV) AS OUT_VLR_PREV,
  SUM(OUT_VLR_REAL) AS OUT_VLR_REAL,
  NVL(ROUND((SUM(OUT_VLR_REAL) / NULLIF(SUM(OUT_VLR_PREV), 0)) * 100, 2), 0) AS OUT_PCT_VLR,
  SUM(NOV_QTDPREV) AS NOV_QTDPREV,
  SUM(NOV_QTDREAL) AS NOV_QTDREAL,
  NVL(ROUND((SUM(NOV_QTDREAL) / NULLIF(SUM(NOV_QTDPREV), 0)) * 100, 2), 0) AS NOV_PCT_QTD,
  SUM(NOV_VLR_PREV) AS NOV_VLR_PREV,
  SUM(NOV_VLR_REAL) AS NOV_VLR_REAL,
  NVL(ROUND((SUM(NOV_VLR_REAL) / NULLIF(SUM(NOV_VLR_PREV), 0)) * 100, 2), 0) AS NOV_PCT_VLR,
  SUM(DEZ_QTDPREV) AS DEZ_QTDPREV,
  SUM(DEZ_QTDREAL) AS DEZ_QTDREAL,
  NVL(ROUND((SUM(DEZ_QTDREAL) / NULLIF(SUM(DEZ_QTDPREV), 0)) * 100, 2), 0) AS DEZ_PCT_QTD,
  SUM(DEZ_VLR_PREV) AS DEZ_VLR_PREV,
  SUM(DEZ_VLR_REAL) AS DEZ_VLR_REAL,
  NVL(ROUND((SUM(DEZ_VLR_REAL) / NULLIF(SUM(DEZ_VLR_PREV), 0)) * 100, 2), 0) AS DEZ_PCT_VLR,
  SUM(JAN_QTDPREV) AS JAN_QTDPREV,
  SUM(JAN_QTDREAL) AS JAN_QTDREAL,
  NVL(ROUND((SUM(JAN_QTDREAL) / NULLIF(SUM(JAN_QTDPREV), 0)) * 100, 2), 0) AS JAN_PCT_QTD,
  SUM(JAN_VLR_PREV) AS JAN_VLR_PREV,
  SUM(JAN_VLR_REAL) AS JAN_VLR_REAL,
  NVL(ROUND((SUM(JAN_VLR_REAL) / NULLIF(SUM(JAN_VLR_PREV), 0)) * 100, 2), 0) AS JAN_PCT_VLR,
  SUM(FEV_QTDPREV) AS FEV_QTDPREV,
  SUM(FEV_QTDREAL) AS FEV_QTDREAL,
  NVL(ROUND((SUM(FEV_QTDREAL) / NULLIF(SUM(FEV_QTDPREV), 0)) * 100, 2), 0) AS FEV_PCT_QTD,
  SUM(FEV_VLR_PREV) AS FEV_VLR_PREV,
  SUM(FEV_VLR_REAL) AS FEV_VLR_REAL,
  NVL(ROUND((SUM(FEV_VLR_REAL) / NULLIF(SUM(FEV_VLR_PREV), 0)) * 100, 2), 0) AS FEV_PCT_VLR,
  SUM(MAR_QTDPREV) AS MAR_QTDPREV,
  SUM(MAR_QTDREAL) AS MAR_QTDREAL,
  NVL(ROUND((SUM(MAR_QTDREAL) / NULLIF(SUM(MAR_QTDPREV), 0)) * 100, 2), 0) AS MAR_PCT_QTD,
  SUM(MAR_VLR_PREV) AS MAR_VLR_PREV,
  SUM(MAR_VLR_REAL) AS MAR_VLR_REAL,
  NVL(ROUND((SUM(MAR_VLR_REAL) / NULLIF(SUM(MAR_VLR_PREV), 0)) * 100, 2), 0) AS MAR_PCT_VLR,
  SUM(ABR_QTDPREV) AS ABR_QTDPREV,
  SUM(ABR_QTDREAL) AS ABR_QTDREAL,
  NVL(ROUND((SUM(ABR_QTDREAL) / NULLIF(SUM(ABR_QTDPREV), 0)) * 100, 2), 0) AS ABR_PCT_QTD,
  SUM(ABR_VLR_PREV) AS ABR_VLR_PREV,
  SUM(ABR_VLR_REAL) AS ABR_VLR_REAL,
  NVL(ROUND((SUM(ABR_VLR_REAL) / NULLIF(SUM(ABR_VLR_PREV), 0)) * 100, 2), 0) AS ABR_PCT_VLR,
  SUM(MAI_QTDPREV) AS MAI_QTDPREV,
  SUM(MAI_QTDREAL) AS MAI_QTDREAL,
  NVL(ROUND((SUM(MAI_QTDREAL) / NULLIF(SUM(MAI_QTDPREV), 0)) * 100, 2), 0) AS MAI_PCT_QTD,
  SUM(MAI_VLR_PREV) AS MAI_VLR_PREV,
  SUM(MAI_VLR_REAL) AS MAI_VLR_REAL,
  NVL(ROUND((SUM(MAI_VLR_REAL) / NULLIF(SUM(MAI_VLR_PREV), 0)) * 100, 2), 0) AS MAI_PCT_VLR,
  SUM(JUN_QTDPREV) AS JUN_QTDPREV,
  SUM(JUN_QTDREAL) AS JUN_QTDREAL,
  NVL(ROUND((SUM(JUN_QTDREAL) / NULLIF(SUM(JUN_QTDPREV), 0)) * 100, 2), 0) AS JUN_PCT_QTD,
  SUM(JUN_VLR_PREV) AS JUN_VLR_PREV,
  SUM(JUN_VLR_REAL) AS JUN_VLR_REAL,
  NVL(ROUND((SUM(JUN_VLR_REAL) / NULLIF(SUM(JUN_VLR_PREV), 0)) * 100, 2), 0) AS JUN_PCT_VLR,
  SUM(TTL_QTDPREV) AS TTL_QTDPREV,
  SUM(TTL_QTDREAL) AS TTL_QTDREAL,
  NVL(ROUND((SUM(TTL_QTDREAL) / NULLIF(SUM(TTL_QTDPREV), 0)) * 100, 2), 0) AS TTL_PCT_QTD,
  SUM(TTL_VLR_PREV) AS TTL_VLR_PREV,
  SUM(TTL_VLR_REAL) AS TTL_VLR_REAL,
  NVL(ROUND((SUM(TTL_VLR_REAL) / NULLIF(SUM(TTL_VLR_PREV), 0)) * 100, 2), 0) AS TTL_PCT_VLR
FROM (
  WITH VEND AS (
    SELECT
      VEN.CODVEND,
      VEN.APELIDO AS VENDEDOR,
      VEN.CODGER,
      VEN1.APELIDO AS COORD
    FROM TGFVEN VEN
    INNER JOIN TGFVEN VEN1 ON VEN.CODGER = VEN1.CODVEND
  )
  SELECT
    CASE
      WHEN :P_AGRUP_COORDENADOR = 'S' THEN VEND.CODGER
      ELSE X.CODVEND
    END AS CODVEND,
    CASE
      WHEN :P_AGRUP_COORDENADOR = 'S' THEN VEND.COORD
      ELSE VEND.VENDEDOR
    END AS VENDEDOR,
    JUL_QTDPREV,
    JUL_QTDREAL,
    JUL_VLR_PREV,
    JUL_VLR_REAL,
    AGO_QTDPREV,
    AGO_QTDREAL,
    AGO_VLR_PREV,
    AGO_VLR_REAL,
    SET_QTDPREV,
    SET_QTDREAL,
    SET_VLR_PREV,
    SET_VLR_REAL,
    OUT_QTDPREV,
    OUT_QTDREAL,
    OUT_VLR_PREV,
    OUT_VLR_REAL,
    NOV_QTDPREV,
    NOV_QTDREAL,
    NOV_VLR_PREV,
    NOV_VLR_REAL,
    DEZ_QTDPREV,
    DEZ_QTDREAL,
    DEZ_VLR_PREV,
    DEZ_VLR_REAL,
    JAN_QTDPREV,
    JAN_QTDREAL,
    JAN_VLR_PREV,
    JAN_VLR_REAL,
    FEV_QTDPREV,
    FEV_QTDREAL,
    FEV_VLR_PREV,
    FEV_VLR_REAL,
    MAR_QTDPREV,
    MAR_QTDREAL,
    MAR_VLR_PREV,
    MAR_VLR_REAL,
    ABR_QTDPREV,
    ABR_QTDREAL,
    ABR_VLR_PREV,
    ABR_VLR_REAL,
    MAI_QTDPREV,
    MAI_QTDREAL,
    MAI_VLR_PREV,
    MAI_VLR_REAL,
    JUN_QTDPREV,
    JUN_QTDREAL,
    JUN_VLR_PREV,
    JUN_VLR_REAL,
    TTL_QTDPREV,
    TTL_QTDREAL,
    TTL_VLR_PREV,
    TTL_VLR_REAL
  FROM (
    SELECT
      T.*,
      (JUL_QTDPREV + AGO_QTDPREV + SET_QTDPREV + OUT_QTDPREV + NOV_QTDPREV + DEZ_QTDPREV + JAN_QTDPREV + FEV_QTDPREV + MAR_QTDPREV + ABR_QTDPREV + MAI_QTDPREV + JUN_QTDPREV) AS TTL_QTDPREV,
      (JUL_QTDREAL + AGO_QTDREAL + SET_QTDREAL + OUT_QTDREAL + NOV_QTDREAL + DEZ_QTDREAL + JAN_QTDREAL + FEV_QTDREAL + MAR_QTDREAL + ABR_QTDREAL + MAI_QTDREAL + JUN_QTDREAL) AS TTL_QTDREAL,
      (JUL_VLR_PREV + AGO_VLR_PREV + SET_VLR_PREV + OUT_VLR_PREV + NOV_VLR_PREV + DEZ_VLR_PREV + JAN_VLR_PREV + FEV_VLR_PREV + MAR_VLR_PREV + ABR_VLR_PREV + MAI_VLR_PREV + JUN_VLR_PREV) AS TTL_VLR_PREV,
      (JUL_VLR_REAL + AGO_VLR_REAL + SET_VLR_REAL + OUT_VLR_REAL + NOV_VLR_REAL + DEZ_VLR_REAL + JAN_VLR_REAL + FEV_VLR_REAL + MAR_VLR_REAL + ABR_VLR_REAL + MAI_VLR_REAL + JUN_VLR_REAL) AS TTL_VLR_REAL
    FROM (
      SELECT
        A.CODVEND,
        APELIDO,
        SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 7  AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.INI, 'YYYY') THEN QTDPREV ELSE 0 END) AS JUL_QTDPREV,
        SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 7  AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.INI, 'YYYY') THEN QTDREAL ELSE 0 END) AS JUL_QTDREAL,
        SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 7  AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.INI, 'YYYY') THEN (QTDPREV * PRECOLT) ELSE 0 END) AS JUL_VLR_PREV,
        SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 7  AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.INI, 'YYYY') THEN VLRREAL ELSE 0 END) AS JUL_VLR_REAL,
        SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 8  AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.INI, 'YYYY') THEN QTDPREV ELSE 0 END) AS AGO_QTDPREV,
        SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 8  AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.INI, 'YYYY') THEN QTDREAL ELSE 0 END) AS AGO_QTDREAL,
        SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 8  AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.INI, 'YYYY') THEN (QTDPREV * PRECOLT) ELSE 0 END) AS AGO_VLR_PREV,
        SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 8  AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.INI, 'YYYY') THEN VLRREAL ELSE 0 END) AS AGO_VLR_REAL,
        SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 9  AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.INI, 'YYYY') THEN QTDPREV ELSE 0 END) AS SET_QTDPREV,
        SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 9  AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.INI, 'YYYY') THEN QTDREAL ELSE 0 END) AS SET_QTDREAL,
        SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 9  AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.INI, 'YYYY') THEN (QTDPREV * PRECOLT) ELSE 0 END) AS SET_VLR_PREV,
        SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 9  AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.INI, 'YYYY') THEN VLRREAL ELSE 0 END) AS SET_VLR_REAL,
        SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 10 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.INI, 'YYYY') THEN QTDPREV ELSE 0 END) AS OUT_QTDPREV,
        SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 10 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.INI, 'YYYY') THEN QTDREAL ELSE 0 END) AS OUT_QTDREAL,
        SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 10 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.INI, 'YYYY') THEN (QTDPREV * PRECOLT) ELSE 0 END) AS OUT_VLR_PREV,
        SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 10 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.INI, 'YYYY') THEN VLRREAL ELSE 0 END) AS OUT_VLR_REAL,
        SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 11 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.INI, 'YYYY') THEN QTDPREV ELSE 0 END) AS NOV_QTDPREV,
        SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 11 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.INI, 'YYYY') THEN QTDREAL ELSE 0 END) AS NOV_QTDREAL,
        SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 11 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.INI, 'YYYY') THEN (QTDPREV * PRECOLT) ELSE 0 END) AS NOV_VLR_PREV,
        SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 11 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.INI, 'YYYY') THEN VLRREAL ELSE 0 END) AS NOV_VLR_REAL,
        SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 12 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.INI, 'YYYY') THEN QTDPREV ELSE 0 END) AS DEZ_QTDPREV,
        SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 12 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.INI, 'YYYY') THEN QTDREAL ELSE 0 END) AS DEZ_QTDREAL,
        SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 12 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.INI, 'YYYY') THEN (QTDPREV * PRECOLT) ELSE 0 END) AS DEZ_VLR_PREV,
        SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 12 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.INI, 'YYYY') THEN VLRREAL ELSE 0 END) AS DEZ_VLR_REAL,
        SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 1  AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.FIN, 'YYYY') THEN QTDPREV ELSE 0 END) AS JAN_QTDPREV,
        SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 1  AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.FIN, 'YYYY') THEN QTDREAL ELSE 0 END) AS JAN_QTDREAL,
        SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 1  AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.FIN, 'YYYY') THEN (QTDPREV * PRECOLT) ELSE 0 END) AS JAN_VLR_PREV,
        SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 1  AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.FIN, 'YYYY') THEN VLRREAL ELSE 0 END) AS JAN_VLR_REAL,
        SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 2  AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.FIN, 'YYYY') THEN QTDPREV ELSE 0 END) AS FEV_QTDPREV,
        SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 2  AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.FIN, 'YYYY') THEN QTDREAL ELSE 0 END) AS FEV_QTDREAL,
        SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 2  AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.FIN, 'YYYY') THEN (QTDPREV * PRECOLT) ELSE 0 END) AS FEV_VLR_PREV,
        SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 2  AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.FIN, 'YYYY') THEN VLRREAL ELSE 0 END) AS FEV_VLR_REAL,
        SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 3  AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.FIN, 'YYYY') THEN QTDPREV ELSE 0 END) AS MAR_QTDPREV,
        SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 3  AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.FIN, 'YYYY') THEN QTDREAL ELSE 0 END) AS MAR_QTDREAL,
        SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 3  AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.FIN, 'YYYY') THEN (QTDPREV * PRECOLT) ELSE 0 END) AS MAR_VLR_PREV,
        SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 3  AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.FIN, 'YYYY') THEN VLRREAL ELSE 0 END) AS MAR_VLR_REAL,
        SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 4  AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.FIN, 'YYYY') THEN QTDPREV ELSE 0 END) AS ABR_QTDPREV,
        SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 4  AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.FIN, 'YYYY') THEN QTDREAL ELSE 0 END) AS ABR_QTDREAL,
        SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 4  AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.FIN, 'YYYY') THEN (QTDPREV * PRECOLT) ELSE 0 END) AS ABR_VLR_PREV,
        SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 4  AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.FIN, 'YYYY') THEN VLRREAL ELSE 0 END) AS ABR_VLR_REAL,
        SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 5  AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.FIN, 'YYYY') THEN QTDPREV ELSE 0 END) AS MAI_QTDPREV,
        SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 5  AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.FIN, 'YYYY') THEN QTDREAL ELSE 0 END) AS MAI_QTDREAL,
        SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 5  AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.FIN, 'YYYY') THEN (QTDPREV * PRECOLT) ELSE 0 END) AS MAI_VLR_PREV,
        SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 5  AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.FIN, 'YYYY') THEN VLRREAL ELSE 0 END) AS MAI_VLR_REAL,
        SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 6  AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.FIN, 'YYYY') THEN QTDPREV ELSE 0 END) AS JUN_QTDPREV,
        SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 6  AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.FIN, 'YYYY') THEN QTDREAL ELSE 0 END) AS JUN_QTDREAL,
        SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 6  AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.FIN, 'YYYY') THEN (QTDPREV * PRECOLT) ELSE 0 END) AS JUN_VLR_PREV,
        SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 6  AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.FIN, 'YYYY') THEN VLRREAL ELSE 0 END) AS JUN_VLR_REAL
      FROM (
        SELECT
          MET.DTREF,
          NVL(MET.CODVEND, 0) AS CODVEND,
          NVL(MET.CODPARC, 0) AS CODPARC,
          NVL(MET.MARCA, 0) AS MARCA,
          NVL(VGF.CODCENCUS, 0) AS CODCENCUS,
          NVL(MET.QTDPREV, 0) AS QTDPREV,
          SUM(NVL(VGF.QTD, 0)) AS QTDREAL,
          NVL(PRC.VLRVENDALT, 0) AS PRECOLT,
          SUM(NVL(VGF.VLR, 0)) AS VLRREAL
        FROM TGFMET MET
        LEFT JOIN VGF_VENDAS_SATIS VGF ON MET.DTREF = TRUNC(VGF.DTMOV, 'MM')
          AND MET.CODVEND = VGF.CODVEND
          AND MET.CODPARC = VGF.CODPARC
          AND MET.MARCA = VGF.MARCA
          AND VGF.BONIFICACAO = 'N'
        LEFT JOIN AD_PRECOMARCA PRC ON MET.MARCA = PRC.MARCA
          AND PRC.CODMETA = MET.CODMETA
          AND PRC.DTREF = (
            SELECT MAX(DTREF)
            FROM AD_PRECOMARCA
            WHERE CODMETA = MET.CODMETA
              AND DTREF <= MET.DTREF
              AND MARCA = MET.MARCA
          )
        WHERE
          MET.CODMETA = :P_CODMETA
          AND MET.DTREF BETWEEN :P_PERIODO1.INI AND :P_PERIODO1.FIN
          AND ((:P_NTEMMETA = 'S' AND (MET.QTDPREV <> 0 OR MET.QTDREAL <> 0)) OR :P_NTEMMETA = 'N')
          AND (VGF.CODGRUPOPROD = :P_GRUPOPROD OR :P_GRUPOPROD IS NULL)
        GROUP BY
          MET.DTREF,
          NVL(MET.CODVEND, 0),
          NVL(MET.CODPARC, 0),
          NVL(MET.MARCA, 0),
          NVL(VGF.CODCENCUS, 0),
          NVL(MET.QTDPREV, 0),
          NVL(PRC.VLRVENDALT, 0)
      ) A
      INNER JOIN TGFPAR PAR ON A.CODPARC = PAR.CODPARC
      INNER JOIN TGFVEN VEN ON A.CODVEND = VEN.CODVEND
      WHERE
        (VEN.CODVEND IN :P_CODVEND)
        AND (VEN.CODGER IN :P_CODGER)
        AND (PAR.CODPARC = :P_CODPARC OR :P_CODPARC IS NULL)
        AND (A.MARCA = :A_MARCA)
        AND (A.CODCENCUS = :P_CR OR :P_CR IS NULL)
        AND (
          VEN.CODVEND = (SELECT CODVEND FROM TSIUSU WHERE CODUSU = STP_GET_CODUSULOGADO)
          OR VEN.CODVEND IN (
            SELECT VEN.CODVEND
            FROM TGFVEN VEN,
                 TSIUSU USU
            WHERE USU.CODVEND = VEN.CODGER
              AND USU.CODUSU = STP_GET_CODUSULOGADO
          )
          OR (SELECT AD_GESTOR_META FROM TSIUSU WHERE CODUSU = STP_GET_CODUSULOGADO) = 'S'
        )
      GROUP BY
        A.CODVEND,
        APELIDO
    ) T
  ) X
  INNER JOIN VEND ON X.CODVEND = VEND.CODVEND
)
GROUP BY CODVEND, VENDEDOR
ORDER BY 2;

