-- Query otimizada com percentual de atingimento da meta por MARCA
-- Calcula datas e valores uma vez para reutilização
-- Adiciona colunas de % de atingimento (realizado/meta * 100) para quantidade e valor
-- Focado em MARCA com dois períodos comparativos
WITH PERIODO_CALC AS (
    -- Calcula as datas do período 1 e anos uma única vez
    SELECT 
        TO_DATE(:P_PERIODO.INI) AS DATA_INI,
        TO_DATE(:P_PERIODO.FIN) AS DATA_FIN,
        TO_CHAR(:P_PERIODO.INI, 'YYYY') AS ANO_INI,
        TO_CHAR(:P_PERIODO.FIN, 'YYYY') AS ANO_FIN
    FROM DUAL
),
PERIODO1_CALC AS (
    -- Calcula as datas do período 2 e anos uma única vez
    SELECT 
        TO_DATE(:P_PERIODO1.INI) AS DATA_INI,
        TO_DATE(:P_PERIODO1.FIN) AS DATA_FIN,
        TO_CHAR(:P_PERIODO1.INI, 'YYYY') AS ANO_INI,
        TO_CHAR(:P_PERIODO1.FIN, 'YYYY') AS ANO_FIN
    FROM DUAL
),
MESES_DATAS AS (
    -- Calcula as datas de início de cada mês para ambos os anos do período 1
    SELECT 
        TO_DATE('01-07-' || ANO_INI, 'DD-MM-YYYY') AS JUL_DATA_INI,
        TO_DATE('01-07-' || ANO_FIN, 'DD-MM-YYYY') AS JUL_DATA_FIN,
        TO_DATE('01-08-' || ANO_INI, 'DD-MM-YYYY') AS AGO_DATA_INI,
        TO_DATE('01-08-' || ANO_FIN, 'DD-MM-YYYY') AS AGO_DATA_FIN,
        TO_DATE('01-09-' || ANO_INI, 'DD-MM-YYYY') AS SET_DATA_INI,
        TO_DATE('01-09-' || ANO_FIN, 'DD-MM-YYYY') AS SET_DATA_FIN,
        TO_DATE('01-10-' || ANO_INI, 'DD-MM-YYYY') AS OUT_DATA_INI,
        TO_DATE('01-10-' || ANO_FIN, 'DD-MM-YYYY') AS OUT_DATA_FIN,
        TO_DATE('01-11-' || ANO_INI, 'DD-MM-YYYY') AS NOV_DATA_INI,
        TO_DATE('01-11-' || ANO_FIN, 'DD-MM-YYYY') AS NOV_DATA_FIN,
        TO_DATE('01-12-' || ANO_INI, 'DD-MM-YYYY') AS DEZ_DATA_INI,
        TO_DATE('01-12-' || ANO_FIN, 'DD-MM-YYYY') AS DEZ_DATA_FIN,
        TO_DATE('01-01-' || ANO_INI, 'DD-MM-YYYY') AS JAN_DATA_INI,
        TO_DATE('01-01-' || ANO_FIN, 'DD-MM-YYYY') AS JAN_DATA_FIN,
        TO_DATE('01-02-' || ANO_INI, 'DD-MM-YYYY') AS FEV_DATA_INI,
        TO_DATE('01-02-' || ANO_FIN, 'DD-MM-YYYY') AS FEV_DATA_FIN,
        TO_DATE('01-03-' || ANO_INI, 'DD-MM-YYYY') AS MAR_DATA_INI,
        TO_DATE('01-03-' || ANO_FIN, 'DD-MM-YYYY') AS MAR_DATA_FIN,
        TO_DATE('01-04-' || ANO_INI, 'DD-MM-YYYY') AS ABR_DATA_INI,
        TO_DATE('01-04-' || ANO_FIN, 'DD-MM-YYYY') AS ABR_DATA_FIN,
        TO_DATE('01-05-' || ANO_INI, 'DD-MM-YYYY') AS MAI_DATA_INI,
        TO_DATE('01-05-' || ANO_FIN, 'DD-MM-YYYY') AS MAI_DATA_FIN,
        TO_DATE('01-06-' || ANO_INI, 'DD-MM-YYYY') AS JUN_DATA_INI,
        TO_DATE('01-06-' || ANO_FIN, 'DD-MM-YYYY') AS JUN_DATA_FIN,
        DATA_INI,
        DATA_FIN
    FROM PERIODO_CALC
)

SELECT
MARCA,PERIODO,
CASE WHEN MD.JUL_DATA_INI BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN JUL_QTDPREV
     WHEN MD.JUL_DATA_FIN BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN JUL_QTDPREV ELSE NULL END AS JUL_QTDPREV,
CASE WHEN MD.JUL_DATA_INI BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN JUL_QTDREAL
     WHEN MD.JUL_DATA_FIN BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN JUL_QTDREAL ELSE NULL END AS JUL_QTDREAL,
NVL(CASE WHEN MD.JUL_DATA_INI BETWEEN MD.DATA_INI AND MD.DATA_FIN OR MD.JUL_DATA_FIN BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN
     CASE WHEN NVL(JUL_QTDPREV, 0) > 0 THEN ROUND((NVL(JUL_QTDREAL, 0) / JUL_QTDPREV) * 100, 2) ELSE NULL END
     ELSE NULL END, 0) AS JUL_PCT_QTD,
CASE WHEN MD.JUL_DATA_INI BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN JUL_VLR_PREV
     WHEN MD.JUL_DATA_FIN BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN JUL_VLR_PREV ELSE NULL END AS JUL_VLR_PREV,
CASE WHEN MD.JUL_DATA_INI BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN JUL_VLR_REAL
     WHEN MD.JUL_DATA_FIN BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN JUL_VLR_REAL ELSE NULL END AS JUL_VLR_REAL,
NVL(CASE WHEN MD.JUL_DATA_INI BETWEEN MD.DATA_INI AND MD.DATA_FIN OR MD.JUL_DATA_FIN BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN
     CASE WHEN NVL(JUL_VLR_PREV, 0) > 0 THEN ROUND((NVL(JUL_VLR_REAL, 0) / JUL_VLR_PREV) * 100, 2) ELSE NULL END
     ELSE NULL END, 0) AS JUL_PCT_VLR,

CASE WHEN MD.AGO_DATA_INI BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN AGO_QTDPREV
     WHEN MD.AGO_DATA_FIN BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN AGO_QTDPREV ELSE NULL END AS AGO_QTDPREV,
CASE WHEN MD.AGO_DATA_INI BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN AGO_QTDREAL
     WHEN MD.AGO_DATA_FIN BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN AGO_QTDREAL ELSE NULL END AS AGO_QTDREAL,
NVL(CASE WHEN MD.AGO_DATA_INI BETWEEN MD.DATA_INI AND MD.DATA_FIN OR MD.AGO_DATA_FIN BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN
     CASE WHEN NVL(AGO_QTDPREV, 0) > 0 THEN ROUND((NVL(AGO_QTDREAL, 0) / AGO_QTDPREV) * 100, 2) ELSE NULL END
     ELSE NULL END, 0) AS AGO_PCT_QTD,
CASE WHEN MD.AGO_DATA_INI BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN AGO_VLR_PREV
     WHEN MD.AGO_DATA_FIN BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN AGO_VLR_PREV ELSE NULL END AS AGO_VLR_PREV,
CASE WHEN MD.AGO_DATA_INI BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN AGO_VLR_REAL
     WHEN MD.AGO_DATA_FIN BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN AGO_VLR_REAL ELSE NULL END AS AGO_VLR_REAL,
NVL(CASE WHEN MD.AGO_DATA_INI BETWEEN MD.DATA_INI AND MD.DATA_FIN OR MD.AGO_DATA_FIN BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN
     CASE WHEN NVL(AGO_VLR_PREV, 0) > 0 THEN ROUND((NVL(AGO_VLR_REAL, 0) / AGO_VLR_PREV) * 100, 2) ELSE NULL END
     ELSE NULL END, 0) AS AGO_PCT_VLR,

CASE WHEN MD.SET_DATA_INI BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN SET_QTDPREV
     WHEN MD.SET_DATA_FIN BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN SET_QTDPREV ELSE NULL END AS SET_QTDPREV,
CASE WHEN MD.SET_DATA_INI BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN SET_QTDREAL
     WHEN MD.SET_DATA_FIN BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN SET_QTDREAL ELSE NULL END AS SET_QTDREAL,
NVL(CASE WHEN MD.SET_DATA_INI BETWEEN MD.DATA_INI AND MD.DATA_FIN OR MD.SET_DATA_FIN BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN
     CASE WHEN NVL(SET_QTDPREV, 0) > 0 THEN ROUND((NVL(SET_QTDREAL, 0) / SET_QTDPREV) * 100, 2) ELSE NULL END
     ELSE NULL END, 0) AS SET_PCT_QTD,
CASE WHEN MD.SET_DATA_INI BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN SET_VLR_PREV
     WHEN MD.SET_DATA_FIN BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN SET_VLR_PREV ELSE NULL END AS SET_VLR_PREV,
CASE WHEN MD.SET_DATA_INI BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN SET_VLR_REAL
     WHEN MD.SET_DATA_FIN BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN SET_VLR_REAL ELSE NULL END AS SET_VLR_REAL,
NVL(CASE WHEN MD.SET_DATA_INI BETWEEN MD.DATA_INI AND MD.DATA_FIN OR MD.SET_DATA_FIN BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN
     CASE WHEN NVL(SET_VLR_PREV, 0) > 0 THEN ROUND((NVL(SET_VLR_REAL, 0) / SET_VLR_PREV) * 100, 2) ELSE NULL END
     ELSE NULL END, 0) AS SET_PCT_VLR,

CASE WHEN MD.OUT_DATA_INI BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN OUT_QTDPREV
     WHEN MD.OUT_DATA_FIN BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN OUT_QTDPREV ELSE NULL END AS OUT_QTDPREV,
CASE WHEN MD.OUT_DATA_INI BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN OUT_QTDREAL
     WHEN MD.OUT_DATA_FIN BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN OUT_QTDREAL ELSE NULL END AS OUT_QTDREAL,
NVL(CASE WHEN MD.OUT_DATA_INI BETWEEN MD.DATA_INI AND MD.DATA_FIN OR MD.OUT_DATA_FIN BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN
     CASE WHEN NVL(OUT_QTDPREV, 0) > 0 THEN ROUND((NVL(OUT_QTDREAL, 0) / OUT_QTDPREV) * 100, 2) ELSE NULL END
     ELSE NULL END, 0) AS OUT_PCT_QTD,
CASE WHEN MD.OUT_DATA_INI BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN OUT_VLR_PREV
     WHEN MD.OUT_DATA_FIN BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN OUT_VLR_PREV ELSE NULL END AS OUT_VLR_PREV,
CASE WHEN MD.OUT_DATA_INI BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN OUT_VLR_REAL
     WHEN MD.OUT_DATA_FIN BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN OUT_VLR_REAL ELSE NULL END AS OUT_VLR_REAL,
NVL(CASE WHEN MD.OUT_DATA_INI BETWEEN MD.DATA_INI AND MD.DATA_FIN OR MD.OUT_DATA_FIN BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN
     CASE WHEN NVL(OUT_VLR_PREV, 0) > 0 THEN ROUND((NVL(OUT_VLR_REAL, 0) / OUT_VLR_PREV) * 100, 2) ELSE NULL END
     ELSE NULL END, 0) AS OUT_PCT_VLR,

CASE WHEN MD.NOV_DATA_INI BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN NOV_QTDPREV
     WHEN MD.NOV_DATA_FIN BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN NOV_QTDPREV ELSE NULL END AS NOV_QTDPREV,
CASE WHEN MD.NOV_DATA_INI BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN NOV_QTDREAL
     WHEN MD.NOV_DATA_FIN BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN NOV_QTDREAL ELSE NULL END AS NOV_QTDREAL,
NVL(CASE WHEN MD.NOV_DATA_INI BETWEEN MD.DATA_INI AND MD.DATA_FIN OR MD.NOV_DATA_FIN BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN
     CASE WHEN NVL(NOV_QTDPREV, 0) > 0 THEN ROUND((NVL(NOV_QTDREAL, 0) / NOV_QTDPREV) * 100, 2) ELSE NULL END
     ELSE NULL END, 0) AS NOV_PCT_QTD,
CASE WHEN MD.NOV_DATA_INI BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN NOV_VLR_PREV
     WHEN MD.NOV_DATA_FIN BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN NOV_VLR_PREV ELSE NULL END AS NOV_VLR_PREV,
CASE WHEN MD.NOV_DATA_INI BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN NOV_VLR_REAL
     WHEN MD.NOV_DATA_FIN BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN NOV_VLR_REAL ELSE NULL END AS NOV_VLR_REAL,
NVL(CASE WHEN MD.NOV_DATA_INI BETWEEN MD.DATA_INI AND MD.DATA_FIN OR MD.NOV_DATA_FIN BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN
     CASE WHEN NVL(NOV_VLR_PREV, 0) > 0 THEN ROUND((NVL(NOV_VLR_REAL, 0) / NOV_VLR_PREV) * 100, 2) ELSE NULL END
     ELSE NULL END, 0) AS NOV_PCT_VLR,

CASE WHEN MD.DEZ_DATA_INI BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN DEZ_QTDPREV
     WHEN MD.DEZ_DATA_FIN BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN DEZ_QTDPREV ELSE NULL END AS DEZ_QTDPREV,
CASE WHEN MD.DEZ_DATA_INI BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN DEZ_QTDREAL
     WHEN MD.DEZ_DATA_FIN BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN DEZ_QTDREAL ELSE NULL END AS DEZ_QTDREAL,
NVL(CASE WHEN MD.DEZ_DATA_INI BETWEEN MD.DATA_INI AND MD.DATA_FIN OR MD.DEZ_DATA_FIN BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN
     CASE WHEN NVL(DEZ_QTDPREV, 0) > 0 THEN ROUND((NVL(DEZ_QTDREAL, 0) / DEZ_QTDPREV) * 100, 2) ELSE NULL END
     ELSE NULL END, 0) AS DEZ_PCT_QTD,
CASE WHEN MD.DEZ_DATA_INI BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN DEZ_VLR_PREV
     WHEN MD.DEZ_DATA_FIN BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN DEZ_VLR_PREV ELSE NULL END AS DEZ_VLR_PREV,
CASE WHEN MD.DEZ_DATA_INI BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN DEZ_VLR_REAL
     WHEN MD.DEZ_DATA_FIN BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN DEZ_VLR_REAL ELSE NULL END AS DEZ_VLR_REAL,
NVL(CASE WHEN MD.DEZ_DATA_INI BETWEEN MD.DATA_INI AND MD.DATA_FIN OR MD.DEZ_DATA_FIN BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN
     CASE WHEN NVL(DEZ_VLR_PREV, 0) > 0 THEN ROUND((NVL(DEZ_VLR_REAL, 0) / DEZ_VLR_PREV) * 100, 2) ELSE NULL END
     ELSE NULL END, 0) AS DEZ_PCT_VLR,

CASE WHEN MD.JAN_DATA_INI BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN JAN_QTDPREV
     WHEN MD.JAN_DATA_FIN BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN JAN_QTDPREV ELSE NULL END AS JAN_QTDPREV,
CASE WHEN MD.JAN_DATA_INI BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN JAN_QTDREAL
     WHEN MD.JAN_DATA_FIN BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN JAN_QTDREAL ELSE NULL END AS JAN_QTDREAL,
NVL(CASE WHEN MD.JAN_DATA_INI BETWEEN MD.DATA_INI AND MD.DATA_FIN OR MD.JAN_DATA_FIN BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN
     CASE WHEN NVL(JAN_QTDPREV, 0) > 0 THEN ROUND((NVL(JAN_QTDREAL, 0) / JAN_QTDPREV) * 100, 2) ELSE NULL END
     ELSE NULL END, 0) AS JAN_PCT_QTD,
CASE WHEN MD.JAN_DATA_INI BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN JAN_VLR_PREV
     WHEN MD.JAN_DATA_FIN BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN JAN_VLR_PREV ELSE NULL END AS JAN_VLR_PREV,
CASE WHEN MD.JAN_DATA_INI BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN JAN_VLR_REAL
     WHEN MD.JAN_DATA_FIN BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN JAN_VLR_REAL ELSE NULL END AS JAN_VLR_REAL,
NVL(CASE WHEN MD.JAN_DATA_INI BETWEEN MD.DATA_INI AND MD.DATA_FIN OR MD.JAN_DATA_FIN BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN
     CASE WHEN NVL(JAN_VLR_PREV, 0) > 0 THEN ROUND((NVL(JAN_VLR_REAL, 0) / JAN_VLR_PREV) * 100, 2) ELSE NULL END
     ELSE NULL END, 0) AS JAN_PCT_VLR,

CASE WHEN MD.FEV_DATA_INI BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN FEV_QTDPREV
     WHEN MD.FEV_DATA_FIN BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN FEV_QTDPREV ELSE NULL END AS FEV_QTDPREV,
CASE WHEN MD.FEV_DATA_INI BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN FEV_QTDREAL
     WHEN MD.FEV_DATA_FIN BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN FEV_QTDREAL ELSE NULL END AS FEV_QTDREAL,
NVL(CASE WHEN MD.FEV_DATA_INI BETWEEN MD.DATA_INI AND MD.DATA_FIN OR MD.FEV_DATA_FIN BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN
     CASE WHEN NVL(FEV_QTDPREV, 0) > 0 THEN ROUND((NVL(FEV_QTDREAL, 0) / FEV_QTDPREV) * 100, 2) ELSE NULL END
     ELSE NULL END, 0) AS FEV_PCT_QTD,
CASE WHEN MD.FEV_DATA_INI BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN FEV_VLR_PREV
     WHEN MD.FEV_DATA_FIN BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN FEV_VLR_PREV ELSE NULL END AS FEV_VLR_PREV,
CASE WHEN MD.FEV_DATA_INI BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN FEV_VLR_REAL
     WHEN MD.FEV_DATA_FIN BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN FEV_VLR_REAL ELSE NULL END AS FEV_VLR_REAL,
NVL(CASE WHEN MD.FEV_DATA_INI BETWEEN MD.DATA_INI AND MD.DATA_FIN OR MD.FEV_DATA_FIN BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN
     CASE WHEN NVL(FEV_VLR_PREV, 0) > 0 THEN ROUND((NVL(FEV_VLR_REAL, 0) / FEV_VLR_PREV) * 100, 2) ELSE NULL END
     ELSE NULL END, 0) AS FEV_PCT_VLR,

CASE WHEN MD.MAR_DATA_INI BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN MAR_QTDPREV
     WHEN MD.MAR_DATA_FIN BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN MAR_QTDPREV ELSE NULL END AS MAR_QTDPREV,
CASE WHEN MD.MAR_DATA_INI BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN MAR_QTDREAL
     WHEN MD.MAR_DATA_FIN BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN MAR_QTDREAL ELSE NULL END AS MAR_QTDREAL,
NVL(CASE WHEN MD.MAR_DATA_INI BETWEEN MD.DATA_INI AND MD.DATA_FIN OR MD.MAR_DATA_FIN BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN
     CASE WHEN NVL(MAR_QTDPREV, 0) > 0 THEN ROUND((NVL(MAR_QTDREAL, 0) / MAR_QTDPREV) * 100, 2) ELSE NULL END
     ELSE NULL END, 0) AS MAR_PCT_QTD,
CASE WHEN MD.MAR_DATA_INI BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN MAR_VLR_PREV
     WHEN MD.MAR_DATA_FIN BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN MAR_VLR_PREV ELSE NULL END AS MAR_VLR_PREV,
CASE WHEN MD.MAR_DATA_INI BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN MAR_VLR_REAL
     WHEN MD.MAR_DATA_FIN BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN MAR_VLR_REAL ELSE NULL END AS MAR_VLR_REAL,
NVL(CASE WHEN MD.MAR_DATA_INI BETWEEN MD.DATA_INI AND MD.DATA_FIN OR MD.MAR_DATA_FIN BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN
     CASE WHEN NVL(MAR_VLR_PREV, 0) > 0 THEN ROUND((NVL(MAR_VLR_REAL, 0) / MAR_VLR_PREV) * 100, 2) ELSE NULL END
     ELSE NULL END, 0) AS MAR_PCT_VLR,

CASE WHEN MD.ABR_DATA_INI BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN ABR_QTDPREV
     WHEN MD.ABR_DATA_FIN BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN ABR_QTDPREV ELSE NULL END AS ABR_QTDPREV,
CASE WHEN MD.ABR_DATA_INI BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN ABR_QTDREAL
     WHEN MD.ABR_DATA_FIN BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN ABR_QTDREAL ELSE NULL END AS ABR_QTDREAL,
NVL(CASE WHEN MD.ABR_DATA_INI BETWEEN MD.DATA_INI AND MD.DATA_FIN OR MD.ABR_DATA_FIN BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN
     CASE WHEN NVL(ABR_QTDPREV, 0) > 0 THEN ROUND((NVL(ABR_QTDREAL, 0) / ABR_QTDPREV) * 100, 2) ELSE NULL END
     ELSE NULL END, 0) AS ABR_PCT_QTD,
CASE WHEN MD.ABR_DATA_INI BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN ABR_VLR_PREV
     WHEN MD.ABR_DATA_FIN BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN ABR_VLR_PREV ELSE NULL END AS ABR_VLR_PREV,
CASE WHEN MD.ABR_DATA_INI BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN ABR_VLR_REAL
     WHEN MD.ABR_DATA_FIN BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN ABR_VLR_REAL ELSE NULL END AS ABR_VLR_REAL,
NVL(CASE WHEN MD.ABR_DATA_INI BETWEEN MD.DATA_INI AND MD.DATA_FIN OR MD.ABR_DATA_FIN BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN
     CASE WHEN NVL(ABR_VLR_PREV, 0) > 0 THEN ROUND((NVL(ABR_VLR_REAL, 0) / ABR_VLR_PREV) * 100, 2) ELSE NULL END
     ELSE NULL END, 0) AS ABR_PCT_VLR,

CASE WHEN MD.MAI_DATA_INI BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN MAI_QTDPREV
     WHEN MD.MAI_DATA_FIN BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN MAI_QTDPREV ELSE NULL END AS MAI_QTDPREV,
CASE WHEN MD.MAI_DATA_INI BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN MAI_QTDREAL
     WHEN MD.MAI_DATA_FIN BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN MAI_QTDREAL ELSE NULL END AS MAI_QTDREAL,
NVL(CASE WHEN MD.MAI_DATA_INI BETWEEN MD.DATA_INI AND MD.DATA_FIN OR MD.MAI_DATA_FIN BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN
     CASE WHEN NVL(MAI_QTDPREV, 0) > 0 THEN ROUND((NVL(MAI_QTDREAL, 0) / MAI_QTDPREV) * 100, 2) ELSE NULL END
     ELSE NULL END, 0) AS MAI_PCT_QTD,
CASE WHEN MD.MAI_DATA_INI BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN MAI_VLR_PREV
     WHEN MD.MAI_DATA_FIN BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN MAI_VLR_PREV ELSE NULL END AS MAI_VLR_PREV,
CASE WHEN MD.MAI_DATA_INI BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN MAI_VLR_REAL
     WHEN MD.MAI_DATA_FIN BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN MAI_VLR_REAL ELSE NULL END AS MAI_VLR_REAL,
NVL(CASE WHEN MD.MAI_DATA_INI BETWEEN MD.DATA_INI AND MD.DATA_FIN OR MD.MAI_DATA_FIN BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN
     CASE WHEN NVL(MAI_VLR_PREV, 0) > 0 THEN ROUND((NVL(MAI_VLR_REAL, 0) / MAI_VLR_PREV) * 100, 2) ELSE NULL END
     ELSE NULL END, 0) AS MAI_PCT_VLR,

CASE WHEN MD.JUN_DATA_INI BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN JUN_QTDPREV
     WHEN MD.JUN_DATA_FIN BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN JUN_QTDPREV ELSE NULL END AS JUN_QTDPREV,
CASE WHEN MD.JUN_DATA_INI BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN JUN_QTDREAL
     WHEN MD.JUN_DATA_FIN BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN JUN_QTDREAL ELSE NULL END AS JUN_QTDREAL,
NVL(CASE WHEN MD.JUN_DATA_INI BETWEEN MD.DATA_INI AND MD.DATA_FIN OR MD.JUN_DATA_FIN BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN
     CASE WHEN NVL(JUN_QTDPREV, 0) > 0 THEN ROUND((NVL(JUN_QTDREAL, 0) / JUN_QTDPREV) * 100, 2) ELSE NULL END
     ELSE NULL END, 0) AS JUN_PCT_QTD,
CASE WHEN MD.JUN_DATA_INI BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN JUN_VLR_PREV
     WHEN MD.JUN_DATA_FIN BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN JUN_VLR_PREV ELSE NULL END AS JUN_VLR_PREV,
CASE WHEN MD.JUN_DATA_INI BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN JUN_VLR_REAL
     WHEN MD.JUN_DATA_FIN BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN JUN_VLR_REAL ELSE NULL END AS JUN_VLR_REAL,
NVL(CASE WHEN MD.JUN_DATA_INI BETWEEN MD.DATA_INI AND MD.DATA_FIN OR MD.JUN_DATA_FIN BETWEEN MD.DATA_INI AND MD.DATA_FIN THEN
     CASE WHEN NVL(JUN_VLR_PREV, 0) > 0 THEN ROUND((NVL(JUN_VLR_REAL, 0) / JUN_VLR_PREV) * 100, 2) ELSE NULL END
     ELSE NULL END, 0) AS JUN_PCT_VLR,

(CASE WHEN SUBSTR(PERIODO, 1, 9) = 'Periodo 2' THEN '#feffed' ELSE '#acfd96' END) AS BKCOLOR,
TTL_QTDPREV,TTL_QTDREAL,TTL_VLR_PREV,TTL_VLR_REAL,
NVL(CASE WHEN NVL(TTL_QTDPREV, 0) > 0 THEN ROUND((NVL(TTL_QTDREAL, 0) / TTL_QTDPREV) * 100, 2) ELSE NULL END, 0) AS TTL_PCT_QTD,
NVL(CASE WHEN NVL(TTL_VLR_PREV, 0) > 0 THEN ROUND((NVL(TTL_VLR_REAL, 0) / TTL_VLR_PREV) * 100, 2) ELSE NULL END, 0) AS TTL_PCT_VLR

FROM
(

SELECT
MARCA, 'Periodo 1: de '||:P_PERIODO.INI||' até '||:P_PERIODO.FIN AS PERIODO,SUM(JUL_QTDPREV) AS JUL_QTDPREV, SUM(JUL_QTDREAL) AS JUL_QTDREAL,  SUM(JUL_VLR_PREV) AS JUL_VLR_PREV, SUM(JUL_VLR_REAL) AS JUL_VLR_REAL, SUM(AGO_QTDPREV) AS AGO_QTDPREV, SUM(AGO_QTDREAL) AS AGO_QTDREAL, SUM(AGO_VLR_PREV) AS AGO_VLR_PREV, SUM(AGO_VLR_REAL) AS AGO_VLR_REAL, SUM(SET_QTDPREV) AS SET_QTDPREV, SUM(SET_QTDREAL) AS SET_QTDREAL, SUM(SET_VLR_PREV) AS SET_VLR_PREV, SUM(SET_VLR_REAL) AS SET_VLR_REAL, SUM(OUT_QTDPREV) AS OUT_QTDPREV, SUM(OUT_QTDREAL) AS OUT_QTDREAL, SUM(OUT_VLR_PREV) AS OUT_VLR_PREV, SUM(OUT_VLR_REAL) AS OUT_VLR_REAL, SUM(NOV_QTDPREV) AS NOV_QTDPREV, SUM(NOV_QTDREAL) AS NOV_QTDREAL, SUM(NOV_VLR_PREV) AS NOV_VLR_PREV, SUM(NOV_VLR_REAL) AS NOV_VLR_REAL, SUM(DEZ_QTDPREV) AS DEZ_QTDPREV, SUM(DEZ_QTDREAL) AS DEZ_QTDREAL, SUM(DEZ_VLR_PREV) AS DEZ_VLR_PREV, SUM(DEZ_VLR_REAL) AS DEZ_VLR_REAL, SUM(JAN_QTDPREV) AS JAN_QTDPREV, SUM(JAN_QTDREAL) AS JAN_QTDREAL, SUM(JAN_VLR_PREV) AS JAN_VLR_PREV, SUM(JAN_VLR_REAL) AS JAN_VLR_REAL, SUM(FEV_QTDPREV) AS FEV_QTDPREV, SUM(FEV_QTDREAL) AS FEV_QTDREAL, SUM(FEV_VLR_PREV) AS FEV_VLR_PREV, SUM(FEV_VLR_REAL) AS FEV_VLR_REAL, SUM(MAR_QTDPREV) AS MAR_QTDPREV, SUM(MAR_QTDREAL) AS MAR_QTDREAL, SUM(MAR_VLR_PREV) AS MAR_VLR_PREV, SUM(MAR_VLR_REAL) AS MAR_VLR_REAL, SUM(ABR_QTDPREV) AS ABR_QTDPREV, SUM(ABR_QTDREAL) AS ABR_QTDREAL, SUM(ABR_VLR_PREV) AS ABR_VLR_PREV, SUM(ABR_VLR_REAL) AS ABR_VLR_REAL, SUM(MAI_QTDPREV) AS MAI_QTDPREV, SUM(MAI_QTDREAL) AS MAI_QTDREAL, SUM(MAI_VLR_PREV) AS MAI_VLR_PREV, SUM(MAI_VLR_REAL) AS MAI_VLR_REAL, SUM(JUN_QTDPREV) AS JUN_QTDPREV, SUM(JUN_QTDREAL) AS JUN_QTDREAL, SUM(JUN_VLR_PREV) AS JUN_VLR_PREV, SUM(JUN_VLR_REAL) AS JUN_VLR_REAL, SUM(TTL_QTDPREV) AS TTL_QTDPREV, SUM(TTL_QTDREAL) AS TTL_QTDREAL, SUM(TTL_VLR_PREV) AS TTL_VLR_PREV, SUM(TTL_VLR_REAL) AS TTL_VLR_REAL 

FROM
(
SELECT
T.*,
(JUL_QTDPREV + AGO_QTDPREV + SET_QTDPREV + OUT_QTDPREV+NOV_QTDPREV+DEZ_QTDPREV+JAN_QTDPREV+FEV_QTDPREV+MAR_QTDPREV+ABR_QTDPREV+MAI_QTDPREV+JUN_QTDPREV) AS TTL_QTDPREV,
(JUL_QTDREAL + AGO_QTDREAL + SET_QTDREAL + OUT_QTDREAL+NOV_QTDREAL+DEZ_QTDREAL+JAN_QTDREAL+FEV_QTDREAL+MAR_QTDREAL+ABR_QTDREAL+MAI_QTDREAL+JUN_QTDREAL) AS TTL_QTDREAL,
(JUL_VLR_PREV + AGO_VLR_PREV + SET_VLR_PREV + OUT_VLR_PREV+NOV_VLR_PREV+DEZ_VLR_PREV+JAN_VLR_PREV+FEV_VLR_PREV+MAR_VLR_PREV+ABR_VLR_PREV+MAI_VLR_PREV+JUN_VLR_PREV) AS TTL_VLR_PREV,
(JUL_VLR_REAL + AGO_VLR_REAL + SET_VLR_REAL + OUT_VLR_REAL+NOV_VLR_REAL+DEZ_VLR_REAL+JAN_VLR_REAL+FEV_VLR_REAL+MAR_VLR_REAL+ABR_VLR_REAL+MAI_VLR_REAL+JUN_VLR_REAL) AS TTL_VLR_REAL



FROM (

SELECT 
A.MARCA,

SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 7 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN QTDPREV ELSE 0 END) AS JUL_QTDPREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 7 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN QTDREAL ELSE 0 END) AS JUL_QTDREAL,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 7 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN (QTDPREV * PRECOLT) ELSE 0 END) AS JUL_VLR_PREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 7 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN (VLRREAL) ELSE 0 END) AS JUL_VLR_REAL,

SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 8 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN QTDPREV ELSE 0 END) AS AGO_QTDPREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 8 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN QTDREAL ELSE 0 END) AS AGO_QTDREAL,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 8 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN (QTDPREV * PRECOLT) ELSE 0 END) AS AGO_VLR_PREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 8 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN (VLRREAL) ELSE 0 END) AS AGO_VLR_REAL,

SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 9 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN QTDPREV ELSE 0 END) AS SET_QTDPREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 9 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN QTDREAL ELSE 0 END) AS SET_QTDREAL,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 9 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN (QTDPREV * PRECOLT) ELSE 0 END) AS SET_VLR_PREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 9 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN (VLRREAL) ELSE 0 END) AS SET_VLR_REAL,

SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 10 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN QTDPREV ELSE 0 END) AS OUT_QTDPREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 10 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN QTDREAL ELSE 0 END) AS OUT_QTDREAL,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 10 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN (QTDPREV * PRECOLT) ELSE 0 END) AS OUT_VLR_PREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 10 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN (VLRREAL) ELSE 0 END) AS OUT_VLR_REAL,

SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 11 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN QTDPREV ELSE 0 END) AS NOV_QTDPREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 11 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN QTDREAL ELSE 0 END) AS NOV_QTDREAL,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 11 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN (QTDPREV * PRECOLT) ELSE 0 END) AS NOV_VLR_PREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 11 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN (VLRREAL) ELSE 0 END) AS NOV_VLR_REAL,

SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 12 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN QTDPREV ELSE 0 END) AS DEZ_QTDPREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 12 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN QTDREAL ELSE 0 END) AS DEZ_QTDREAL,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 12 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN (QTDPREV * PRECOLT) ELSE 0 END) AS DEZ_VLR_PREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 12 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN (VLRREAL) ELSE 0 END) AS DEZ_VLR_REAL,

SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 1 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN QTDPREV ELSE 0 END) AS JAN_QTDPREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 1 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN QTDREAL ELSE 0 END) AS JAN_QTDREAL,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 1 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN (QTDPREV * PRECOLT) ELSE 0 END) AS JAN_VLR_PREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 1 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN (VLRREAL) ELSE 0 END) AS JAN_VLR_REAL,

SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 2 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN QTDPREV ELSE 0 END) AS FEV_QTDPREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 2 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN QTDREAL ELSE 0 END) AS FEV_QTDREAL,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 2 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN (QTDPREV * PRECOLT) ELSE 0 END) AS FEV_VLR_PREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 2 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN (VLRREAL) ELSE 0 END) AS FEV_VLR_REAL,

SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 3 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN QTDPREV ELSE 0 END) AS MAR_QTDPREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 3 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN QTDREAL ELSE 0 END) AS MAR_QTDREAL,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 3 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN (QTDPREV * PRECOLT) ELSE 0 END) AS MAR_VLR_PREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 3 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN (VLRREAL) ELSE 0 END) AS MAR_VLR_REAL,

SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 4 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN QTDPREV ELSE 0 END) AS ABR_QTDPREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 4 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN QTDREAL ELSE 0 END) AS ABR_QTDREAL,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 4 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN (QTDPREV * PRECOLT) ELSE 0 END) AS ABR_VLR_PREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 4 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN (VLRREAL) ELSE 0 END) AS ABR_VLR_REAL,

SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 5 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN QTDPREV ELSE 0 END) AS MAI_QTDPREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 5 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN QTDREAL ELSE 0 END) AS MAI_QTDREAL,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 5 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN (QTDPREV * PRECOLT) ELSE 0 END) AS MAI_VLR_PREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 5 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN (VLRREAL) ELSE 0 END) AS MAI_VLR_REAL,

SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 6 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN QTDPREV ELSE 0 END) AS JUN_QTDPREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 6 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN QTDREAL ELSE 0 END) AS JUN_QTDREAL,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 6 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN (QTDPREV * PRECOLT) ELSE 0 END) AS JUN_VLR_PREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 6 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN (VLRREAL) ELSE 0 END) AS JUN_VLR_REAL

FROM
(
SELECT MET.DTREF, NVL(MET.CODVEND,0) AS CODVEND, NVL(MET.CODPARC,0) AS CODPARC, NVL(MET.MARCA,0) AS MARCA,NVL(VGF.CODCENCUS,0) AS CODCENCUS, NVL(MET.QTDPREV,0) AS QTDPREV, SUM(NVL(VGF.QTD,0)) AS QTDREAL,NVL(PRC.VLRVENDALT,0)AS PRECOLT, SUM(NVL(VGF.VLR,0)) AS VLRREAL
FROM TGFMET MET
LEFT JOIN VGF_VENDAS_SATIS VGF ON MET.DTREF = TRUNC(VGF.DTMOV,'MM') AND MET.CODVEND = VGF.CODVEND AND MET.CODPARC = VGF.CODPARC AND MET.MARCA = VGF.MARCA AND VGF.BONIFICACAO = 'N'
LEFT JOIN AD_PRECOMARCA PRC ON (MET.MARCA = PRC.MARCA AND PRC.CODMETA = MET.CODMETA AND PRC.DTREF = (SELECT MAX(DTREF) FROM AD_PRECOMARCA WHERE CODMETA = MET.CODMETA AND DTREF <= MET.DTREF AND MARCA = MET.MARCA))
WHERE 
MET.CODMETA = :P_CODMETA
AND MET.DTREF BETWEEN :P_PERIODO.INI   AND  :P_PERIODO.FIN

AND (VGF.CODGRUPOPROD = :P_GRUPOPROD OR :P_GRUPOPROD IS NULL)

GROUP BY MET.DTREF,NVL(MET.CODVEND,0),NVL(MET.CODPARC,0),NVL(MET.MARCA,0),NVL(VGF.CODCENCUS,0), NVL(MET.QTDPREV,0), NVL(PRC.VLRVENDALT,0)



)A
INNER JOIN TGFPAR PAR ON A.CODPARC = PAR.CODPARC
INNER JOIN TGFVEN VEN ON A.CODVEND = VEN.CODVEND
WHERE
(VEN.CODVEND IN :P_CODVEND)
AND (VEN.CODGER IN :P_CODGER)
AND (PAR.CODPARC = :P_CODPARC OR :P_CODPARC IS NULL)
AND (A.MARCA IN (SELECT MARCA FROM TGFPRO WHERE CODPROD IN :P_MARCA))
AND (A.CODCENCUS = :P_CR OR :P_CR IS NULL)
AND
(
VEN.CODVEND = (SELECT CODVEND FROM TSIUSU WHERE CODUSU = STP_GET_CODUSULOGADO) ---CONSULTA VENDEDOR
OR VEN.CODVEND IN (SELECT VEN.CODVEND FROM TGFVEN VEN, TSIUSU USU WHERE USU.CODVEND = VEN.CODGER AND USU.CODUSU = STP_GET_CODUSULOGADO) ---CONSULTA GERENTE
OR (SELECT AD_GESTOR_META FROM TSIUSU WHERE CODUSU = STP_GET_CODUSULOGADO) = 'S' ---CONSULTA MASTER
)
GROUP BY A.MARCA)T
)
GROUP BY MARCA

UNION ALL

SELECT
MARCA, 'Periodo 2: de '||:P_PERIODO1.INI||' até '||:P_PERIODO1.FIN AS PERIODO,SUM(JUL_QTDPREV) AS JUL_QTDPREV, SUM(JUL_QTDREAL) AS JUL_QTDREAL,  SUM(JUL_VLR_PREV) AS JUL_VLR_PREV, SUM(JUL_VLR_REAL) AS JUL_VLR_REAL, SUM(AGO_QTDPREV) AS AGO_QTDPREV, SUM(AGO_QTDREAL) AS AGO_QTDREAL, SUM(AGO_VLR_PREV) AS AGO_VLR_PREV, SUM(AGO_VLR_REAL) AS AGO_VLR_REAL, SUM(SET_QTDPREV) AS SET_QTDPREV, SUM(SET_QTDREAL) AS SET_QTDREAL, SUM(SET_VLR_PREV) AS SET_VLR_PREV, SUM(SET_VLR_REAL) AS SET_VLR_REAL, SUM(OUT_QTDPREV) AS OUT_QTDPREV, SUM(OUT_QTDREAL) AS OUT_QTDREAL, SUM(OUT_VLR_PREV) AS OUT_VLR_PREV, SUM(OUT_VLR_REAL) AS OUT_VLR_REAL, SUM(NOV_QTDPREV) AS NOV_QTDPREV, SUM(NOV_QTDREAL) AS NOV_QTDREAL, SUM(NOV_VLR_PREV) AS NOV_VLR_PREV, SUM(NOV_VLR_REAL) AS NOV_VLR_REAL, SUM(DEZ_QTDPREV) AS DEZ_QTDPREV, SUM(DEZ_QTDREAL) AS DEZ_QTDREAL, SUM(DEZ_VLR_PREV) AS DEZ_VLR_PREV, SUM(DEZ_VLR_REAL) AS DEZ_VLR_REAL, SUM(JAN_QTDPREV) AS JAN_QTDPREV, SUM(JAN_QTDREAL) AS JAN_QTDREAL, SUM(JAN_VLR_PREV) AS JAN_VLR_PREV, SUM(JAN_VLR_REAL) AS JAN_VLR_REAL, SUM(FEV_QTDPREV) AS FEV_QTDPREV, SUM(FEV_QTDREAL) AS FEV_QTDREAL, SUM(FEV_VLR_PREV) AS FEV_VLR_PREV, SUM(FEV_VLR_REAL) AS FEV_VLR_REAL, SUM(MAR_QTDPREV) AS MAR_QTDPREV, SUM(MAR_QTDREAL) AS MAR_QTDREAL, SUM(MAR_VLR_PREV) AS MAR_VLR_PREV, SUM(MAR_VLR_REAL) AS MAR_VLR_REAL, SUM(ABR_QTDPREV) AS ABR_QTDPREV, SUM(ABR_QTDREAL) AS ABR_QTDREAL, SUM(ABR_VLR_PREV) AS ABR_VLR_PREV, SUM(ABR_VLR_REAL) AS ABR_VLR_REAL, SUM(MAI_QTDPREV) AS MAI_QTDPREV, SUM(MAI_QTDREAL) AS MAI_QTDREAL, SUM(MAI_VLR_PREV) AS MAI_VLR_PREV, SUM(MAI_VLR_REAL) AS MAI_VLR_REAL, SUM(JUN_QTDPREV) AS JUN_QTDPREV, SUM(JUN_QTDREAL) AS JUN_QTDREAL, SUM(JUN_VLR_PREV) AS JUN_VLR_PREV, SUM(JUN_VLR_REAL) AS JUN_VLR_REAL, SUM(TTL_QTDPREV) AS TTL_QTDPREV, SUM(TTL_QTDREAL) AS TTL_QTDREAL, SUM(TTL_VLR_PREV) AS TTL_VLR_PREV, SUM(TTL_VLR_REAL) AS TTL_VLR_REAL 

FROM
(
SELECT
T.*,
(JUL_QTDPREV + AGO_QTDPREV + SET_QTDPREV + OUT_QTDPREV+NOV_QTDPREV+DEZ_QTDPREV+JAN_QTDPREV+FEV_QTDPREV+MAR_QTDPREV+ABR_QTDPREV+MAI_QTDPREV+JUN_QTDPREV) AS TTL_QTDPREV,
(JUL_QTDREAL + AGO_QTDREAL + SET_QTDREAL + OUT_QTDREAL+NOV_QTDREAL+DEZ_QTDREAL+JAN_QTDREAL+FEV_QTDREAL+MAR_QTDREAL+ABR_QTDREAL+MAI_QTDREAL+JUN_QTDREAL) AS TTL_QTDREAL,
(JUL_VLR_PREV + AGO_VLR_PREV + SET_VLR_PREV + OUT_VLR_PREV+NOV_VLR_PREV+DEZ_VLR_PREV+JAN_VLR_PREV+FEV_VLR_PREV+MAR_VLR_PREV+ABR_VLR_PREV+MAI_VLR_PREV+JUN_VLR_PREV) AS TTL_VLR_PREV,
(JUL_VLR_REAL + AGO_VLR_REAL + SET_VLR_REAL + OUT_VLR_REAL+NOV_VLR_REAL+DEZ_VLR_REAL+JAN_VLR_REAL+FEV_VLR_REAL+MAR_VLR_REAL+ABR_VLR_REAL+MAI_VLR_REAL+JUN_VLR_REAL) AS TTL_VLR_REAL



FROM (

SELECT 
A.MARCA,

SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 7 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.INI, 'YYYY') THEN QTDPREV ELSE 0 END) AS JUL_QTDPREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 7 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.INI, 'YYYY') THEN QTDREAL ELSE 0 END) AS JUL_QTDREAL,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 7 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.INI, 'YYYY') THEN (QTDPREV * PRECOLT) ELSE 0 END) AS JUL_VLR_PREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 7 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.INI, 'YYYY') THEN (VLRREAL) ELSE 0 END) AS JUL_VLR_REAL,

SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 8 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.INI, 'YYYY') THEN QTDPREV ELSE 0 END) AS AGO_QTDPREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 8 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.INI, 'YYYY') THEN QTDREAL ELSE 0 END) AS AGO_QTDREAL,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 8 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.INI, 'YYYY') THEN (QTDPREV * PRECOLT) ELSE 0 END) AS AGO_VLR_PREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 8 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.INI, 'YYYY') THEN (VLRREAL) ELSE 0 END) AS AGO_VLR_REAL,

SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 9 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.INI, 'YYYY') THEN QTDPREV ELSE 0 END) AS SET_QTDPREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 9 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.INI, 'YYYY') THEN QTDREAL ELSE 0 END) AS SET_QTDREAL,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 9 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.INI, 'YYYY') THEN (QTDPREV * PRECOLT) ELSE 0 END) AS SET_VLR_PREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 9 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.INI, 'YYYY') THEN (VLRREAL) ELSE 0 END) AS SET_VLR_REAL,

SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 10 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.INI, 'YYYY') THEN QTDPREV ELSE 0 END) AS OUT_QTDPREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 10 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.INI, 'YYYY') THEN QTDREAL ELSE 0 END) AS OUT_QTDREAL,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 10 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.INI, 'YYYY') THEN (QTDPREV * PRECOLT) ELSE 0 END) AS OUT_VLR_PREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 10 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.INI, 'YYYY') THEN (VLRREAL) ELSE 0 END) AS OUT_VLR_REAL,

SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 11 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.INI, 'YYYY') THEN QTDPREV ELSE 0 END) AS NOV_QTDPREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 11 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.INI, 'YYYY') THEN QTDREAL ELSE 0 END) AS NOV_QTDREAL,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 11 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.INI, 'YYYY') THEN (QTDPREV * PRECOLT) ELSE 0 END) AS NOV_VLR_PREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 11 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.INI, 'YYYY') THEN (VLRREAL) ELSE 0 END) AS NOV_VLR_REAL,

SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 12 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.INI, 'YYYY') THEN QTDPREV ELSE 0 END) AS DEZ_QTDPREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 12 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.INI, 'YYYY') THEN QTDREAL ELSE 0 END) AS DEZ_QTDREAL,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 12 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.INI, 'YYYY') THEN (QTDPREV * PRECOLT) ELSE 0 END) AS DEZ_VLR_PREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 12 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.INI, 'YYYY') THEN (VLRREAL) ELSE 0 END) AS DEZ_VLR_REAL,

SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 1 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.FIN, 'YYYY') THEN QTDPREV ELSE 0 END) AS JAN_QTDPREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 1 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.FIN, 'YYYY') THEN QTDREAL ELSE 0 END) AS JAN_QTDREAL,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 1 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.FIN, 'YYYY') THEN (QTDPREV * PRECOLT) ELSE 0 END) AS JAN_VLR_PREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 1 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.FIN, 'YYYY') THEN (VLRREAL) ELSE 0 END) AS JAN_VLR_REAL,

SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 2 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.FIN, 'YYYY') THEN QTDPREV ELSE 0 END) AS FEV_QTDPREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 2 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.FIN, 'YYYY') THEN QTDREAL ELSE 0 END) AS FEV_QTDREAL,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 2 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.FIN, 'YYYY') THEN (QTDPREV * PRECOLT) ELSE 0 END) AS FEV_VLR_PREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 2 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.FIN, 'YYYY') THEN (VLRREAL) ELSE 0 END) AS FEV_VLR_REAL,

SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 3 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.FIN, 'YYYY') THEN QTDPREV ELSE 0 END) AS MAR_QTDPREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 3 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.FIN, 'YYYY') THEN QTDREAL ELSE 0 END) AS MAR_QTDREAL,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 3 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.FIN, 'YYYY') THEN (QTDPREV * PRECOLT) ELSE 0 END) AS MAR_VLR_PREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 3 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.FIN, 'YYYY') THEN (VLRREAL) ELSE 0 END) AS MAR_VLR_REAL,

SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 4 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.FIN, 'YYYY') THEN QTDPREV ELSE 0 END) AS ABR_QTDPREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 4 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.FIN, 'YYYY') THEN QTDREAL ELSE 0 END) AS ABR_QTDREAL,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 4 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.FIN, 'YYYY') THEN (QTDPREV * PRECOLT) ELSE 0 END) AS ABR_VLR_PREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 4 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.FIN, 'YYYY') THEN (VLRREAL) ELSE 0 END) AS ABR_VLR_REAL,

SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 5 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.FIN, 'YYYY') THEN QTDPREV ELSE 0 END) AS MAI_QTDPREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 5 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.FIN, 'YYYY') THEN QTDREAL ELSE 0 END) AS MAI_QTDREAL,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 5 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.FIN, 'YYYY') THEN (QTDPREV * PRECOLT) ELSE 0 END) AS MAI_VLR_PREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 5 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.FIN, 'YYYY') THEN (VLRREAL) ELSE 0 END) AS MAI_VLR_REAL,

SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 6 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.FIN, 'YYYY') THEN QTDPREV ELSE 0 END) AS JUN_QTDPREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 6 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.FIN, 'YYYY') THEN QTDREAL ELSE 0 END) AS JUN_QTDREAL,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 6 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.FIN, 'YYYY') THEN (QTDPREV * PRECOLT) ELSE 0 END) AS JUN_VLR_PREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 6 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO1.FIN, 'YYYY') THEN (VLRREAL) ELSE 0 END) AS JUN_VLR_REAL

FROM
(
SELECT MET.DTREF, NVL(MET.CODVEND,0) AS CODVEND, NVL(MET.CODPARC,0) AS CODPARC, NVL(MET.MARCA,0) AS MARCA,NVL(VGF.CODCENCUS,0) AS CODCENCUS, NVL(MET.QTDPREV,0) AS QTDPREV, SUM(NVL(VGF.QTD,0)) AS QTDREAL,NVL(PRC.VLRVENDALT,0)AS PRECOLT, SUM(NVL(VGF.VLR,0)) AS VLRREAL
FROM TGFMET MET
LEFT JOIN VGF_VENDAS_SATIS VGF ON MET.DTREF = TRUNC(VGF.DTMOV,'MM') AND MET.CODVEND = VGF.CODVEND AND MET.CODPARC = VGF.CODPARC AND MET.MARCA = VGF.MARCA AND VGF.BONIFICACAO = 'N'
LEFT JOIN AD_PRECOMARCA PRC ON (MET.MARCA = PRC.MARCA AND PRC.CODMETA = MET.CODMETA AND PRC.DTREF = (SELECT MAX(DTREF) FROM AD_PRECOMARCA WHERE CODMETA = MET.CODMETA AND DTREF <= MET.DTREF AND MARCA = MET.MARCA))
WHERE 
MET.CODMETA = :P_CODMETA
AND MET.DTREF BETWEEN :P_PERIODO1.INI   AND  :P_PERIODO1.FIN

AND (VGF.CODGRUPOPROD = :P_GRUPOPROD OR :P_GRUPOPROD IS NULL)

GROUP BY MET.DTREF,NVL(MET.CODVEND,0),NVL(MET.CODPARC,0),NVL(MET.MARCA,0),NVL(VGF.CODCENCUS,0), NVL(MET.QTDPREV,0), NVL(PRC.VLRVENDALT,0)



)A
INNER JOIN TGFPAR PAR ON A.CODPARC = PAR.CODPARC
INNER JOIN TGFVEN VEN ON A.CODVEND = VEN.CODVEND
WHERE
(VEN.CODVEND IN :P_CODVEND)
AND (VEN.CODGER IN :P_CODGER)
AND (PAR.CODPARC = :P_CODPARC OR :P_CODPARC IS NULL)
AND (A.MARCA IN (SELECT MARCA FROM TGFPRO WHERE CODPROD IN :P_MARCA))
AND (A.CODCENCUS = :P_CR OR :P_CR IS NULL)
AND
(
VEN.CODVEND = (SELECT CODVEND FROM TSIUSU WHERE CODUSU = STP_GET_CODUSULOGADO) ---CONSULTA VENDEDOR
OR VEN.CODVEND IN (SELECT VEN.CODVEND FROM TGFVEN VEN, TSIUSU USU WHERE USU.CODVEND = VEN.CODGER AND USU.CODUSU = STP_GET_CODUSULOGADO) ---CONSULTA GERENTE
OR (SELECT AD_GESTOR_META FROM TSIUSU WHERE CODUSU = STP_GET_CODUSULOGADO) = 'S' ---CONSULTA MASTER
)
GROUP BY A.MARCA)T
)
GROUP BY MARCA
) DADOS
CROSS JOIN MESES_DATAS MD
WHERE ((:P_NTEMMETA = 'S' AND (DADOS.TTL_QTDPREV <> 0 OR DADOS.TTL_QTDREAL <> 0 OR DADOS.TTL_VLR_PREV <> 0 OR DADOS.TTL_VLR_REAL<> 0)) OR :P_NTEMMETA = 'N')

ORDER BY 1,2

