-- Exemplo de uso da query final com parâmetros
-- Este arquivo mostra como usar a query final com diferentes parâmetros

-- Exemplo 1: Consulta para uma empresa específica
-- :P_EMPRESA = 1
-- :P_CODTAB = NULL (todas as tabelas)
-- :P_CODPROD = NULL (todos os produtos)
-- :P_MARCA = 'MARCA1,MARCA2' (marcas específicas)

-- Exemplo 2: Consulta para um produto específico
-- :P_EMPRESA = 1
-- :P_CODTAB = 1
-- :P_CODPROD = 12345
-- :P_MARCA = NULL (todas as marcas)

-- Exemplo 3: Consulta para uma tabela específica
-- :P_EMPRESA = 1
-- :P_CODTAB = 2
-- :P_CODPROD = NULL
-- :P_MARCA = 'MARCA1'

-- Para executar a query final, use:
-- @final_query.sql

-- Ou execute diretamente:
/*
SELECT 
  NVL(NUTAB,0) NUTAB,
  CODTAB,
  SUBSTR(NOMETAB, 1, 3) NOMETAB,
  CODPROD,
  DESCRPROD,
  MARCA,
  AD_QTDVOLLT,
  POND_MARCA,
  CUSTO_SATIS,
  PRECO_TAB,
  MARGEM,
  PRECO_TAB_MENOS15,
  MARGEM_MENOS15,
  PRECO_TAB_MENOS65,
  MARGEM_MENOS65,
  TICKET_MEDIO_OBJETIVO,
  TICKET_MEDIO_ULT_12_M,
  TICKET_MEDIO_SAFRA,
  CUSTO_SATIS_ATU 
FROM (
  -- Query para produtos individuais
  SELECT 
    NUTAB,
    CODTAB, 
    NOMETAB, 
    CODPROD, 
    DESCRPROD, 
    MARCA,
    AD_QTDVOLLT,
    POND_MARCA,
    DTVIGOR,
    CUSTO_SATIS,
    PRECO_TAB,
    NVL(((PRECO_TAB - CUSTO_SATIS) / NULLIF(PRECO_TAB, 0)) * 100, 0) AS MARGEM,
    PRECO_TAB * 0.85 AS PRECO_TAB_MENOS15,
    NVL((((PRECO_TAB * 0.85) - CUSTO_SATIS) / NULLIF(PRECO_TAB * 0.85, 0)) * 100, 0) AS MARGEM_MENOS15,
    PRECO_TAB * 0.65 AS PRECO_TAB_MENOS65,
    NVL((((PRECO_TAB * 0.65) - CUSTO_SATIS) / NULLIF(PRECO_TAB * 0.65, 0)) * 100, 0) AS MARGEM_MENOS65,
    NVL(TICKET_MEDIO_OBJETIVO,0) TICKET_MEDIO_OBJETIVO,
    NVL(TICKET_MEDIO_PRO_ULT_12_M,0) TICKET_MEDIO_ULT_12_M,
    NVL(TICKET_MEDIO_PRO_SAFRA,0) TICKET_MEDIO_SAFRA,
    NVL(CUSTO_SATIS_ATU,0) CUSTO_SATIS_ATU
  FROM VW_BASE_PRINCIPAL
  WHERE RN = 1
    AND (:P_CODTAB IS NULL OR CODTAB = :P_CODTAB)
    AND (:P_CODPROD IS NULL OR CODPROD = :P_CODPROD)
    AND (:P_MARCA IS NULL OR MARCA IN (:P_MARCA))
    AND (:P_EMPRESA IS NULL OR EXISTS (
      SELECT 1 FROM VW_CUSTO_SATISFACAO CUS 
      WHERE CUS.CODPROD = CODPROD 
      AND CUS.CODEMP = :P_EMPRESA
    ))

  UNION ALL

  -- Query para totais por marca
  SELECT 
    NULL NUTAB,
    CODTAB,
    NOMETAB,
    NULL CODPROD,
    '1' DESCRPROD,
    MARCA,
    NULL AD_QTDVOLLT,
    NULL POND_MARCA,
    NULL DTVIGOR,
    SUM((CUSTO_SATIS / NULLIF(AD_QTDVOLLT, 0)) * POND_MARCA) AS CUSTO_SATIS,
    SUM((PRECO_TAB / NULLIF(AD_QTDVOLLT, 0)) * POND_MARCA) AS PRECO_TAB,
    NVL((
      SUM((PRECO_TAB / NULLIF(AD_QTDVOLLT, 0)) * POND_MARCA) - 
      SUM((CUSTO_SATIS / NULLIF(AD_QTDVOLLT, 0)) * POND_MARCA)
    ) / NULLIF(SUM((PRECO_TAB / NULLIF(AD_QTDVOLLT, 0)) * POND_MARCA), 0) * 100, 0) AS MARGEM,
    SUM((PRECO_TAB / NULLIF(AD_QTDVOLLT, 0)) * POND_MARCA) * 0.85 AS PRECO_TAB_MENOS15,
    NVL((
      SUM(((PRECO_TAB * 0.85) / NULLIF(AD_QTDVOLLT, 0)) * POND_MARCA) - 
      SUM((CUSTO_SATIS / NULLIF(AD_QTDVOLLT, 0)) * POND_MARCA)
    ) / NULLIF(SUM(((PRECO_TAB * 0.85) / NULLIF(AD_QTDVOLLT, 0)) * POND_MARCA), 0) * 100, 0) AS MARGEM_MENOS15,
    SUM((PRECO_TAB / NULLIF(AD_QTDVOLLT, 0)) * POND_MARCA) * 0.65 AS PRECO_TAB_MENOS65,
    NVL((
      SUM(((PRECO_TAB * 0.65) / NULLIF(AD_QTDVOLLT, 0)) * POND_MARCA) - 
      SUM((CUSTO_SATIS / NULLIF(AD_QTDVOLLT, 0)) * POND_MARCA)
    ) / NULLIF(SUM(((PRECO_TAB * 0.65) / NULLIF(AD_QTDVOLLT, 0)) * POND_MARCA), 0) * 100, 0) AS MARGEM_MENOS65,
    TICKET_MEDIO_OBJETIVO_MARCA TICKET_MEDIO_OBJETIVO,
    SUM(TICKET_MEDIO_ULT_12_M * POND_MARCA) AS TICKET_MEDIO_ULT_12_M,
    SUM(TICKET_MEDIO_SAFRA * POND_MARCA) AS TICKET_MEDIO_SAFRA,
    SUM((CUSTO_SATIS_ATU / NULLIF(AD_QTDVOLLT, 0)) * POND_MARCA) CUSTO_SATIS_ATU
  FROM VW_BASE_PRINCIPAL
  WHERE RN = 1
    AND (:P_CODTAB IS NULL OR CODTAB = :P_CODTAB)
    AND (:P_CODPROD IS NULL OR CODPROD = :P_CODPROD)
    AND (:P_MARCA IS NULL OR MARCA IN (:P_MARCA))
    AND (:P_EMPRESA IS NULL OR EXISTS (
      SELECT 1 FROM VW_CUSTO_SATISFACAO CUS 
      WHERE CUS.CODPROD = CODPROD 
      AND CUS.CODEMP = :P_EMPRESA
    ))
  GROUP BY 
    CODTAB,
    NOMETAB,
    MARCA,
    TICKET_MEDIO_OBJETIVO_MARCA
)
ORDER BY 2, 6, 4 DESC;
*/ 