    SELECT 
        NVL(NUTAB,0)NUTAB,
        CODTAB,
        SUBSTR(NOMETAB, 1, 3) NOMETAB,
        CODPROD,
        DESCRPROD,
        MARCA,
        NVL(AD_QTDVOLLT,0) AS AD_QTDVOLLT,
        NVL(POND_MARCA,0) AS POND_MARCA,
        CUSTO_SATIS,
        PRECO_TAB,
        MARGEM,
        PRECO_TAB_MENOS15,
        MARGEM_MENOS15,
        PRECO_TAB_MENOS65,
        MARGEM_MENOS65,
        NVL(TICKET_MEDIO_OBJETIVO,0) TICKET_MEDIO_OBJETIVO,
        NVL(TICKET_MEDIO_ULT_12_M,0) TICKET_MEDIO_ULT_12_M,
        NVL(TICKET_MEDIO_SAFRA,0) TICKET_MEDIO_SAFRA,
        NVL(MARGEM_ULT_12_M,0) MARGEM_ULT_12_M,
        NVL(MARGEM_SAFRA,0) MARGEM_SAFRA,
        CUSTO_SATIS_ATU 
        FROM (

        WITH CUS AS (
        SELECT CODPROD, CODEMP, CUSTO_SATIS
        FROM (
        SELECT
          CODPROD,
          CODEMP,
          OBTEMCUSTO_SATIS(CODPROD, 'S', CODEMP, 'N', 0, 'N', ' ', TO_DATE('${periodo}', 'DDMMYYYY'), 3) AS CUSTO_SATIS,
          ROW_NUMBER() OVER (PARTITION BY CODEMP, CODPROD ORDER BY DTATUAL DESC) AS RN
        FROM TGFCUS
        WHERE DTATUAL <= TO_DATE('${periodo}', 'DDMMYYYY')
        AND CODEMP = ${empresa} 
        )
        WHERE RN = 1
        ),
        CUS_ATUAL AS (
        SELECT CODPROD, CODEMP, CUSTO_SATIS
        FROM (
        SELECT
          CODPROD,
          CODEMP,
          OBTEMCUSTO_SATIS(CODPROD, 'S', CODEMP, 'N', 0, 'N', ' ', SYSDATE, 3) AS CUSTO_SATIS,
          ROW_NUMBER() OVER (PARTITION BY CODEMP, CODPROD ORDER BY DTATUAL DESC) AS RN
        FROM TGFCUS
        WHERE DTATUAL <= SYSDATE
        AND CODEMP =  ${empresa} 
        )
        WHERE RN = 1
        ),
        PON AS (
        SELECT 
        CODEMP,
        PROD,
        CODPROD,
        DESCRPROD,
        MARCA,
        CODGRUPOPROD,
        DESCRGRUPOPROD,
        ROUND(SUM(QTD) /  NULLIF(SUM(SUM(QTD)) OVER (PARTITION BY MARCA),0),2) AS POND_MARCA

        FROM VGF_VENDAS_SATIS
        WHERE DTNEG >= ADD_MONTHS(TO_DATE('${periodo}', 'DDMMYYYY'), -12)
        AND DTNEG < TO_DATE('${periodo}', 'DDMMYYYY')
        AND CODEMP =  ${empresa} 

        GROUP BY CODEMP, PROD, CODPROD, DESCRPROD, MARCA, CODGRUPOPROD, DESCRGRUPOPROD
        ),
        MET AS (
        SELECT 
        MARCA, 
        SUM(QTDPREV) AS QTDPREV,
        SUM(VLR_PREV) AS VLR_PREV,
        SUM(VLR_PREV) / NULLIF(SUM(QTDPREV), 0) AS TICKET_MEDIO_OBJETIVO
        FROM (
        SELECT DISTINCT
          MET.CODMETA,
          MET.DTREF,
          MET.CODVEND,
          MET.CODPARC,
          MET.MARCA,
          MET.QTDPREV,
          MET.QTDPREV * PRC.VLRVENDALT AS VLR_PREV
        FROM TGFMET MET
        LEFT JOIN VGF_VENDAS_SATIS VGF 
          ON MET.DTREF = TRUNC(VGF.DTMOV, 'MM') 
        AND MET.CODVEND = VGF.CODVEND 
        AND MET.CODPARC = VGF.CODPARC 
        AND MET.MARCA = VGF.MARCA 
        AND VGF.BONIFICACAO = 'N'
        LEFT JOIN AD_PRECOMARCA PRC 
          ON MET.MARCA = PRC.MARCA 
        AND PRC.CODMETA = MET.CODMETA 
        AND PRC.DTREF = (
            SELECT MAX(DTREF)
            FROM AD_PRECOMARCA
            WHERE CODMETA = MET.CODMETA
              AND DTREF <= MET.DTREF
              AND MARCA = MET.MARCA
        )
        LEFT JOIN TGFPAR PAR ON MET.CODPARC = PAR.CODPARC
        LEFT JOIN TGFVEN VEN ON MET.CODVEND = VEN.CODVEND
        WHERE MET.CODMETA = 4
        AND (${codparc || 'NULL'} IS NULL OR MET.CODPARC = ${codparc || 'NULL'})
        AND MET.DTREF BETWEEN 
            CASE 
                WHEN EXTRACT(MONTH FROM TO_DATE('${periodo}', 'DDMMYYYY')) <= 6 
                THEN TRUNC(TO_DATE('${periodo}', 'DDMMYYYY'), 'YYYY') - INTERVAL '6' MONTH
                ELSE TRUNC(TO_DATE('${periodo}', 'DDMMYYYY'), 'YYYY') + INTERVAL '6' MONTH
            END
        AND 
            CASE 
                WHEN EXTRACT(MONTH FROM TO_DATE('${periodo}', 'DDMMYYYY')) <= 6 
                THEN LAST_DAY(TRUNC(TO_DATE('${periodo}', 'DDMMYYYY'), 'YYYY') + INTERVAL '5' MONTH)
                ELSE LAST_DAY(TRUNC(TO_DATE('${periodo}', 'DDMMYYYY'), 'YYYY') + INTERVAL '17' MONTH)
            END
        )
        GROUP BY MARCA
        ),
        FAT AS (
        SELECT CODEMP,PROD,CODPROD,DESCRPROD,MARCA,CODGRUPOPROD,DESCRGRUPOPROD, NVL(SUM(QTD),0) QTD,NVL(SUM(VLR),0) VLR,
        NVL(SUM(VLR)/NULLIF(SUM(QTD),0),0) TICKET_MEDIO_ULT_12_M,NVL(SUM(VLR)/NULLIF(SUM(QTDNEG),0),0) TICKET_MEDIO_PRO_ULT_12_M,
        -- Cálculo da margem dos últimos 12 meses: (VLR - CUSTO) / VLR * 100
        NVL((SUM(VLR) - SUM(VLRCUSICM1)) / NULLIF(SUM(VLR), 0) * 100, 0) AS MARGEM_ULT_12_M        
        FROM VGF_VENDAS_SATIS
        WHERE 
        DTNEG >= ADD_MONTHS(TO_DATE('${periodo}', 'DDMMYYYY'), -12)
        AND DTNEG < TO_DATE('${periodo}', 'DDMMYYYY')
        AND CODEMP =  ${empresa} 
        AND (${codparc || 'NULL'} IS NULL OR CODPARC = ${codparc || 'NULL'})
        GROUP BY CODEMP,PROD,CODPROD,DESCRPROD,MARCA,CODGRUPOPROD,DESCRGRUPOPROD
        ),
        FAT1 AS (
        SELECT CODEMP,PROD,CODPROD,DESCRPROD,MARCA,CODGRUPOPROD,DESCRGRUPOPROD, NVL(SUM(QTD),0) QTD_SAFRA,NVL(SUM(VLR),0) VLR_SAFRA,
        NVL(SUM(VLR)/NULLIF(SUM(QTD),0),0) TICKET_MEDIO_SAFRA,NVL(SUM(VLR)/NULLIF(SUM(QTDNEG),0),0) TICKET_MEDIO_PRO_SAFRA,
        NVL((SUM(VLR) - SUM(VLRCUSICM1)) / NULLIF(SUM(VLR), 0) * 100, 0) AS MARGEM_SAFRA
        FROM VGF_VENDAS_SATIS
        WHERE 
        DTNEG BETWEEN 
        CASE 
        WHEN EXTRACT(MONTH FROM TO_DATE('${periodo}', 'DDMMYYYY')) <= 6 
        THEN TRUNC(TO_DATE('${periodo}', 'DDMMYYYY'), 'YYYY') - INTERVAL '6' MONTH
        ELSE TRUNC(TO_DATE('${periodo}', 'DDMMYYYY'), 'YYYY') + INTERVAL '6' MONTH
        END
        AND 
        CASE 
        WHEN EXTRACT(MONTH FROM TO_DATE('${periodo}', 'DDMMYYYY')) <= 6 
        THEN LAST_DAY(TRUNC(TO_DATE('${periodo}', 'DDMMYYYY'), 'YYYY') + INTERVAL '5' MONTH)
        ELSE LAST_DAY(TRUNC(TO_DATE('${periodo}', 'DDMMYYYY'), 'YYYY') + INTERVAL '17' MONTH)
        END
        AND CODEMP = ${empresa}
        AND (${codparc || 'NULL'} IS NULL OR CODPARC = ${codparc || 'NULL'})
        GROUP BY CODEMP,PROD,CODPROD,DESCRPROD,MARCA,CODGRUPOPROD,DESCRGRUPOPROD
        ),
        PRE_ATUAL AS (
        SELECT 
        CODTAB,NOMETAB,DTVIGOR,CODPROD,VLRVENDA_ATUAL
        FROM (
        SELECT
        TAB.CODTAB,
        NTA.NOMETAB,
        TAB.DTVIGOR,
        PRO.CODPROD,
        NVL(EXC.VLRVENDA,0) VLRVENDA_ATUAL,
        ROW_NUMBER() OVER (PARTITION BY TAB.CODTAB,PRO.CODPROD ORDER BY TAB.DTVIGOR DESC) AS RN
        FROM TGFPRO PRO
        LEFT JOIN TGFMAR MAR ON MAR.DESCRICAO = PRO.MARCA
        LEFT JOIN TGFEXC EXC ON PRO.CODPROD = EXC.CODPROD
        LEFT JOIN TGFTAB TAB ON EXC.NUTAB = TAB.NUTAB
        LEFT JOIN TGFNTA NTA ON TAB.CODTAB = NTA.CODTAB
        WHERE SUBSTR(MAR.AD_GRUPOPROD, 1, 1) = '1'
        AND NTA.ATIVO = 'S' AND PRO.ATIVO = 'S' AND TAB.DTVIGOR <= SYSDATE

        ) SUB
        WHERE RN = 1
        ),
        BAS AS (
        SELECT * FROM (
        SELECT DISTINCT
        TAB.NUTAB,
        NTA.CODTAB, 
        NTA.NOMETAB, 
        PRO.CODPROD, 
        PRO.DESCRPROD, 
        PRO.MARCA,
        PRO.AD_QTDVOLLT,
        NVL(PON.POND_MARCA, 0) AS POND_MARCA,
        TAB.DTVIGOR,
        NVL(SNK_GET_PRECO(TAB.NUTAB, PRO.CODPROD, TO_DATE('${periodo}', 'DDMMYYYY')), 0) AS PRECO_TAB,
        NVL(CUS.CUSTO_SATIS, 0) AS CUSTO_SATIS,
        MET.TICKET_MEDIO_OBJETIVO * PRO.AD_QTDVOLLT AS TICKET_MEDIO_OBJETIVO,
        MET.TICKET_MEDIO_OBJETIVO TICKET_MEDIO_OBJETIVO_MARCA,
        FAT.TICKET_MEDIO_ULT_12_M,
        FAT.TICKET_MEDIO_PRO_ULT_12_M,
        FAT.MARGEM_ULT_12_M,
        FAT1.TICKET_MEDIO_SAFRA,
        FAT1.TICKET_MEDIO_PRO_SAFRA,
        FAT1.MARGEM_SAFRA,
        PRE.VLRVENDA_ATUAL,
        CUS_ATU.CUSTO_SATIS CUSTO_SATIS_ATU,
        ROW_NUMBER() OVER (PARTITION BY TAB.CODTAB, PRO.CODPROD ORDER BY TAB.DTVIGOR DESC) AS RN
        FROM TGFPRO PRO
        LEFT JOIN TGFMAR MAR ON MAR.DESCRICAO = PRO.MARCA 
        LEFT JOIN TGFEXC EXC ON PRO.CODPROD = EXC.CODPROD
        LEFT JOIN TGFTAB TAB ON EXC.NUTAB = TAB.NUTAB
        LEFT JOIN TGFNTA NTA ON TAB.CODTAB = NTA.CODTAB
        LEFT JOIN TGFPAR PAR ON (${codparc || 'NULL'} IS NOT NULL AND PAR.CODPARC = ${codparc || 'NULL'})
        LEFT JOIN CUS ON PRO.CODPROD = CUS.CODPROD
        LEFT JOIN CUS_ATUAL CUS_ATU ON PRO.CODPROD = CUS_ATU.CODPROD
        LEFT JOIN PON ON PRO.CODPROD = PON.CODPROD
        LEFT JOIN MET ON PRO.MARCA = MET.MARCA
        LEFT JOIN FAT ON PRO.CODPROD = FAT.CODPROD
        LEFT JOIN FAT1 ON PRO.CODPROD = FAT1.CODPROD
        LEFT JOIN PRE_ATUAL PRE ON PRO.CODPROD = PRE.CODPROD AND TAB.CODTAB = PRE.CODTAB
        WHERE NTA.ATIVO = 'S'
        AND MAR.AD_GRUPOPROD LIKE '1%'
        AND PRO.ATIVO = 'S'
        AND TAB.DTVIGOR <= TO_DATE('${periodo}', 'DDMMYYYY')
        AND (${codparc || 'NULL'} IS NULL OR PAR.CODTAB = TAB.CODTAB)
        ORDER BY NTA.CODTAB, PRO.CODPROD
        )WHERE RN = 1)

        SELECT 
        NUTAB,
        CODTAB, 
        NOMETAB, 
        CODPROD, 
        DESCRPROD, 
        MARCA,
        AD_QTDVOLLT,
        POND_MARCA,
        DTVIGOR,
        CUSTO_SATIS,
        PRECO_TAB,
        NVL(((PRECO_TAB - CUSTO_SATIS) / NULLIF(PRECO_TAB, 0)) * 100, 0) AS MARGEM,
        PRECO_TAB * 0.85 AS PRECO_TAB_MENOS15,
        NVL((((PRECO_TAB * 0.85) - CUSTO_SATIS) / NULLIF(PRECO_TAB * 0.85, 0)) * 100, 0) AS MARGEM_MENOS15,
        PRECO_TAB * 0.65 AS PRECO_TAB_MENOS65,
        NVL((((PRECO_TAB * 0.65) - CUSTO_SATIS) / NULLIF(PRECO_TAB * 0.65, 0)) * 100, 0) AS MARGEM_MENOS65,
        NVL(TICKET_MEDIO_OBJETIVO,0)TICKET_MEDIO_OBJETIVO,
        NVL(TICKET_MEDIO_PRO_ULT_12_M,0)TICKET_MEDIO_ULT_12_M,
        NVL(TICKET_MEDIO_PRO_SAFRA,0)TICKET_MEDIO_SAFRA,
        NVL(MARGEM_ULT_12_M,0) MARGEM_ULT_12_M,
        NVL(MARGEM_SAFRA,0) MARGEM_SAFRA,
        NVL(CUSTO_SATIS_ATU,0) CUSTO_SATIS_ATU
        FROM BAS

        UNION ALL

        SELECT 
        NULL NUTAB,
        CODTAB,
        NOMETAB,
        NULL CODPROD,
        '1' DESCRPROD,
        MARCA,
        NULL AD_QTDVOLLT,
        SUM(POND_MARCA) POND_MARCA,
        NULL DTVIGOR,
        SUM((CUSTO_SATIS / NULLIF(AD_QTDVOLLT, 0)) * POND_MARCA) AS CUSTO_SATIS,
        SUM((PRECO_TAB / NULLIF(AD_QTDVOLLT, 0)) * POND_MARCA) AS PRECO_TAB,

        NVL((
        SUM((PRECO_TAB / NULLIF(AD_QTDVOLLT, 0)) * POND_MARCA) - 
        SUM((CUSTO_SATIS / NULLIF(AD_QTDVOLLT, 0)) * POND_MARCA)
        ) / NULLIF(SUM((PRECO_TAB / NULLIF(AD_QTDVOLLT, 0)) * POND_MARCA), 0) * 100, 0) AS MARGEM,

        SUM((PRECO_TAB / NULLIF(AD_QTDVOLLT, 0)) * POND_MARCA)*0.85 AS PRECO_TAB_MENOS15,

        NVL((
        SUM(((PRECO_TAB*0.85) / NULLIF(AD_QTDVOLLT, 0)) * POND_MARCA) - 
        SUM((CUSTO_SATIS / NULLIF(AD_QTDVOLLT, 0)) * POND_MARCA)
        ) / NULLIF( SUM(((PRECO_TAB*0.85) / NULLIF(AD_QTDVOLLT, 0)) * POND_MARCA) , 0) * 100, 0) AS MARGEM_MENOS15,

        SUM((PRECO_TAB / NULLIF(AD_QTDVOLLT, 0)) * POND_MARCA)*0.65 AS PRECO_TAB_MENOS65,

        NVL((
        SUM(((PRECO_TAB*0.65)  / NULLIF(AD_QTDVOLLT, 0)) * POND_MARCA) - 
        SUM((CUSTO_SATIS / NULLIF(AD_QTDVOLLT, 0)) * POND_MARCA)
        ) / NULLIF(SUM(((PRECO_TAB*0.65)  / NULLIF(AD_QTDVOLLT, 0)) * POND_MARCA), 0) * 100, 0) AS MARGEM_MENOS65,


        TICKET_MEDIO_OBJETIVO_MARCA TICKET_MEDIO_OBJETIVO,
        SUM(TICKET_MEDIO_ULT_12_M  * POND_MARCA) AS TICKET_MEDIO_ULT_12_M,
        SUM(TICKET_MEDIO_SAFRA  * POND_MARCA) AS TICKET_MEDIO_SAFRA,
        SUM(MARGEM_ULT_12_M * POND_MARCA) AS MARGEM_ULT_12_M,
        SUM(MARGEM_SAFRA * POND_MARCA) AS MARGEM_SAFRA,
        SUM((CUSTO_SATIS_ATU / NULLIF(AD_QTDVOLLT, 0)) * POND_MARCA) CUSTO_SATIS_ATU
        FROM BAS
        GROUP BY 
        CODTAB,
        NOMETAB,
        MARCA,
        TICKET_MEDIO_OBJETIVO_MARCA
        )
ORDER BY 2,6,4 DESC