CREATE OR REPLACE VIEW VW_CUSTOS_ATUAIS AS
-- View para custos atuais
-- Calcula o custo de satisfação atual por produto e empresa
SELECT CODPROD, CODEMP, CUSTO_SATIS
FROM (
SELECT
  CODPROD,
  CODEMP,
  OBTEMCUSTO_SATIS(CODPROD, 'S', CODEMP, 'N', 0, 'N', ' ', SYSDATE, 3) AS CUSTO_SATIS,
  ROW_NUMBER() OVER (PARTITION BY CODEMP, CODPROD ORDER BY DTATUAL DESC) AS RN
FROM TGFCUS
WHERE DTATUAL <= SYSDATE
AND CODEMP IS NOT NULL
)
WHERE RN = 1; 