CREATE OR REPLACE VIEW VW_METAS_OBJETIVOS AS
-- View para metas e objetivos
-- Calcula o ticket médio objetivo por marca baseado nas metas
SELECT 
MARCA, 
SUM(QTDPREV) AS QTDPREV,
SUM(VLR_PREV) AS VLR_PREV,
SUM(VLR_PREV) / NULLIF(SUM(QTDPREV), 0) AS TICKET_MEDIO_OBJETIVO
FROM (
SELECT DISTINCT
  MET.CODMETA,
  MET.DTREF,
  MET.CODVEND,
  MET.CODPARC,
  MET.MARCA,
  MET.QTDPREV,
  MET.QTDPREV * PRC.VLRVENDALT AS VLR_PREV
FROM TGFMET MET
LEFT JOIN VGF_VENDAS_SATIS VGF 
  ON MET.DTREF = TRUNC(VGF.DTMOV, 'MM') 
 AND MET.CODVEND = VGF.CODVEND 
 AND MET.CODPARC = VGF.CODPARC 
 AND MET.MARCA = VGF.MARCA 
 AND VGF.BONIFICACAO = 'N'
LEFT JOIN AD_PRECOMARCA PRC 
  ON MET.MARCA = PRC.MARCA 
 AND PRC.CODMETA = MET.CODMETA 
 AND PRC.DTREF = (
     SELECT MAX(DTREF)
     FROM AD_PRECOMARCA
     WHERE CODMETA = MET.CODMETA
       AND DTREF <= MET.DTREF
       AND MARCA = MET.MARCA
 )
LEFT JOIN TGFPAR PAR ON MET.CODPARC = PAR.CODPARC
LEFT JOIN TGFVEN VEN ON MET.CODVEND = VEN.CODVEND
WHERE MET.CODMETA = 4
AND MET.MARCA IS NOT NULL
)
GROUP BY MARCA; 