-- View base consolidada
-- Integra todas as informações de produtos, preços, custos e métricas
CREATE OR REPLACE VIEW VW_BASE_CONSOLIDADA AS
SELECT DISTINCT
TAB.NUTAB,
NTA.CODTAB, 
NTA.NOMETAB, 
PRO.CODPROD, 
PRO.DESCRPROD, 
PRO.MARCA,
PRO.AD_QTDVOLLT,
NVL(PON.POND_MARCA, 0) AS POND_MARCA,
TAB.DTVIGOR,
NVL(CUS.CUSTO_SATIS, 0) AS CUSTO_SATIS,
MET.TICKET_MEDIO_OBJETIVO * PRO.AD_QTDVOLLT AS TICKET_MEDIO_OBJETIVO,
MET.TICKET_MEDIO_OBJETIVO TICKET_MEDIO_OBJETIVO_MARCA,
FAT.TICKET_MEDIO_ULT_12_M,
FAT.TICKET_MEDIO_PRO_ULT_12_M,
FAT1.TICKET_MEDIO_SAFRA,
FAT1.TICKET_MEDIO_PRO_SAFRA,
PRE.VLRVENDA_ATUAL,
CUS_ATU.CUSTO_SATIS CUSTO_SATIS_ATU,
ROW_NUMBER() OVER (PARTITION BY TAB.CODTAB, PRO.CODPROD ORDER BY TAB.DTVIGOR DESC) AS RN
FROM TGFPRO PRO
INNER JOIN TGFGRU GRU ON PRO.CODGRUPOPROD = GRU.CODGRUPOPROD
LEFT JOIN TGFEXC EXC ON PRO.CODPROD = EXC.CODPROD
LEFT JOIN TGFTAB TAB ON EXC.NUTAB = TAB.NUTAB
LEFT JOIN TGFNTA NTA ON TAB.CODTAB = NTA.CODTAB
LEFT JOIN VW_CUSTOS_HISTORICOS CUS ON PRO.CODPROD = CUS.CODPROD
LEFT JOIN VW_CUSTOS_ATUAIS CUS_ATU ON PRO.CODPROD = CUS_ATU.CODPROD
LEFT JOIN VW_PONDERACOES_MARCA PON ON PRO.CODPROD = PON.CODPROD
LEFT JOIN VW_METAS_OBJETIVOS MET ON PRO.MARCA = MET.MARCA
LEFT JOIN VW_FATURAMENTO_HISTORICO FAT ON PRO.CODPROD = FAT.CODPROD
LEFT JOIN VW_FATURAMENTO_SAFRA FAT1 ON PRO.CODPROD = FAT1.CODPROD
LEFT JOIN VW_PRECOS_ATUAIS PRE ON PRO.CODPROD = PRE.CODPROD AND TAB.CODTAB = PRE.CODTAB
WHERE NTA.ATIVO = 'S'
AND PRO.CODGRUPOPROD LIKE '1%'
AND PRO.ATIVO = 'S'
AND PRO.MARCA IS NOT NULL; 