CREATE OR REPLACE VIEW VW_CUSTOS_HISTORICOS AS
-- View para custos históricos
-- Calcula o custo de satisfação por produto e empresa para um período específico
SELECT CODPROD, CODEMP, CUSTO_SATIS
FROM (
SELECT
  CODPROD,
  CODEMP,
  OBTEMCUSTO_SATIS(CODPROD, 'S', CODEMP, 'N', 0, 'N', ' ', DTATUAL, 3) AS CUSTO_SATIS,
  ROW_NUMBER() OVER (PARTITION BY CODEMP, CODPROD ORDER BY DTATUAL DESC) AS RN
FROM TGFCUS
WHERE CODEMP IS NOT NULL
) 
WHERE RN = 1; 