CREATE OR REPLACE VIEW VW_FATURAMENTO_SAFRA AS
-- View para faturamento da safra
-- Calcula métricas de vendas do período da safra por produto
SELECT 
CODEMP,
PROD,
CODPROD,
DESCRPROD,
MARCA,
CODGRUPOPROD,
DESCRGRUPOPROD, 
NVL(SUM(QTD),0) QTD_SAFRA,
NVL(SUM(VLR),0) VLR_SAFRA,
NVL(SUM(VLR)/NULLIF(SUM(QTD),0),0) TICKET_MEDIO_SAFRA,
NVL(SUM(VLR)/NULLIF(SUM(QTDNEG),0),0) TICKET_MEDIO_PRO_SAFRA
FROM VGF_VENDAS_SATIS
WHERE CODEMP IS NOT NULL
AND MARCA IS NOT NULL
GROUP BY CODEMP,PROD,CODPROD,DESCRPROD,MARCA,CODGRUPOPROD,DESCRGRUPOPROD; 