CREATE OR REPLACE VIEW VW_PRECOS_ATUAIS AS
-- View para preços atuais
-- Obtém os preços vigentes por produto e tabela
SELECT 
CODTAB,
NOMETAB,
DTVIGOR,
CODPROD,
VLRVENDA_ATUAL
FROM (
SELECT
TAB.CODTAB,
NTA.NOMETAB,
TAB.DTVIGOR,
PRO.CODPROD,
NVL(EXC.VLRVENDA,0) VLRVENDA_ATUAL,
ROW_NUMBER() OVER (PARTITION BY TAB.CODTAB,PRO.CODPROD ORDER BY TAB.DTVIGOR DESC) AS RN
FROM TGFPRO PRO
INNER JOIN TGFGRU GRU ON PRO.CODGRUPOPROD = GRU.CODGRUPOPROD
LEFT JOIN TGFEXC EXC ON PRO.CODPROD = EXC.CODPROD
LEFT JOIN TGFTAB TAB ON EXC.NUTAB = TAB.NUTAB
LEFT JOIN TGFNTA NTA ON TAB.CODTAB = NTA.CODTAB
WHERE SUBSTR(PRO.CODGRUPOPROD, 1, 1) = '1'
AND NTA.ATIVO = 'S' 
AND PRO.ATIVO = 'S' 
AND TAB.DTVIGOR <= SYSDATE
AND PRO.MARCA IS NOT NULL
) SUB
WHERE RN = 1; 