CREATE OR REPLACE VIEW VW_FATURAMENTO_HISTORICO AS
-- View para faturamento histórico
-- Calcula métricas de vendas dos últimos 12 meses por produto
SELECT 
CODEMP,
PROD,
CODPROD,
DESCRPROD,
MARCA,
CODGRUPOPROD,
DESCRGRUPOPROD, 
NVL(SUM(QTD),0) QTD,
NVL(SUM(VLR),0) VLR,
NVL(SUM(VLR)/NULLIF(SUM(QTD),0),0) TICKET_MEDIO_ULT_12_M,
NVL(SUM(VLR)/NULLIF(SUM(QTDNEG),0),0) TICKET_MEDIO_PRO_ULT_12_M
FROM VGF_VENDAS_SATIS
WHERE CODEMP IS NOT NULL
AND MARCA IS NOT NULL
GROUP BY CODEMP,PROD,CODPROD,DESCRPROD,MARCA,CODGRUPOPROD,DESCRGRUPOPROD; 