SELECT 
TGFFIN.*
    -- TGFFIN.CODPARC,
    -- TGFFIN.RECDESP,
    -- TGFFIN.VLRDESDOB,
    -- TGFFIN.PROVISAO,
    -- TGFFIN.DHBAIXA
FROM TGFFIN WITH (NOLOCK)
     LEFT JOIN TSIBCO Banco (NOLOCK)  ON (TGFFIN.CODBCO = Banco.CODBCO)
     LEFT JOIN TSICUS CentroResultado (NOLOCK)  ON (TGFFIN.CODCENCUS = CentroResultado.CODCENCUS)
     LEFT JOIN TGFCFO ClassificacaoFiscalOperacao (NOLOCK)  ON (TGFFIN.CODCFO = ClassificacaoFiscalOperacao.CODCFO)
     LEFT JOIN TGFRNF CompFinancReinf (NOLOCK)  ON (TGFFIN.NUFIN = CompFinancReinf.NUFIN)
     LEFT JOIN TGFNRR CadastroNaturezaRendimentos4_1 (NOLOCK)  ON (CompFinancReinf.CODNATREND = CadastroNaturezaRendimentos4_1.CODNATREND)
     LEFT JOIN TSICTA ContaBancaria (NOLOCK)  ON (TGFFIN.CODCTABCOINT = ContaBancaria.CODCTABCOINT)
     LEFT JOIN TGFCTT Contato (NOLOCK)  ON (TGFFIN.CODPARC = Contato.CODPARC AND TGFFIN.CODCONTATO = Contato.CODCONTATO)
     LEFT JOIN TSIEMP Empresa (NOLOCK)  ON (TGFFIN.CODEMP = Empresa.CODEMP)
     LEFT JOIN TSIEMP EmpresaBaixa (NOLOCK)  ON (TGFFIN.CODEMPBAIXA = EmpresaBaixa.CODEMP)
     LEFT JOIN TFPFUN Funcionario (NOLOCK)  ON (TGFFIN.CODEMP = Funcionario.CODEMP AND TGFFIN.CODFUNC = Funcionario.CODFUNC)
     LEFT JOIN TSIEMP ImovelRural (NOLOCK)  ON (TGFFIN.CODIMOVELRURAL = ImovelRural.CODEMP)
     LEFT JOIN TGFLST ListaServicoSintegra (NOLOCK)  ON (TGFFIN.CODLST = ListaServicoSintegra.CODLST)
     LEFT JOIN TSIMOE Moeda (NOLOCK)  ON (TGFFIN.CODMOEDA = Moeda.CODMOEDA)
     LEFT JOIN TGFNAT Natureza (NOLOCK)  ON (TGFFIN.CODNAT = Natureza.CODNAT)
     LEFT JOIN TGFOBS ObservacaoNotasFiscais (NOLOCK)  ON (TGFFIN.CODOBSPADRAO = ObservacaoNotasFiscais.CODOBSPADRAO)
     LEFT JOIN TGFPAR Parceiro (NOLOCK)  ON (TGFFIN.CODPARC = Parceiro.CODPARC)
     LEFT JOIN TSICID Cidade16_1 (NOLOCK)  ON (Parceiro.CODCID = Cidade16_1.CODCID)
     LEFT JOIN TSIUFS UnidadeFederativa16_2 (NOLOCK)  ON (Cidade16_1.UF = UnidadeFederativa16_2.CODUF)
     LEFT JOIN TGFPIXTEF PixTEF (NOLOCK)  ON (TGFFIN.PIXTEF = PixTEF.SEQPIXTEF)
     LEFT JOIN TCSPRJ Projeto (NOLOCK)  ON (TGFFIN.CODPROJ = Projeto.CODPROJ)
     LEFT JOIN TGFRDARF ReceitaDarf (NOLOCK)  ON (TGFFIN.CODRECEITA = ReceitaDarf.CODRECEITA)
     LEFT JOIN TGFTEF TEF (NOLOCK)  ON (TGFFIN.NUFIN = TEF.NUFIN)
     LEFT JOIN TSICTA TimContaBancaria (NOLOCK)  ON (TGFFIN.TIMCONTALANC = TimContaBancaria.CODCTABCOINT)
     LEFT JOIN TIMIMV TimImovel (NOLOCK)  ON (TGFFIN.TIMIMOVEL = TimImovel.IMVCODIGO)
     LEFT JOIN TIMTIN TimTipoIntermed (NOLOCK)  ON (TGFFIN.TIMTIPOINTERMED = TimTipoIntermed.TINCODIGO)
     LEFT JOIN TGFTOP TipoOperacao (NOLOCK)  ON (TGFFIN.CODTIPOPER = TipoOperacao.CODTIPOPER AND TGFFIN.DHTIPOPER = TipoOperacao.DHALTER)
     LEFT JOIN TGFTOP TipoOperacaoBaixa (NOLOCK)  ON (TGFFIN.CODTIPOPERBAIXA = TipoOperacaoBaixa.CODTIPOPER AND TGFFIN.DHTIPOPERBAIXA = TipoOperacaoBaixa.DHALTER)
     LEFT JOIN TGFTIT TipoTitulo (NOLOCK)  ON (TGFFIN.CODTIPTIT = TipoTitulo.CODTIPTIT)
     LEFT JOIN TSIUSU Usuario (NOLOCK)  ON (TGFFIN.CODUSU = Usuario.CODUSU)
     LEFT JOIN TSIUSU Usuario2 (NOLOCK)  ON (TGFFIN.TIMREPINTELIGENTE = Usuario2.CODUSU)
     LEFT JOIN TSIUSU UsuarioBaixa (NOLOCK)  ON (TGFFIN.CODUSUBAIXA = UsuarioBaixa.CODUSU)
     LEFT JOIN TGFVEN Vendedor (NOLOCK)  ON (TGFFIN.CODVEND = Vendedor.CODVEND)
WHERE 
    TGFFIN.RECDESP = 1
    AND TGFFIN.PROVISAO = 'N'
    AND TGFFIN.DHBAIXA IS NULL
    AND DATEADD(DAY, DATEDIFF(DAY, 0, TGFFIN.DTNEG), 0) <= DATEADD(DAY, DATEDIFF(DAY, 0, '31/08/2025'), 0)
    AND TGFFIN.CODEMP IN (1)
    AND NOT (TGFFIN.PROVISAO = 'S' AND TGFFIN.DHBAIXA IS NOT NULL AND TGFFIN.ORIGEM = 'E');
