SELECT  CAB.CODEMP,
		LAN.CODCTACTB,
		PLA.CTACTB,
		PLA.DESCRCTA,
        CAB.NUNOTA AS NUMERO_UNICO, 
        CAB.NUMNOTA AS NUMNOTA, 
        CAB.CODPARC AS PARCEIRO,
		PAR.NOMEPARC AS NOMEPARC,
        CAB.CODTIPOPER AS OPERACAO,
		TOP.DESCROPER AS DESCROPER,
        CASE WHEN LAN.TIPLANC = 'D' THEN 'DEBITO' ELSE 'CREDITO' END AS TIPLANC,
		LAN.NUMLOTE, 
        LAN.NUMLANC, 
        LAN.VLRLANC,
        CAB.OBSERVACAO AS HISTORICOORIGEM,
        LAN.COMPLHIST AS HISTORICOLAN,
        'ORIGEM PORTAL' AS RECEITADESPESA,
        CAB.CODNAT AS CODNATUREZA,
        NAT.DESCRNAT AS NATUREZA,
        CASE CAB.TIPMOV
        WHEN 'C' THEN 'COMPRAS - PORTAL DE COMPRAS'
        WHEN 'E' THEN 'DEV. COMPRAS - PORTAL DE COMPRAS'
        WHEN 'V' THEN 'VENDA - PORTAL DE VENDAS'
        WHEN 'D' THEN 'DEV. VENDA - PORTAL DE VENDAS'
        WHEN 'Q' THEN 'REQUISICAO - PORTAL DE MOV. INTERNA'
        WHEN 'L' THEN 'DEV. REQUISICAO - PORTAL DE MOV. INTERNA'
		WHEN 'F' THEN 'PRODUÇÃO - MÓDULO DE PRODUÇÃO'
		WHEN 'T' THEN 'TRANSFERENCIA'
        ELSE 'ORIGEM NAO ESPERADA = '|| CAB.TIPMOV
        END AS ORIGEM, 
        CAB.TIPMOV AS MOVIMENTO,
		CASE WHEN LAN.TIPLANC = 'D' THEN 'RED' ELSE 'BLUE' END AS FGCOLOR
        
FROM TCBLAN LAN
INNER JOIN TCBPLA PLA ON (PLA.CODCTACTB = LAN.CODCTACTB)
INNER JOIN TCBINT IT ON (IT.CODEMP=LAN.CODEMP AND IT.REFERENCIA=LAN.REFERENCIA AND IT.NUMLANC=LAN.NUMLANC AND IT.TIPLANC=LAN.TIPLANC AND IT.NUMLOTE=LAN.NUMLOTE AND IT.SEQUENCIA = LAN.SEQUENCIA)
INNER JOIN TGFCAB CAB ON (CAB.NUNOTA = IT.NUNICO AND IT.ORIGEM = 'E')
INNER JOIN TGFPAR PAR ON (PAR.CODPARC = CAB.CODPARC)
INNER JOIN TGFNAT NAT ON (NAT.CODNAT = CAB.CODNAT)
INNER JOIN TGFTOP TOP ON (TOP.CODTIPOPER = CAB.CODTIPOPER AND TOP.DHALTER = CAB.DHTIPOPER)

WHERE    	LAN.CODEMP = :CODEMP   
AND      	((LAN.CODCTACTB = :CODCTACTB) OR (:CODCTACTB IS NULL)) 
AND      	((LAN.TIPLANC = :TIPLANC) OR (:TIPLANC = 'A')) 
AND      	LAN.REFERENCIA >= :REFERENCIAINI
AND       	LAN.REFERENCIA <= :REFERENCIAFIM
AND       	((LAN.NUMLOTE >= :NUMLOTEINI) OR (:NUMLOTEINI IS NULL))
AND       	((LAN.NUMLOTE <= :NUMLOTEFIM) OR (:NUMLOTEFIM IS NULL))
AND			((CAB.NUNOTA = :NUNICO) OR (:NUNICO IS NULL))

UNION ALL

SELECT  FIN.CODEMP,
		LAN.CODCTACTB,
		PLA.CTACTB,
		PLA.DESCRCTA,
        FIN.NUFIN AS NUMERO_UNICO, 
        FIN.NUMNOTA AS NUMNOTA, 
        FIN.CODPARC AS PARCEIRO,
		PAR.NOMEPARC AS NOMEPARC,
        FIN.CODTIPOPER AS OPERACAO,
		TOP.DESCROPER AS DESCROPER,
        CASE WHEN LAN.TIPLANC = 'D' THEN 'DEBITO' ELSE 'CREDITO' END AS TIPLANC,
        LAN.NUMLOTE, 
        LAN.NUMLANC, 
        LAN.VLRLANC,
        FIN.HISTORICO AS HISTORICOORIGEM,
        LAN.COMPLHIST AS HISTORICOLAN,
        CASE WHEN FIN.RECDESP = 1 THEN 'RECEITA' ELSE 'DESPESA' END AS RECEITADESPESA,
        FIN.CODNAT AS CODNATUREZA,
        NAT.DESCRNAT AS NATUREZA,
        'LANÇAMENTO FINANCEIRO' AS ORIGEM, 
        'FINANCEIRO' AS MOVIMENTO,
		CASE WHEN LAN.TIPLANC = 'D' THEN 'RED' ELSE 'BLUE' END AS FGCOLOR


FROM TCBLAN LAN
INNER JOIN TCBPLA PLA ON (PLA.CODCTACTB = LAN.CODCTACTB)
INNER JOIN TCBINT IT ON (IT.CODEMP=LAN.CODEMP AND IT.REFERENCIA=LAN.REFERENCIA AND IT.NUMLANC=LAN.NUMLANC AND IT.TIPLANC=LAN.TIPLANC AND IT.NUMLOTE=LAN.NUMLOTE AND IT.SEQUENCIA = LAN.SEQUENCIA)
INNER JOIN TGFFIN FIN ON (FIN.NUFIN = IT.NUNICO AND IT.ORIGEM = 'F')
INNER JOIN TGFPAR PAR ON (PAR.CODPARC = FIN.CODPARC)
INNER JOIN TGFNAT NAT ON (NAT.CODNAT = FIN.CODNAT)
INNER JOIN TGFTOP TOP ON (TOP.CODTIPOPER = FIN.CODTIPOPER AND TOP.DHALTER = FIN.DHTIPOPER)

WHERE     	LAN.CODEMP = :CODEMP   
AND        	((LAN.CODCTACTB = :CODCTACTB) OR (:CODCTACTB IS NULL)) 
AND     	((LAN.TIPLANC = :TIPLANC) OR (:TIPLANC = 'A')) 
AND     	LAN.REFERENCIA >= :REFERENCIAINI
AND     	LAN.REFERENCIA <= :REFERENCIAFIM
AND        ((LAN.NUMLOTE >= :NUMLOTEINI) OR (:NUMLOTEINI IS NULL))
AND        ((LAN.NUMLOTE <= :NUMLOTEFIM) OR (:NUMLOTEFIM IS NULL))
AND			((FIN.NUFIN = :NUNICO) OR (:NUNICO IS NULL))

UNION ALL

SELECT  FIN.CODEMP,
		LAN.CODCTACTB,
		PLA.CTACTB,
		PLA.DESCRCTA,
        FIN.NUFIN AS NUMERO_UNICO, 
        FIN.NUMNOTA AS NUMNOTA, 
        FIN.CODPARC AS PARCEIRO,
		PAR.NOMEPARC AS NOMEPARC,
        FIN.CODTIPOPERBAIXA AS OPERACAO,
		TOP.DESCROPER AS DESCROPER,
        CASE WHEN LAN.TIPLANC = 'D' THEN 'DEBITO' ELSE 'CREDITO' END AS TIPLANC,
        LAN.NUMLOTE, 
        LAN.NUMLANC, 
        LAN.VLRLANC,
        FIN.HISTORICO AS HISTORICOORIGEM,
        LAN.COMPLHIST AS HISTORICOLAN,
        CASE WHEN FIN.RECDESP = 1 THEN 'RECEITA' ELSE 'DESPESA' END AS RECEITADESPESA,
        FIN.CODNAT AS CODNATUREZA,
        NAT.DESCRNAT AS NATUREZA,
        'BAIXA DE TITULO' AS ORIGEM, 
        'BAIXA' AS MOVIMENTO,
		CASE WHEN LAN.TIPLANC = 'D' THEN 'RED' ELSE 'BLUE' END AS FGCOLOR


FROM TCBLAN LAN
INNER JOIN TCBPLA PLA ON (PLA.CODCTACTB = LAN.CODCTACTB)
INNER JOIN TCBINT IT ON (IT.CODEMP=LAN.CODEMP AND IT.REFERENCIA=LAN.REFERENCIA AND IT.NUMLANC=LAN.NUMLANC AND IT.TIPLANC=LAN.TIPLANC AND IT.NUMLOTE=LAN.NUMLOTE AND IT.SEQUENCIA = LAN.SEQUENCIA)
INNER JOIN TGFFIN FIN ON (FIN.NUFIN = IT.NUNICO AND IT.ORIGEM = 'B')
INNER JOIN TGFPAR PAR ON (PAR.CODPARC = FIN.CODPARC)
INNER JOIN TGFNAT NAT ON (NAT.CODNAT = FIN.CODNAT)
INNER JOIN TGFTOP TOP ON (TOP.CODTIPOPER = FIN.CODTIPOPERBAIXA AND TOP.DHALTER = FIN.DHTIPOPERBAIXA)

WHERE     	LAN.CODEMP = :CODEMP   
AND        	((LAN.CODCTACTB = :CODCTACTB) OR (:CODCTACTB IS NULL)) 
AND     	((LAN.TIPLANC = :TIPLANC) OR (:TIPLANC = 'A')) 
AND     	LAN.REFERENCIA >= :REFERENCIAINI
AND        	LAN.REFERENCIA <= :REFERENCIAFIM
AND        	((LAN.NUMLOTE >= :NUMLOTEINI) OR (:NUMLOTEINI IS NULL))
AND        	((LAN.NUMLOTE <= :NUMLOTEFIM) OR (:NUMLOTEFIM IS NULL))
AND			((FIN.NUFIN = :NUNICO) OR (:NUNICO IS NULL))

UNION ALL

SELECT  FIN.CODEMP,
		LAN.CODCTACTB,
		PLA.CTACTB,
		PLA.DESCRCTA,
        FIN.NUFIN AS NUMERO_UNICO, 
        FIN.NUMNOTA AS NUMNOTA, 
        FIN.CODPARC AS PARCEIRO,
		PAR.NOMEPARC AS NOMEPARC,
        FIN.CODTIPOPER AS OPERACAO,
		TOP.DESCROPER AS DESCROPER,
        CASE WHEN LAN.TIPLANC = 'D' THEN 'DEBITO' ELSE 'CREDITO' END AS TIPLANC,
        LAN.NUMLOTE, 
        LAN.NUMLANC, 
        LAN.VLRLANC,
        FIN.HISTORICO AS HISTORICOORIGEM,
        LAN.COMPLHIST AS HISTORICOLAN,
        CASE WHEN FIN.RECDESP = 1 THEN 'RECEITA' ELSE 'DESPESA' END AS RECEITADESPESA,
        FIN.CODNAT AS CODNATUREZA,
        NAT.DESCRNAT AS NATUREZA,
        'RENEGOCIACAO' AS ORIGEM, 
        'RENEGOCIACAO' AS MOVIMENTO,
		CASE WHEN LAN.TIPLANC = 'D' THEN 'RED' ELSE 'BLUE' END AS FGCOLOR


FROM TCBLAN LAN
INNER JOIN TCBPLA PLA ON (PLA.CODCTACTB = LAN.CODCTACTB)
INNER JOIN TCBINT IT ON (IT.CODEMP=LAN.CODEMP AND IT.REFERENCIA=LAN.REFERENCIA AND IT.NUMLANC=LAN.NUMLANC AND IT.TIPLANC=LAN.TIPLANC AND IT.NUMLOTE=LAN.NUMLOTE AND IT.SEQUENCIA = LAN.SEQUENCIA)
INNER JOIN TGFFIN FIN ON (FIN.NUFIN = IT.NUNICO AND IT.ORIGEM = 'R')
INNER JOIN TGFPAR PAR ON (PAR.CODPARC = FIN.CODPARC)
INNER JOIN TGFNAT NAT ON (NAT.CODNAT = FIN.CODNAT)
INNER JOIN TGFTOP TOP ON (TOP.CODTIPOPER = FIN.CODTIPOPER AND TOP.DHALTER = FIN.DHTIPOPER)


WHERE     	LAN.CODEMP = :CODEMP   
AND        	((LAN.CODCTACTB = :CODCTACTB) OR (:CODCTACTB IS NULL)) 
AND     	((LAN.TIPLANC = :TIPLANC) OR (:TIPLANC = 'A')) 
AND     	LAN.REFERENCIA >= :REFERENCIAINI
AND        	LAN.REFERENCIA <= :REFERENCIAFIM
AND        	((LAN.NUMLOTE >= :NUMLOTEINI) OR (:NUMLOTEINI IS NULL))
AND        	((LAN.NUMLOTE <= :NUMLOTEFIM) OR (:NUMLOTEFIM IS NULL))
AND			((FIN.NUFIN = :NUNICO) OR (:NUNICO IS NULL))

UNION ALL

SELECT  0 AS CODEMP,
		LAN.CODCTACTB,
		PLA.CTACTB,
		PLA.DESCRCTA,
        MBC.NUBCO AS NUMERO_UNICO, 
        MBC.NUMDOC AS NUMNOTA, 
        0 AS PARCEIRO,
		CTA.DESCRICAO AS NOMEPARC,
        MBC.CODTIPOPER AS OPERACAO,
		TOP.DESCROPER AS DESCROPER,
        CASE WHEN LAN.TIPLANC = 'D' THEN 'DEBITO' ELSE 'CREDITO' END AS TIPLANC,
        LAN.NUMLOTE, 
        LAN.NUMLANC, 
        LAN.VLRLANC,
        MBC.HISTORICO AS HISTORICOORIGEM,
        LAN.COMPLHIST AS HISTORICOLAN,
        CASE WHEN MBC.RECDESP = 1 THEN 'RECEITA' ELSE 'DESPESA' END AS RECEITADESPESA,
        0 AS CODNATUREZA,
        'MOV. BANCARIO' AS NATUREZA,
        'MOV. BANCARIO' AS ORIGEM, 
        'MOV. BANCARIO' AS MOVIMENTO,
		CASE WHEN LAN.TIPLANC = 'D' THEN 'RED' ELSE 'BLUE' END AS FGCOLOR


FROM TCBLAN LAN
INNER JOIN TCBPLA PLA ON (PLA.CODCTACTB = LAN.CODCTACTB)
INNER JOIN TCBINT IT ON (IT.CODEMP=LAN.CODEMP AND IT.REFERENCIA=LAN.REFERENCIA AND IT.NUMLANC=LAN.NUMLANC AND IT.TIPLANC=LAN.TIPLANC AND IT.NUMLOTE=LAN.NUMLOTE AND IT.SEQUENCIA = LAN.SEQUENCIA)
INNER JOIN TGFMBC MBC ON (MBC.NUBCO = IT.NUNICO AND IT.ORIGEM = 'M')
INNER JOIN TGFTOP TOP ON (TOP.CODTIPOPER = MBC.CODTIPOPER AND TOP.DHALTER = MBC.DHTIPOPER)
INNER JOIN TSICTA CTA ON (CTA.CODCTABCOINT = MBC.CODCTABCOINT)


WHERE     	LAN.CODEMP = :CODEMP   
AND        	((LAN.CODCTACTB = :CODCTACTB) OR (:CODCTACTB IS NULL)) 
AND     	((LAN.TIPLANC = :TIPLANC) OR (:TIPLANC = 'A')) 
AND     	LAN.REFERENCIA >= :REFERENCIAINI
AND        	LAN.REFERENCIA <= :REFERENCIAFIM
AND        	((LAN.NUMLOTE >= :NUMLOTEINI) OR (:NUMLOTEINI IS NULL))
AND        	((LAN.NUMLOTE <= :NUMLOTEFIM) OR (:NUMLOTEFIM IS NULL))
AND			((MBC.NUBCO = :NUNICO) OR (:NUNICO IS NULL))

UNION ALL

SELECT  LAN.CODEMP,
		LAN.CODCTACTB,
		PLA.CTACTB,
		PLA.DESCRCTA,
        0 AS NUMERO_UNICO, 
        0 AS NUMNOTA, 
        0 AS PARCEIRO,
		'SEM PARCEIRO - LANCAMENTO MANUAL' AS NOMEPARC,
        0 AS OPERACAO,
		'SEM OPERAÇÃO - LANÇAMENTO MANUAL' AS DESCROPER,
        CASE WHEN LAN.TIPLANC = 'D' THEN 'DEBITO' ELSE 'CREDITO' END AS TIPLANC,
        LAN.NUMLOTE, 
        LAN.NUMLANC, 
        LAN.VLRLANC,
        'SEM HISTORICO ORIGEM - LCT MANUAL' AS HISTORICOORIGEM,
        LAN.COMPLHIST AS HISTORICOLAN,
        'LCTO MANUAL' AS RECEITADESPESA,
        0 AS CODNATUREZA,
        'SEM NATUREZA - LCTO MANUAL' AS NATUREZA,
        'SEM ORIGEM - LCTO MANUAL' AS ORIGEM, 
        'MANUAL' AS MOVIMENTO,
		CASE WHEN LAN.TIPLANC = 'D' THEN 'RED' ELSE 'BLUE' END AS FGCOLOR


FROM TCBLAN LAN
INNER JOIN TCBPLA PLA ON (PLA.CODCTACTB = LAN.CODCTACTB)

WHERE     	LAN.CODEMP = :CODEMP   
AND        	((LAN.CODCTACTB = :CODCTACTB) OR (:CODCTACTB IS NULL)) 
AND     	((LAN.TIPLANC = :TIPLANC) OR (:TIPLANC = 'A')) 
AND     	LAN.REFERENCIA >= :REFERENCIAINI
AND        	LAN.REFERENCIA <= :REFERENCIAFIM
AND        	((LAN.NUMLOTE >= :NUMLOTEINI) OR (:NUMLOTEINI IS NULL))
AND        	((LAN.NUMLOTE <= :NUMLOTEFIM) OR (:NUMLOTEFIM IS NULL))
AND      	NOT EXISTS (SELECT 1 FROM TCBINT IT
						WHERE IT.CODEMP=LAN.CODEMP 
						AND IT.REFERENCIA=LAN.REFERENCIA 
						AND IT.NUMLANC=LAN.NUMLANC 
						AND IT.TIPLANC=LAN.TIPLANC 
						AND IT.NUMLOTE=LAN.NUMLOTE)

ORDER BY 1, 5, 13, 10 DESC