services:
  nfsesvc:
    build: .
    image: nfsesvc:latest
    ports:
      - target: 8080
        published: 0
        protocol: tcp
    environment:
      - SERVER_PORT=8080
      - NFSE_ENDPOINT=https://homologacao.seu-provider.gov.br/ws
      - NFSE_TIMEOUT_MS=30000
      - KEYSTORE_PATH=/certs/client.p12
      - KEYSTORE_PASSWORD=changeit
      - KEYSTORE_TYPE=PKCS12
      - TRUSTSTORE_PATH=/certs/truststore.jks
      - TRUSTSTORE_PASSWORD=changeit
      - TRUSTSTORE_TYPE=JKS
    volumes:
      - ./certs:/certs:ro
