

SELECT DISTINCT
ORD.CODEMP,
EMP.RAZAOSOCIAL,
ENDI.NOMEEND,
EMP.NUMEND,
EMP.COMPLEMENTO,
BAI.NOMEBAI,
CID.NOMECID,
UFS.UF,
EMP.CEP,
EMP.CGC
FROM TGFORD ORD
INNER JOIN TSIEMP EMP ON ORD.CODEMP = EMP.CODEMP
INNER JOIN TSIEND ENDI on EMP.CODEND = ENDI.CODEND
INNER JOIN TSIBAI BAI on EMP.CODBAI = BAI.CODBAI
INNER JOIN TSICID CID on EMP.CODCID = CID.CODCID
INNER JOIN TSIUFS UFS ON CID.UF = UFS.CODUF
INNER JOIN TGFCAB CAB ON ORD.ORDEMCARGA = CAB.ORDEMCARGA
INNER JOIN TGFPAR PAR ON ORD.CODPARCTRANSP = PAR.CODPARC
WHERE
PAR.TRANSPORTADORA = 'S'


UPDATE TGFITE
SELECT * FROM TGFVEI
SELECT * FROM TGFPAR WHERE TRANSPORTADORA = 'S'
SELECT ORDEMCARGA FROM TGFCAB WHERE ORDEMCARGA IS NOT NULL
SELECT  
CODEMP,
RAZAOSOCIAL,
CODEND,
NUMEND,
COMPLEMENTO,
CODBAI,
CODCID,
CEP,
TELEFONE,
CGC,
INSCESTAD,
INSCMUN,
CODMUN
FROM TSIEMP



SELECT OPC.* 
FROM TDDCAM CAM 
JOIN TDDOPC OPC ON OPC.NUCAMPO = CAM.NUCAMPO
WHERE CAM.NOMETAB='TGFORD' AND CAM.NOMECAMPO='CODTIPPARC'
ORDER BY OPC.ORDEM