SELECT
    TESTE,
    NUBCO,
    DHCONCILIACAO,
    DTLANC,
    NUMDOC,
    CODAGE,
    CODCTABCO,
    DESCRICAO,
    HISTORICO,
    SALDO_INI,
    VLRMOV,
    SUM(SALDO_INI + VLRMOV) OVER (ORDER BY DHCONCILIACAO, NUBCO) AS VLRMOV_ACC
FROM (
    SELECT
        ROW_NUMBER() OVER (ORDER BY MBC.DHCONCILIACAO, MBC.NUBCO) AS TESTE,
        MBC.NUBCO,
        MBC.DHCONCILIACAO,
        MBC.DTLANC,
        MBC.NUMDOC,
        CTA.CODAGE,
        CTA.CODCTABCO,
        CTA.DESCRICAO,
        MBC.HISTORICO,
        CASE WHEN ROW_NUMBER() OVER (ORDER BY MBC.DHCONCILIACAO, MBC.NUBCO) = 1 
        THEN  
        (SELECT DISTINCT
            SUM(SALDO_INI) AS SALDO_INI
        FROM (
            SELECT DISTINCT
                CTA.SALDOBCO AS SALDO_INI
            FROM TSICTA CTA
            INNER JOIN TGFMBC MBC ON CTA.CODCTABCOINT = MBC.CODCTABCOINT
            WHERE (CTA.CODEMP = 60) AND (MBC.CODCTABCOINT = 1)
            UNION ALL
            SELECT DISTINCT
                SUM(CASE
                        WHEN (MBC.DHCONCILIACAO >= TO_DATE('2022-01-01', 'YYYY-MM-DD')
                            AND MBC.DHCONCILIACAO < TO_DATE('2023-07-03', 'YYYY-MM-DD'))
                        THEN MBC.VLRLANC * MBC.RECDESP
                        ELSE 0
                    END) AS SALDO_INI
            FROM TGFMBC MBC
            INNER JOIN TSICTA CTA ON MBC.CODCTABCOINT = CTA.CODCTABCOINT
            WHERE (CTA.CODEMP = 60) AND (MBC.CODCTABCOINT = 1)
        ))
        ELSE 0 END SALDO_INI,
        MBC.VLRLANC * MBC.RECDESP AS VLRMOV
    FROM
        TGFMBC MBC
    INNER JOIN TSICTA CTA ON MBC.CODCTABCOINT = CTA.CODCTABCOINT
    WHERE
        CTA.CODEMP = 60
        AND MBC.CODCTABCOINT = 1
        AND (MBC.DHCONCILIACAO >= TO_DATE('2023-07-01', 'YYYY-MM-DD')
        AND MBC.DHCONCILIACAO <= TO_DATE('2023-07-31', 'YYYY-MM-DD'))
) SUBQUERY;










SELECT
    ROW_NUMBER() OVER (ORDER BY MBC.DHCONCILIACAO, MBC.NUBCO) AS TESTE,
    MBC.NUBCO,
    MBC.DHCONCILIACAO,
    MBC.DTLANC,
    MBC.NUMDOC,
    CTA.CODAGE,
    CTA.CODCTABCO,
    CTA.DESCRICAO,
    MBC.HISTORICO,
    CASE WHEN ROW_NUMBER() OVER (ORDER BY MBC.DHCONCILIACAO, MBC.NUBCO) = 1 
    THEN  
    (SELECT DISTINCT
        SUM(SALDO_INI) AS SALDO_INI
    FROM (
        SELECT DISTINCT
            CTA.SALDOBCO AS SALDO_INI
        FROM TSICTA CTA
        INNER JOIN TGFMBC MBC ON CTA.CODCTABCOINT = MBC.CODCTABCOINT
        WHERE (CTA.CODEMP = 60) AND (MBC.CODCTABCOINT = 1)
        UNION ALL
        SELECT DISTINCT
            SUM(CASE
                    WHEN (MBC.DHCONCILIACAO >= TO_DATE('2022-01-01', 'YYYY-MM-DD')
                        AND MBC.DHCONCILIACAO < TO_DATE('2023-07-03', 'YYYY-MM-DD'))
                    THEN MBC.VLRLANC * MBC.RECDESP
                    ELSE 0
                END) AS SALDO_INI
        FROM TGFMBC MBC
        INNER JOIN TSICTA CTA ON MBC.CODCTABCOINT = CTA.CODCTABCOINT
        WHERE (CTA.CODEMP = 60) AND (MBC.CODCTABCOINT = 1)
    ))
    ELSE 0 END SALDO_INI,
    MBC.VLRLANC * MBC.RECDESP AS VLRMOV
    
    
FROM
    TGFMBC MBC
INNER JOIN TSICTA CTA ON MBC.CODCTABCOINT = CTA.CODCTABCOINT
WHERE
    CTA.CODEMP = 60
    AND MBC.CODCTABCOINT = 1
    AND (MBC.DHCONCILIACAO >= TO_DATE('2023-07-01', 'YYYY-MM-DD')
    AND MBC.DHCONCILIACAO <= TO_DATE('2023-07-31', 'YYYY-MM-DD'))
--ORDER BY 1






---SALDO INICIAL NO SALDO ACUMULADO
(SUM(SUM(MBC.VLRLANC*MBC.RECDESP) +
(
CASE WHEN ROWNUM = 1 THEN
(SELECT DISTINCT
SUM(SALDO_INI) AS SALDO_INI
FROM
(
SELECT DISTINCT
CTA.SALDOBCO AS SALDO_INI
FROM TSICTA CTA
INNER JOIN TGFMBC MBC ON CTA.CODCTABCOINT = MBC.CODCTABCOINT
WHERE (CTA.CODEMP = $P{P_EMPRESA}) AND (MBC.CODCTABCOINT = $P{P_CONTA})
UNION ALL
SELECT DISTINCT
SUM(CASE WHEN (MBC.DHCONCILIACAO >= '01/01/2022'
AND MBC.DHCONCILIACAO < TRUNC($P{P_P0}))
THEN MBC.VLRLANC * MBC.RECDESP ELSE 0
END) AS SALDO_INI
FROM TGFMBC MBC
INNER JOIN TSICTA CTA ON MBC.CODCTABCOINT = CTA.CODCTABCOINT
WHERE (CTA.CODEMP = $P{P_EMPRESA}) AND (MBC.CODCTABCOINT = $P{P_CONTA}))) ELSE 0 END
)
) OVER (ORDER BY MBC.NUBCO ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW)) AS VLRMOV_ACC





WHERE
CTA.CODEMP = $P{P_EMPRESA} AND MBC.CODCTABCOINT = $P{P_CONTA}
AND ((MBC.DHCONCILIACAO >= TRUNC($P{P_P0}))
AND (MBC.DHCONCILIACAO <= TRUNC($P{P_P1})))


GROUP BY
ROWNUM,
MBC.NUBCO,
MBC.DHCONCILIACAO,
MBC.DTLANC,
MBC.NUMDOC,
CTA.CODAGE,
CTA.CODCTABCO,
CTA.DESCRICAO,
MBC.HISTORICO,
MBC.VLRLANC*MBC.RECDESP

ORDER BY MBC.NUBCO