CREATE OR REPLACE PROCEDURE STP_INS_CODPARC_LANC_SKW
AS
P_COUNT             INT;
P_COUNTPARCZERO     INT;

BEGIN

/* Verifica se existe lançamentos sem CODPARC do ano atual e ano anterior*/
SELECT    COUNT(NUMLANC) INTO P_COUNT
FROM     TCBLAN
WHERE     ((AD_CODPARC = 0) OR (AD_CODPARC IS NULL))
AND     REFERENCIA >= ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -24)
AND 	(SELECT NVL(PLA.AD_EXIGPARCLCONT,'N') FROM TCBPLA PLA WHERE PLA.CODCTACTB=TCBLAN.CODCTACTB) = 'S';

IF P_COUNT <> 0 THEN

UPDATE TCBLAN SET AD_CODPARC = 0
WHERE    AD_CODPARC IS NULL
AND     REFERENCIA >= ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -24)
AND		(SELECT NVL(PLA.AD_EXIGPARCLCONT,'N') FROM TCBPLA PLA WHERE PLA.CODCTACTB=TCBLAN.CODCTACTB) = 'S';

COMMIT;

UPDATE    TCBLAN SET AD_CODPARC = ( SELECT MAX(CODPARC)
									FROM     VIEW_ORIGEM_LANCAMENTO_SKW V
									WHERE    V.CODEMP = TCBLAN.CODEMP
									AND      V.REFERENCIA = TCBLAN.REFERENCIA
									AND      V.NUMLOTE = TCBLAN.NUMLOTE
									AND      V.NUMLANC = TCBLAN.NUMLANC
									AND      V.TIPLANC = TCBLAN.TIPLANC
									AND      V.SEQUENCIA = TCBLAN.SEQUENCIA
									)
WHERE
(SELECT NVL(PLA.AD_EXIGPARCLCONT,'N') FROM TCBPLA PLA WHERE PLA.CODCTACTB=TCBLAN.CODCTACTB) = 'S'
AND    (AD_CODPARC IS NULL OR AD_CODPARC = 0)
AND     REFERENCIA >= ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -24);

COMMIT;

END IF;

END; 
/
/
