CREATE OR REPLACE TRIGGER "TRG_INC_TCBINT_CODPARC" 
AFTER INSERT ON TCBINT
FOR EACH ROW
DECLARE

    P_CODPARC    INT;
        
    
BEGIN
        
    IF    :NEW.ORIGEM = 'E' THEN
    
    SELECT    CODPARC INTO P_CODPARC
    FROM    TGFCAB
    WHERE    NUNOTA = :NEW.NUNICO;
    
    UPDATE    TCBLAN SET AD_CODPARC = P_CODPARC
    WHERE    CODEMP = :NEW.CODEMP
    AND        REFERENCIA = :NEW.REFERENCIA
    AND        NUMLOTE = :NEW.NUMLOTE
    AND        NUMLANC = :NEW.NUMLANC
    AND        TIPLANC = :NEW.TIPLANC
    AND        SEQUENCIA = :NEW.SEQUENCIA
    AND     (SELECT NVL(PLA.AD_EXIGPARCLCONT,'N') FROM TCBPLA PLA WHERE PLA.CODCTACTB=TCBLAN.CODCTACTB) = 'S';    
    
    END    IF;
    
    IF    :NEW.ORIGEM = 'F' THEN
    
    SELECT    CODPARC INTO P_CODPARC
    FROM    TGFFIN
    WHERE    NUFIN = :NEW.NUNICO;
    
    UPDATE    TCBLAN SET AD_CODPARC = P_CODPARC
    WHERE    CODEMP = :NEW.CODEMP
    AND        REFERENCIA = :NEW.REFERENCIA
    AND        NUMLOTE = :NEW.NUMLOTE
    AND        NUMLANC = :NEW.NUMLANC
    AND        TIPLANC = :NEW.TIPLANC
    AND        SEQUENCIA = :NEW.SEQUENCIA
    AND        (SELECT NVL(PLA.AD_EXIGPARCLCONT,'N') FROM TCBPLA PLA WHERE PLA.CODCTACTB=TCBLAN.CODCTACTB) = 'S';        
    
    END    IF;
    
    
    IF    :NEW.ORIGEM = 'B' THEN
    
    SELECT    CODPARC INTO P_CODPARC
    FROM    TGFFIN
    WHERE    NUFIN = :NEW.NUNICO;
    
    UPDATE    TCBLAN SET AD_CODPARC = P_CODPARC
    WHERE    CODEMP = :NEW.CODEMP
    AND        REFERENCIA = :NEW.REFERENCIA
    AND        NUMLOTE = :NEW.NUMLOTE
    AND        NUMLANC = :NEW.NUMLANC
    AND        TIPLANC = :NEW.TIPLANC
    AND        SEQUENCIA = :NEW.SEQUENCIA
    AND        (SELECT NVL(PLA.AD_EXIGPARCLCONT,'N') FROM TCBPLA PLA WHERE PLA.CODCTACTB=TCBLAN.CODCTACTB) = 'S';            
    
    END    IF;
    
    IF    :NEW.ORIGEM = 'R' THEN
    
    SELECT    CODPARC INTO P_CODPARC
    FROM    TGFFIN
    WHERE    NUFIN = :NEW.NUNICO;
    
    UPDATE    TCBLAN SET AD_CODPARC = P_CODPARC
    WHERE    CODEMP = :NEW.CODEMP
    AND        REFERENCIA = :NEW.REFERENCIA
    AND        NUMLOTE = :NEW.NUMLOTE
    AND        NUMLANC = :NEW.NUMLANC
    AND        TIPLANC = :NEW.TIPLANC
    AND        SEQUENCIA = :NEW.SEQUENCIA
    AND        (SELECT NVL(PLA.AD_EXIGPARCLCONT,'N') FROM TCBPLA PLA WHERE PLA.CODCTACTB=TCBLAN.CODCTACTB) = 'S';            
    
    END    IF;
       
END;
/
