SELECT
MARCA, 'Periodo 1: '||SUBSTR(:P_PERIODO.INI, LENGTH(:P_PERIODO.INI) - 4, 5)||' - '||SUBSTR(:P_PERIODO.FIN, LENGTH(:P_PERIODO.FIN) - 4, 5)AS PERIODO,SUM(JUL_QTDPREV) AS JUL_QTDPREV, SUM(JUL_QTDREAL) AS JUL_QTDREAL,  SUM(JUL_VLR_PREV) AS JUL_VLR_PREV, SUM(JUL_VLR_REAL) AS JUL_VLR_REAL, SUM(AGO_QTDPREV) AS AGO_QTDPREV, SUM(AGO_QTDREAL) AS AGO_QTDREAL, SUM(AGO_VLR_PREV) AS AGO_VLR_PREV, SUM(AGO_VLR_REAL) AS AGO_VLR_REAL, SUM(SET_QTDPREV) AS SET_QTDPREV, SUM(SET_QTDREAL) AS SET_QTDREAL, SUM(SET_VLR_PREV) AS SET_VLR_PREV, SUM(SET_VLR_REAL) AS SET_VLR_REAL, SUM(OUT_QTDPREV) AS OUT_QTDPREV, SUM(OUT_QTDREAL) AS OUT_QTDREAL, SUM(OUT_VLR_PREV) AS OUT_VLR_PREV, SUM(OUT_VLR_REAL) AS OUT_VLR_REAL, SUM(NOV_QTDPREV) AS NOV_QTDPREV, SUM(NOV_QTDREAL) AS NOV_QTDREAL, SUM(NOV_VLR_PREV) AS NOV_VLR_PREV, SUM(NOV_VLR_REAL) AS NOV_VLR_REAL, SUM(DEZ_QTDPREV) AS DEZ_QTDPREV, SUM(DEZ_QTDREAL) AS DEZ_QTDREAL, SUM(DEZ_VLR_PREV) AS DEZ_VLR_PREV, SUM(DEZ_VLR_REAL) AS DEZ_VLR_REAL, SUM(JAN_QTDPREV) AS JAN_QTDPREV, SUM(JAN_QTDREAL) AS JAN_QTDREAL, SUM(JAN_VLR_PREV) AS JAN_VLR_PREV, SUM(JAN_VLR_REAL) AS JAN_VLR_REAL, SUM(FEV_QTDPREV) AS FEV_QTDPREV, SUM(FEV_QTDREAL) AS FEV_QTDREAL, SUM(FEV_VLR_PREV) AS FEV_VLR_PREV, SUM(FEV_VLR_REAL) AS FEV_VLR_REAL, SUM(MAR_QTDPREV) AS MAR_QTDPREV, SUM(MAR_QTDREAL) AS MAR_QTDREAL, SUM(MAR_VLR_PREV) AS MAR_VLR_PREV, SUM(MAR_VLR_REAL) AS MAR_VLR_REAL, SUM(ABR_QTDPREV) AS ABR_QTDPREV, SUM(ABR_QTDREAL) AS ABR_QTDREAL, SUM(ABR_VLR_PREV) AS ABR_VLR_PREV, SUM(ABR_VLR_REAL) AS ABR_VLR_REAL, SUM(MAI_QTDPREV) AS MAI_QTDPREV, SUM(MAI_QTDREAL) AS MAI_QTDREAL, SUM(MAI_VLR_PREV) AS MAI_VLR_PREV, SUM(MAI_VLR_REAL) AS MAI_VLR_REAL, SUM(JUN_QTDPREV) AS JUN_QTDPREV, SUM(JUN_QTDREAL) AS JUN_QTDREAL, SUM(JUN_VLR_PREV) AS JUN_VLR_PREV, SUM(JUN_VLR_REAL) AS JUN_VLR_REAL, SUM(TTL_QTDPREV) AS TTL_QTDPREV, SUM(TTL_QTDREAL) AS TTL_QTDREAL, SUM(TTL_VLR_PREV) AS TTL_VLR_PREV, SUM(TTL_VLR_REAL) AS TTL_VLR_REAL 

FROM
(


---------------------------------------------------------------- NIVEL 3

SELECT
T.*,
(JUL_QTDPREV + AGO_QTDPREV + SET_QTDPREV + OUT_QTDPREV+NOV_QTDPREV+DEZ_QTDPREV+JAN_QTDPREV+FEV_QTDPREV+MAR_QTDPREV+ABR_QTDPREV+MAI_QTDPREV+JUN_QTDPREV) AS TTL_QTDPREV,
(JUL_QTDREAL + AGO_QTDREAL + SET_QTDREAL + OUT_QTDREAL+NOV_QTDREAL+DEZ_QTDREAL+JAN_QTDREAL+FEV_QTDREAL+MAR_QTDREAL+ABR_QTDREAL+MAI_QTDREAL+JUN_QTDREAL) AS TTL_QTDREAL,
(JUL_VLR_PREV + AGO_VLR_PREV + SET_VLR_PREV + OUT_VLR_PREV+NOV_VLR_PREV+DEZ_VLR_PREV+JAN_VLR_PREV+FEV_VLR_PREV+MAR_VLR_PREV+ABR_VLR_PREV+MAI_VLR_PREV+JUN_VLR_PREV) AS TTL_VLR_PREV,
(JUL_VLR_REAL + AGO_VLR_REAL + SET_VLR_REAL + OUT_VLR_REAL+NOV_VLR_REAL+DEZ_VLR_REAL+JAN_VLR_REAL+FEV_VLR_REAL+MAR_VLR_REAL+ABR_VLR_REAL+MAI_VLR_REAL+JUN_VLR_REAL) AS TTL_VLR_REAL



FROM (

---------------------------------------------------------------- NIVEL 2
SELECT 
A.MARCA,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 7 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN QTDPREV ELSE 0 END) AS JUL_QTDPREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 7 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN QTDREAL ELSE 0 END) AS JUL_QTDREAL,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 7 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN (QTDPREV * PRECOLT) ELSE 0 END) AS JUL_VLR_PREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 7 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN (VLRREAL) ELSE 0 END) AS JUL_VLR_REAL,

SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 8 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN QTDPREV ELSE 0 END) AS AGO_QTDPREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 8 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN QTDREAL ELSE 0 END) AS AGO_QTDREAL,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 8 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN (QTDPREV * PRECOLT) ELSE 0 END) AS AGO_VLR_PREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 8 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN (VLRREAL) ELSE 0 END) AS AGO_VLR_REAL,

SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 9 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN QTDPREV ELSE 0 END) AS SET_QTDPREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 9 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN QTDREAL ELSE 0 END) AS SET_QTDREAL,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 9 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN (QTDPREV * PRECOLT) ELSE 0 END) AS SET_VLR_PREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 9 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN (VLRREAL) ELSE 0 END) AS SET_VLR_REAL,

SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 10 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN QTDPREV ELSE 0 END) AS OUT_QTDPREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 10 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN QTDREAL ELSE 0 END) AS OUT_QTDREAL,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 10 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN (QTDPREV * PRECOLT) ELSE 0 END) AS OUT_VLR_PREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 10 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN (VLRREAL) ELSE 0 END) AS OUT_VLR_REAL,

SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 11 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN QTDPREV ELSE 0 END) AS NOV_QTDPREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 11 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN QTDREAL ELSE 0 END) AS NOV_QTDREAL,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 11 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN (QTDPREV * PRECOLT) ELSE 0 END) AS NOV_VLR_PREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 11 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN (VLRREAL) ELSE 0 END) AS NOV_VLR_REAL,

SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 12 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN QTDPREV ELSE 0 END) AS DEZ_QTDPREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 12 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN QTDREAL ELSE 0 END) AS DEZ_QTDREAL,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 12 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN (QTDPREV * PRECOLT) ELSE 0 END) AS DEZ_VLR_PREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 12 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN (VLRREAL) ELSE 0 END) AS DEZ_VLR_REAL,

SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 1 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN QTDPREV ELSE 0 END) AS JAN_QTDPREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 1 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN QTDREAL ELSE 0 END) AS JAN_QTDREAL,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 1 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN (QTDPREV * PRECOLT) ELSE 0 END) AS JAN_VLR_PREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 1 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN (VLRREAL) ELSE 0 END) AS JAN_VLR_REAL,

SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 2 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN QTDPREV ELSE 0 END) AS FEV_QTDPREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 2 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN QTDREAL ELSE 0 END) AS FEV_QTDREAL,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 2 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN (QTDPREV * PRECOLT) ELSE 0 END) AS FEV_VLR_PREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 2 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN (VLRREAL) ELSE 0 END) AS FEV_VLR_REAL,

SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 3 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN QTDPREV ELSE 0 END) AS MAR_QTDPREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 3 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN QTDREAL ELSE 0 END) AS MAR_QTDREAL,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 3 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN (QTDPREV * PRECOLT) ELSE 0 END) AS MAR_VLR_PREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 3 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN (VLRREAL) ELSE 0 END) AS MAR_VLR_REAL,

SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 4 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN QTDPREV ELSE 0 END) AS ABR_QTDPREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 4 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN QTDREAL ELSE 0 END) AS ABR_QTDREAL,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 4 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN (QTDPREV * PRECOLT) ELSE 0 END) AS ABR_VLR_PREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 4 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN (VLRREAL) ELSE 0 END) AS ABR_VLR_REAL,

SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 5 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN QTDPREV ELSE 0 END) AS MAI_QTDPREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 5 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN QTDREAL ELSE 0 END) AS MAI_QTDREAL,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 5 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN (QTDPREV * PRECOLT) ELSE 0 END) AS MAI_VLR_PREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 5 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN (VLRREAL) ELSE 0 END) AS MAI_VLR_REAL,

SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 6 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN QTDPREV ELSE 0 END) AS JUN_QTDPREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 6 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN QTDREAL ELSE 0 END) AS JUN_QTDREAL,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 6 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN (QTDPREV * PRECOLT) ELSE 0 END) AS JUN_VLR_PREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 6 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN (VLRREAL) ELSE 0 END) AS JUN_VLR_REAL

FROM
(
---------------------------------------------------------------------------- NIVEL 1
SELECT MET.DTREF, NVL(MET.CODVEND,0) AS CODVEND, NVL(MET.CODPARC,0) AS CODPARC, NVL(MET.MARCA,0) AS MARCA,NVL(VGF.CODCENCUS,0) AS CODCENCUS, NVL(MET.QTDPREV,0) AS QTDPREV, SUM(NVL(VGF.QTD,0)) AS QTDREAL,NVL(PRC.VLRVENDALT,0)AS PRECOLT, SUM(NVL(VGF.VLR,0)) AS VLRREAL
FROM TGFMET MET
LEFT JOIN VGF_VENDAS_SATIS VGF ON MET.DTREF = TRUNC(VGF.DTMOV,'MM') AND MET.CODVEND = VGF.CODVEND AND MET.CODPARC = VGF.CODPARC AND MET.MARCA = VGF.MARCA AND VGF.BONIFICACAO = 'N'
LEFT JOIN AD_PRECOMARCA PRC ON (MET.MARCA = PRC.MARCA AND PRC.CODMETA = MET.CODMETA AND PRC.DTREF = (SELECT MAX(DTREF) FROM AD_PRECOMARCA WHERE CODMETA = MET.CODMETA AND DTREF <= MET.DTREF AND MARCA = MET.MARCA))
WHERE 
MET.CODMETA = :P_CODMETA
AND MET.DTREF BETWEEN :P_PERIODO.INI   AND  :P_PERIODO.FIN
AND ((:P_NTEMMETA = 'S' AND (MET.QTDPREV <> 0 OR MET.QTDREAL <> 0)) OR :P_NTEMMETA = 'N')
AND (VGF.CODGRUPOPROD = :P_GRUPOPROD OR :P_GRUPOPROD IS NULL)

GROUP BY MET.DTREF,NVL(MET.CODVEND,0),NVL(MET.CODPARC,0),NVL(MET.MARCA,0),NVL(VGF.CODCENCUS,0), NVL(MET.QTDPREV,0), NVL(PRC.VLRVENDALT,0)
---------------------------------------------------------------- NIVEL 1

)A
INNER JOIN TGFPAR PAR ON A.CODPARC = PAR.CODPARC
INNER JOIN TGFVEN VEN ON A.CODVEND = VEN.CODVEND
WHERE
(VEN.CODVEND IN :P_CODVEND)
AND (VEN.CODGER IN :P_CODGER)
AND (PAR.CODPARC = :P_CODPARC OR :P_CODPARC IS NULL)
AND (A.MARCA IN (SELECT MARCA FROM TGFPRO WHERE CODPROD IN :P_MARCA))
AND (A.CODCENCUS = :P_CR OR :P_CR IS NULL)
AND
(
VEN.CODVEND = (SELECT CODVEND FROM TSIUSU WHERE CODUSU = STP_GET_CODUSULOGADO) ---CONSULTA VENDEDOR
OR VEN.CODVEND IN (SELECT VEN.CODVEND FROM TGFVEN VEN, TSIUSU USU WHERE USU.CODVEND = VEN.CODGER AND USU.CODUSU = STP_GET_CODUSULOGADO) ---CONSULTA GERENTE
OR (SELECT AD_GESTOR_META FROM TSIUSU WHERE CODUSU = STP_GET_CODUSULOGADO) = 'S' ---CONSULTA MASTER
)
GROUP BY A.MARCA
	
------------------------------------------------------------------- NIVEL 2	
)T

	
---------------------------------------------------------------- NIVEL 3	
)
GROUP BY MARCA

UNION ALL

SELECT
MARCA, 'Periodo 2: '||SUBSTR(:P_PERIODO1.INI, LENGTH(:P_PERIODO1.INI) - 4, 5)||' - '||SUBSTR(:P_PERIODO1.FIN, LENGTH(:P_PERIODO1.FIN) - 4, 5)AS PERIODO,SUM(JUL_QTDPREV) AS JUL_QTDPREV, SUM(JUL_QTDREAL) AS JUL_QTDREAL,  SUM(JUL_VLR_PREV) AS JUL_VLR_PREV, SUM(JUL_VLR_REAL) AS JUL_VLR_REAL, SUM(AGO_QTDPREV) AS AGO_QTDPREV, SUM(AGO_QTDREAL) AS AGO_QTDREAL, SUM(AGO_VLR_PREV) AS AGO_VLR_PREV, SUM(AGO_VLR_REAL) AS AGO_VLR_REAL, SUM(SET_QTDPREV) AS SET_QTDPREV, SUM(SET_QTDREAL) AS SET_QTDREAL, SUM(SET_VLR_PREV) AS SET_VLR_PREV, SUM(SET_VLR_REAL) AS SET_VLR_REAL, SUM(OUT_QTDPREV) AS OUT_QTDPREV, SUM(OUT_QTDREAL) AS OUT_QTDREAL, SUM(OUT_VLR_PREV) AS OUT_VLR_PREV, SUM(OUT_VLR_REAL) AS OUT_VLR_REAL, SUM(NOV_QTDPREV) AS NOV_QTDPREV, SUM(NOV_QTDREAL) AS NOV_QTDREAL, SUM(NOV_VLR_PREV) AS NOV_VLR_PREV, SUM(NOV_VLR_REAL) AS NOV_VLR_REAL, SUM(DEZ_QTDPREV) AS DEZ_QTDPREV, SUM(DEZ_QTDREAL) AS DEZ_QTDREAL, SUM(DEZ_VLR_PREV) AS DEZ_VLR_PREV, SUM(DEZ_VLR_REAL) AS DEZ_VLR_REAL, SUM(JAN_QTDPREV) AS JAN_QTDPREV, SUM(JAN_QTDREAL) AS JAN_QTDREAL, SUM(JAN_VLR_PREV) AS JAN_VLR_PREV, SUM(JAN_VLR_REAL) AS JAN_VLR_REAL, SUM(FEV_QTDPREV) AS FEV_QTDPREV, SUM(FEV_QTDREAL) AS FEV_QTDREAL, SUM(FEV_VLR_PREV) AS FEV_VLR_PREV, SUM(FEV_VLR_REAL) AS FEV_VLR_REAL, SUM(MAR_QTDPREV) AS MAR_QTDPREV, SUM(MAR_QTDREAL) AS MAR_QTDREAL, SUM(MAR_VLR_PREV) AS MAR_VLR_PREV, SUM(MAR_VLR_REAL) AS MAR_VLR_REAL, SUM(ABR_QTDPREV) AS ABR_QTDPREV, SUM(ABR_QTDREAL) AS ABR_QTDREAL, SUM(ABR_VLR_PREV) AS ABR_VLR_PREV, SUM(ABR_VLR_REAL) AS ABR_VLR_REAL, SUM(MAI_QTDPREV) AS MAI_QTDPREV, SUM(MAI_QTDREAL) AS MAI_QTDREAL, SUM(MAI_VLR_PREV) AS MAI_VLR_PREV, SUM(MAI_VLR_REAL) AS MAI_VLR_REAL, SUM(JUN_QTDPREV) AS JUN_QTDPREV, SUM(JUN_QTDREAL) AS JUN_QTDREAL, SUM(JUN_VLR_PREV) AS JUN_VLR_PREV, SUM(JUN_VLR_REAL) AS JUN_VLR_REAL, SUM(TTL_QTDPREV) AS TTL_QTDPREV, SUM(TTL_QTDREAL) AS TTL_QTDREAL, SUM(TTL_VLR_PREV) AS TTL_VLR_PREV, SUM(TTL_VLR_REAL) AS TTL_VLR_REAL 

FROM
(


---------------------------------------------------------------- NIVEL 3

SELECT
T.*,
(JUL_QTDPREV + AGO_QTDPREV + SET_QTDPREV + OUT_QTDPREV+NOV_QTDPREV+DEZ_QTDPREV+JAN_QTDPREV+FEV_QTDPREV+MAR_QTDPREV+ABR_QTDPREV+MAI_QTDPREV+JUN_QTDPREV) AS TTL_QTDPREV,
(JUL_QTDREAL + AGO_QTDREAL + SET_QTDREAL + OUT_QTDREAL+NOV_QTDREAL+DEZ_QTDREAL+JAN_QTDREAL+FEV_QTDREAL+MAR_QTDREAL+ABR_QTDREAL+MAI_QTDREAL+JUN_QTDREAL) AS TTL_QTDREAL,
(JUL_VLR_PREV + AGO_VLR_PREV + SET_VLR_PREV + OUT_VLR_PREV+NOV_VLR_PREV+DEZ_VLR_PREV+JAN_VLR_PREV+FEV_VLR_PREV+MAR_VLR_PREV+ABR_VLR_PREV+MAI_VLR_PREV+JUN_VLR_PREV) AS TTL_VLR_PREV,
(JUL_VLR_REAL + AGO_VLR_REAL + SET_VLR_REAL + OUT_VLR_REAL+NOV_VLR_REAL+DEZ_VLR_REAL+JAN_VLR_REAL+FEV_VLR_REAL+MAR_VLR_REAL+ABR_VLR_REAL+MAI_VLR_REAL+JUN_VLR_REAL) AS TTL_VLR_REAL



FROM (

---------------------------------------------------------------- NIVEL 2
SELECT 
A.MARCA,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 7 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN QTDPREV ELSE 0 END) AS JUL_QTDPREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 7 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN QTDREAL ELSE 0 END) AS JUL_QTDREAL,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 7 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN (QTDPREV * PRECOLT) ELSE 0 END) AS JUL_VLR_PREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 7 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN (VLRREAL) ELSE 0 END) AS JUL_VLR_REAL,

SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 8 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN QTDPREV ELSE 0 END) AS AGO_QTDPREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 8 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN QTDREAL ELSE 0 END) AS AGO_QTDREAL,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 8 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN (QTDPREV * PRECOLT) ELSE 0 END) AS AGO_VLR_PREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 8 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN (VLRREAL) ELSE 0 END) AS AGO_VLR_REAL,

SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 9 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN QTDPREV ELSE 0 END) AS SET_QTDPREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 9 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN QTDREAL ELSE 0 END) AS SET_QTDREAL,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 9 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN (QTDPREV * PRECOLT) ELSE 0 END) AS SET_VLR_PREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 9 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN (VLRREAL) ELSE 0 END) AS SET_VLR_REAL,

SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 10 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN QTDPREV ELSE 0 END) AS OUT_QTDPREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 10 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN QTDREAL ELSE 0 END) AS OUT_QTDREAL,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 10 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN (QTDPREV * PRECOLT) ELSE 0 END) AS OUT_VLR_PREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 10 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN (VLRREAL) ELSE 0 END) AS OUT_VLR_REAL,

SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 11 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN QTDPREV ELSE 0 END) AS NOV_QTDPREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 11 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN QTDREAL ELSE 0 END) AS NOV_QTDREAL,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 11 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN (QTDPREV * PRECOLT) ELSE 0 END) AS NOV_VLR_PREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 11 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN (VLRREAL) ELSE 0 END) AS NOV_VLR_REAL,

SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 12 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN QTDPREV ELSE 0 END) AS DEZ_QTDPREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 12 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN QTDREAL ELSE 0 END) AS DEZ_QTDREAL,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 12 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN (QTDPREV * PRECOLT) ELSE 0 END) AS DEZ_VLR_PREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 12 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.INI, 'YYYY') THEN (VLRREAL) ELSE 0 END) AS DEZ_VLR_REAL,

SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 1 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN QTDPREV ELSE 0 END) AS JAN_QTDPREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 1 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN QTDREAL ELSE 0 END) AS JAN_QTDREAL,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 1 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN (QTDPREV * PRECOLT) ELSE 0 END) AS JAN_VLR_PREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 1 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN (VLRREAL) ELSE 0 END) AS JAN_VLR_REAL,

SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 2 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN QTDPREV ELSE 0 END) AS FEV_QTDPREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 2 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN QTDREAL ELSE 0 END) AS FEV_QTDREAL,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 2 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN (QTDPREV * PRECOLT) ELSE 0 END) AS FEV_VLR_PREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 2 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN (VLRREAL) ELSE 0 END) AS FEV_VLR_REAL,

SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 3 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN QTDPREV ELSE 0 END) AS MAR_QTDPREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 3 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN QTDREAL ELSE 0 END) AS MAR_QTDREAL,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 3 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN (QTDPREV * PRECOLT) ELSE 0 END) AS MAR_VLR_PREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 3 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN (VLRREAL) ELSE 0 END) AS MAR_VLR_REAL,

SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 4 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN QTDPREV ELSE 0 END) AS ABR_QTDPREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 4 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN QTDREAL ELSE 0 END) AS ABR_QTDREAL,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 4 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN (QTDPREV * PRECOLT) ELSE 0 END) AS ABR_VLR_PREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 4 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN (VLRREAL) ELSE 0 END) AS ABR_VLR_REAL,

SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 5 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN QTDPREV ELSE 0 END) AS MAI_QTDPREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 5 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN QTDREAL ELSE 0 END) AS MAI_QTDREAL,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 5 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN (QTDPREV * PRECOLT) ELSE 0 END) AS MAI_VLR_PREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 5 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN (VLRREAL) ELSE 0 END) AS MAI_VLR_REAL,

SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 6 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN QTDPREV ELSE 0 END) AS JUN_QTDPREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 6 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN QTDREAL ELSE 0 END) AS JUN_QTDREAL,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 6 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN (QTDPREV * PRECOLT) ELSE 0 END) AS JUN_VLR_PREV,
SUM(CASE WHEN EXTRACT(MONTH FROM DTREF) = 6 AND EXTRACT(YEAR FROM DTREF) = TO_CHAR(:P_PERIODO.FIN, 'YYYY') THEN (VLRREAL) ELSE 0 END) AS JUN_VLR_REAL

FROM
(
---------------------------------------------------------------------------- NIVEL 1
SELECT MET.DTREF, NVL(MET.CODVEND,0) AS CODVEND, NVL(MET.CODPARC,0) AS CODPARC, NVL(MET.MARCA,0) AS MARCA,NVL(VGF.CODCENCUS,0) AS CODCENCUS, NVL(MET.QTDPREV,0) AS QTDPREV, SUM(NVL(VGF.QTD,0)) AS QTDREAL,NVL(PRC.VLRVENDALT,0)AS PRECOLT, SUM(NVL(VGF.VLR,0)) AS VLRREAL
FROM TGFMET MET
LEFT JOIN VGF_VENDAS_SATIS VGF ON MET.DTREF = TRUNC(VGF.DTMOV,'MM') AND MET.CODVEND = VGF.CODVEND AND MET.CODPARC = VGF.CODPARC AND MET.MARCA = VGF.MARCA AND VGF.BONIFICACAO = 'N'
LEFT JOIN AD_PRECOMARCA PRC ON (MET.MARCA = PRC.MARCA AND PRC.CODMETA = MET.CODMETA AND PRC.DTREF = (SELECT MAX(DTREF) FROM AD_PRECOMARCA WHERE CODMETA = MET.CODMETA AND DTREF <= MET.DTREF AND MARCA = MET.MARCA))
WHERE 
MET.CODMETA = :P_CODMETA
AND MET.DTREF BETWEEN :P_PERIODO1.INI   AND  :P_PERIODO1.FIN
AND ((:P_NTEMMETA = 'S' AND (MET.QTDPREV <> 0 OR MET.QTDREAL <> 0)) OR :P_NTEMMETA = 'N')
AND (VGF.CODGRUPOPROD = :P_GRUPOPROD OR :P_GRUPOPROD IS NULL)

GROUP BY MET.DTREF,NVL(MET.CODVEND,0),NVL(MET.CODPARC,0),NVL(MET.MARCA,0),NVL(VGF.CODCENCUS,0), NVL(MET.QTDPREV,0), NVL(PRC.VLRVENDALT,0)
---------------------------------------------------------------- NIVEL 1

)A
INNER JOIN TGFPAR PAR ON A.CODPARC = PAR.CODPARC
INNER JOIN TGFVEN VEN ON A.CODVEND = VEN.CODVEND
WHERE
(VEN.CODVEND IN :P_CODVEND)
AND (VEN.CODGER IN :P_CODGER)
AND (PAR.CODPARC = :P_CODPARC OR :P_CODPARC IS NULL)
AND (A.MARCA IN (SELECT MARCA FROM TGFPRO WHERE CODPROD IN :P_MARCA))
AND (A.CODCENCUS = :P_CR OR :P_CR IS NULL)
AND
(
VEN.CODVEND = (SELECT CODVEND FROM TSIUSU WHERE CODUSU = STP_GET_CODUSULOGADO) ---CONSULTA VENDEDOR
OR VEN.CODVEND IN (SELECT VEN.CODVEND FROM TGFVEN VEN, TSIUSU USU WHERE USU.CODVEND = VEN.CODGER AND USU.CODUSU = STP_GET_CODUSULOGADO) ---CONSULTA GERENTE
OR (SELECT AD_GESTOR_META FROM TSIUSU WHERE CODUSU = STP_GET_CODUSULOGADO) = 'S' ---CONSULTA MASTER
)
GROUP BY A.MARCA
	
------------------------------------------------------------------- NIVEL 2	
)T

	
---------------------------------------------------------------- NIVEL 3	
)
GROUP BY MARCA


ORDER BY 1,2