WITH TOTAL_BP_ATUAL AS (
    SELECT
        ID_CONTA_CONTABIL,
        SUM(BP_TECWAY) AS VALOR
    FROM BP_TECWAY
    WHERE
        MES = :VAR_MES
        AND ID_EMPRESA IN (:VAR_EMPRESA)
    GROUP BY
        ID_CONTA_CONTABIL
),

TOTAL_BP_ANTERIOR AS (
    SELECT
        ID_CONTA_CONTABIL,
        SUM(BP_TECWAY) AS VALOR
    FROM BP_TECWAY
    WHERE
        MES = CONCAT(
            SUBSTRING(:VAR_MES, 1, 2),
            '/',
            CAST(SUBSTRING(:VAR_MES, 4, 4) AS UNSIGNED) - 1
        )
        AND ID_EMPRESA IN (:VAR_EMPRESA)
    GROUP BY
        ID_CONTA_CONTABIL
),

TOTAL_DRE_ATUAL AS (
    SELECT
        ID_CONTA_CONTABIL,
        SUM(DRE_TECWAY) AS VALOR
    FROM DRE_TECWAY
    WHERE
        MES = :VAR_MES
        AND ID_EMPRESA IN (:VAR_EMPRESA)
    GROUP BY
        ID_CONTA_CONTABIL
),

TOTAL_DRE_ANTERIOR AS (
    SELECT
        ID_CONTA_CONTABIL,
        SUM(DRE_TECWAY) AS VALOR
    FROM DRE_TECWAY
    WHERE
        MES = CONCAT(
            SUBSTRING(:VAR_MES, 1, 2),
            '/',
            CAST(SUBSTRING(:VAR_MES, 4, 4) AS UNSIGNED) - 1
        )
        AND ID_EMPRESA IN (:VAR_EMPRESA)
    GROUP BY
        ID_CONTA_CONTABIL
)

SELECT DISTINCT
    SUB.ID_DET_INICIAL_NOTAS,
    SUB.DESCRICAO AS DESCRICAO_CONTA,

    COALESCE(
        SUM(
            CASE
                WHEN DETINI.TIPO = 'BP' THEN COALESCE(TOTAL_BP_ATUAL.VALOR, 0)
                WHEN DETINI.TIPO = 'DRE' THEN COALESCE(TOTAL_DRE_ATUAL.VALOR, 0)
                ELSE 0
            END
        ),
        0
    ) AS VALOR_ATUAL,

    COALESCE(
        SUM(
            CASE
                WHEN DETINI.TIPO = 'BP' THEN COALESCE(TOTAL_BP_ANTERIOR.VALOR, 0)
                WHEN DETINI.TIPO = 'DRE' THEN COALESCE(TOTAL_DRE_ANTERIOR.VALOR, 0)
                ELSE 0
            END
        ),
        0
    ) AS VALOR_ANTERIOR

FROM INICIAL_NOTAS INI

INNER JOIN DET_INICIAL_NOTAS DETINI
    ON INI.ID = DETINI.ID_INICIAL_NOTA

INNER JOIN SUB_DET_INICIAL_NOTAS SUB
    ON DETINI.ID = SUB.ID_DET_INICIAL_NOTAS

INNER JOIN CONTA_SUB_DET_INICIAL_NOTAS CONTA
    ON SUB.ID = CONTA.ID_SUB_DET_INICIAL_NOTAS

LEFT JOIN TOTAL_BP_ATUAL
    ON CONTA.ID_CONTA_CONTABIL = TOTAL_BP_ATUAL.ID_CONTA_CONTABIL

LEFT JOIN TOTAL_BP_ANTERIOR
    ON CONTA.ID_CONTA_CONTABIL = TOTAL_BP_ANTERIOR.ID_CONTA_CONTABIL

LEFT JOIN TOTAL_DRE_ATUAL
    ON CONTA.ID_CONTA_CONTABIL = TOTAL_DRE_ATUAL.ID_CONTA_CONTABIL

LEFT JOIN TOTAL_DRE_ANTERIOR
    ON CONTA.ID_CONTA_CONTABIL = TOTAL_DRE_ANTERIOR.ID_CONTA_CONTABIL

WHERE
    INI.MES_REFERENCIA = :VAR_MES

GROUP BY
    SUB.ID_DET_INICIAL_NOTAS,
    SUB.DESCRICAO

ORDER BY
    SUB.ID;