SELECT
    
    DET.ID,
    DET.ID_MES_REFERENCIA,
    DET.TITULO,
    DET.DESCRICAO,
    DET.ORDEM
FROM DET_INICIAL_NOTAS DET
  INNER JOIN INICIAL_NOTAS INI ON DET.ID_INICIAL_NOTA = INI.ID
WHERE
    DET.ID_MES_REFERENCIA = :VAR_MES
    AND INI.EMPRESA IN (:VAR_EMPRESA)