SELECT
    A.ORDEM AS HIERARQUIA,
    A.NOME_GRUPO AS DESCRICAO,
    NULL AS NOTA,
    SUM(
        CASE
            WHEN A.REFERENCIA = DATE(:VAR_DATA_REF_DRE)
            THEN IFNULL(A.VLRLANC, 0)
            ELSE 0
        END
    ) AS VALOR_ANO_ATUAL,
    SUM(
        CASE
            WHEN A.REFERENCIA = DATE_SUB(DATE(:VAR_DATA_REF_DRE), INTERVAL 1 YEAR)
            THEN IFNULL(A.VLRLANC, 0)
            ELSE 0
        END
    ) AS VALOR_ANO_ANTERIOR
FROM (
    SELECT
        D.ORDEM,
        D.NOME_GRUPO,
        R.REFERENCIA,
        C.PADRAO_CTACTB,
        IFNULL(B.VLRLANC, 0) AS VLRLANC
    FROM DET_DEMONSTRATIVO D
    INNER JOIN ESTR_DEMONSTRATIVOS E
        ON E.ID = D.ID_ESTR_DEMONSTRATIVO
    INNER JOIN DET_DEMONSTRATIVO_REFERENCIA R
        ON R.ID_DET_DEMONSTRATIVO = D.ID
    INNER JOIN DET_DEMONSTRATIVO_CTACTB C
        ON C.ID_DET_DEMONSTRATIVO_REFERENCIA = R.ID
    LEFT JOIN IMP_BASE_BALANCETE B
        ON B.CTACTB = C.PADRAO_CTACTB
        AND B.REFERENCIA = R.REFERENCIA
        AND B.CODEMP = :VAR_EMPRESA_DRE
        AND (
            B.CTACTB LIKE '3%'
            OR B.CTACTB LIKE '4%'
            OR B.CTACTB LIKE '5%'
        )
    WHERE
        E.ID = 3
        AND R.REFERENCIA IN (
            DATE(:VAR_DATA_REF_DRE),
            DATE_SUB(DATE(:VAR_DATA_REF_DRE), INTERVAL 1 YEAR)
        )
    GROUP BY
        D.ORDEM,
        D.NOME_GRUPO,
        R.REFERENCIA,
        C.PADRAO_CTACTB,
        IFNULL(B.VLRLANC, 0)
) A
GROUP BY
    A.ORDEM,
    A.NOME_GRUPO
ORDER BY
    A.ORDEM;
