SELECT 
    TGFFIN.ABATIMENTO AS ABATIMENTO,
    TGFFIN.ABATIMENTOCAN AS ABATIMENTOCAN,
    TGFFIN.AGENCIA_CMC7 AS AGENCIA_CMC7,
    TGFFIN.ALIQICMS AS ALIQICMS,
    TGFFIN.AUTORIZADO AS AUTORIZADO,
    TGFFIN.BAIXAAPI AS BAIXAAPI,
    TGFFIN.BASEICMS AS BASEICMS,
    TGFFIN.BASEINSS AS BASEINSS,
    TGFFIN.BASEIRF AS BASEIRF,
    TGFFIN.BLOQVAR AS BLOQVAR,
    TGFFIN.CARTA AS CARTA,
    TGFFIN.CARTAODESC AS CARTAODESC,
    TGFFIN.CGC_CPF_CMC7 AS CGC_CPF_CMC7,
    TGFFIN.CHAVECTE AS CHAVECTE,
    TGFFIN.CHAVECTEREF AS CHAVECTEREF,
    TGFFIN.CHAVENFEGNRE AS CHAVENFEGNRE,
    TGFFIN.CHEQUERASTREADO_CMC7 AS CHEQUERASTREADO_CMC7,
    TGFFIN.CLASSIFCESSAOOBRA AS CLASSIFCESSAOOBRA,
    TGFFIN.CODBARRA AS CODBARRA,
    TGFFIN.CODBCO AS CODBCO,
    TGFFIN.CODBCO_CMC7 AS CODBCO_CMC7,
    TGFFIN.CODCBE AS CODCBE,
    TGFFIN.CODCC AS CODCC,
    TGFFIN.CODCENCUS AS CODCENCUS,
    TGFFIN.CODCFO AS CODCFO,
    TGFFIN.CODCIDFIMCTE AS CODCIDFIMCTE,
    TGFFIN.CODCIDINICTE AS CODCIDINICTE,
    TGFFIN.CODCONTATO AS CODCONTATO,
    TGFFIN.CODCTABCOINT AS CODCTABCOINT,
    TGFFIN.CODEMP AS CODEMP,
    TGFFIN.CODEMPBAIXA AS CODEMPBAIXA,
    TGFFIN.CODFUNC AS CODFUNC,
    TGFFIN.CODIGOBARRA AS CODIGOBARRA,
    TGFFIN.CODIMOVELRURAL AS CODIMOVELRURAL,
    TGFFIN.CODIPTU AS CODIPTU,
    TGFFIN.CODLST AS CODLST,
    TGFFIN.CODMOEDA AS CODMOEDA,
    TGFFIN.CODNAT AS CODNAT,
    TGFFIN.CODOBRA AS CODOBRA,
    TGFFIN.CODOBSPADRAO AS CODOBSPADRAO,
    TGFFIN.CODPARC AS CODPARC,
    TGFFIN.CODPROJ AS CODPROJ,
    TGFFIN.CODRECEITA AS CODRECEITA,
    TGFFIN.CODREGUA AS CODREGUA,
    TGFFIN.CODTIPOPER AS CODTIPOPER,
    TGFFIN.CODTIPOPERBAIXA AS CODTIPOPERBAIXA,
    TGFFIN.CODTIPTIT AS CODTIPTIT,
    TGFFIN.CODTRIB AS CODTRIB,
    TGFFIN.CODUSU AS CODUSU,
    TGFFIN.CODUSUBAIXA AS CODUSUBAIXA,
    TGFFIN.CODUSUCOBR AS CODUSUCOBR,
    TGFFIN.CODVEICULO AS CODVEICULO,
    TGFFIN.CODVEND AS CODVEND,
    TGFFIN.CONTA_CMC7 AS CONTA_CMC7,
    TGFFIN.CUSTASPROCESSUAIS AS CUSTASPROCESSUAIS,
    TGFFIN.DEPOSITOJUDICIAL AS DEPOSITOJUDICIAL,
    TGFFIN.DESCRTPAGNFCE AS DESCRTPAGNFCE,
    TGFFIN.DESDOBDUPL AS DESDOBDUPL,
    TGFFIN.DESDOBRAMENTO AS DESDOBRAMENTO,
    TGFFIN.DESPADVOGADO AS DESPADVOGADO,
    TGFFIN.DESPCART AS DESPCART,
    TGFFIN.DHBAIXA AS DHBAIXA,
    TGFFIN.DHMOV AS DHMOV,
    TGFFIN.DHTIPOPER AS DHTIPOPER,
    TGFFIN.DHTIPOPERBAIXA AS DHTIPOPERBAIXA,
    TGFFIN.DH_IMPRESSAO AS DH_IMPRESSAO,
    TGFFIN.DIGSAFRA AS DIGSAFRA,
    TGFFIN.DTALTER AS DTALTER,
    TGFFIN.DTBAIXAPREV AS DTBAIXAPREV,

    -- EXEMPLO DE CAMPOS CALCULADOS ORGANIZADOS
    (
        CASE 
            WHEN NUANTBANC IS NOT NULL 
                 AND EXISTS (
                    SELECT 1 
                    FROM TGFANB 
                    WHERE NUFINTITORI = TGFFIN.NUFIN
                 ) 
            THEN 'S'
            ELSE 'N'
        END
    ) AS ANTECIPADO,

    (
        CASE 
            WHEN TGFFIN.DTVENC IS NULL THEN 0 
            ELSE
                CASE 
                    WHEN TGFFIN.DHBAIXA IS NOT NULL 
                         AND (TGFFIN.VLRBAIXA <> 0 OR TGFFIN.VLRDESC >= TGFFIN.VLRDESDOB)
                    THEN TRUNC(TGFFIN.DHBAIXA - TGFFIN.DTVENC)
                    ELSE TRUNC(TRUNC(SYSDATE) - TRUNC(TGFFIN.DTVENC))
                END
        END
    ) AS ATRASO,

    (
        SELECT PAR.CGC_CPF
        FROM TGFPAR PAR
        WHERE PAR.CODPARC = TGFFIN.CODPARC
    ) AS CGC_CPF_PARC,

    Banco.NOMEBCO AS l0_NOMEBCO,
    CentroResultado.DESCRCENCUS AS l1_DESCRCENCUS,
    ClassificacaoFiscalOperacao.DESCRCFO AS l2_DESCRCFO

FROM TGFFIN

LEFT JOIN (
    SELECT NOMEBCO, CODBCO 
    FROM TSIBCO
) Banco 
    ON TGFFIN.CODBCO = Banco.CODBCO

LEFT JOIN (
    SELECT DESCRCENCUS, CODCENCUS 
    FROM TSICUS
) CentroResultado 
    ON TGFFIN.CODCENCUS = CentroResultado.CODCENCUS

LEFT JOIN (
    SELECT CODCFO, DESCRCFO 
    FROM TGFCFO
) ClassificacaoFiscalOperacao 
    ON TGFFIN.CODCFO = ClassificacaoFiscalOperacao.CODCFO

WHERE 
    TGFFIN.RECDESP IN (1, -1)
    AND TGFFIN.PROVISAO IN ('N','S')
    AND TGFFIN.DHBAIXA IS NOT NULL
    AND TRUNC(TGFFIN.DHBAIXA) >= TRUNC(?)
    AND TRUNC(TGFFIN.DHBAIXA) <= TRUNC(?)
    AND TGFFIN.CODNAT IN (15010101)
    AND NOT (
        TGFFIN.PROVISAO = 'S'
        AND TGFFIN.DHBAIXA IS NOT NULL
        AND TGFFIN.ORIGEM = 'E'
    );