CREATE
OR REPLACE PROCEDURE "STP_ATUBASEPROV" AS FIELD_CODIGO NUMBER;

FIELD_ID NUMBER;
V_CODIGO NUMBER;
V_REF VARCHAR(100);
V_CODNAT NUMBER;
V_CODCENCUS NUMBER;
V_CODPROJ NUMBER;
V_VLRPREV NUMBER;
V_VLRREAL NUMBER;
V_SALDO NUMBER;
V_VLRAPROV NUMBER;
V_COUNT NUMBER;
V_COUNT2 NUMBER;
V_MAXSEQ NUMBER;
V_CODNAT2 NUMBER;
V_CODCENCUS2 NUMBER;
V_CODPROJ2 NUMBER;
V_VLRAPROV2 NUMBER;
V_MAXNUFIN NUMBER;
V_DHTOP DATE;
V_CODIGO2 NUMBER;
V_ID2 NUMBER;


CURSOR CUR_PROVISOES IS
SELECT
    CODIGO, REF, CODNAT,CODCENCUS,CODPROJ,VLRPREV,VLRREAL,SALDO,VLRAPROV
FROM
    (
        SELECT
            CODIGO,CODNAT,CODCENCUS,CODPROJ,ANO,MES,REF,VLRPREV,VLRREAL,VLRPREV - VLRREAL AS SALDO,
            CASE
                WHEN VLRPREV <= VLRREAL THEN 0 
                --WHEN MES < TO_CHAR(SYSDATE,'MM') THEN 0
                WHEN VLRPREV > VLRREAL THEN VLRPREV - VLRREAL
            END AS VLRAPROV
        FROM
            (
                WITH FIN AS (
                    SELECT
                        FIN.CODNAT,
                        FIN.CODCENCUS,
                        FIN.CODPROJ,
                        TO_CHAR(FIN.DHBAIXA, 'YYYY') AS ANO,
                        TO_CHAR(FIN.DHBAIXA, 'MM') AS MES,
                        TO_CHAR(FIN.DHBAIXA, 'MM-YYYY') AS REF,
                        0 AS VLRPREV,
                        SUM(NVL(FIN.VLRBAIXA, 0)) AS VLRREAL
                    FROM
                        VGF_RESULTADO_SATIS FIN
                    WHERE
                        FIN.DHBAIXA IS NOT NULL
                    GROUP BY
                        FIN.CODNAT,
                        FIN.CODCENCUS,
                        FIN.CODPROJ,
                        TO_CHAR(FIN.DHBAIXA, 'YYYY'),
                        TO_CHAR(FIN.DHBAIXA, 'MM'),
                        TO_CHAR(FIN.DHBAIXA, 'MM-YYYY')
                )
                SELECT
                    NAN.CODIGO,
                    MET.CODNAT,
                    MET.CODCENCUS,
                    MET.CODPROJ,
                    TO_CHAR(MET.DTREF, 'YYYY') AS ANO,
                    TO_CHAR(MET.DTREF, 'MM') AS MES,
                    TO_CHAR(MET.DTREF, 'MM-YYYY') AS REF,
                    ABS(PREVREC - PREVDESP) AS VLRPREV,
                    ABS(SUM(VLRREAL)) AS VLRREAL
                FROM TGFMET MET
                    INNER JOIN FIN ON MET.CODNAT = FIN.CODNAT AND (MET.CODPROJ = FIN.CODPROJ OR MET.CODPROJ = 0 ) AND (MET.CODCENCUS = FIN.CODCENCUS OR MET.CODCENCUS = 0) AND FIN.MES = TO_CHAR(MET.DTREF, 'MM')
                    INNER JOIN AD_PROVIFINAN NAN ON MET.CODMETA = NAN.CODMETA AND TO_CHAR(MET.DTREF, 'YYYY') = NAN.REF
                WHERE FIN.ANO = NAN.REF
                GROUP BY
                    NAN.CODIGO,
                    MET.CODNAT,
                    MET.CODCENCUS,
                    MET.CODPROJ,
                    TO_CHAR(MET.DTREF, 'YYYY'),
                    TO_CHAR(MET.DTREF, 'MM'),
                    TO_CHAR(MET.DTREF, 'MM-YYYY'),
                    ABS(PREVREC - PREVDESP)
            )
    );

CURSOR CUR_PROVISOES_FIN IS
SELECT
    CODIGO,
    ID,
    REF,
    CODNAT,
    CODCENCUS,
    CODPROJ,
    VLRAPROV
FROM
    AD_DETPROVFINAN
WHERE
    NUFIN IS NULL
    AND VLRAPROV > 0;

--CURSOR CUR_VERIFICACAO_FIN IS
BEGIN OPEN CUR_PROVISOES;

LOOP FETCH CUR_PROVISOES INTO V_CODIGO,
V_REF,
V_CODNAT,
V_CODCENCUS,
V_CODPROJ,
V_VLRPREV,
V_VLRREAL,
V_SALDO,
V_VLRAPROV;

EXIT
WHEN CUR_PROVISOES % NOTFOUND;

SELECT
    COUNT(*) INTO V_COUNT
FROM
    AD_DETPROVFINAN
WHERE
    CODIGO = V_CODIGO
    AND REF = V_REF
    AND CODNAT = V_CODNAT
    AND CODCENCUS = V_CODCENCUS
    AND CODPROJ = V_CODPROJ;

IF V_COUNT = 0 THEN
SELECT
    NVL(MAX(ID), 0) + 1 INTO V_MAXSEQ
FROM
    AD_DETPROVFINAN;

INSERT INTO
    AD_DETPROVFINAN (
        CODIGO,
        ID,
        REF,
        CODNAT,
        CODCENCUS,
        CODPROJ,
        VLRPREV,
        VLRREAL,
        SALDO,
        VLRAPROV
    )
VALUES
(
        V_CODIGO,
        V_MAXSEQ,
        V_REF,
        V_CODNAT,
        V_CODCENCUS,
        V_CODPROJ,
        V_VLRPREV,
        V_VLRREAL,
        V_SALDO,
        V_VLRAPROV
    );

COMMIT;

ELSE
SELECT
    COUNT(*) INTO V_COUNT2
FROM
    AD_DETPROVFINAN
WHERE
    CODIGO = V_CODIGO
    AND REF = V_REF
    AND CODNAT = V_CODNAT
    AND CODCENCUS = V_CODCENCUS
    AND CODPROJ = V_CODPROJ
    AND (
        VLRPREV <> V_VLRPREV
        OR VLRREAL <> V_VLRREAL
    );

IF V_COUNT2 > 0 THEN
UPDATE
    AD_DETPROVFINAN
SET
    VLRPREV = V_VLRPREV,
    VLRREAL = V_VLRREAL,
    SALDO = V_SALDO,
    VLRAPROV = V_VLRAPROV
WHERE
    CODIGO = V_CODIGO
    AND REF = V_REF
    AND CODNAT = V_CODNAT
    AND CODCENCUS = V_CODCENCUS
    AND CODPROJ = V_CODPROJ;

COMMIT;

END IF;

END IF;

END LOOP;

CLOSE CUR_PROVISOES;

OPEN CUR_PROVISOES_FIN;

LOOP FETCH CUR_PROVISOES_FIN INTO V_CODIGO2,
V_ID2,
V_REF,
V_CODNAT2,
V_CODCENCUS2,
V_CODPROJ2,
V_VLRAPROV2;

EXIT
WHEN CUR_PROVISOES_FIN % NOTFOUND;

SELECT
    NVL(MAX(NUFIN), 0) + 1 INTO V_MAXNUFIN
FROM
    TGFFIN;

SELECT
    MAX(DHALTER) INTO V_DHTOP
FROM
    TGFTOP
WHERE
    CODTIPOPER = 1300;

INSERT INTO
   TGFFIN ( NUFIN, CODEMP, NUMNOTA, SERIENOTA, DTNEG, DESDOBRAMENTO, DHMOV, DTVENCINIC, DTVENC, CODPARC, CODTIPOPER, DHTIPOPER, CODBCO, CODCTABCOINT, CODNAT, CODCENCUS, CODPROJ, 
   CODVEND, CODMOEDA, CODTIPTIT, VLRDESDOB, VLRVENDOR, VLRIRF, VLRISS, DESPCART, ISSRETIDO, VLRDESC, VLRMULTA, VLRINSS, TIPMULTA, VLRJURO, TIPJURO, BASEICMS, ALIQICMS, CODTIPOPERBAIXA, 
   DHTIPOPERBAIXA, VLRBAIXA, AUTORIZADO, RECDESP, PROVISAO, ORIGEM, TIPMARCCHEQ, NUNOTA, RATEADO, DTENTSAI, VLRPROV, IRFRETIDO, INSSRETIDO, CARTAODESC, DTALTER, NUMCONTRATO, ORDEMCARGA, 
   CODVEICULO, CODUSU, SEQUENCIA, VLRDESCEMBUT, VLRJUROEMBUT, VLRMULTAEMBUT, VLRMOEDA, VLRMOEDABAIXA, VLRMULTANEGOC, VLRJURONEGOC, VLRMULTALIB, VLRJUROLIB, NRODOCTEF, TPAGNFCE, BLOQVAR, 
   VLRHONOR, DTPRAZO, TIMBLOQUEADA, TIMTXADMGERALU, HISTORICO ) ( 
   SELECT
      V_MAXNUFIN, 1, 1, '', TO_DATE('01-' || V_REF), 1, TO_DATE('01-' || V_REF), TO_DATE('01-' || V_REF) , TO_DATE('01-' || V_REF), 1, 1300, V_DHTOP, 0, 0, V_CODNAT2, V_CODCENCUS2, 
      V_CODPROJ2, 0, 0 , 2, V_VLRAPROV2, 0, 0, 0, 0, 'N', 0, 0, 0, '1', 0, '1', 0, 0, 0, TO_DATE( '01/01/1998 00:00:00', 'MM/DD/YYYY HH24:MI:SS'), 0, 'N', - 1, 'S', 'F', 'I', NULL , 
      'N', TO_DATE('01-' || V_REF), 0, 'N', 'N', 0, SYSDATE, 0, 0, STP_GET_CODUSULOGADO, 0, 0, 0, 0, 0, 0 , 0, 0, 0, 0, 0, 0, '15', 'N', 0, TO_DATE('01-' || V_REF), 'N', 'S', 
      'GERADO PELO PROVISIONAMENTO AUTOMATICO COM BASE NO FINANCEIRO' 
   FROM
      DUAL );
COMMIT;


UPDATE AD_DETPROVFINAN SET NUFIN = V_MAXNUFIN WHERE CODIGO = V_CODIGO2 AND ID = V_ID2; 
COMMIT;

END LOOP;

CLOSE CUR_PROVISOES_FIN;

-- <ESCREVA SEU CÓDIGO AQUI (SERÁ EXECUTADO PARA CADA REGISTRO SELECIONADO)> --
--END LOOP;
-- <ESCREVA SEU CÓDIGO DE FINALIZAÇÃO AQUI> --
END;

/