SELECT
    ID_CONTA_CONTABIL,
    SUM(VALOR_TOTAL) AS VALOR_FINAL
FROM (
    SELECT
        c.ID_CONTA_CONTABIL,
        SUM(b.BP_TECWAY) AS VALOR_TOTAL
    FROM DET_INICIAL_NOTAS d
    INNER JOIN CONTAS_DET_INICIAL_NOTAS c
        ON c.ID_DET_INICIAL_NOTAS = d.ID
    INNER JOIN BP_TECWAY b
        ON b.ID_CONTA_CONTABIL = c.ID_CONTA_CONTABIL
       AND b.MES = d.ID_MES_REFERENCIA
    WHERE d.TIPO = 'BP'
    GROUP BY c.ID_CONTA_CONTABIL

    UNION ALL

    SELECT
        c.ID_CONTA_CONTABIL,
        SUM(dr.DRE_TECWAY) AS VALOR_TOTAL
    FROM DET_INICIAL_NOTAS d
    INNER JOIN CONTAS_DET_INICIAL_NOTAS c
        ON c.ID_DET_INICIAL_NOTAS = d.ID
    INNER JOIN DRE_TECWAY dr
        ON dr.ID_CONTA_CONTABIL = c.ID_CONTA_CONTABIL
       AND dr.MES = d.ID_MES_REFERENCIA
    WHERE d.TIPO = 'DRE'
    GROUP BY c.ID_CONTA_CONTABIL
) x
GROUP BY ID_CONTA_CONTABIL;
