SELECT
    DET.ID AS ID,
    DET.ID_MES_REFERENCIA AS ID_MES_REFERENCIA,
    DET.TITULO AS TITULO,
    DET.DESCRICAO AS DESCRICAO,
    DET.ORDEM AS ORDEM

FROM DET_INICIAL_NOTAS DET

INNER JOIN INICIAL_NOTAS INI
    ON DET.ID_INICIAL_NOTA = INI.ID

WHERE
    DET.ID_MES_REFERENCIA = :VAR_MES
    AND INI.ID_EMPRESA IN (:VAR_EMPRESA);