SELECT 
    atual.MES,
    atual.ID_EMPRESA,
    atual.ID_CONTA_CONTABIL,
    atual.VALOR_ATUAL,
    anterior.VALOR_ANTERIOR
FROM (
    SELECT 
        MES,
        ID_EMPRESA,
        ID_CONTA_CONTABIL,
        SUM(BP_TECWAY) AS VALOR_ATUAL
    FROM BP_TECWAY
    WHERE ID_CONTA_CONTABIL IN ('2.3.04.01.000009')
      AND MES = '12/2025'
      AND ID_EMPRESA = 999
      AND ID_HISTORICO > 0
    GROUP BY MES, ID_EMPRESA, ID_CONTA_CONTABIL
) atual
LEFT JOIN (
    SELECT 
        MES,
        ID_EMPRESA,
        ID_CONTA_CONTABIL,
        SUM(BP_TECWAY) AS VALOR_ANTERIOR
    FROM BP_TECWAY
    WHERE ID_HISTORICO > 0
    GROUP BY MES, ID_EMPRESA, ID_CONTA_CONTABIL
) anterior
ON anterior.ID_EMPRESA = atual.ID_EMPRESA
AND anterior.ID_CONTA_CONTABIL = atual.ID_CONTA_CONTABIL
AND STR_TO_DATE(CONCAT('01/', anterior.MES), '%d/%m/%Y') = 
    DATE_SUB(STR_TO_DATE(CONCAT('01/', atual.MES), '%d/%m/%Y'), INTERVAL 1 YEAR);