WITH UltimoPreco AS (
    SELECT
        TAB.CODTAB,
        NTA.NOMETAB,
        TAB.DTVIGOR,
        PRO.CODPROD,
        ISNULL(EXC.VLRVENDA,0) VLRVENDA_ATUAL,
        ROW_NUMBER() OVER (
            PARTITION BY TAB.CODTAB, PRO.CODPROD
            ORDER BY TAB.DTVIGOR DESC
        ) AS RN
    FROM TGFPRO PRO
    INNER JOIN TGFGRU GRU 
        ON PRO.CODGRUPOPROD = GRU.CODGRUPOPROD
    LEFT JOIN TGFEXC EXC 
        ON PRO.CODPROD = EXC.CODPROD
    LEFT JOIN TGFTAB TAB 
        ON EXC.NUTAB = TAB.NUTAB
    LEFT JOIN TGFNTA NTA 
        ON TAB.CODTAB = NTA.CODTAB
    WHERE 
        NTA.ATIVO = 'S' 
        AND PRO.ATIVO = 'S'
        AND PRO.CODPROD = 1716
        AND TAB.DTVIGOR <= '01/08/2025'
)
SELECT 
    CODTAB,
    NOMETAB,
    DTVIGOR,
    CODPROD,
    VLRVENDA_ATUAL
FROM UltimoPreco
WHERE RN = 1;
