FROM node:20

# Define o diretório de trabalho dentro do container
WORKDIR /app

# Copia os arquivos do projeto (se houver) para o container
COPY . .

# Comando padrão (pode ser sobrescrito pelo docker-compose)
CMD [ "yarn", "start" ]
