select distinct  CODPARCMATRIZ CODPARC, RAZAOSOCIAL NOMEPARC,LIMCRED LIMCREDTOTAL,LIMCREDCONSUM LIMCREDCONSED, LIMCREDISP LIMCREDDISP

from(

        SELECT
            COALESCE(PAR.CODPARCMATRIZ, PAR.CODPARC) AS CODPARCMATRIZ,
            COALESCE(PAR2.RAZAOSOCIAL, PAR.RAZAOSOCIAL) AS RAZAOSOCIAL,
            PAR2.ATIVO,
            NVL(PAR2.LIMCRED, 0) AS LIMCRED,
            SUM(NVL(FIN.VLRDESDOB, 0)) AS LIMCREDCONSUM,
            NVL(PAR2.LIMCRED, 0) - SUM(NVL(FIN.VLRDESDOB, 0)) AS LIMCREDISP
        FROM TGFPAR PAR 
        LEFT JOIN TGFFIN FIN ON PAR.CODPARC = FIN.CODPARC
        LEFT JOIN TGFPAR PAR2 ON PAR.CODPARCMATRIZ = PAR2.CODPARC
        LEFT JOIN TGFCAB CAB  ON FIN.NUNOTA = CAB.NUNOTA
        WHERE 
            FIN.RECDESP = 1 
            AND FIN.DHBAIXA IS NULL
            AND (CAB.STATUSNOTA = 'L' OR FIN.NUNOTA IS NULL)
            AND PAR.CLIENTE = 'S'

        GROUP BY
            COALESCE(PAR.CODPARCMATRIZ, PAR.CODPARC),
            COALESCE(PAR2.RAZAOSOCIAL, PAR.RAZAOSOCIAL),
            PAR2.ATIVO, PAR2.LIMCRED

        UNION ALL

        SELECT
            COALESCE(PAR.CODPARCMATRIZ, PAR.CODPARC) AS CODPARCMATRIZ,
            COALESCE(PAR2.RAZAOSOCIAL, PAR.RAZAOSOCIAL) AS RAZAOSOCIAL,
            PAR2.ATIVO,
            NVL(PAR2.LIMCRED, 0) AS LIMCRED,
            0 AS LIMCREDCONSUM,
            NVL(PAR2.LIMCRED, 0) AS LIMCREDISP
        FROM TGFPAR PAR
        LEFT JOIN TGFPAR PAR2 ON PAR.CODPARCMATRIZ = PAR2.CODPARC
        WHERE PAR.CLIENTE = 'S'
            AND COALESCE(PAR.CODPARCMATRIZ, PAR.CODPARC) IS NOT NULL
            AND COALESCE(PAR.CODPARCMATRIZ, PAR.CODPARC) NOT IN (
                SELECT
                    COALESCE(PAR.CODPARCMATRIZ, PAR.CODPARC)
                FROM TGFPAR PAR 
                LEFT JOIN TGFFIN FIN ON PAR.CODPARC = FIN.CODPARC
                LEFT JOIN TGFPAR PAR2 ON PAR.CODPARCMATRIZ = PAR2.CODPARC
                LEFT JOIN TGFCAB CAB  ON FIN.NUNOTA = CAB.NUNOTA
                WHERE 
                    FIN.RECDESP = 1 
                    AND FIN.DHBAIXA IS NULL
                    AND (CAB.STATUSNOTA = 'L' OR FIN.NUNOTA IS NULL)
                    AND PAR.CLIENTE = 'S'

                GROUP BY
                    COALESCE(PAR.CODPARCMATRIZ, PAR.CODPARC)
            )
)