SELECT
CAB.NUNOTA, ITE.SEQUENCIA, CAB.CODEMP, EMP.NOMEFANTASIA EMPRESA,
CAB.TIPMOV, TOP1.AD_COMPOE_FAT, CAB.DTNEG, TOP1.ATIVO,
CAB.CODNAT,NAT.DESCRNAT,NAT.ATIVA ATIVA _NAT, CAB.CODCENCUS, CAB.CODVEND,
CASE WHEN ISNULL(CAB.CODVEND, 0) = 0 THEN 'SEM INFORMACAO' ELSE VEN.APELIDO END AS VENDEDOR,
ISNULL(VEN.CODGER, 0) AS CODGER,
CASE WHEN ISNULL(VEN.CODGER, 0) = 0 THEN 'SEM INFORMACAO' ELSE VENG.APELIDO END AS GERENTE,
CAB.CODPARC, PAR.NOMEPARC, PAR.CODTIPPARC,
UPPER(CASE WHEN TPP.DESCRTIPPARC = '<SEM TIPO PARCEIRO>' THEN 'SEM INFORMACAO' ELSE TPP.DESCRTIPPARC END) AS DESCRTIPPARC,
PAR.CODCID, UPPER(CID.NOMECID) AS NOMECID, PAR.CODBAI, BAI.NOMEBAI,
CAB.CODTIPOPER, TOP1.DESCROPER,TOP1.AD_COMPOE_FAT,  ITE.CODPROD, PRO.DESCRPROD, ITE.CODVOL, ITE.VLRUNIT,
ITE.QTDNEG * CASE WHEN CAB.TIPMOV = 'D' THEN -1 ELSE 1 END AS QTDNEG,
ITE.VLRDESC * CASE WHEN CAB.TIPMOV = 'D' THEN -1 ELSE 1 END AS VLRDESC,
CASE WHEN CAB.TIPMOV = 'D' THEN (ITE.VLRTOT + ITE.VLRIPI + ITE.VLRSUBST - ITE.VLRDESC) * -1 ELSE 0 END AS VLRDEV,
CASE WHEN CAB.TIPMOV = 'D' THEN (ITE.VLRTOT + ITE.VLRIPI + ITE.VLRSUBST - ITE.VLRDESC) * -1 ELSE (ITE.VLRTOT + ITE.VLRIPI + ITE.VLRSUBST - ITE.VLRDESC) END AS TOTALLIQ,

ITE.VLRIPI * CASE WHEN CAB.TIPMOV = 'D' THEN -1 ELSE 1 END AS VLRIPI,
ITE.VLRSUBST * CASE WHEN CAB.TIPMOV = 'D' THEN -1 ELSE 1 END AS VLRSUBST,
ITE.VLRICMS * CASE WHEN CAB.TIPMOV = 'D' THEN -1 ELSE 1 END AS VLRICMS,


ISNULL(
    (SELECT SUM(VALOR) 
     FROM TGFDIN 
     WHERE NUNOTA = CAB.NUNOTA 
       AND SEQUENCIA = ITE.SEQUENCIA 
       AND CODIMP = 6), 0
) * CASE WHEN CAB.TIPMOV = 'D' THEN -1 ELSE 1 END AS VLRPIS,

ISNULL(
    (SELECT SUM(VALOR) 
     FROM TGFDIN 
     WHERE NUNOTA = CAB.NUNOTA 
       AND SEQUENCIA = ITE.SEQUENCIA 
       AND CODIMP = 7), 0
) * CASE WHEN CAB.TIPMOV = 'D' THEN -1 ELSE 1 END AS VLRCOFINS,


ISNULL(CUS1.CUSREP, 0) CUSREP_UN,
ISNULL(CUS1.CUSREP, 0) * ITE.QTDNEG * CASE WHEN CAB.TIPMOV = 'D' THEN -1 ELSE 1 END AS CUSREP_TOT,



(
  (ITE.VLRTOT - ITE.VLRDESC - ITE.VLRICMS)
  - ISNULL((SELECT SUM(VALOR) FROM TGFDIN WHERE NUNOTA = CAB.NUNOTA AND SEQUENCIA = ITE.SEQUENCIA AND CODIMP = 6), 0)
  - ISNULL((SELECT SUM(VALOR) FROM TGFDIN WHERE NUNOTA = CAB.NUNOTA AND SEQUENCIA = ITE.SEQUENCIA AND CODIMP = 7), 0)
  - ISNULL(CUS1.CUSREP, 0) * ITE.QTDNEG
) * CASE WHEN CAB.TIPMOV = 'D' THEN -1 ELSE 1 END AS MARGEMNON,

(
  (
    (ITE.VLRTOT - ITE.VLRDESC - ITE.VLRICMS)
    - ISNULL((SELECT SUM(VALOR) FROM TGFDIN WHERE NUNOTA = CAB.NUNOTA AND SEQUENCIA = ITE.SEQUENCIA AND CODIMP = 6), 0)
    - ISNULL((SELECT SUM(VALOR) FROM TGFDIN WHERE NUNOTA = CAB.NUNOTA AND SEQUENCIA = ITE.SEQUENCIA AND CODIMP = 7), 0)
    - ISNULL(CUS1.CUSREP, 0) * ITE.QTDNEG
  )
  * 100.0 
  / NULLIF((ITE.VLRTOT + ITE.VLRIPI + ITE.VLRSUBST - ITE.VLRDESC), 0)
) AS PERCMARGEM








FROM TGFCAB CAB
JOIN TGFITE ITE ON CAB.NUNOTA = ITE.NUNOTA
JOIN TGFPAR PAR ON CAB.CODPARC = PAR.CODPARC
JOIN TSICID CID ON PAR.CODCID = CID.CODCID
JOIN TSIBAI BAI ON PAR.CODBAI = BAI.CODBAI
JOIN TSIEMP EMP ON CAB.CODEMP = EMP.CODEMP
JOIN TGFNAT NAT ON CAB.CODNAT = NAT.CODNAT
JOIN TSICUS CUS ON CAB.CODCENCUS = CUS.CODCENCUS
JOIN TGFTOP TOP1 ON CAB.CODTIPOPER = TOP1.CODTIPOPER
JOIN TGFTPV TPV ON CAB.CODTIPVENDA = TPV.CODTIPVENDA AND TPV.DHALTER = CAB.DHTIPVENDA
JOIN TGFVEN VEN ON CAB.CODVEND = VEN.CODVEND
LEFT JOIN TGFVEN VENG ON VENG.CODVEND = VEN.CODGER
LEFT JOIN TGFPRO PRO ON ITE.CODPROD = PRO.CODPROD
LEFT JOIN TGFPAR PARM ON PARM.CODPARC = PAR.CODPARCMATRIZ
LEFT JOIN TGFTPP TPP ON PAR.CODTIPPARC = TPP.CODTIPPARC
LEFT JOIN TGFCUS CUS1 ON CUS1.CODPROD = ITE.CODPROD AND CUS1.CODEMP = 1 AND CUS1.DTATUAL = (SELECT MAX(DTATUAL)FROM TGFCUS WHERE DTATUAL <= CAB.DTNEG AND CODPROD = ITE.CODPROD AND CODEMP = 1)


WHERE

TOP1.DHALTER = (
  SELECT MAX(DHALTER)
  FROM TGFTOP
  WHERE CODTIPOPER = CAB.CODTIPOPER
)




AND CAB.DTNEG BETWEEN '01/08/2025' AND '31/08/2025'