SELECT
LPAD(CODIGO, 10, '0') AS CODIGO,
SUBSTR(LPAD(CODIGO, 10, '0'), 1, 2) AS GRAU1,
SUBSTR(LPAD(CODIGO, 10, '0'), 1, 4) AS GRAU2,
SUBSTR(LPAD(CODIGO, 10, '0'), 1, 6) AS GRAU3,
SUBSTR(LPAD(CODIGO, 10, '0'), 1, 8) AS GRAU4,
SUBSTR(LPAD(CODIGO, 10, '0'), 1, 10) AS GRAU5,
DESCRICAO,
SUM(VALOR) AS VALOR

FROM 
(


WITH DRE AS
(
SELECT 
DRE1.CODIGO,
DRE1.DESCRICAO,
DRE1.AD_TPPROD,
DRE1.TIPMOV
FROM AD_DREGERFIN DRE1
)

SELECT
DRE.CODIGO,
DRE.DESCRICAO,
SUM(ITE.VLRTOT + ITE.VLRIPI + ITE.VLRSUBST - ITE.VLRDESC) AS VALOR
FROM TGFCAB CAB
INNER JOIN TGFITE ITE ON CAB.NUNOTA = ITE.NUNOTA
INNER JOIN TGFTOP TOP ON CAB.CODTIPOPER = TOP.CODTIPOPER AND TOP.DHALTER = (SELECT MAX(DHALTER) FROM TGFTOP WHERE CODTIPOPER = CAB.CODTIPOPER)
INNER JOIN TGFPRO PRO ON ITE.CODPROD = PRO.CODPROD
INNER JOIN DRE ON (PRO.AD_TPPROD = DRE.AD_TPPROD OR DRE.AD_TPPROD = 7) AND (CAB.TIPMOV = DRE.TIPMOV OR DRE.TIPMOV = 'A')
WHERE TOP.GOLSINAL = -1
AND (CAB.DTNEG BETWEEN '01-01-2024' AND '31-01-2024')--:P_PERIODO.INI AND  :P_PERIODO.FIN)
--AND (CAB.CODEMP IN :P_EMPRESA)
AND TOP.TIPMOV IN ('V', 'D')
AND TOP.ATIVO = 'S'
AND PRO.AD_TPPROD IS NOT NULL
GROUP BY
DRE.CODIGO,
DRE.DESCRICAO


UNION ALL

SELECT
DRE1.CODIGO,
DRE1.DESCRICAO,
SUM(RES.VLRBAIXA) AS VALOR
FROM VGF_RESULTADO_GM RES
INNER JOIN AD_DREGERFINDETALHE DRE2 ON RES.CODNAT = DRE2.CODNAT
INNER JOIN AD_DREGERFIN DRE1 ON DRE2.CODIGO = DRE1.CODIGO
WHERE
(RES.DHBAIXA BETWEEN '01-01-2024' AND '31-01-2024')
GROUP BY
DRE1.CODIGO
,DRE1.DESCRICAO
)

GROUP BY
CODIGO,
DESCRICAO