/*
SUBSTR(LPAD(CODIGO, 10, '0'), 1, 2)||'00000000' AS GRAU1,
SUBSTR(LPAD(CODIGO, 10, '0'), 1, 4)||'000000' AS GRAU2,
SUBSTR(LPAD(CODIGO, 10, '0'), 1, 6)||'0000' AS GRAU3,
SUBSTR(LPAD(CODIGO, 10, '0'), 1, 8)||'00' AS GRAU4,
SUBSTR(LPAD(CODIGO, 10, '0'), 1, 10) AS GRAU5,
*/

WITH B AS (SELECT * FROM (SELECT LPAD(CODIGO, 10, '0') AS CODIGO, GRAU,ANALITICO,DESCRICAO FROM AD_DREGERFIN))
SELECT
DRE3.GRAU AS CODIGO,
B.DESCRICAO,
DRE3.VALOR,
CASE 
WHEN B.GRAU = 1 THEN '#8EA9DB' 
WHEN B.GRAU = 2 THEN '#c6d4ed'
WHEN B.GRAU = 3 THEN '#dde5f4'
WHEN B.GRAU = 4 THEN '#e8f5cc'
WHEN B.GRAU = 5 THEN '#f0eaf5'
END AS BKCOLOR
FROM
(
/*GRAU1*/
SELECT
SUBSTR(LPAD(CODIGO, 10, '0'), 1, 2)||'00000000' AS GRAU,
SUM(VALOR) AS VALOR

FROM 
(


WITH DRE AS
(
SELECT 
DRE1.CODIGO,
DRE1.DESCRICAO,
DRE1.AD_TPPROD,
DRE1.TIPMOV
FROM AD_DREGERFIN DRE1
)

SELECT
DRE.CODIGO,
DRE.DESCRICAO,
SUM(CASE WHEN CAB.TIPMOV = 'D' THEN (ITE.VLRTOT + ITE.VLRIPI + ITE.VLRSUBST - ITE.VLRDESC) * -1 ELSE (ITE.VLRTOT + ITE.VLRIPI + ITE.VLRSUBST - ITE.VLRDESC) END) AS VALOR
FROM TGFCAB CAB
INNER JOIN TGFITE ITE ON CAB.NUNOTA = ITE.NUNOTA
INNER JOIN TGFTOP TOP ON CAB.CODTIPOPER = TOP.CODTIPOPER AND TOP.DHALTER = (SELECT MAX(DHALTER) FROM TGFTOP WHERE CODTIPOPER = CAB.CODTIPOPER)
INNER JOIN TGFPRO PRO ON ITE.CODPROD = PRO.CODPROD
INNER JOIN DRE ON (PRO.AD_TPPROD = DRE.AD_TPPROD OR DRE.AD_TPPROD = 7) AND (CAB.TIPMOV = DRE.TIPMOV OR DRE.TIPMOV = 'A')
WHERE TOP.GOLSINAL = -1
AND (CAB.DTNEG BETWEEN :P_PERIODO.INI AND  :P_PERIODO.FIN)
/*AND (CAB.CODEMP IN :P_EMPRESA)*/
AND TOP.TIPMOV IN ('V', 'D')
AND TOP.ATIVO = 'S'
AND PRO.AD_TPPROD IS NOT NULL
GROUP BY
DRE.CODIGO,
DRE.DESCRICAO


UNION ALL

SELECT
DRE1.CODIGO,
DRE1.DESCRICAO,
SUM(RES.VLRBAIXA) AS VALOR
FROM VGF_RESULTADO_GM RES
INNER JOIN AD_DREGERFINDETALHE DRE2 ON RES.CODNAT = DRE2.CODNAT
INNER JOIN AD_DREGERFIN DRE1 ON DRE2.CODIGO = DRE1.CODIGO
WHERE
(RES.DHBAIXA BETWEEN :P_PERIODO.INI AND  :P_PERIODO.FIN)
GROUP BY
DRE1.CODIGO
,DRE1.DESCRICAO
)

GROUP BY
SUBSTR(LPAD(CODIGO, 10, '0'), 1, 2)||'00000000'

UNION ALL

/*GRAU2*/
SELECT
SUBSTR(LPAD(CODIGO, 10, '0'), 1, 4)||'000000' AS GRAU,
SUM(VALOR) AS VALOR

FROM 
(


WITH DRE AS
(
SELECT 
DRE1.CODIGO,
DRE1.DESCRICAO,
DRE1.AD_TPPROD,
DRE1.TIPMOV
FROM AD_DREGERFIN DRE1
)

SELECT
DRE.CODIGO,
DRE.DESCRICAO,
SUM(CASE WHEN CAB.TIPMOV = 'D' THEN (ITE.VLRTOT + ITE.VLRIPI + ITE.VLRSUBST - ITE.VLRDESC) * -1 ELSE (ITE.VLRTOT + ITE.VLRIPI + ITE.VLRSUBST - ITE.VLRDESC) END) AS VALOR
FROM TGFCAB CAB
INNER JOIN TGFITE ITE ON CAB.NUNOTA = ITE.NUNOTA
INNER JOIN TGFTOP TOP ON CAB.CODTIPOPER = TOP.CODTIPOPER AND TOP.DHALTER = (SELECT MAX(DHALTER) FROM TGFTOP WHERE CODTIPOPER = CAB.CODTIPOPER)
INNER JOIN TGFPRO PRO ON ITE.CODPROD = PRO.CODPROD
INNER JOIN DRE ON (PRO.AD_TPPROD = DRE.AD_TPPROD OR DRE.AD_TPPROD = 7) AND (CAB.TIPMOV = DRE.TIPMOV OR DRE.TIPMOV = 'A')
WHERE TOP.GOLSINAL = -1
AND (CAB.DTNEG BETWEEN :P_PERIODO.INI AND  :P_PERIODO.FIN)
/*AND (CAB.CODEMP IN :P_EMPRESA)*/
AND TOP.TIPMOV IN ('V', 'D')
AND TOP.ATIVO = 'S'
AND PRO.AD_TPPROD IS NOT NULL
GROUP BY
DRE.CODIGO,
DRE.DESCRICAO


UNION ALL

SELECT
DRE1.CODIGO,
DRE1.DESCRICAO,
SUM(RES.VLRBAIXA) AS VALOR
FROM VGF_RESULTADO_GM RES
INNER JOIN AD_DREGERFINDETALHE DRE2 ON RES.CODNAT = DRE2.CODNAT
INNER JOIN AD_DREGERFIN DRE1 ON DRE2.CODIGO = DRE1.CODIGO
WHERE
(RES.DHBAIXA BETWEEN :P_PERIODO.INI AND  :P_PERIODO.FIN)
GROUP BY
DRE1.CODIGO
,DRE1.DESCRICAO
)

GROUP BY
SUBSTR(LPAD(CODIGO, 10, '0'), 1, 4)||'000000'

UNION ALL

/*GRAU3*/
SELECT
SUBSTR(LPAD(CODIGO, 10, '0'), 1, 6)||'0000' AS GRAU,
SUM(VALOR) AS VALOR

FROM 
(


WITH DRE AS
(
SELECT 
DRE1.CODIGO,
DRE1.DESCRICAO,
DRE1.AD_TPPROD,
DRE1.TIPMOV
FROM AD_DREGERFIN DRE1
)

SELECT
DRE.CODIGO,
DRE.DESCRICAO,
SUM(CASE WHEN CAB.TIPMOV = 'D' THEN (ITE.VLRTOT + ITE.VLRIPI + ITE.VLRSUBST - ITE.VLRDESC) * -1 ELSE (ITE.VLRTOT + ITE.VLRIPI + ITE.VLRSUBST - ITE.VLRDESC) END) AS VALOR
FROM TGFCAB CAB
INNER JOIN TGFITE ITE ON CAB.NUNOTA = ITE.NUNOTA
INNER JOIN TGFTOP TOP ON CAB.CODTIPOPER = TOP.CODTIPOPER AND TOP.DHALTER = (SELECT MAX(DHALTER) FROM TGFTOP WHERE CODTIPOPER = CAB.CODTIPOPER)
INNER JOIN TGFPRO PRO ON ITE.CODPROD = PRO.CODPROD
INNER JOIN DRE ON (PRO.AD_TPPROD = DRE.AD_TPPROD OR DRE.AD_TPPROD = 7) AND (CAB.TIPMOV = DRE.TIPMOV OR DRE.TIPMOV = 'A')
WHERE TOP.GOLSINAL = -1
AND (CAB.DTNEG BETWEEN :P_PERIODO.INI AND  :P_PERIODO.FIN)
/*AND (CAB.CODEMP IN :P_EMPRESA)*/
AND TOP.TIPMOV IN ('V', 'D')
AND TOP.ATIVO = 'S'
AND PRO.AD_TPPROD IS NOT NULL
GROUP BY
DRE.CODIGO,
DRE.DESCRICAO


UNION ALL

SELECT
DRE1.CODIGO,
DRE1.DESCRICAO,
SUM(RES.VLRBAIXA) AS VALOR
FROM VGF_RESULTADO_GM RES
INNER JOIN AD_DREGERFINDETALHE DRE2 ON RES.CODNAT = DRE2.CODNAT
INNER JOIN AD_DREGERFIN DRE1 ON DRE2.CODIGO = DRE1.CODIGO
WHERE
(RES.DHBAIXA BETWEEN :P_PERIODO.INI AND  :P_PERIODO.FIN)
GROUP BY
DRE1.CODIGO
,DRE1.DESCRICAO
)

GROUP BY
SUBSTR(LPAD(CODIGO, 10, '0'), 1, 6)||'0000'

UNION ALL

/*GRAU4*/
SELECT
SUBSTR(LPAD(CODIGO, 10, '0'), 1, 8)||'00' AS GRAU,
SUM(VALOR) AS VALOR

FROM 
(


WITH DRE AS
(
SELECT 
DRE1.CODIGO,
DRE1.DESCRICAO,
DRE1.AD_TPPROD,
DRE1.TIPMOV
FROM AD_DREGERFIN DRE1
)

SELECT
DRE.CODIGO,
DRE.DESCRICAO,
SUM(CASE WHEN CAB.TIPMOV = 'D' THEN (ITE.VLRTOT + ITE.VLRIPI + ITE.VLRSUBST - ITE.VLRDESC) * -1 ELSE (ITE.VLRTOT + ITE.VLRIPI + ITE.VLRSUBST - ITE.VLRDESC) END) AS VALOR
FROM TGFCAB CAB
INNER JOIN TGFITE ITE ON CAB.NUNOTA = ITE.NUNOTA
INNER JOIN TGFTOP TOP ON CAB.CODTIPOPER = TOP.CODTIPOPER AND TOP.DHALTER = (SELECT MAX(DHALTER) FROM TGFTOP WHERE CODTIPOPER = CAB.CODTIPOPER)
INNER JOIN TGFPRO PRO ON ITE.CODPROD = PRO.CODPROD
INNER JOIN DRE ON (PRO.AD_TPPROD = DRE.AD_TPPROD OR DRE.AD_TPPROD = 7) AND (CAB.TIPMOV = DRE.TIPMOV OR DRE.TIPMOV = 'A')
WHERE TOP.GOLSINAL = -1
AND (CAB.DTNEG BETWEEN :P_PERIODO.INI AND  :P_PERIODO.FIN)
/*AND (CAB.CODEMP IN :P_EMPRESA)*/
AND TOP.TIPMOV IN ('V', 'D')
AND TOP.ATIVO = 'S'
AND PRO.AD_TPPROD IS NOT NULL
GROUP BY
DRE.CODIGO,
DRE.DESCRICAO


UNION ALL

SELECT
DRE1.CODIGO,
DRE1.DESCRICAO,
SUM(RES.VLRBAIXA) AS VALOR
FROM VGF_RESULTADO_GM RES
INNER JOIN AD_DREGERFINDETALHE DRE2 ON RES.CODNAT = DRE2.CODNAT
INNER JOIN AD_DREGERFIN DRE1 ON DRE2.CODIGO = DRE1.CODIGO
WHERE
(RES.DHBAIXA BETWEEN :P_PERIODO.INI AND  :P_PERIODO.FIN)
GROUP BY
DRE1.CODIGO
,DRE1.DESCRICAO
)

GROUP BY
SUBSTR(LPAD(CODIGO, 10, '0'), 1, 8)||'00'

UNION ALL

/*GRAU5*/
SELECT
SUBSTR(LPAD(CODIGO, 10, '0'), 1, 10) AS GRAU,
SUM(VALOR) AS VALOR

FROM 
(


WITH DRE AS
(
SELECT 
DRE1.CODIGO,
DRE1.DESCRICAO,
DRE1.AD_TPPROD,
DRE1.TIPMOV
FROM AD_DREGERFIN DRE1
)

SELECT
DRE.CODIGO,
DRE.DESCRICAO,
SUM(CASE WHEN CAB.TIPMOV = 'D' THEN (ITE.VLRTOT + ITE.VLRIPI + ITE.VLRSUBST - ITE.VLRDESC) * -1 ELSE (ITE.VLRTOT + ITE.VLRIPI + ITE.VLRSUBST - ITE.VLRDESC) END) AS VALOR
FROM TGFCAB CAB
INNER JOIN TGFITE ITE ON CAB.NUNOTA = ITE.NUNOTA
INNER JOIN TGFTOP TOP ON CAB.CODTIPOPER = TOP.CODTIPOPER AND TOP.DHALTER = (SELECT MAX(DHALTER) FROM TGFTOP WHERE CODTIPOPER = CAB.CODTIPOPER)
INNER JOIN TGFPRO PRO ON ITE.CODPROD = PRO.CODPROD
INNER JOIN DRE ON (PRO.AD_TPPROD = DRE.AD_TPPROD OR DRE.AD_TPPROD = 7) AND (CAB.TIPMOV = DRE.TIPMOV OR DRE.TIPMOV = 'A')
WHERE TOP.GOLSINAL = -1
AND (CAB.DTNEG BETWEEN :P_PERIODO.INI AND  :P_PERIODO.FIN)
/*AND (CAB.CODEMP IN :P_EMPRESA)*/
AND TOP.TIPMOV IN ('V', 'D')
AND TOP.ATIVO = 'S'
AND PRO.AD_TPPROD IS NOT NULL
GROUP BY
DRE.CODIGO,
DRE.DESCRICAO


UNION ALL

SELECT
DRE1.CODIGO,
DRE1.DESCRICAO,
SUM(RES.VLRBAIXA) AS VALOR
FROM VGF_RESULTADO_GM RES
INNER JOIN AD_DREGERFINDETALHE DRE2 ON RES.CODNAT = DRE2.CODNAT
INNER JOIN AD_DREGERFIN DRE1 ON DRE2.CODIGO = DRE1.CODIGO
WHERE
(RES.DHBAIXA BETWEEN :P_PERIODO.INI AND :P_PERIODO.FIN)
GROUP BY
DRE1.CODIGO
,DRE1.DESCRICAO
)
GROUP BY
SUBSTR(LPAD(CODIGO, 10, '0'), 1, 10)
) DRE3

INNER JOIN B ON DRE3.GRAU = B.CODIGO
GROUP BY
DRE3.GRAU,
B.DESCRICAO,
B.GRAU,
DRE3.VALOR

ORDER BY 1
