
SELECT DISTINCT
ORD.ORDEMCARGA,
ORD.CODEMP,
EMP.RAZAOSOCIAL RAZAOSOCIAL1,
ENDI.NOMEEND,
EMP.NUMEND,
EMP.COMPLEMENTO,
BAI.NOMEBAI,
CID.NOMECID,
UFS.UF,
EMP.CEP,
EMP.CGC,
EMP.INSCESTAD,
EMP.INSCMUN,
EMP.TELEFONE,
ORD.ORDEMCARGA,
PAR.RAZAOSOCIAL RAZAOSOCIAL,
ORD.CODVEICULO,
VEI.PLACA,
VEI.CODCID,
CID1.NOMECID NOMECID1,
PAR1.RAZAOSOCIAL RAZAOSOCIAL2,
CID2.NOMECID NOMECID2,
UFS1.UF UF1,
ORD.ROTEIRO,
CAB.OBSERVACAO,
CAB.AD_NUTICKET,
ORD.DTINCLUSAO 
FROM TGFORD ORD
INNER JOIN TSIEMP EMP ON ORD.CODEMP = EMP.CODEMP
INNER JOIN TSIEND ENDI on EMP.CODEND = ENDI.CODEND
INNER JOIN TSIBAI BAI on EMP.CODBAI = BAI.CODBAI
INNER JOIN TSICID CID on EMP.CODCID = CID.CODCID
INNER JOIN TSIUFS UFS ON CID.UF = UFS.CODUF
INNER JOIN TGFCAB CAB ON ORD.ORDEMCARGA = CAB.ORDEMCARGA
INNER JOIN TGFPAR PAR ON ORD.CODPARCTRANSP = PAR.CODPARC
INNER JOIN TGFVEI VEI ON ORD.CODVEICULO = VEI.CODVEICULO 
INNER JOIN TSICID CID1 on VEI.CODCID = CID1.CODCID
INNER JOIN TGFPAR PAR1 ON CAB.CODPARC = PAR1.CODPARC
INNER JOIN TSICID CID2 ON PAR1.CODCID = CID2.CODCID
INNER JOIN TSIUFS UFS1 ON CID2.UF = UFS1.CODUF
WHERE
PAR.TRANSPORTADORA = 'S'



SELECT * FROM TGFVTP
SELECT * FROM TGFPRO
SELECT * FROM TSICID
SELECT * FROM TSIUFS
SELECT * FROM TGFCAB
SELECT * FROM TGFVEI
SELECT * FROM TGFORD
SELECT * FROM TGFPAR WHERE TRANSPORTADORA = 'S'
SELECT ORDEMCARGA FROM TGFCAB WHERE ORDEMCARGA IS NOT NULL
SELECT * FROM TGFITE


WITH EMB AS (SELECT OPC.* 
FROM TDDCAM CAM 
JOIN TDDOPC OPC ON OPC.NUCAMPO = CAM.NUCAMPO
WHERE CAM.NOMETAB='TGFITE' AND CAM.NOMECAMPO='AD_TIPO_EMBALAGEM'
ORDER BY OPC.ORDEM)
SELECT
ORD.ORDEMCARGA,
ITE.NUNOTA,
ITE.CODPROD,
PRO.DESCRPROD,
PRO.CODVOL,
EMB.OPCAO,
ITE.QTDNEG,
CAB.QTDVOL,
ITE.OBSERVACAO
FROM TGFORD ORD
INNER JOIN TGFCAB CAB ON ORD.ORDEMCARGA = CAB.ORDEMCARGA
INNER JOIN TGFITE ITE ON CAB.NUNOTA = ITE.NUNOTA
INNER JOIN TGFPRO PRO ON ITE.CODPROD = PRO.CODPROD
INNER JOIN EMB ON ITE.AD_TIPO_EMBALAGEM = EMB.VALOR




SELECT OPC.* 
FROM TDDCAM CAM 
JOIN TDDOPC OPC ON OPC.NUCAMPO = CAM.NUCAMPO
WHERE CAM.NOMETAB='TGFITE' AND CAM.NOMECAMPO='AD_TIPO_EMBALAGEM'
ORDER BY OPC.ORDEM