
SELECT
* 
FROM TGFORD ORD
INNER JOIN TGFCAB CAB ON ORD.ORDEMCARGA = CAB.ORDEMCARGA
INNER JOIN TSIEMP EMP ON ORD.CODEMP = EMP.CODEMP
INNER JOIN TGFPAR PAR ON ORD.CODPARCTRANSP = PAR.CODPARC

WHERE
PAR.TRANSPORTADORA = 'S'







SELECT * FROM TGFVEI
SELECT * FROM TGFPAR WHERE TRANSPORTADORA = 'S'

SELECT ORDEMCARGA FROM TGFCAB WHERE ORDEMCARGA IS NOT NULL
SELECT  
CODEMP,
RAZAOSOCIAL,
CODEND,
NUMEND,
COMPLEMENTO,
CODBAI,
CODCID,
CEP,
TELEFONE,
CGC,
INSCESTAD,
INSCMUN,
CODMUN
FROM TSIEMP



SELECT OPC.* 
FROM TDDCAM CAM 
JOIN TDDOPC OPC ON OPC.NUCAMPO = CAM.NUCAMPO
WHERE CAM.NOMETAB='TGFORD' AND CAM.NOMECAMPO='CODTIPPARC'
ORDER BY OPC.ORDEM