(
SELECT
DTREF,
CODMETA,
CODVEND,
APELIDO,
CODGER,
CODPARC,
PARCEIRO,
MARCA,
CODGRUPOPROD,
SUM(QTDPREV) AS QTDPREV,
SUM(QTDREAL) AS QTDREAL,
SUM(QTDPREV * PRECOLT) AS VLR_PREV,
SUM(NVL(VLRREAL, 0)) AS VLR_REAL
FROM(
SELECT MET.CODMETA,MET.DTREF, NVL(MET.CODVEND,0) AS CODVEND, NVL(VEN.APELIDO,0) AS APELIDO,NVL(VGF.CODGER,0) AS CODGER, NVL(MET.CODPARC,0) AS CODPARC, 
NVL(PAR.RAZAOSOCIAL,0) AS PARCEIRO, 
NVL(MET.MARCA,0) AS MARCA,
NVL(VGF.CODGRUPOPROD,0) AS CODGRUPOPROD,
NVL(VGF.CODCENCUS,0) AS CODCENCUS, 
NVL(MET.QTDPREV,0) AS QTDPREV, 
SUM(NVL(VGF.QTD,0)) AS QTDREAL,
NVL(PRC.VLRVENDALT,0)AS PRECOLT, 
SUM(NVL(VGF.VLR,0)) AS VLRREAL
FROM TGFMET MET
LEFT JOIN VGF_VENDAS_SATIS VGF ON MET.DTREF = TRUNC(VGF.DTMOV,'MM') AND MET.CODVEND = VGF.CODVEND AND MET.CODPARC = VGF.CODPARC AND MET.MARCA = VGF.MARCA
LEFT JOIN AD_PRECOMARCA PRC ON (MET.MARCA = PRC.MARCA AND PRC.CODMETA = MET.CODMETA AND PRC.DTREF = '01/07/2023')
LEFT JOIN TGFPAR PAR ON MET.CODPARC = PAR.CODPARC
LEFT JOIN TGFVEN VEN ON MET.CODVEND = VEN.CODVEND
GROUP BY MET.CODMETA,MET.DTREF,NVL(MET.CODVEND,0),NVL(VEN.APELIDO,0),NVL(VGF.CODGER,0),NVL(MET.CODPARC,0),NVL(PAR.RAZAOSOCIAL,0),NVL(MET.MARCA,0),NVL(VGF.CODGRUPOPROD,0),NVL(VGF.CODCENCUS,0), NVL(MET.QTDPREV,0), NVL(PRC.VLRVENDALT,0)

)
WHERE 
CODMETA = :P_CODMETA
AND DTREF BETWEEN :P_PERIODO.INI   AND  :P_PERIODO.FIN

AND ((:P_NTEMMETA = 'S' AND (QTDPREV <> 0 OR QTDREAL <>  0 OR VLRREAL<>0)) OR :P_NTEMMETA = 'N')
AND (CODGRUPOPROD = :P_GRUPOPROD OR :P_GRUPOPROD IS NULL)
AND (CODPARC = :P_CODPARC OR :P_CODPARC IS NULL)
AND (CODVEND IN :P_CODVEND)
AND (MARCA IN :P_MARCA)

AND
(
CODVEND = (SELECT CODVEND FROM TSIUSU WHERE CODUSU = STP_GET_CODUSULOGADO) 
OR CODVEND IN (SELECT VEN.CODVEND FROM TGFVEN VEN, TSIUSU USU WHERE USU.CODVEND = VEN.CODGER AND USU.CODUSU = STP_GET_CODUSULOGADO) 
OR (SELECT AD_GESTOR_META FROM TSIUSU WHERE CODUSU = STP_GET_CODUSULOGADO) = 'S' 
)
GROUP BY
DTREF,
CODMETA,
CODVEND,
APELIDO,
CODGER,
CODPARC,
PARCEIRO,
MARCA,
CODGRUPOPROD
)