server:
  port: 8081

spring:
  thymeleaf:
    cache: false
  datasource:
    # Banco interno H2 para armazenar conexões e queries salvas
    url: jdbc:h2:file:./data/oracle-query-app;DB_CLOSE_DELAY=-1;MODE=Oracle
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.springframework.web: INFO
    org.hibernate.SQL: INFO


