SELECT
  SUM(saldoreal) saldoreal,
  SUM(saldobco) saldobco
FROM (
  -- SALDO REFERÊNCIA
  SELECT
      E.RAZAOABREV,
      sbc.CODCTABCOINT || '-' || cta.codctabco || '-' || cta.descricao DESCRICAO,
      cta.CODBCO,
      cta.CODAGE,
      sbc.SALDOREAL,
      sbc.SALDOBCO
  FROM tgfsbc sbc
  LEFT JOIN tsicta cta ON sbc.CODCTABCOINT = cta.CODCTABCOINT
  LEFT JOIN tsiemp E ON E.CODEMP = cta.CODEMP
  WHERE
    SBC.REFERENCIA = (
      SELECT MAX(REFERENCIA)
      FROM TGFSBC T2
      WHERE T2.CODCTABCOINT = SBC.CODCTABCOINT
        AND T2.REFERENCIA <= TRUNC(NVL($P{DT_ESCOLHA}, $P{DTINI}), 'MM')
    )
    AND cta.CODEMP IS NOT NULL
    AND ($P{P_EMPRESA} IS NULL OR cta.CODEMP = $P{P_EMPRESA})
    AND CTA.AD_USAFLUXOCAIXA='S'

  UNION ALL

  -- MOVIMENTAÇÃO SALDO REAL
  SELECT
      E.RAZAOABREV,
      MBC.CODCTABCOINT || '-' || cta.codctabco || '-' || cta.descricao DESCRICAO,
      cta.CODBCO,
      cta.CODAGE,
      NVL(MBC.VLRLANC * MBC.RECDESP, 0) AS SALDOREAL,
      0 AS SALDOBCO
  FROM TGFMBC MBC
  LEFT JOIN tsicta cta ON MBC.CODCTABCOINT = cta.CODCTABCOINT
  LEFT JOIN tsiemp E ON E.CODEMP = cta.CODEMP
  WHERE
    MBC.DTLANC >= TRUNC(NVL($P{DT_ESCOLHA}, $P{DTINI}), 'MM')
    AND MBC.DTLANC <= NVL($P{DT_ESCOLHA}, $P{DTINI})
    AND cta.CODEMP IS NOT NULL
    AND ($P{P_EMPRESA} IS NULL OR cta.CODEMP = $P{P_EMPRESA})
    AND CTA.AD_USAFLUXOCAIXA='S'


  UNION ALL

  -- MOVIMENTAÇÃO SALDO BANCO
  SELECT
      E.RAZAOABREV,
      MBC.CODCTABCOINT || '-' || cta.codctabco || '-' || cta.descricao DESCRICAO,
      cta.CODBCO,
      cta.CODAGE,
      0 AS SALDOREAL,
      NVL(MBC.VLRLANC * MBC.RECDESP, 0) AS SALDOBCO
  FROM TGFMBC MBC
  LEFT JOIN tsicta cta ON MBC.CODCTABCOINT = cta.CODCTABCOINT
  LEFT JOIN tsiemp E ON E.CODEMP = cta.CODEMP
  WHERE
    MBC.DTLANC >= TRUNC(NVL($P{DT_ESCOLHA}, $P{DTINI}), 'MM')
    AND MBC.DTLANC <= NVL($P{DT_ESCOLHA}, $P{DTINI})
    AND MBC.CONCILIADO = 'S'
    AND cta.CODEMP IS NOT NULL
    AND ($P{P_EMPRESA} IS NULL OR cta.CODEMP = $P{P_EMPRESA})
    AND CTA.AD_USAFLUXOCAIXA='S'

)