SELECT
SUM(A_RECEBER_PROV_S) A_RECEBER_PROV_S,
SUM(A_RECEBER_PROV_N) A_RECEBER_PROV_N,
SUM(A_REC_VEIC_PROV_N) A_REC_VEIC_PROV_N,
SUM(A_RECEBER_PROV_S) +
SUM(A_RECEBER_PROV_N) +
SUM(A_REC_VEIC_PROV_N) A_RECEBER_TOT,
SUM(A_PAGAR_PROV_S) A_PAGAR_PROV_S,
SUM(A_PAGAR_PROV_N) A_PAGAR_PROV_N,
SUM(A_PAGAR_PROV_S) +
SUM(A_PAGAR_PROV_N) A_PAGAR_TOT,

SUM(DIFERENCA) DIFERENCA

FROM (

WITH BASE_DADOS AS (
  SELECT
    DTVENC,
    CODCTABCOINT AS CONTA,
    CODNAT,
    RECDESP,
    PROVISAO,
    VLRDESDOB
  FROM TGFFIN
  WHERE
    TRUNC(DTVENC) < $P{DTINI}
    AND DHBAIXA IS NULL
    AND ($P{P_EMPRESA} IS NULL OR CODEMP = $P{P_EMPRESA})
    AND RECDESP <> 0
    AND (NUNOTA IS NULL OR NUNOTA IN (
    SELECT
    FIN1.NUNOTA
    FROM TGFFIN FIN1
    LEFT JOIN TGFCAB CAB ON FIN1.NUNOTA = CAB.NUNOTA
    WHERE FIN1.DTVENC < $P{DTINI}
    AND (FIN1.NUNOTA IS NULL OR CAB.STATUSNOTA = 'L')))

)

SELECT
  BAS.DTVENC,
  NVL(SUM(CASE WHEN BAS.RECDESP = 1 AND BAS.PROVISAO = 'S' THEN BAS.VLRDESDOB END), 0) AS A_RECEBER_PROV_S,
  NVL(SUM(CASE WHEN BAS.RECDESP = 1 AND BAS.CODNAT <> 5010500 AND NVL(BAS.PROVISAO, 'N') = 'N' THEN BAS.VLRDESDOB END), 0) AS A_RECEBER_PROV_N,
  NVL(SUM(CASE WHEN BAS.RECDESP = 1 AND BAS.CODNAT = 5010500 AND NVL(BAS.PROVISAO, 'N') = 'N' THEN BAS.VLRDESDOB END), 0) AS A_REC_VEIC_PROV_N,
  NVL(SUM(CASE WHEN BAS.RECDESP = -1 AND BAS.PROVISAO = 'S' THEN -1 * BAS.VLRDESDOB END), 0) AS A_PAGAR_PROV_S,
  NVL(SUM(CASE WHEN BAS.RECDESP = -1 AND NVL(BAS.PROVISAO, 'N') = 'N' THEN -1 * BAS.VLRDESDOB END), 0) AS A_PAGAR_PROV_N,

  -- DIFERENÇA DO DIA
  NVL(SUM(CASE WHEN BAS.RECDESP = 1 THEN BAS.VLRDESDOB END), 0) -
  NVL(SUM(CASE WHEN BAS.RECDESP = -1 THEN BAS.VLRDESDOB END), 0) AS DIFERENCA

FROM BASE_DADOS BAS
LEFT JOIN TSICTA CTA ON BAS.CONTA = CTA.CODCTABCOINT


GROUP BY DTVENC
ORDER BY DTVENC
)