SELECT
    CODEMP,
    RAZAOABREV,
    DESCRNAT,
    TO_CHAR(DTVENC,'DD/MM/YYYY') DTVENC,
    NUFIN,
    DESDOBRAMENTO,
    CODPARC,
    RAZAOSOCIAL,
    SUM(A_RECEBER_PROV_S)A_RECEBER_PROV_S,
    SUM(A_RECEBER_PROV_N)A_RECEBER_PROV_N,
    SUM(A_PAGAR_PROV_S) A_PAGAR_PROV_S,
    SUM(A_PAGAR_PROV_N)A_PAGAR_PROV_N,
    SUM(DIFERENCA)DIFERENCA,
  -- ACUMULADO
  SUM(
    SUM(DIFERENCA)+SUM(SALDO_INI)
  ) OVER (ORDER BY TO_CHAR(DTVENC,'DD/MM/YYYY'),RECDESP DESC, NUFIN ROWS UNBOUNDED PRECEDING) AS DIFERENCA_ACUMULADA

FROM (

    SELECT
    CODEMP,RAZAOABREV,DESCRNAT,DTVENC,NUFIN,DESDOBRAMENTO,CODPARC,RAZAOSOCIAL,A_RECEBER_PROV_S,A_RECEBER_PROV_N,A_PAGAR_PROV_S,A_PAGAR_PROV_N,DIFERENCA,SUM(SALDO_INI)SALDO_INI, RECDESP
    FROM(

        SELECT
            9999 CODEMP,
            'Saldo' RAZAOABREV,
            '1-Saldo' DESCRNAT,
            NVL($P{DT_ESCOLHA}, $P{DTINI}) DTVENC,
            1 NUFIN,
            '1' DESDOBRAMENTO,
            0 CODPARC,
            'Saldo das Contas' RAZAOSOCIAL,
            0 A_RECEBER_PROV_S,
            0 A_RECEBER_PROV_N,
            0 A_PAGAR_PROV_S,
            0 A_PAGAR_PROV_N,
            0 DIFERENCA,
            sum(CASE WHEN $P{P_CONSID_SALDO} = 1 then SALDOREAL else 0 end) SALDO_INI,
            0 RECDESP
        FROM (
          -- SALDO REFERÊNCIA
          SELECT
              CTA.CODEMP,
              EMP.RAZAOABREV,
              sbc.SALDOREAL
          FROM tgfsbc sbc
          LEFT JOIN tsicta cta ON sbc.CODCTABCOINT = cta.CODCTABCOINT
          LEFT JOIN TSIEMP EMP ON cta.CODEMP = EMP.CODEMP
          WHERE
            SBC.REFERENCIA = (
              SELECT MAX(REFERENCIA)
              FROM TGFSBC T2
              WHERE T2.CODCTABCOINT = SBC.CODCTABCOINT
                AND T2.REFERENCIA <= TRUNC(NVL($P{DT_ESCOLHA}, $P{DTINI}), 'MM')
            )
            AND ($P{P_EMPRESA} IS NULL OR cta.CODEMP = $P{P_EMPRESA})
            AND cta.CODEMP IS NOT NULL


          UNION ALL

          -- MOVIMENTAÇÃO SALDO REAL
          SELECT
              CTA.CODEMP,
              EMP.RAZAOABREV,
              NVL(MBC.VLRLANC * MBC.RECDESP, 0) AS SALDOREAL
          FROM TGFMBC MBC
          LEFT JOIN tsicta cta ON MBC.CODCTABCOINT = cta.CODCTABCOINT
          LEFT JOIN TSIEMP EMP ON cta.CODEMP = EMP.CODEMP
          WHERE
            MBC.DTLANC >= TRUNC(NVL($P{DT_ESCOLHA}, $P{DTINI}), 'MM')
            AND MBC.DTLANC <= NVL($P{DT_ESCOLHA}, $P{DTINI})
            AND ($P{P_EMPRESA} IS NULL OR cta.CODEMP = $P{P_EMPRESA})
            AND cta.CODEMP IS NOT NULL


          UNION ALL

          -- MOVIMENTAÇÃO SALDO BANCO (IGNORADA NO SOMATÓRIO)
          SELECT
              CTA.CODEMP,
              EMP.RAZAOABREV,
              0 AS SALDOREAL
          FROM TGFMBC MBC
          LEFT JOIN tsicta cta ON MBC.CODCTABCOINT = cta.CODCTABCOINT
          LEFT JOIN TSIEMP EMP ON cta.CODEMP = EMP.CODEMP
          WHERE
            MBC.DTLANC >= TRUNC(NVL($P{DT_ESCOLHA}, $P{DTINI}), 'MM')
            AND MBC.DTLANC <= NVL($P{DT_ESCOLHA}, $P{DTINI})
            AND MBC.CONCILIADO = 'S'
            AND ($P{P_EMPRESA} IS NULL OR cta.CODEMP = $P{P_EMPRESA})
            AND cta.CODEMP IS NOT NULL

        )GROUP BY CODEMP,  RAZAOABREV
    )GROUP BY CODEMP,RAZAOABREV,DESCRNAT,DTVENC,NUFIN,DESDOBRAMENTO,CODPARC,RAZAOSOCIAL,A_RECEBER_PROV_S,A_RECEBER_PROV_N,A_PAGAR_PROV_S,A_PAGAR_PROV_N,DIFERENCA, RECDESP




UNION ALL


SELECT
CODEMP,
RAZAOABREV,
DESCRNAT,
DTVENC,
NUFIN,
DESDOBRAMENTO,
CODPARC,
RAZAOSOCIAL,
SUM(A_RECEBER_PROV_S)A_RECEBER_PROV_S,
SUM(A_RECEBER_PROV_N)A_RECEBER_PROV_N,
SUM(A_PAGAR_PROV_S) A_PAGAR_PROV_S,
SUM(A_PAGAR_PROV_N)A_PAGAR_PROV_N,
SUM(DIFERENCA)DIFERENCA,
0 SALDO_INI,
RECDESP

FROM (


    WITH BASE_DADOS AS (
      SELECT
        FIN.NUFIN,
        FIN.DESDOBRAMENTO DESDOBRAMENTO,
        FIN.CODEMP,
        EMP.RAZAOABREV,
        FIN.CODNAT,
        FIN.CODNAT || ' - '|| NAT.DESCRNAT DESCRNAT,
        FIN.CODPARC,
        PAR.RAZAOSOCIAL,
        FIN.CODCTABCOINT AS CONTA,
        FIN.DTVENC,
        FIN.RECDESP,
        FIN.PROVISAO,
        FIN.VLRDESDOB
      FROM TGFFIN FIN
      LEFT JOIN TGFPAR PAR ON FIN.CODPARC = PAR.CODPARC
      LEFT JOIN TSIEMP EMP ON FIN.CODEMP = EMP.CODEMP
      LEFT JOIN TGFNAT NAT ON FIN.CODNAT = NAT.CODNAT
      WHERE
        TRUNC(FIN.DTVENC) BETWEEN $P{DTINI} AND $P{DTFIM}
        AND FIN.DHBAIXA IS NULL

        AND ($P{P_EMPRESA} IS NULL OR FIN.CODEMP = $P{P_EMPRESA})
        AND (FIN.NUNOTA IS NULL OR FIN.NUNOTA IN (
        SELECT
        FIN.NUNOTA
        FROM TGFFIN FIN
        LEFT JOIN TGFCAB CAB ON FIN.NUNOTA = CAB.NUNOTA
        WHERE FIN.DTVENC BETWEEN $P{DTINI} AND $P{DTFIM}
        AND CAB.STATUSNOTA = 'L'))
        AND (
          ($P{P_CONSIDERAR_ADTO} = 1)
          OR
          (NVL($P{P_CONSIDERAR_ADTO},0) = 0 AND FIN.CODNAT NOT IN (6010100,6010200,6010300,6020100,6020200,6020300))
        )
        AND (
          ($P{P_CONSID_DESP_DEV_VENDA} = 1)
          OR
          (NVL($P{P_CONSID_DESP_DEV_VENDA},0) = 0 AND FIN.CODNAT NOT IN (1020000))
        )



  UNION ALL


    SELECT
      99999999 AS NUFIN,
      '1' AS DESDOBRAMENTO,
      PEA.SIMULA_EMPRESA CODEMP,
      EMP.RAZAOABREV,
      PEA.SIMULA_NAT CODNAT,
      PEA.SIMULA_NAT || ' - '|| NAT.DESCRNAT DESCRNAT,
      PEA.SIMULA_PARCEIRO AS CODPARC,
      PAR.RAZAOSOCIAL AS RAZAOSOCIAL,
      PEA.SIMULA_CONTA AS CONTA,
      PEA.SIMULA_DTVENC AS DTVENC,
      PEA.SIMULA_RECDESP AS RECDESP,
      PEA.SIMULA_PROVISAO AS PROVISAO,
      PEA.SIMULA_VLRDESDOB AS VLRDESDOB
    FROM AD_SIMULACAIXA PEA
    LEFT JOIN TGFPAR PAR ON PEA.SIMULA_PARCEIRO = PAR.CODPARC
    LEFT JOIN TSIEMP EMP ON PEA.SIMULA_EMPRESA = EMP.CODEMP
    LEFT JOIN TGFNAT NAT ON PEA.SIMULA_NAT = NAT.CODNAT
    WHERE
      TRUNC(PEA.SIMULA_DTVENC) BETWEEN $P{DTINI} AND $P{DTFIM}
      AND PEA.SIMULA_PROVISAO = 'S'
      AND ($P{P_EMPRESA} IS NULL OR PEA.SIMULA_EMPRESA = $P{P_EMPRESA})

    )

    SELECT
      BAS.RECDESP,
      BAS.CODEMP,
      BAS.RAZAOABREV,
      BAS.DESCRNAT,
      BAS.DTVENC,
      BAS.NUFIN,
      BAS.DESDOBRAMENTO,
      BAS.CODPARC,
      UPPER(BAS.RAZAOSOCIAL) RAZAOSOCIAL,

    NVL(SUM(
      CASE
        WHEN NVL($P{P_CONSIDERAR_REC_PROV}, 0) = 1
         AND BAS.RECDESP = 1
         AND BAS.PROVISAO = 'S'
         AND (
           (NVL($P{P_REMOVER_LIM_REC}, 0) = 0 AND BAS.CODNAT IN (1010000, 4020304, 2040600)) OR
           NVL($P{P_REMOVER_LIM_REC}, 0) = 1
         )
        THEN BAS.VLRDESDOB
        ELSE 0
      END
    ), 0) AS A_RECEBER_PROV_S,






      NVL(SUM(CASE
    WHEN BAS.RECDESP = 1 AND NVL(BAS.PROVISAO, 'N') = 'N' AND BAS.CODNAT IN (1010000,4020304,2040600)  AND NVL($P{P_REMOVER_LIM_REC},0) = 0 THEN BAS.VLRDESDOB
    WHEN BAS.RECDESP = 1 AND NVL(BAS.PROVISAO, 'N') = 'N' AND $P{P_REMOVER_LIM_REC} = 1 THEN BAS.VLRDESDOB END), 0) AS A_RECEBER_PROV_N,


      NVL(SUM(CASE WHEN BAS.RECDESP = -1 AND BAS.PROVISAO = 'S' THEN -1 * BAS.VLRDESDOB END), 0) AS A_PAGAR_PROV_S,
      NVL(SUM(CASE WHEN BAS.RECDESP = -1 AND NVL(BAS.PROVISAO, 'N') = 'N' THEN -1 * BAS.VLRDESDOB END), 0) AS A_PAGAR_PROV_N,

      -- DIFERENÇA DO DIA

    NVL(SUM(
      CASE
        WHEN $P{P_CONSIDERAR_REC_PROV} = 1 AND BAS.RECDESP = 1 AND BAS.PROVISAO = 'S' AND ((NVL($P{P_REMOVER_LIM_REC}, 0) = 0 AND BAS.CODNAT IN (1010000, 4020304, 2040600)) OR $P{P_REMOVER_LIM_REC} = 1 ) THEN BAS.VLRDESDOB
        WHEN NVL($P{P_CONSIDERAR_REC_PROV}, 0) = 0 AND BAS.RECDESP = 1 AND BAS.PROVISAO <> 'S' AND ((NVL($P{P_REMOVER_LIM_REC}, 0) = 0 AND BAS.CODNAT IN (1010000, 4020304, 2040600)) OR $P{P_REMOVER_LIM_REC} = 1 ) THEN BAS.VLRDESDOB
      END
    ), 0)
    -
     NVL(SUM(CASE WHEN BAS.RECDESP = -1 THEN BAS.VLRDESDOB END), 0) AS DIFERENCA



    FROM BASE_DADOS BAS
    LEFT JOIN TSICTA CTA ON BAS.CONTA = CTA.CODCTABCOINT



    GROUP BY   BAS.RECDESP, BAS.CODEMP, BAS.RAZAOABREV,  BAS.DESCRNAT,BAS.DTVENC,BAS.NUFIN,BAS.DESDOBRAMENTO,BAS.CODPARC,BAS.RAZAOSOCIAL
    )
    GROUP BY
    RECDESP,
    CODEMP,
    RAZAOABREV,
    DESCRNAT,
    DTVENC,
    NUFIN,
    DESDOBRAMENTO,
    CODPARC,
    RAZAOSOCIAL

)
GROUP BY CODEMP,RAZAOABREV,DESCRNAT,DTVENC,NUFIN,DESDOBRAMENTO,CODPARC,RAZAOSOCIAL, RECDESP
HAVING
    NOT (
        SUM(A_RECEBER_PROV_S) = 0 AND
        SUM(A_RECEBER_PROV_N) = 0 AND
        SUM(A_PAGAR_PROV_S) = 0 AND
        SUM(A_PAGAR_PROV_N) = 0
    )
ORDER BY TO_DATE(DTVENC,'DD/MM/YYYY'),RECDESP DESC, NUFIN