CREATE OR REPLACE PROCEDURE          STP_ATUAL_STATUSA2W_SATIS2
 AS
BEGIN
DECLARE
       P_COUNT                           INT;
       P_NUNOTA         INT;
       P_STATUS         VARCHAR2(1000);

       CURSOR CUR_STATUSA2W IS 
            SELECT DISTINCT VGF.NUNOTA, STATUS
            FROM AD_VGFSTATUSA2W VGF
            INNER JOIN TGFCAB CAB ON CAB.NUNOTA = VGF.NUNOTA
            WHERE (CAB.AD_STATUSA2WV2 <> VGF.STATUS OR CAB.AD_STATUSA2WV2 IS NULL);

BEGIN

    EXECUTE IMMEDIATE 'ALTER TRIGGER TRG_AD_TGFCABVENCI_SATIS DISABLE';
    EXECUTE IMMEDIATE 'ALTER TRIGGER TRG_UPD_TGFCAB DISABLE';
    EXECUTE IMMEDIATE 'ALTER TRIGGER TRG_AD_TGFCABVENCI_SATIS DISABLE';
    EXECUTE IMMEDIATE 'ALTER TRIGGER TRG_INC_UPD_TGFCAB_ORD DISABLE';
    EXECUTE IMMEDIATE 'ALTER TRIGGER TRG_LIBCARGA_SATIS  DISABLE';
    EXECUTE IMMEDIATE 'ALTER TRIGGER TRG_CARGAINTERNA_SATIS  DISABLE';
    EXECUTE IMMEDIATE 'ALTER TRIGGER TRG_INSLIB_TGFFINLIB_SATIS  DISABLE';
    EXECUTE IMMEDIATE 'ALTER TRIGGER TRG_INC_UPD_TGFCAB_SATIS  DISABLE';
    EXECUTE IMMEDIATE 'ALTER TRIGGER TRG_DTCOLCARGANOTA_SATIS  DISABLE';
    EXECUTE IMMEDIATE 'ALTER TRIGGER TGF_TRVDATAEFET_SATIS  DISABLE';



    OPEN CUR_STATUSA2W;
    LOOP
      FETCH CUR_STATUSA2W INTO P_NUNOTA, P_STATUS;
      EXIT WHEN CUR_STATUSA2W%NOTFOUND;

            UPDATE TGFCAB
               SET AD_STATUSA2WV2 = P_STATUS
             WHERE NUNOTA = P_NUNOTA;

            UPDATE TGFCAB CAB1
               SET CAB1.AD_STATUSA2WV2 = P_STATUS
             WHERE CAB1.NUNOTA IN (
                       SELECT VAR.NUNOTA
                         FROM TGFVAR VAR
                        WHERE VAR.NUNOTAORIG = P_NUNOTA);

            UPDATE TGFCAB CAB2
               SET CAB2.AD_STATUSA2WV2 = P_STATUS
             WHERE CAB2.NUNOTA IN (
                       SELECT VAR1.NUNOTA
                         FROM TGFVAR VAR
                         JOIN TGFVAR VAR1
                           ON VAR.NUNOTA = VAR1.NUNOTAORIG
                        WHERE VAR.NUNOTAORIG = P_NUNOTA);

                COMMIT;
    
    END LOOP;
    CLOSE CUR_STATUSA2W;



    EXECUTE IMMEDIATE 'ALTER TRIGGER TRG_AD_TGFCABVENCI_SATIS ENABLE';
    EXECUTE IMMEDIATE 'ALTER TRIGGER TRG_UPD_TGFCAB ENABLE';
    EXECUTE IMMEDIATE 'ALTER TRIGGER TRG_AD_TGFCABVENCI_SATIS ENABLE';
    EXECUTE IMMEDIATE 'ALTER TRIGGER TRG_INC_UPD_TGFCAB_ORD ENABLE';
    EXECUTE IMMEDIATE 'ALTER TRIGGER TRG_LIBCARGA_SATIS  ENABLE';
    EXECUTE IMMEDIATE 'ALTER TRIGGER TRG_CARGAINTERNA_SATIS  ENABLE';
    EXECUTE IMMEDIATE 'ALTER TRIGGER TRG_INSLIB_TGFFINLIB_SATIS  ENABLE';
    EXECUTE IMMEDIATE 'ALTER TRIGGER TRG_INC_UPD_TGFCAB_SATIS  ENABLE';    
    EXECUTE IMMEDIATE 'ALTER TRIGGER TRG_DTCOLCARGANOTA_SATIS  ENABLE';    
    EXECUTE IMMEDIATE 'ALTER TRIGGER TGF_TRVDATAEFET_SATIS  ENABLE';    



END;
END;
/