import { pgTable, uuid, varchar, text, timestamp, boolean, numeric, jsonb, integer } from 'drizzle-orm/pg-core';

export const emitente = pgTable('emitente', {
  id: uuid('id').primaryKey().defaultRandom(),
  apelido: varchar('apelido', { length: 120 }).notNull(),
  cnpj: varchar('cnpj', { length: 14 }).notNull().unique(),
  inscricaoEstadual: varchar('inscricao_estadual', { length: 14 }).notNull(),
  razaoSocial: varchar('razao_social', { length: 255 }).notNull(),
  nomeFantasia: varchar('nome_fantasia', { length: 255 }),
  crt: varchar('crt', { length: 1 }).notNull().default('1'),
  cnae: varchar('cnae', { length: 7 }),
  endereco: jsonb('endereco').notNull().default({}),
  telefone: varchar('telefone', { length: 20 }),
  email: varchar('email', { length: 255 }),
  ambiente: varchar('ambiente', { length: 10 }).notNull().default('homolog'),
  seriePadrao: integer('serie_padrao').notNull().default(1),
  ultimoNumero: integer('ultimo_numero').notNull().default(0),
  credenciadoSiare: boolean('credenciado_siare').notNull().default(false),
  credenciadoSiareEm: timestamp('credenciado_siare_em', { withTimezone: true }),
  certStorageKey: text('cert_storage_key'),
  certPasswordEnc: text('cert_password_enc'),
  certCnpj: varchar('cert_cnpj', { length: 14 }),
  certValidade: timestamp('cert_validade', { withTimezone: true }),
  certSubject: text('cert_subject'),
  ativo: boolean('ativo').notNull().default(true),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
});

export const serieNumeracao = pgTable('serie_numeracao', {
  id: uuid('id').primaryKey().defaultRandom(),
  emitenteId: uuid('emitente_id').notNull().references(() => emitente.id),
  serie: integer('serie').notNull(),
  ultimoNumero: integer('ultimo_numero').notNull().default(0),
  ambiente: varchar('ambiente', { length: 10 }).notNull().default('homolog'),
});

export const destinatario = pgTable('destinatario', {
  id: uuid('id').primaryKey().defaultRandom(),
  emitenteId: uuid('emitente_id').notNull().references(() => emitente.id),
  apelido: varchar('apelido', { length: 120 }).notNull(),
  tipo: varchar('tipo', { length: 2 }).notNull(),
  cpfCnpj: varchar('cpf_cnpj', { length: 14 }).notNull(),
  razaoSocial: varchar('razao_social', { length: 255 }),
  inscricaoEstadual: varchar('inscricao_estadual', { length: 14 }),
  indIEDest: varchar('ind_ie_dest', { length: 1 }).notNull().default('9'),
  email: varchar('email', { length: 255 }),
  telefone: varchar('telefone', { length: 20 }),
  endereco: jsonb('endereco'),
  ativo: boolean('ativo').default(true).notNull(),
  papelCliente: boolean('papel_cliente').notNull().default(true),
  papelFornecedor: boolean('papel_fornecedor').notNull().default(false),
  papelTransportadora: boolean('papel_transportadora').notNull().default(false),
  inscricaoMunicipal: varchar('inscricao_municipal', { length: 20 }),
  emailXml: varchar('email_xml', { length: 255 }),
  finalidade: varchar('finalidade', { length: 20 }),
  consumidorFinal: boolean('consumidor_final').notNull().default(false),
  regime: varchar('regime', { length: 20 }),
  ieStatus: varchar('ie_status', { length: 20 }).notNull().default('NAO_VERIFICADA'),
  suframa: varchar('suframa', { length: 20 }),
  areaIncentivada: boolean('area_incentivada').notNull().default(false),
  cnae: varchar('cnae', { length: 7 }),
  tipoFornecimento: varchar('tipo_fornecimento', { length: 20 }),
  cfopEntradaPadrao: varchar('cfop_entrada_padrao', { length: 4 }),
  emiteDocumentoFiscal: boolean('emite_documento_fiscal').notNull().default(true),
  idEstrangeiro: varchar('id_estrangeiro', { length: 20 }),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
});

export const produto = pgTable('produto', {
  id: uuid('id').primaryKey().defaultRandom(),
  emitenteId: uuid('emitente_id').notNull().references(() => emitente.id),
  codigo: varchar('codigo', { length: 60 }).notNull(),
  descricao: varchar('descricao', { length: 120 }).notNull(),
  descricaoFiscal: varchar('descricao_fiscal', { length: 120 }),
  ncm: varchar('ncm', { length: 8 }).notNull(),
  cfop: varchar('cfop', { length: 4 }).notNull(),
  cfopEntradaPadrao: varchar('cfop_entrada_padrao', { length: 4 }),
  unidade: varchar('unidade', { length: 6 }).notNull().default('UN'),
  valorUnitario: numeric('valor_unitario', { precision: 15, scale: 4 }).notNull().default('0'),
  origem: varchar('origem', { length: 1 }).notNull().default('0'),
  csosn: varchar('csosn', { length: 3 }),
  cst: varchar('cst', { length: 3 }),
  cest: varchar('cest', { length: 7 }),
  gtin: varchar('gtin', { length: 14 }),
  tipoItemSped: varchar('tipo_item_sped', { length: 2 }).notNull().default('00'),
  cstPis: varchar('cst_pis', { length: 2 }),
  cstCofins: varchar('cst_cofins', { length: 2 }),
  aliquotaPis: numeric('aliquota_pis', { precision: 7, scale: 4 }),
  aliquotaCofins: numeric('aliquota_cofins', { precision: 7, scale: 4 }),
  cstIbsCbs: varchar('cst_ibs_cbs', { length: 3 }),
  cclassTrib: varchar('cclass_trib', { length: 6 }),
  aliquotaIbs: numeric('aliquota_ibs', { precision: 7, scale: 4 }),
  aliquotaCbs: numeric('aliquota_cbs', { precision: 7, scale: 4 }),
  cstIs: varchar('cst_is', { length: 3 }),
  cclassTribIs: varchar('cclass_trib_is', { length: 6 }),
  aliquotaIs: numeric('aliquota_is', { precision: 7, scale: 4 }),
  sujeitoIs: boolean('sujeito_is').notNull().default(false),
  cbenef: varchar('cbenef', { length: 10 }),
  ativo: boolean('ativo').default(true).notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
});

export const nfe = pgTable('nfe', {
  id: uuid('id').primaryKey().defaultRandom(),
  emitenteId: uuid('emitente_id').notNull().references(() => emitente.id),
  chaveAcesso: varchar('chave_acesso', { length: 44 }).notNull().unique(),
  situacao: varchar('situacao', { length: 24 }).notNull().default('RASCUNHO'),
  modelo: varchar('modelo', { length: 2 }).notNull().default('55'),
  serie: integer('serie').notNull(),
  numero: integer('numero').notNull(),
  naturezaOperacao: varchar('natureza_operacao', { length: 60 }).notNull(),
  tpNf: varchar('tp_nf', { length: 1 }).notNull().default('1'),
  idDest: varchar('id_dest', { length: 1 }).notNull().default('1'),
  finNfe: varchar('fin_nfe', { length: 1 }).notNull().default('1'),
  indFinal: varchar('ind_final', { length: 1 }).notNull().default('1'),
  indPres: varchar('ind_pres', { length: 1 }).notNull().default('1'),
  tpEmis: varchar('tp_emis', { length: 1 }).notNull().default('1'),
  tpAmb: varchar('tp_amb', { length: 1 }).notNull(),
  destinatarioId: uuid('destinatario_id').references(() => destinatario.id),
  destCpfCnpj: varchar('dest_cpf_cnpj', { length: 14 }).notNull(),
  destRazaoSocial: varchar('dest_razao_social', { length: 255 }).notNull(),
  valorProdutos: numeric('valor_produtos', { precision: 15, scale: 2 }).notNull().default('0'),
  valorNf: numeric('valor_nf', { precision: 15, scale: 2 }).notNull().default('0'),
  xmlStorageKey: text('xml_storage_key'),
  procNfeStorageKey: text('proc_nfe_storage_key'),
  nRec: varchar('n_rec', { length: 15 }),
  nProt: varchar('n_prot', { length: 15 }),
  cStat: varchar('c_stat', { length: 3 }),
  xMotivo: text('x_motivo'),
  dhEmi: timestamp('dh_emi', { withTimezone: true }).defaultNow().notNull(),
  dhAutorizacao: timestamp('dh_autorizacao', { withTimezone: true }),
  payloadHash: varchar('payload_hash', { length: 64 }),
  correlationId: varchar('correlation_id', { length: 64 }),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
});

export const nfeItem = pgTable('nfe_item', {
  id: uuid('id').primaryKey().defaultRandom(),
  nfeId: uuid('nfe_id').notNull().references(() => nfe.id),
  nItem: integer('n_item').notNull(),
  produtoId: uuid('produto_id').references(() => produto.id),
  codigo: varchar('codigo', { length: 60 }).notNull(),
  descricao: varchar('descricao', { length: 120 }).notNull(),
  ncm: varchar('ncm', { length: 8 }).notNull(),
  cfop: varchar('cfop', { length: 4 }).notNull(),
  unidade: varchar('unidade', { length: 6 }).notNull(),
  quantidade: numeric('quantidade', { precision: 15, scale: 4 }).notNull(),
  valorUnitario: numeric('valor_unitario', { precision: 15, scale: 4 }).notNull(),
  valorTotal: numeric('valor_total', { precision: 15, scale: 2 }).notNull(),
  origem: varchar('origem', { length: 1 }).notNull().default('0'),
  csosn: varchar('csosn', { length: 3 }),
  cst: varchar('cst', { length: 3 }),
  cest: varchar('cest', { length: 7 }),
  cstIbsCbs: varchar('cst_ibs_cbs', { length: 3 }),
  cclassTrib: varchar('cclass_trib', { length: 6 }),
  cstPis: varchar('cst_pis', { length: 2 }),
  cstCofins: varchar('cst_cofins', { length: 2 }),
});

export const evento = pgTable('evento', {
  id: uuid('id').primaryKey().defaultRandom(),
  nfeId: uuid('nfe_id').notNull().references(() => nfe.id),
  chaveAcesso: varchar('chave_acesso', { length: 44 }).notNull(),
  tipo: varchar('tipo', { length: 6 }).notNull(),
  sequencial: integer('sequencial').notNull(),
  statusRegistro: varchar('status_registro', { length: 20 }).notNull(),
  nProt: varchar('n_prot', { length: 15 }),
  xmlStorageKey: text('xml_storage_key'),
  motivo: text('motivo'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
});

export const inutilizacao = pgTable('inutilizacao', {
  id: uuid('id').primaryKey().defaultRandom(),
  emitenteId: uuid('emitente_id').notNull().references(() => emitente.id),
  serie: integer('serie').notNull(),
  numeroIni: integer('numero_ini').notNull(),
  numeroFim: integer('numero_fim').notNull(),
  ano: integer('ano').notNull(),
  tpAmb: varchar('tp_amb', { length: 1 }).notNull(),
  motivo: text('motivo').notNull(),
  nProt: varchar('n_prot', { length: 15 }),
  cStat: varchar('c_stat', { length: 3 }),
  xmlStorageKey: text('xml_storage_key'),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
});

export const lote = pgTable('lote', {
  id: uuid('id').primaryKey().defaultRandom(),
  emitenteId: uuid('emitente_id').notNull().references(() => emitente.id),
  idLote: varchar('id_lote', { length: 15 }).notNull(),
  nRec: varchar('n_rec', { length: 15 }),
  nfeId: uuid('nfe_id').references(() => nfe.id),
  status: varchar('status', { length: 20 }).notNull().default('ENVIADO'),
  tentativas: integer('tentativas').notNull().default(0),
  proximoPollEm: timestamp('proximo_poll_em', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
});

export const idempotency = pgTable('idempotency', {
  key: varchar('key', { length: 64 }).primaryKey(),
  response: jsonb('response').notNull(),
  expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
});

export const outbox = pgTable('outbox', {
  id: uuid('id').primaryKey().defaultRandom(),
  eventType: varchar('event_type', { length: 50 }).notNull(),
  payload: jsonb('payload').notNull(),
  published: boolean('published').default(false).notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
});

export const auditLog = pgTable('audit_log', {
  id: uuid('id').primaryKey().defaultRandom(),
  action: varchar('action', { length: 50 }).notNull(),
  entity: varchar('entity', { length: 50 }).notNull(),
  entityId: varchar('entity_id', { length: 64 }).notNull(),
  emitenteId: uuid('emitente_id'),
  metadata: jsonb('metadata'),
  ip: varchar('ip', { length: 45 }),
  createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
});

export const systemSettings = pgTable('system_settings', {
  id: integer('id').primaryKey().default(1),
  emitentePadraoId: uuid('emitente_padrao_id').references(() => emitente.id),
  logLevel: varchar('log_level', { length: 10 }),
  webPasswordHash: varchar('web_password_hash', { length: 128 }),
  updatedAt: timestamp('updated_at', { withTimezone: true }).defaultNow().notNull(),
});
