# Use the official Python base image
FROM python:3.8-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the Python script into the container
COPY main.py .

# Run the Python script when the container starts
CMD ["python", "main.py"]



# docker build -t bisect-docker .


# docker run bisect-docker
