SELECT 
VAR.DESCRVAR,
AVG(TET.PERCREAL) PERC,
SUM(TET.BASECALC) BENEFICIO_REAL,
0 BENEFICIO_PREVISTO_POR_ENQUANTO
FROM AD_REALSINTET TET
INNER JOIN AD_VARIAVPLUS VAR ON TET.CODVAR = VAR.NUVARIAV
WHERE TET.AGRUPADOR not like 'GATILHO' 
AND TET.CODFECH = 1 --SUBST. POR VAR NO JS
GROUP BY 
VAR.DESCRVAR
