SELECT 

CODEMP,
NUNOTA,
VLRNOTA
SUM(VLRNOTA) OVER (PARTITION BY CODEMP) AS SOMA_VLRNOTA


FROM (
SELECT CODEMP, NUNOTA, VLRNOTA FROM TGFCAB
WHERE ROWNUM <= 20 AND CODEMP IN (6)
UNION ALL
SELECT CODEMP, NUNOTA, VLRNOTA FROM TGFCAB
WHERE ROWNUM <= 20 AND CODEMP IN (5)
UNION ALL
SELECT CODEMP, NUNOTA, VLRNOTA FROM TGFCAB
WHERE ROWNUM <= 20 AND CODEMP IN (4)
UNION ALL
SELECT CODEMP, NUNOTA, VLRNOTA FROM TGFCAB
WHERE ROWNUM <= 20 AND CODEMP IN (3)
UNION ALL
SELECT CODEMP, NUNOTA, VLRNOTA FROM TGFCAB
WHERE ROWNUM <= 20 AND CODEMP IN (2)
UNION ALL
SELECT CODEMP, NUNOTA, VLRNOTA FROM TGFCAB
WHERE ROWNUM <= 20 AND CODEMP IN (1)
)