
/*query do card*/
SELECT
  COUNT(CASE WHEN NVL(TMT.TIPO,'NF') = 'CO' THEN 1 END) AS qtd_co,
  COUNT(*) AS total_ordens,
  ROUND(100 * COUNT(CASE WHEN NVL(TMT.TIPO,'NF') = 'CO' THEN 1 END) / NULLIF(COUNT(*), 0), 2) AS participacao_pct_co
FROM TMEOMT OMT
LEFT JOIN TMETMT TMT ON OMT.CODTMT = TMT.CODTMT
WHERE OMT.DTHRCAD BETWEEN TO_DATE(:dtInicial, 'DD-MM-YYYY') AND TO_DATE(:dtFinal, 'DD-MM-YYYY')





/*query do grafico*/

SELECT
  TO_CHAR(OMT.DTHRCAD,'YYYY') ANO,
  TO_CHAR(OMT.DTHRCAD,'MM') MES,
  COUNT(CASE WHEN NVL(TMT.TIPO,'NF') = 'CO' THEN 1 END) AS qtd_co,
  COUNT(*) AS total_ordens,
  ROUND(100 * COUNT(CASE WHEN NVL(TMT.TIPO,'NF') = 'CO' THEN 1 END) / NULLIF(COUNT(*), 0), 2) AS participacao_pct_co
FROM TMEOMT OMT
LEFT JOIN TMETMT TMT ON OMT.CODTMT = TMT.CODTMT
WHERE OMT.DTHRCAD BETWEEN TO_DATE(:dtInicial, 'DD-MM-YYYY') AND TO_DATE(:dtFinal, 'DD-MM-YYYY')
GROUP BY 
  TO_CHAR(OMT.DTHRCAD,'YYYY'),
  TO_CHAR(OMT.DTHRCAD,'MM')
ORDER BY
  TO_CHAR(OMT.DTHRCAD,'YYYY'),
  TO_CHAR(OMT.DTHRCAD,'MM')
  
  
  
/*query dA TABELA*/  
SELECT
OMT.codomt,
OMT.codimt,
NVL(TMT.DESCRICAO,'NAO INFORMADO')DESCRICAO,
NVL(TMT.TIPO,'NF')TIPO,
NVL(F_DESCROPC('TMETMT', 'TIPO', TMT.TIPO),'NAO INFORMADO') DESC_TIPO,
OMT.status,
F_DESCROPC('TMEOMT', 'STATUS', OMT.STATUS) DESC_STATUS,
OMT.DTHRCAD,
OMT.DTHRCONCLUSAO,
OMT.TEMPOPARADO,
OMT.USUSOL
FROM TMEOMT OMT
LEFT JOIN TMETMT TMT ON OMT.CODTMT = TMT.CODTMT
WHERE OMT.DTHRCAD BETWEEN TO_DATE(:dtInicial, 'DD-MM-YYYY') AND TO_DATE(:dtFinal, 'DD-MM-YYYY')
AND NVL(TMT.TIPO,'NF') = 'CO' 

  
  
  
  
  
  
  
  
  