select
OMT.codomt,
OMT.codimt,
NVL(TMT.DESCRICAO,'NAO INFORMADO')DESCRICAO,
NVL(TMT.TIPO,'NF')TIPO,
NVL(F_DESCROPC('TMETMT', 'TIPO', TMT.TIPO),'NAO INFORMADO') DESC_TIPO,
OMT.status,
F_DESCROPC('TMEOMT', 'STATUS', OMT.STATUS) DESC_STATUS,
OMT.DTHRCAD
from TMEOMT OMT
LEFT JOIN TMETMT TMT ON OMT.codimt = TMT.CODTMT