SELECT 
       CODIGO_ITEM,
       ITEM,
       CODIGO_GRUPO,
       GRUPO,
       CODVOL,
       QUANTIDADE,
       TOTALUNID,
       QTDPREV,
       QUANTIDADE / NULLIF(QTDPREV,0) AS PERC_REALIZADO,
       TOTALUNID -QTDPREV AS DIFERENCA
FROM (
    SELECT 
           I.CODPROD AS CODIGO_ITEM,
           P.DESCRPROD AS ITEM,
           P.CODGRUPOPROD AS CODIGO_GRUPO,
           G.DESCRGRUPOPROD AS GRUPO,
           I.CODVOL,
           SUM(I.QTDNEG) AS QUANTIDADE,
           SUM(I.QTDNEG * AD_QTDVOLLT) as TOTALUNID,
           (SELECT SUM(MET.QTDPREV / ABS(TO_CHAR(last_day(TO_DATE(MET.DTREF)),'DD')) *
                    (ABS((CASE WHEN TO_DATE('31/01/2026') > last_day(TO_DATE(MET.DTREF)) THEN last_day(TO_DATE(MET.DTREF)) ELSE TO_DATE('31/01/2026') END -  		TRUNC(MET.DTREF,'MM')))+1)) AS QTDPREV
            FROM TGMMET MET
            WHERE MET.CODMETA = 8
            AND MET.DTREF BETWEEN TRUNC(TO_DATE('01/07/2025'),'MM') AND '31/01/2026'
            AND MET.CODPROD = I.CODPROD) AS QTDPREV
    FROM TGFCAB C
    INNER JOIN TGFITE I ON I.NUNOTA = C.NUNOTA
    INNER JOIN TGFPRO P ON P.CODPROD = I.CODPROD
    INNER JOIN TGFGRU G ON G.CODGRUPOPROD = P.CODGRUPOPROD
    WHERE C.TIPMOV = 'F'
      AND C.CODTIPOPER = 801
      AND C.DTNEG BETWEEN '01/07/2025' AND '31/01/2026'
      --AND I.SEQUENCIA = 1
      AND I.USOPROD = 'V'
    GROUP BY
           I.CODPROD,
           P.DESCRPROD,
           P.CODGRUPOPROD,
           G.DESCRGRUPOPROD,
           I.CODVOL

    UNION ALL

    SELECT 
           P.CODPROD AS CODIGO_ITEM,
           P.DESCRPROD AS ITEM,
           P.CODGRUPOPROD AS CODIGO_GRUPO,
           G.DESCRGRUPOPROD AS GRUPO,
           P.CODVOL,
           0 AS QUANTIDADE,
           0 AS TOTALUNID,
           (SELECT SUM(MET.QTDPREV / ABS(TO_CHAR(last_day(TO_DATE(MET.DTREF)),'DD')) *
                    (ABS((CASE WHEN TO_DATE('31/01/2026') > last_day(TO_DATE(MET.DTREF)) THEN last_day(TO_DATE(MET.DTREF)) ELSE TO_DATE('31/01/2026') END -  		TRUNC(MET.DTREF,'MM')))+1)) AS QTDPREV
            FROM TGMMET MET
            WHERE MET.CODMETA = 8
            AND MET.DTREF BETWEEN TRUNC(TO_DATE('01/07/2025'),'MM') AND '31/01/2026'
            AND MET.CODPROD = P.CODPROD) AS QTDPREV
    FROM TGMMET M
    INNER JOIN TGFPRO P ON P.CODPROD = M.CODPROD
    INNER JOIN TGFGRU G ON G.CODGRUPOPROD = P.CODGRUPOPROD
    WHERE M.CODMETA = 8
      AND NVL(M.QTDPREV,0) <> 0
      AND NOT EXISTS (SELECT 1 FROM TGFITE I, TGFCAB C WHERE C.NUNOTA = I.NUNOTA AND I.CODPROD = M.CODPROD AND C.CODTIPOPER = 801 AND C.DTNEG BETWEEN '01/07/2025' AND '31/01/2026' AND I.USOPROD = 'V')
    GROUP BY
           P.CODPROD,
           P.DESCRPROD,
           P.CODGRUPOPROD,
           G.DESCRGRUPOPROD,
           P.CODVOL
) 
WHERE QTDPREV > 0
ORDER BY 1
