select 
cab.CODEMP,
cab.NUNOTA,
cab.NUMNOTA,
cab.CODPARC,
par.nomeparc,
cab.DTNEG,
cab.DTFATUR,
cab.DTENTSAI,
cab.DTMOV,
cab.VLRNOTA,
cab.VLRFRETE,
CASE 
    WHEN cab.VLRNOTA > 0 THEN ROUND((cab.VLRFRETE / cab.VLRNOTA) * 100, 2)
    ELSE 0
END AS PERC_FRETE_VLRNOTA
FROM TGFCAB cab
INNER JOIN TGFPAR PAR ON CAB.CODPARC = PAR.CODPARC
WHERE cab.TIPMOV = 'C' and cab.VLRFRETE > 0
