SELECT ORDEMCARGA,AD_DTENTREGAEFETIVA, AD_DTENTREGAPREV, AD_DTENTREGAPREV - AD_DTENTREGAEFETIVA AS DIFERENCA_DIAS FROM (
select ORDEMCARGA,min(AD_DTENTREGAEFETIVA)AD_DTENTREGAEFETIVA, min(AD_DTENTREGAPREV)AD_DTENTREGAPREV FROM (

SELECT 1 AS AD_ANEXO,1 AS AD_ANEXONF,TGFCAB.AD_ATUALICMS AS AD_ATUALICMS,TGFCAB.AD_CALCPALETE AS AD_CALCPALETE,TGFCAB.AD_CAMPCASHENV AS AD_CAMPCASHENV,TGFCAB.AD_CAMPNROENV AS AD_CAMPNROENV,TGFCAB.AD_CNPJ_CPF AS AD_CNPJ_CPF,TGFCAB.AD_CODAGENTE AS AD_CODAGENTE,TGFCAB.AD_CODCOMP AS AD_CODCOMP,TGFCAB.AD_CODEMPORIGEM AS AD_CODEMPORIGEM,TGFCAB.AD_CODPARCCAMP AS AD_CODPARCCAMP,TGFCAB.AD_CODPARCLDR AS AD_CODPARCLDR,TGFCAB.AD_CODPUBLALVO AS AD_CODPUBLALVO,TGFCAB.AD_CODTIPTIT AS AD_CODTIPTIT,TGFCAB.AD_CODTIPVENDAMKT AS AD_CODTIPVENDAMKT,TGFCAB.AD_CODTIPVENDAORIG AS AD_CODTIPVENDAORIG,TGFCAB.AD_CODUSUENV AS AD_CODUSUENV,TGFCAB.AD_CODVENDRTV AS AD_CODVENDRTV,TGFCAB.AD_DISTANCIAKM AS AD_DISTANCIAKM,TGFCAB.AD_DTAPREVCOMERCIAL AS AD_DTAPREVCOMERCIAL,TGFCAB.AD_DTCOLETAEFETIVA AS AD_DTCOLETAEFETIVA,TGFCAB.AD_DTCOLETAPREVISTA AS AD_DTCOLETAPREVISTA,TGFCAB.AD_DTENTREGAEFETIVA AS AD_DTENTREGAEFETIVA,TGFCAB.AD_DTENTREGAPREV AS AD_DTENTREGAPREV,TGFCAB.AD_DTENVFIS AS AD_DTENVFIS,TGFCAB.AD_DTESTFIS AS AD_DTESTFIS,TGFCAB.AD_DTNEC AS AD_DTNEC,TGFCAB.AD_DTORDCARGA AS AD_DTORDCARGA,TGFCAB.AD_DTREENVFIS AS AD_DTREENVFIS,TGFCAB.AD_DTVENC AS AD_DTVENC,TGFCAB.AD_DTVENCIMENT AS AD_DTVENCIMENT,TGFCAB.AD_DTVENCORIG AS AD_DTVENCORIG,TGFCAB.AD_DT_CHEGADA_FABRICA AS AD_DT_CHEGADA_FABRICA,TGFCAB.AD_DT_CHEGADA_PORTO AS AD_DT_CHEGADA_PORTO,TGFCAB.AD_DT_EMBARQUE AS AD_DT_EMBARQUE,TGFCAB.AD_DUPLENV AS AD_DUPLENV,TGFCAB.AD_EMAILENV AS AD_EMAILENV,TGFCAB.AD_EMBARQUE AS AD_EMBARQUE,TGFCAB.AD_ENTREGUE AS AD_ENTREGUE,TGFCAB.AD_ENVRELMAPA AS AD_ENVRELMAPA,TGFCAB.AD_ESTORNFIS AS AD_ESTORNFIS,TGFCAB.AD_ESTRADATERRA AS AD_ESTRADATERRA,TGFCAB.AD_EXIGEBOL AS AD_EXIGEBOL,TGFCAB.AD_FEEDBACK AS AD_FEEDBACK,TGFCAB.AD_FEEDBACKCOMPRA AS AD_FEEDBACKCOMPRA,TGFCAB.AD_GERFINCOM AS AD_GERFINCOM,TGFCAB.AD_GUIAEMITIDA AS AD_GUIAEMITIDA,TGFCAB.AD_HRRECFIN AS AD_HRRECFIN,TGFCAB.AD_HRRECINI AS AD_HRRECINI,TGFCAB.AD_IDFAT AS AD_IDFAT,TGFCAB.AD_IMPSALDO AS AD_IMPSALDO,TGFCAB.AD_LIBERADO AS AD_LIBERADO,TGFCAB.AD_LIBERADOPEDCOM AS AD_LIBERADOPEDCOM,TGFCAB.AD_LIBFATURAMENTO AS AD_LIBFATURAMENTO,TGFCAB.AD_LINHAPROD1 AS AD_LINHAPROD1,TGFCAB.AD_LINHAPROD2 AS AD_LINHAPROD2,TGFCAB.AD_LINHAPROD3 AS AD_LINHAPROD3,TGFCAB.AD_LINHASPROD AS AD_LINHASPROD,TGFCAB.AD_LOCALVALID AS AD_LOCALVALID,TGFCAB.AD_LOGENTREEFTIVA AS AD_LOGENTREEFTIVA,TGFCAB.AD_MOTCANCELAMENTO AS AD_MOTCANCELAMENTO,TGFCAB.AD_MOTESTFIS AS AD_MOTESTFIS,TGFCAB.AD_MOTEXCLUSAO AS AD_MOTEXCLUSAO,TGFCAB.AD_MOTIVO AS AD_MOTIVO,TGFCAB.AD_MTVMOV AS AD_MTVMOV,TGFCAB.AD_NOTIFICALIB AS AD_NOTIFICALIB,TGFCAB.AD_NROUNICOADT AS AD_NROUNICOADT,TGFCAB.AD_NUNOTANF AS AD_NUNOTANF,TGFCAB.AD_NUNOTAORIG AS AD_NUNOTAORIG,TGFCAB.AD_NUNOTAPED AS AD_NUNOTAPED,TGFCAB.AD_NUNOTATRANSF AS AD_NUNOTATRANSF,TGFCAB.AD_NUPEDORIG AS AD_NUPEDORIG,TGFCAB.AD_OBSERVACAOOC AS AD_OBSERVACAOOC,TGFCAB.AD_OBSERVCOT AS AD_OBSERVCOT,TGFCAB.AD_OBSFEEDBACK AS AD_OBSFEEDBACK,TGFCAB.AD_OBSFEEDBACKCOMPRA AS AD_OBSFEEDBACKCOMPRA,TGFCAB.AD_OBSINT AS AD_OBSINT,TGFCAB.AD_OBSINTERNA AS AD_OBSINTERNA,TGFCAB.AD_OBSPAG AS AD_OBSPAG,TGFCAB.AD_PENDENTECOMISSAO AS AD_PENDENTECOMISSAO,TGFCAB.AD_PRAZOFERT AS AD_PRAZOFERT,TGFCAB.AD_QTDESTFIS AS AD_QTDESTFIS,TGFCAB.AD_QTDKMTERRA AS AD_QTDKMTERRA,TGFCAB.AD_QTDPALETE AS AD_QTDPALETE,TGFCAB.AD_QTDREENVFIS AS AD_QTDREENVFIS,TGFCAB.AD_QUALIDADE AS AD_QUALIDADE,TGFCAB.AD_REFENTREGA AS AD_REFENTREGA,TGFCAB.AD_REFFORCA AS AD_REFFORCA,TGFCAB.AD_REFLOC AS AD_REFLOC,TGFCAB.AD_REGIAO AS AD_REGIAO,TGFCAB.AD_RESTVEICULO AS AD_RESTVEICULO,TGFCAB.AD_RETPEDIDO AS AD_RETPEDIDO,TGFCAB.AD_STATUSA2WV2 AS AD_STATUSA2WV2,TGFCAB.AD_STSMAILCLIEN AS AD_STSMAILCLIEN,TGFCAB.AD_TIPVERBA AS AD_TIPVERBA,TGFCAB.AD_URGENCIA AS AD_URGENCIA,TGFCAB.AD_USAVOLPALETE AS AD_USAVOLPALETE,TGFCAB.AD_USUESTFIS AS AD_USUESTFIS,TGFCAB.AD_VALFIN AS AD_VALFIN,TGFCAB.AD_VALFIS AS AD_VALFIS,TGFCAB.AD_VALPRECO AS AD_VALPRECO,TGFCAB.AD_VERIF_FAT_PARCIAL AS AD_VERIF_FAT_PARCIAL,TGFCAB.AD_VLRCUSAD AS AD_VLRCUSAD,TGFCAB.AD_VLRREPREDTOT_BKP AS AD_VLRREPREDTOT_BKP,TGFCAB.AGRUPFINNOTA AS AGRUPFINNOTA,TGFCAB.ALIQICMSRET AS ALIQICMSRET,TGFCAB.ALIQIRF AS ALIQIRF,TGFCAB.ANTT AS ANTT,TGFCAB.APROVADO AS APROVADO,TGFCAB.BASECOFINS AS BASECOFINS,TGFCAB.BASECOFINSST AS BASECOFINSST,TGFCAB.BASEICMS AS BASEICMS,TGFCAB.BASEICMSAT AS BASEICMSAT,TGFCAB.BASEICMSFRETE AS BASEICMSFRETE,TGFCAB.BASEICMSSTFRETE AS BASEICMSSTFRETE,TGFCAB.BASEINSS AS BASEINSS,TGFCAB.BASEIPI AS BASEIPI,TGFCAB.BASEIRF AS BASEIRF,TGFCAB.BASEISS AS BASEISS,TGFCAB.BASEPIS AS BASEPIS,TGFCAB.BASEPISST AS BASEPISST,TGFCAB.BASESUBSTIT AS BASESUBSTIT,TGFCAB.BASESUBSTSEMRED AS BASESUBSTSEMRED,TGFCAB.BCICMSRET AS BCICMSRET,TGFCAB.CARACAD AS CARACAD,TGFCAB.CARACSER AS CARACSER,TGFCAB.CHAVECTE AS CHAVECTE,TGFCAB.CHAVECTEREF AS CHAVECTEREF,TGFCAB.CHAVENFCOM AS CHAVENFCOM,TGFCAB.CHAVENFE AS CHAVENFE,TGFCAB.CHAVENFEREF AS CHAVENFEREF,TGFCAB.CHAVENFETERCEIROREF AS CHAVENFETERCEIROREF,TGFCAB.CHAVENFSE AS CHAVENFSE,TGFCAB.CHAVESINIEF1324 AS CHAVESINIEF1324,TGFCAB.CHVNFEINEREF AS CHVNFEINEREF,TGFCAB.CIF_FOB AS CIF_FOB,TGFCAB.CIOT AS CIOT,TGFCAB.CLASCONS AS CLASCONS,TGFCAB.CLASSIFICMS AS CLASSIFICMS,TGFCAB.CLIENTEIDPARCERIA AS CLIENTEIDPARCERIA,TGFCAB.CMUNFATGER AS CMUNFATGER,TGFCAB.CNPJADQUIRENTE AS CNPJADQUIRENTE,TGFCAB.CODART AS CODART,TGFCAB.CODCC AS CODCC,TGFCAB.CODCENCUS AS CODCENCUS,TGFCAB.CODCFO AS CODCFO,TGFCAB.CODCHECKOUT AS CODCHECKOUT,TGFCAB.CODCID AS CODCID,TGFCAB.CODCIDDESTINO AS CODCIDDESTINO,TGFCAB.CODCIDENTREGA AS CODCIDENTREGA,TGFCAB.CODCIDFIMCTE AS CODCIDFIMCTE,TGFCAB.CODCIDINICTE AS CODCIDINICTE,TGFCAB.CODCIDORIGEM AS CODCIDORIGEM,TGFCAB.CODCIDPREST AS CODCIDPREST,TGFCAB.CODCONTATO AS CODCONTATO,TGFCAB.CODCONTATOENTREGA AS CODCONTATOENTREGA,TGFCAB.CODDOCA AS CODDOCA,TGFCAB.CODDOCARRECAD AS CODDOCARRECAD,TGFCAB.CODEMP AS CODEMP,TGFCAB.CODEMPFUNC AS CODEMPFUNC,TGFCAB.CODEMPNEGOC AS CODEMPNEGOC,TGFCAB.CODFUNC AS CODFUNC,TGFCAB.CODGRUPOTENSAO AS CODGRUPOTENSAO,TGFCAB.CODGUF AS CODGUF,TGFCAB.CODINTERM AS CODINTERM,TGFCAB.CODMAQ AS CODMAQ,TGFCAB.CODMODDOCNOTA AS CODMODDOCNOTA,TGFCAB.CODMOEDA AS CODMOEDA,TGFCAB.CODMOTORISTA AS CODMOTORISTA,TGFCAB.CODNAT AS CODNAT,TGFCAB.CODOBRA AS CODOBRA,TGFCAB.CODOBSPADRAO AS CODOBSPADRAO,TGFCAB.CODPARC AS CODPARC,TGFCAB.CODPARCCONSIGNATARIO AS CODPARCCONSIGNATARIO,TGFCAB.CODPARCDESCARGAMDFE AS CODPARCDESCARGAMDFE,TGFCAB.CODPARCDEST AS CODPARCDEST,TGFCAB.CODPARCREDESPACHO AS CODPARCREDESPACHO,TGFCAB.CODPARCREMETENTE AS CODPARCREMETENTE,TGFCAB.CODPARCRETIRADA AS CODPARCRETIRADA,TGFCAB.CODPARCTRANSP AS CODPARCTRANSP,TGFCAB.CODPARCTRANSPFINAL AS CODPARCTRANSPFINAL,TGFCAB.CODPROJ AS CODPROJ,TGFCAB.CODRASTREAMENTOECT AS CODRASTREAMENTOECT,TGFCAB.CODSITE AS CODSITE,TGFCAB.CODTIPOPER AS CODTIPOPER,TGFCAB.CODTIPVENDA AS CODTIPVENDA,TGFCAB.CODTPD AS CODTPD,TGFCAB.CODUFDESTINO AS CODUFDESTINO,TGFCAB.CODUFENTREGA AS CODUFENTREGA,TGFCAB.CODUFORIGEM AS CODUFORIGEM,TGFCAB.CODUSU AS CODUSU,TGFCAB.CODUSUCOMPRADOR AS CODUSUCOMPRADOR,TGFCAB.CODUSUINC AS CODUSUINC,TGFCAB.CODVEICULO AS CODVEICULO,TGFCAB.CODVEND AS CODVEND,TGFCAB.CODVENDTEC AS CODVENDTEC,TGFCAB.CODVTP AS CODVTP,TGFCAB.COMGER AS COMGER,TGFCAB.COMISSAO AS COMISSAO,TGFCAB.CONFIRMNOTAFAT AS CONFIRMNOTAFAT,TGFCAB.CPFCNPJADQUIRENTE AS CPFCNPJADQUIRENTE,TGFCAB.CPFRESPTEC AS CPFRESPTEC,TGFCAB.CTEGLOBAL AS CTEGLOBAL,TGFCAB.CTELOTACAO AS CTELOTACAO,TGFCAB.DANFE AS DANFE,TGFCAB.DHEMISSEPEC AS DHEMISSEPEC,TGFCAB.DHPROTOC AS DHPROTOC,TGFCAB.DHPROTOCCTE AS DHPROTOCCTE,TGFCAB.DHREGDPEC AS DHREGDPEC,TGFCAB.DHTIPOPER AS DHTIPOPER,TGFCAB.DHTIPVENDA AS DHTIPVENDA,TGFCAB.DHVIAGEM AS DHVIAGEM,TGFCAB.DIGITAL AS DIGITAL,TGFCAB.DIRECAOVIAG AS DIRECAOVIAG,TGFCAB.DISDESAUTIMPEMB AS DISDESAUTIMPEMB,TGFCAB.DTADIAM AS DTADIAM,TGFCAB.DTALTER AS DTALTER,TGFCAB.DTCONTAB AS DTCONTAB,TGFCAB.DTDECLARA AS DTDECLARA,TGFCAB.DTENTSAI AS DTENTSAI,TGFCAB.DTENTSAIINFO AS DTENTSAIINFO,TGFCAB.DTENVIOPMB AS DTENVIOPMB,TGFCAB.DTENVSUF AS DTENVSUF,TGFCAB.DTESCRCONT AS DTESCRCONT,TGFCAB.DTFATUR AS DTFATUR,TGFCAB.DTMOV AS DTMOV,TGFCAB.DTNEG AS DTNEG,TGFCAB.DTPREVENT AS DTPREVENT,TGFCAB.DTREF AS DTREF,TGFCAB.DTREF2 AS DTREF2,TGFCAB.DTREF3 AS DTREF3,TGFCAB.DTREMRET AS DTREMRET,TGFCAB.DTVAL AS DTVAL,TGFCAB.EXIGEISSQN AS EXIGEISSQN,TGFCAB.FISTEL AS FISTEL,TGFCAB.FORMPGTCTE AS FORMPGTCTE,TGFCAB.FRETEVLRPAGO AS FRETEVLRPAGO,TGFCAB.FUSOEMISSEPEC AS FUSOEMISSEPEC,TGFCAB.HISTCONFIG AS HISTCONFIG,TGFCAB.HRADIAM AS HRADIAM,TGFCAB.HRENTSAI AS HRENTSAI,TGFCAB.HRMOV AS HRMOV,TGFCAB.ICMSFRETE AS ICMSFRETE,TGFCAB.ICMSSTFRETE AS ICMSSTFRETE,TGFCAB.IDBALSA01 AS IDBALSA01,TGFCAB.IDBALSA02 AS IDBALSA02,TGFCAB.IDBALSA03 AS IDBALSA03,TGFCAB.IDDESCPARCERIA AS IDDESCPARCERIA,TGFCAB.IDIPROC AS IDIPROC,TGFCAB.IDNAVIO AS IDNAVIO,TGFCAB.IDPONTUACAOPARCERIA AS IDPONTUACAOPARCERIA,TGFCAB.INDNEGMODAL AS INDNEGMODAL,TGFCAB.INDPRESNFCE AS INDPRESNFCE,TGFCAB.INTERMED AS INTERMED,TGFCAB.IPIEMB AS IPIEMB,TGFCAB.IRFRETIDO AS IRFRETIDO,TGFCAB.IRINNAVIO AS IRINNAVIO,TGFCAB.ISSRETIDO AS ISSRETIDO,TGFCAB.KMVEICULO AS KMVEICULO,TGFCAB.LACRES AS LACRES,TGFCAB.LATITUDE AS LATITUDE,TGFCAB.LIBCONF AS LIBCONF,TGFCAB.LOCALCOLETA AS LOCALCOLETA,TGFCAB.LOCALENTREGA AS LOCALENTREGA,TGFCAB.LOCEMBARQ AS LOCEMBARQ,TGFCAB.LONGITUDE AS LONGITUDE,TGFCAB.LOTACAO AS LOTACAO,TGFCAB.M3 AS M3,TGFCAB.MARCA AS MARCA,TGFCAB.MD5MODCOMTEL AS MD5MODCOMTEL,TGFCAB.MODELONFDES AS MODELONFDES,TGFCAB.MODENTREGA AS MODENTREGA,TGFCAB.MODRECEBPDVWEB AS MODRECEBPDVWEB,TGFCAB.MOTNAORETERISSQN AS MOTNAORETERISSQN,TGFCAB.NATUREZAOPERDES AS NATUREZAOPERDES,TGFCAB.NFEDEVRECUSA AS NFEDEVRECUSA,TGFCAB.NFSEID AS NFSEID,TGFCAB.NOMEADQUIRENTE AS NOMEADQUIRENTE,TGFCAB.NOTAEMPENHO AS NOTAEMPENHO,TGFCAB.NOTAPORPEDIDOPDV AS NOTAPORPEDIDOPDV,TGFCAB.NOTASCF AS NOTASCF,TGFCAB.NROCAIXA AS NROCAIXA,TGFCAB.NROREDZ AS NROREDZ,TGFCAB.NUCFR AS NUCFR,TGFCAB.NUCONFATUAL AS NUCONFATUAL,TGFCAB.NUFOP AS NUFOP,TGFCAB.NULOTECTE AS NULOTECTE,TGFCAB.NULOTENFCOM AS NULOTENFCOM,TGFCAB.NULOTENFE AS NULOTENFE,TGFCAB.NULOTENFSE AS NULOTENFSE,TGFCAB.NUMALEATORIO AS NUMALEATORIO,TGFCAB.NUMALEATORIOCTE AS NUMALEATORIOCTE,TGFCAB.NUMCF AS NUMCF,TGFCAB.NUMCONTRATO AS NUMCONTRATO,TGFCAB.NUMCOTACAO AS NUMCOTACAO,TGFCAB.NUMCSTC AS NUMCSTC,TGFCAB.NUMDOCARRECAD AS NUMDOCARRECAD,TGFCAB.NUMERACAOVOLUMES AS NUMERACAOVOLUMES,TGFCAB.NUMGUIA AS NUMGUIA,TGFCAB.NUMNFSE AS NUMNFSE,TGFCAB.NUMNOTA AS NUMNOTA,TGFCAB.NUMOS AS NUMOS,TGFCAB.NUMPEDIDO2 AS NUMPEDIDO2,TGFCAB.NUMPROTOC AS NUMPROTOC,TGFCAB.NUMPROTOCCTE AS NUMPROTOCCTE,TGFCAB.NUMPROTOCINCTE AS NUMPROTOCINCTE,TGFCAB.NUMPROTOCINNFE AS NUMPROTOCINNFE,TGFCAB.NUMPROTOCNFCOM AS NUMPROTOCNFCOM,TGFCAB.NUMRECEITAGRO AS NUMRECEITAGRO,TGFCAB.NUMREGDPEC AS NUMREGDPEC,TGFCAB.NUMTERMTEL AS NUMTERMTEL,TGFCAB.NUNOTA AS NUNOTA,TGFCAB.NUNOTAPEDFRET AS NUNOTAPEDFRET,TGFCAB.NUNOTAREC AS NUNOTAREC,TGFCAB.NUNOTASUB AS NUNOTASUB,TGFCAB.NUODP AS NUODP,TGFCAB.NUPCA AS NUPCA,TGFCAB.NUPEDFRETE AS NUPEDFRETE,TGFCAB.NURD8 AS NURD8,TGFCAB.NURECEBIMENTO AS NURECEBIMENTO,TGFCAB.NUREM AS NUREM,TGFCAB.NUSESSAO AS NUSESSAO,TGFCAB.NUTRANSF AS NUTRANSF,TGFCAB.OBSERVACAO AS OBSERVACAO,TGFCAB.OCCN48 AS OCCN48,TGFCAB.ORDEMCARGA AS ORDEMCARGA,TGFCAB.PENDENTE AS PENDENTE,TGFCAB.PERCDESC AS PERCDESC,TGFCAB.PERCDESCFOB AS PERCDESCFOB,TGFCAB.PERMALTERCENTRAL AS PERMALTERCENTRAL,TGFCAB.PESO AS PESO,TGFCAB.PESOBRUTO AS PESOBRUTO,TGFCAB.PESOBRUTOMANUAL AS PESOBRUTOMANUAL,TGFCAB.PESOLIQUIMANUAL AS PESOLIQUIMANUAL,TGFCAB.PLACA AS PLACA,TGFCAB.PREMIACAOESTADUAL AS PREMIACAOESTADUAL,TGFCAB.PRODPRED AS PRODPRED,TGFCAB.PRODUETLOC AS PRODUETLOC,TGFCAB.QTDUSU AS QTDUSU,TGFCAB.QTDVOL AS QTDVOL,TGFCAB.RATEADO AS RATEADO,TGFCAB.REBOQUE1 AS REBOQUE1,TGFCAB.REBOQUE2 AS REBOQUE2,TGFCAB.REBOQUE3 AS REBOQUE3,TGFCAB.REGESPTRIBUT AS REGESPTRIBUT,TGFCAB.RETGERWMS AS RETGERWMS,TGFCAB.RETORNOEQUIPFISCAL AS RETORNOEQUIPFISCAL,TGFCAB.SEQCARGA AS SEQCARGA,TGFCAB.SERIEGUIA AS SERIEGUIA,TGFCAB.SERIENFDES AS SERIENFDES,TGFCAB.SERIENFSE AS SERIENFSE,TGFCAB.SERIENOTA AS SERIENOTA,TGFCAB.SITESPECIALRESP AS SITESPECIALRESP,TGFCAB.SITUACAOCTE AS SITUACAOCTE,TGFCAB.SITUACAONFCOM AS SITUACAONFCOM,TGFCAB.SOMDESPADUNFENAC AS SOMDESPADUNFENAC,TGFCAB.SOMICMSNFENAC AS SOMICMSNFENAC,TGFCAB.SOMPISCOFNFENAC AS SOMPISCOFNFENAC,TGFCAB.STATUSCFE AS STATUSCFE,TGFCAB.STATUSCTE AS STATUSCTE,TGFCAB.STATUSNFCOM AS STATUSNFCOM,TGFCAB.STATUSNFE AS STATUSNFE,TGFCAB.STATUSNFSE AS STATUSNFSE,TGFCAB.STATUSNOTA AS STATUSNOTA,TGFCAB.SUMVLRIIOUTNOTA AS SUMVLRIIOUTNOTA,TGFCAB.TERMACORDNOTA AS TERMACORDNOTA,TGFCAB.TIMCONTRATOLTV AS TIMCONTRATOLTV,TGFCAB.TIMCONTRATOVENDA AS TIMCONTRATOVENDA,TGFCAB.TIMNUFINORIG AS TIMNUFINORIG,TGFCAB.TIMNUNOTAMOD AS TIMNUNOTAMOD,TGFCAB.TIMORIGEM AS TIMORIGEM,TGFCAB.TIPCLIENTESERVCOM AS TIPCLIENTESERVCOM,TGFCAB.TIPFRETE AS TIPFRETE,TGFCAB.TIPIPIEMB AS TIPIPIEMB,TGFCAB.TIPMOV AS TIPMOV,TGFCAB.TIPNOTAPMB AS TIPNOTAPMB,TGFCAB.TIPOGUIA AS TIPOGUIA,TGFCAB.TIPOPTAGJNFE AS TIPOPTAGJNFE,TGFCAB.TIPPROCIMP AS TIPPROCIMP,TGFCAB.TOTALCUSTOPROD AS TOTALCUSTOPROD,TGFCAB.TOTALCUSTOSERV AS TOTALCUSTOSERV,TGFCAB.TOTDISPDESC AS TOTDISPDESC,TGFCAB.TPAMBCTE AS TPAMBCTE,TGFCAB.TPAMBNFCOM AS TPAMBNFCOM,TGFCAB.TPAMBNFE AS TPAMBNFE,TGFCAB.TPAMBNFSE AS TPAMBNFSE,TGFCAB.TPASSINANTE AS TPASSINANTE,TGFCAB.TPEMISCTE AS TPEMISCTE,TGFCAB.TPEMISNFCOM AS TPEMISNFCOM,TGFCAB.TPEMISNFE AS TPEMISNFE,TGFCAB.TPEMISNFSE AS TPEMISNFSE,TGFCAB.TPFRETAMENTO AS TPFRETAMENTO,TGFCAB.TPLIGACAO AS TPLIGACAO,TGFCAB.TPRETISS AS TPRETISS,TGFCAB.TROCO AS TROCO,TGFCAB.UFADQUIRENTE AS UFADQUIRENTE,TGFCAB.UFEMBARQ AS UFEMBARQ,TGFCAB.UFEMISS AS UFEMISS,TGFCAB.UFEMISSAO AS UFEMISSAO,TGFCAB.UFVEICULO AS UFVEICULO,TGFCAB.VALORDESONPISCOFINS AS VALORDESONPISCOFINS,TGFCAB.VENCFRETE AS VENCFRETE,TGFCAB.VENCIPI AS VENCIPI,TGFCAB.VIATRANSP AS VIATRANSP,TGFCAB.VLRAFRMM AS VLRAFRMM,TGFCAB.VLRCARGAAVERB AS VLRCARGAAVERB,TGFCAB.VLRCOFINS AS VLRCOFINS,TGFCAB.VLRCOFINSST AS VLRCOFINSST,TGFCAB.VLRDESCPARCERIA AS VLRDESCPARCERIA,TGFCAB.VLRDESCSERV AS VLRDESCSERV,TGFCAB.VLRDESCTOT AS VLRDESCTOT,TGFCAB.VLRDESCTOTITEM AS VLRDESCTOTITEM,TGFCAB.VLRDESCTOTITEMMOE AS VLRDESCTOTITEMMOE,TGFCAB.VLRDESTAQUE AS VLRDESTAQUE,TGFCAB.VLREMB AS VLREMB,TGFCAB.VLRFETHAB AS VLRFETHAB,TGFCAB.VLRFRETE AS VLRFRETE,TGFCAB.VLRFRETECALC AS VLRFRETECALC,TGFCAB.VLRFRETECPL AS VLRFRETECPL,TGFCAB.VLRFRETETOTAL AS VLRFRETETOTAL,TGFCAB.VLRICMS AS VLRICMS,TGFCAB.VLRICMSAT AS VLRICMSAT,TGFCAB.VLRICMSDIFALDEST AS VLRICMSDIFALDEST,TGFCAB.VLRICMSDIFALREM AS VLRICMSDIFALREM,TGFCAB.VLRICMSEMB AS VLRICMSEMB,TGFCAB.VLRICMSFCP AS VLRICMSFCP,TGFCAB.VLRICMSFCPINT AS VLRICMSFCPINT,TGFCAB.VLRICMSRET AS VLRICMSRET,TGFCAB.VLRICMSSEG AS VLRICMSSEG,TGFCAB.VLRINDENIZ AS VLRINDENIZ,TGFCAB.VLRINDENIZDIST AS VLRINDENIZDIST,TGFCAB.VLRINSS AS VLRINSS,TGFCAB.VLRIPI AS VLRIPI,TGFCAB.VLRIRF AS VLRIRF,TGFCAB.VLRISS AS VLRISS,TGFCAB.VLRJURO AS VLRJURO,TGFCAB.VLRJURODIST AS VLRJURODIST,TGFCAB.VLRLIQITEMNFE AS VLRLIQITEMNFE,TGFCAB.VLRMERCADORIA AS VLRMERCADORIA,TGFCAB.VLRMOEDA AS VLRMOEDA,TGFCAB.VLRNOTA AS VLRNOTA,TGFCAB.VLROUTROS AS VLROUTROS,TGFCAB.VLRPIS AS VLRPIS,TGFCAB.VLRPISST AS VLRPISST,TGFCAB.VLRPRESTAFRMM AS VLRPRESTAFRMM,TGFCAB.VLRREPREDST AS VLRREPREDST,TGFCAB.VLRREPREDTOT AS VLRREPREDTOT,TGFCAB.VLRREPREDTOTSEMDESC AS VLRREPREDTOTSEMDESC,TGFCAB.VLRREPTERC AS VLRREPTERC,TGFCAB.VLRROYALT AS VLRROYALT,TGFCAB.VLRSEG AS VLRSEG,TGFCAB.VLRSERVICO AS VLRSERVICO,TGFCAB.VLRSTEXTRANOTATOT AS VLRSTEXTRANOTATOT,TGFCAB.VLRSTFCPINT AS VLRSTFCPINT,TGFCAB.VLRSTFCPINTANT AS VLRSTFCPINTANT,TGFCAB.VLRSUBST AS VLRSUBST,TGFCAB.VLRTOTLIQITEMMOE AS VLRTOTLIQITEMMOE,TGFCAB.VLRVENDOR AS VLRVENDOR,TGFCAB.VOLUME AS VOLUME, (
SELECT CGC_CPF FROM TGFPAR WHERE CODPARC=TGFCAB.CODPARC) AS AD_CGC_CPF, (
SELECT UFS.UF|| '|' ||CID.NOMECID   FROM
TSICID CID, TSIUFS UFS, TGFPAR PAR
WHERE PAR.CODCID=CID.CODCID
AND CID.UF=UFS.CODUF
AND PAR.CODPARC=TGFCAB.CODPARC) AS AD_CIDPARC, (
SELECT 
  LISTAGG('Vencto.: ' || FIN.DTVENC || '  Vlr.: ' ||  FIN.VLRDESDOB || '  Tip. Titulo: ' || TIT.DESCRTIPTIT || ' ** ') 
  WITHIN GROUP (ORDER BY FIN.DTVENC, FIN.VLRDESDOB, TIT.DESCRTIPTIT) "DTVENC"
  FROM TGFFIN FIN, TGFCAB CAB1, TGFTOP TP, TGFTIT TIT
  WHERE FIN.NUNOTA = TGFCAB.NUNOTA
  AND FIN.NUNOTA = CAB1.NUNOTA
  AND CAB1.CODTIPOPER = TP.CODTIPOPER
  AND CAB1.DHTIPOPER = TP.DHALTER
  AND FIN.CODTIPTIT = TIT.CODTIPTIT
  AND TP.ATUALFIN <> 0
  GROUP BY FIN.NUNOTA, CAB1.CODTIPOPER, CAB1.DHTIPOPER) AS AD_DTVENCS, (
TGFCAB.AD_DTENTREGAEFETIVA - TGFCAB.AD_DTENTREGAPREV) AS AD_ENTREGAPRAZODIAS, (
SELECT
SYSDATE - LIB.DHSOLICIT
FROM TSILIB LIB
INNER JOIN TGFCAB CAB ON LIB.NUCHAVE = CAB.NUNOTA
WHERE LIB.DHLIB IS NULL AND CAB.TIPMOV = 'J'
AND LIB.NUCHAVE = TGFCAB.NUNOTA) AS AD_LIBPEND, (
CASE WHEN tgfcab.TIPMOV = 'O' THEN 
(SELECT 
LISTAGG(('Dt. Alteração: '|| T.DTALTER||CHR(13)||'Usuário: '||(SELECT USU.CODUSU||' - '|| USU.NOMEUSU FROM TSIUSU USU WHERE USU.CODUSU = T.CODUSU)
||CHR(13)||'Vlr. Anterior: '||T.VLRNOTA||CHR(13)||'Tipo de negociação anterior: '||T.CODTIPVENDA),CHR(13)||CHR(13) ) WITHIN GROUP (ORDER BY T.DTALTER DESC)
FROM TGFCAB_ALT_LIB T WHERE T.NUNOTA = TGFCAB.NUNOTA)
ELSE NULL END) AS AD_LOGALTLIB, (
    WITH REQ AS (
    SELECT NUNOTA, NUMCOTACAO FROM TGFCAB WHERE TIPMOV = 'J' AND numcotacao is not null 
    )
    select 
    NVL(REQ.NUNOTA,0) REQUISICAO
    from tgfcab CAB
    LEFT JOIN REQ ON CAB.NUMCOTACAO = REQ.NUMCOTACAO
    where 
    CAB.numcotacao is not null AND CAB.TIPMOV IN ('O','C') AND CAB.NUNOTA = TGFCAB.NUNOTA) AS AD_NUM_REQUISICAO, (

SELECT MAX(LIB.OBSLIB) 

FROM TGFCAB CAB

INNER JOIN TSILIB LIB ON LIB.NUCHAVE=CAB.NUNOTA

WHERE CAB.NUNOTA=TGFCAB.NUNOTA) AS AD_OBSLIB, (

SELECT MAX(ITC.NUNOTACPA)

FROM TGFCAB CAB

INNER JOIN TGFITC  ITC ON ITC.NUMCOTACAO=CAB.NUMCOTACAO

WHERE CAB.NUMCOTACAO = TGFCAB.NUMCOTACAO
AND CAB.NUNOTA=TGFCAB.NUNOTA) AS AD_PEDCOMPRA, (
SELECT ROUND(MAX(NVL(VLRFRETE,0)) * 100 / SUM(VLRNOTA),2) 
FROM TGFCAB  CAB
INNER JOIN TGFTOP TOP ON CAB.CODTIPOPER=TOP.CODTIPOPER AND CAB.DHTIPOPER=TOP.DHALTER
WHERE NUNOTA= TGFCAB.NUNOTA
AND CAB.VLRNOTA > 0 
AND  VLRFRETE  > 0
AND TOP.CODTIPOPER = ANY ('201','214','101')) AS AD_PERCENTFRETE, (
SELECT 
CASE WHEN (TOP.ATUALFIN=0 )  AND TOP.CODTIPOPER NOT IN (1112,1113) THEN 0
WHEN TOP.ATUALFIN=-1 THEN SUM(ITE.QTDNEG * PRO.AD_QTDVOLLT)*-1
ELSE SUM(ITE.QTDNEG * PRO.AD_QTDVOLLT) END AS VOLUME
FROM TGFITE ITE, TGFPRO PRO, TGFTOP TOP
WHERE ITE.CODPROD=PRO.CODPROD
AND ITE.NUNOTA=TGFCAB.NUNOTA
AND TGFCAB.CODTIPOPER=TOP.CODTIPOPER
AND TGFCAB.DHTIPOPER=TOP.DHALTER
GROUP BY TOP.ATUALFIN,  TOP.CODTIPOPER, TOP.ATUALEST) AS AD_QTDVOLLT, (
SELECT RAZAOSOCIAL FROM TGFPAR WHERE CODPARC=TGFCAB.CODPARC) AS AD_RAZAOSOCIAL, (
TGFCAB.AD_DTENTREGAEFETIVA - TGFCAB.AD_DTCOLETAEFETIVA) AS AD_TEMPODEROTADIAS, (
SELECT CASE WHEN (TOP.ATUALFIN=0)  AND TOP.CODTIPOPER  NOT IN (1112,1113) THEN 0
WHEN TOP.ATUALFIN=-1 THEN SUM(ITE.VLRTOT-ITE.VLRDESC-ITE.VLRREPRED)*-1
ELSE SUM(ITE.VLRTOT-ITE.VLRDESC-ITE.VLRREPRED) END AS VALORFIN
FROM TGFCAB CAB, TGFTOP TOP, TGFITE ITE
WHERE CAB.CODTIPOPER=TOP.CODTIPOPER
AND CAB.DHTIPOPER=TOP.DHALTER
AND CAB.NUNOTA=ITE.NUNOTA
AND ITE.NUNOTA=TGFCAB.NUNOTA
GROUP BY TOP.ATUALFIN,  TOP.CODTIPOPER, TOP.ATUALEST) AS AD_VALROFIN, (
SELECT SUM(VLRTOT)  FROM TGFITE WHERE NUNOTA=TGFCAB.NUNOTA AND SEQUENCIA > 0) AS AD_VLRNOTABRUTO, (

SELECT MAX(ITC.PRECO)

FROM TGFCAB CAB

INNER JOIN TGFITC  ITC ON ITC.NUMCOTACAO=CAB.NUMCOTACAO

WHERE CAB.NUMCOTACAO = TGFCAB.NUMCOTACAO
AND CAB.NUNOTA=TGFCAB.NUNOTA) AS AD_VLRPEDCOMPRA, (
SELECT 
SUM(((ITE.QTDNEG-ITE.QTDENTREGUE)* ITE.AD_PRECOLIQ)) 

FROM TGFITE ITE 
INNER JOIN TGFCAB CAB ON ITE.NUNOTA = CAB.NUNOTA


WHERE CAB.NUNOTA =TGFCAB.NUNOTA) AS AD_VLRPENDENTE, (
SELECT NVL(SUM(VLRREPRED),0) FROM TGFITE WHERE NUNOTA=TGFCAB.NUNOTA) AS AD_VLRREDUCAO, (
SELECT SUM(CASE
    WHEN TGFCAB.TIPMOV IN ('O', 'C', 'E')
        THEN ITE.VLRTOT - ITE.VLRDESC - ITE.VLRREPRED
        ELSE CASE
            WHEN NVL((SELECT INTEIRO FROM TSIPAR WHERE CHAVE = 'TIPTABPRECOS'), 0) <> 9
                THEN ITE.VLRTOT - ITE.VLRDESC - ITE.VLRREPRED
            WHEN NVL((SELECT LOGICO FROM TSIPAR WHERE CHAVE = 'ADIMPVLRTOTLIQ'), 'S') <> 'S'
                THEN ITE.VLRTOT - ITE.VLRDESC - ITE.VLRREPRED
            ELSE (ITE.VLRTOT - ITE.VLRDESC - ITE.VLRREPRED) + ITE.VLRSUBST + ((
                    CASE WHEN ITE.VLRIPI > 0 AND NVL ((SELECT SOMARIPI FROM TGFTOP TP WHERE TP.CODTIPOPER = TGFCAB.CODTIPOPER AND TP.DHALTER = TGFCAB.DHTIPOPER),'N') <> 'N'
                        THEN ITE.VLRIPI
                        ELSE 0
                    END))
            END
        END)
FROM TGFITE ITE
WHERE ITE.NUNOTA = TGFCAB.NUNOTA) AS AD_VLRTOTALCALC, ( 
		      SELECT V.CODAUTORIZACAOVENDAMAIS AS CODAUTHVM FROM TGFCABVM V WHERE V.NUNOTA = TGFCAB.NUNOTA AND (V.ESTORNADO IS NULL OR V.ESTORNADO <> 'S')) AS CODAUTHVM, ( CASE WHEN TGFCAB.STATUSNOTA = 'L' THEN 'Sim' ELSE 'Não' END) AS CONFIRMADA, ( CASE WHEN (SELECT COUNT(*) FROM TCBINT T WHERE T.ORIGEM = 'E' AND T.NUNICO = TGFCAB.NUNOTA) > 0 THEN 'S' ELSE 'N' END) AS CONTABILIZADO, ( CASE WHEN TGFCAB.TERMACORDNOTA='S' AND EXISTS(SELECT 1  FROM TGFTOP  WHERE TGFTOP.CODTIPOPER=TGFCAB.CODTIPOPER  AND TGFTOP.DHALTER = TGFCAB.DHTIPOPER  AND TGFTOP.CODMODDOC IN (67,57)) THEN TGFCAB.VLRICMS ELSE 0 END) AS DESCTERMACORD, ( SELECT T.DTVALIDADE AS DTVALAUTVENDAMAIS FROM TGFCABVM T WHERE T.NUNOTA = TGFCAB.NUNOTA AND T.CODOPERACAOVENDAMAIS IS NULL AND (T.ESTORNADO IS NULL OR T.ESTORNADO <> 'S')) AS DTVALAUTVENDAMAIS, ( SELECT TGFTOP.TIPOEMISSAONFCOM FROM TGFTOP WHERE TGFTOP.CODTIPOPER = TGFCAB.CODTIPOPER AND TGFTOP.DHALTER = TGFCAB.DHTIPOPER AND TGFTOP.CODMODDOC = 62) AS NFCOM, (
SELECT
SUM(NVL(PRO.PESOLIQ, 0) * I.QTDNEG)
FROM TGFITE I
INNER JOIN TGFPRO PRO ON(PRO.CODPROD = I.CODPROD)
WHERE
I.SEQUENCIA > 0
AND I.NUNOTA = TGFCAB.NUNOTA) AS PESOLIQITENS, (
							SELECT COUNT(DISTINCT CODPROD)
							FROM TGFITE
							WHERE NUNOTA = TGFCAB.NUNOTA) AS QTDPRODDISTINTOS, ( 
SELECT
(NVL(
  CASE 
       WHEN (TPO.UTILIZAWMS = 'N' OR TGFCAB.TIPMOV NOT IN ('C','O','P','V','D','E','J','Q','L','T'))  THEN
            -1
       WHEN TGFCAB.TIPMOV IN ('C','O','D') THEN
         NVL((SELECT VREC.COD_SITUACAO FROM VGWRECSITCAB VREC WHERE VREC.NUNOTA = TGFCAB.NUNOTA), -1)
       WHEN TGFCAB.TIPMOV IN ('T') AND TPO.TIPATUALWMS = 'E' THEN
         NVL((SELECT VREC.COD_SITUACAO FROM VGWRECSITCAB VREC WHERE VREC.NUNOTA = TGFCAB.NUNOTA), -1)
       WHEN TGFCAB.TIPMOV IN ('P','V','E','T','J') THEN
         NVL((SELECT VSEP.COD_SITUACAO FROM VGWSEPSITCAB VSEP WHERE VSEP.NUNOTA = TGFCAB.NUNOTA), -1)
   END , -1)) AS SITUACAOWMS
  FROM TGFTOP TPO
  WHERE TPO.CODTIPOPER = TGFCAB.CODTIPOPER
    AND TPO.DHALTER = TGFCAB.DHTIPOPER) AS SITUACAOWMS, ( 
	      SELECT
				CASE
					WHEN V.CODAUTORIZACAOVENDAMAIS IS NOT NULL AND V.ESTORNADO = 'N' AND EXISTS(SELECT 1 FROM TGFCABVM WHERE CODAUTORIZACAOVENDAMAIS = V.CODAUTORIZACAOVENDAMAIS) AND V.TIPMOV = 'P' AND V.DTVALIDADE > SYSDATE THEN 'A'
					WHEN V.CODAUTORIZACAOVENDAMAIS IS NOT NULL AND V.ESTORNADO = 'S' THEN 'C'
					WHEN V.CODAUTORIZACAOVENDAMAIS IS NOT NULL AND V.ESTORNADO = 'N' AND EXISTS(SELECT 1 FROM TGFCABVM WHERE CODAUTORIZACAOVENDAMAIS = V.CODAUTORIZACAOVENDAMAIS AND TIPMOV = 'V' AND CODOPERACAOVENDAMAIS IS NOT NULL) AND V.TIPMOV = 'P' THEN 'U'
					WHEN V.CODAUTORIZACAOVENDAMAIS IS NOT NULL AND V.ESTORNADO = 'N' AND EXISTS(SELECT 1 FROM TGFCABVM WHERE CODAUTORIZACAOVENDAMAIS = V.CODAUTORIZACAOVENDAMAIS) AND V.DTVALIDADE < SYSDATE THEN 'E'
					ELSE NULL 
				END AS STATUSAUTORIZACAOVM
				FROM
					TGFCABVM V
				WHERE
					V.NUNOTA = TGFCAB.NUNOTA) AS STATUSAUTORIZACAOVM, ( 
	     SELECT
			CASE
				WHEN V.CODAUTORIZACAOVENDAMAIS IS NOT NULL AND V.CODOPERACAOVENDAMAIS IS NULL AND (TGFCAB.STATUSNFE IS NULL OR TGFCAB.STATUSNFE <> 'A') THEN 'N'
				WHEN V.CODAUTORIZACAOVENDAMAIS IS NOT NULL AND V.CODOPERACAOVENDAMAIS IS NULL AND TGFCAB.STATUSNFE = 'A' THEN 'E'
				WHEN V.CODAUTORIZACAOVENDAMAIS IS NOT NULL AND V.CODOPERACAOVENDAMAIS IS NOT NULL AND TGFCAB.STATUSNFE = 'A' THEN 'A'
				WHEN V.CODAUTORIZACAOVENDAMAIS IS NULL AND V.CODOPERACAOVENDAMAIS IS NULL AND V.TIPMOV = 'D' AND ((SELECT QTD FROM TGFFILAINTVM WHERE NUCHAVE = V.NUNOTA) = (SELECT QTDMAX FROM TGFFILAINTVM WHERE NUCHAVE = V.NUNOTA)) AND (TGFCAB.STATUSNFE = 'A' OR (TGFCAB.STATUSNFE IS NULL AND TGFCAB.STATUSNOTA = 'L')) THEN 'F'
				WHEN V.CODAUTORIZACAOVENDAMAIS IS NULL AND V.CODOPERACAOVENDAMAIS IS NULL AND V.TIPMOV = 'D' AND (TGFCAB.STATUSNFE = 'A' OR (TGFCAB.STATUSNFE IS NULL AND TGFCAB.STATUSNOTA = 'L')) AND NOT EXISTS(SELECT 1 FROM TGFFILAINTVM WHERE NUCHAVE = V.NUNOTA) THEN 'F'
				WHEN V.CODAUTORIZACAOVENDAMAIS IS NULL AND V.CODOPERACAOVENDAMAIS IS NOT NULL AND V.TIPMOV = 'D' AND (TGFCAB.STATUSNFE = 'A' OR (TGFCAB.STATUSNFE IS NULL AND TGFCAB.STATUSNOTA = 'L')) THEN 'D'
				WHEN V.CODAUTORIZACAOVENDAMAIS IS NULL AND V.CODOPERACAOVENDAMAIS IS NULL AND V.TIPMOV = 'D' AND (TGFCAB.STATUSNFE = 'A' OR (TGFCAB.STATUSNFE IS NULL AND TGFCAB.STATUSNOTA = 'L')) THEN 'P'
				ELSE NULL 
				END AS STATUSVM
	   FROM
		 	TGFCABVM V
	   WHERE
			V.NUNOTA = TGFCAB.NUNOTA
	   AND
			V.TIPMOV IN('V','D')) AS STATUSVM, (
SELECT
		(NVL(
		CASE WHEN (TPO.UTILIZAWMS ='N' OR TGFCAB.TIPMOV NOT IN ('C','O','P','V','D','E','J','Q','L','T')) THEN 4
	     WHEN (SELECT COUNT(*) FROM TGFEMP E WHERE E.CODEMP = TGFCAB.CODEMP AND (E.UTILIZAWMS ='S')) = 0 THEN 4
	     WHEN (TPO.TIPATUALWMS ='E') THEN
	            CASE WHEN (SELECT DISTINCT 1 FROM TGWREC REC, TGWRXN RXN WHERE RXN.NUNOTA = TGFCAB.NUNOTA) IS NULL THEN 3 ELSE 1 END
	ELSE
	      (SELECT
	         CASE WHEN SUM(CASE WHEN (P.UTILIZAWMS ='S' AND L.UTILIZAWMS ='S') THEN I.QTDNEG ELSE 0 END) = 0 THEN 4
		          WHEN (NVL(SUM(NVL(I.QTDWMS,0)),0) = 0) AND (SUM(I.QTDNEG) = SUM(I.QTDCONFERIDA)) THEN 5
	              WHEN (NVL(SUM(NVL(I.QTDWMS,0)),0) = 0) AND (SUM(I.QTDCONFERIDA) <> 0) AND (SUM(I.QTDNEG) <> SUM(I.QTDCONFERIDA)) THEN 0
	              WHEN (NVL(SUM(NVL(I.QTDWMS,0)),0) = 0)  THEN 3
	              WHEN (NVL(SUM(NVL(I.QTDWMS,0)),0) = SUM(CASE WHEN (P.UTILIZAWMS ='S') THEN I.QTDNEG ELSE 0 END)) THEN 1 ELSE 2 END
	       FROM TGFITE I, TGFPRO P, TGFEMP E, TGFLOC L
	       WHERE I.NUNOTA = TGFCAB.NUNOTA
	       AND I.CODEMP = E.CODEMP AND I.CODPROD = P.CODPROD AND I.CODLOCALORIG = L.CODLOCAL  AND I.SEQUENCIA > 0) END , '')) AS COD_STATUSWMS
	FROM TGFTOP TPO
  WHERE TPO.CODTIPOPER = TGFCAB.CODTIPOPER
    AND TPO.DHALTER = TGFCAB.DHTIPOPER) AS STATUSWMS, ( SELECT MAX(CODPROD) CODPROD FROM TGFITE WHERE NUNOTA = (SELECT TGFCAB.NUNOTA FROM DUAL)) AS TIMCODPROD, ( 
SELECT DESCRPROD FROM TGFPRO WHERE CODPROD = (SELECT MAX(CODPROD) FROM TGFITE WHERE NUNOTA = (SELECT TGFCAB.NUNOTA FROM DUAL))) AS TIMDESCPROD, (
SELECT TPO.TIPOCTE
FROM TGFTOP TPO
WHERE
TPO.CODTIPOPER = TGFCAB.CODTIPOPER
AND TPO.DHALTER = TGFCAB.DHTIPOPER) AS TIPOCTE, (
SELECT TPO.TIPSERVCTE
FROM TGFTOP TPO
WHERE
TPO.CODTIPOPER = TGFCAB.CODTIPOPER
AND TPO.DHALTER = TGFCAB.DHTIPOPER) AS TIPSERVCTE, ( SELECT SUM(NVL(CASE WHEN (I.CODTRIB = 51 AND I.CODCFO LIKE '3%') THEN I.VLRICMSDIFERIDO ELSE 0 END, 0)) FROM TGFITE I WHERE I.NUNOTA = TGFCAB.NUNOTA) AS VLRICMSDIFERIDO /*SQL_92_JOINED_FIELDS*/ FROM TGFCAB /*SQL_92_JOINED_TABLES*/   WHERE ((TGFCAB.CODEMP IN (SELECT CODEMP FROM TGFEMP WHERE CODEMPOC = 1)) 
 OR TGFCAB.CODEMP = 1)
)
--WHERE AD_DTENTREGAEFETIVA IS NOT NULL AND AD_DTENTREGAPREV IS NOT NULL
GROUP BY ORDEMCARGA--CODEMP,ORDEMCARGA,AD_DTENTREGAEFETIVA, AD_DTENTREGAPREV
)--WHERE DTNEG BETWEEN '01/10/2025' AND '30/11/2025' --:P_PERIODO.INI AND :P_PERIODO.FIN
WHERE AD_DTENTREGAEFETIVA IS NOT NULL AND AD_DTENTREGAPREV IS NOT NULL
ORDER BY ORDEMCARGA DESC
