SELECT 
       CODIGO_ITEM,
       ITEM,
       CODIGO_GRUPO,
       GRUPO,
       CODVOL,
       QUANTIDADE,
       TOTALUNID,
       QTDPREV,
       TOTALUNID -QTDPREV AS DIFERENCA,
       CASE 
            WHEN (TOTALUNID -QTDPREV)= 0 THEN 'BLUE' 
            WHEN (TOTALUNID -QTDPREV)> 0  THEN 'GREEN'
            WHEN(TOTALUNID -QTDPREV) < 0 THEN 'RED'			
            ELSE '' 
       END AS RGBCOLOR 
FROM (
    SELECT 
           I.CODPROD AS CODIGO_ITEM,
           P.DESCRPROD AS ITEM,
           P.CODGRUPOPROD AS CODIGO_GRUPO,
           G.DESCRGRUPOPROD AS GRUPO,
           I.CODVOL,
           SUM(I.QTDNEG) AS QUANTIDADE,
           SUM(I.QTDNEG * AD_QTDVOLLT) as TOTALUNID,
           (SELECT SUM(MET.QTDPREV / ABS(TO_CHAR(last_day(TO_DATE(MET.DTREF)),'DD')) *
                    (ABS((CASE WHEN TO_DATE(:PERIODO.FIN) > last_day(TO_DATE(MET.DTREF)) THEN last_day(TO_DATE(MET.DTREF)) ELSE TO_DATE(:PERIODO.FIN) END -  		TRUNC(MET.DTREF,'MM')))+1)) AS QTDPREV
            FROM TGMMET MET
            WHERE MET.CODMETA = 8
            AND MET.DTREF BETWEEN TRUNC(TO_DATE(:PERIODO.INI),'MM') AND :PERIODO.FIN
            AND MET.CODPROD = I.CODPROD) AS QTDPREV
    FROM TGFCAB C
    INNER JOIN TGFITE I ON I.NUNOTA = C.NUNOTA
    INNER JOIN TGFPRO P ON P.CODPROD = I.CODPROD
    INNER JOIN TGFGRU G ON G.CODGRUPOPROD = P.CODGRUPOPROD
    WHERE C.TIPMOV = 'F'
      AND C.CODTIPOPER = :P_TOP
      AND C.DTNEG BETWEEN :PERIODO.INI AND :PERIODO.FIN
      --AND I.SEQUENCIA = 1
      AND I.USOPROD = 'V'
    GROUP BY
           I.CODPROD,
           P.DESCRPROD,
           P.CODGRUPOPROD,
           G.DESCRGRUPOPROD,
           I.CODVOL

    UNION ALL

    SELECT 
           P.CODPROD AS CODIGO_ITEM,
           P.DESCRPROD AS ITEM,
           P.CODGRUPOPROD AS CODIGO_GRUPO,
           G.DESCRGRUPOPROD AS GRUPO,
           P.CODVOL,
           0 AS QUANTIDADE,
           0 AS TOTALUNID,
           (SELECT SUM(MET.QTDPREV / ABS(TO_CHAR(last_day(TO_DATE(MET.DTREF)),'DD')) *
                    (ABS((CASE WHEN TO_DATE(:PERIODO.FIN) > last_day(TO_DATE(MET.DTREF)) THEN last_day(TO_DATE(MET.DTREF)) ELSE TO_DATE(:PERIODO.FIN) END -  		TRUNC(MET.DTREF,'MM')))+1)) AS QTDPREV
            FROM TGMMET MET
            WHERE MET.CODMETA = 8
            AND MET.DTREF BETWEEN TRUNC(TO_DATE(:PERIODO.INI),'MM') AND :PERIODO.FIN
            AND MET.CODPROD = P.CODPROD) AS QTDPREV
    FROM TGMMET M
    INNER JOIN TGFPRO P ON P.CODPROD = M.CODPROD
    INNER JOIN TGFGRU G ON G.CODGRUPOPROD = P.CODGRUPOPROD
    WHERE M.CODMETA = 8
      AND NVL(M.QTDPREV,0) <> 0
      AND M.CODPROD NOT IN (SELECT I.CODPROD FROM TGFITE I, TGFCAB C WHERE C.NUNOTA=I.NUNOTA AND C.CODTIPOPER = :P_TOP AND C.DTNEG BETWEEN :PERIODO.INI AND :PERIODO.FIN AND I.USOPROD = 'V')
    GROUP BY
           P.CODPROD,
           P.DESCRPROD,
           P.CODGRUPOPROD,
           G.DESCRGRUPOPROD,
           P.CODVOL
) 
ORDER BY 1
