SELECT
  COUNT(CASE WHEN NVL(TMT.TIPO,'NF') = 'PV' THEN 1 END) AS qtd_pv,
  COUNT(*) AS total_ordens,
  ROUND(100 * COUNT(CASE WHEN NVL(TMT.TIPO,'NF') = 'PV' THEN 1 END) / NULLIF(COUNT(*), 0), 2) AS participacao_pct_pv
FROM TMEOMT OMT
LEFT JOIN TMETMT TMT ON OMT.codimt = TMT.CODTMT
